package br.gov.mec.aghu.paciente.business.exception;

import br.gov.mec.aghu.core.exception.BusinessExceptionCode;

/**
 * Contem as mensagems mais genericas para que sejam utilizadas em mais de um
 * lugar.
 */

public enum PacienteExceptionCode implements BusinessExceptionCode {
	ENDERECO_PADRAO_NAO_ENCONTRADO, AIP_PRONTUARIO_E_CODIGO_NULOS, MENSAGEM_ERRO_PESQUISA_FONETICA_NOME_OBRIGATORIO, AIP_PRONTUARIO_NULO, AIP_PRONTUARIO_INVALIDO, MENSAGEM_PRONTUARIO_NAO_ARQUIVADO, MENSAGEM_PRONTUARIO_SEM_ORIGEM, MENSAGEM_SITUACAO_PRONTUARIO_NAO_PERMITE_MOVIMENTO, MENSAGEM_PRONTUARIO_NAO_PODE_SER_DEVOLVIDO, MESSAGEM_ERRO_MOVIMENTACAO_EM_LOTE_PRIMEIRA_MOVIMENTACAO, MENSAGEM_MOV_PRONT_PARA_LOCAIS_DISTINTOS 

}
