package br.gov.mec.aghu.dao;


/*
 * Enum que descreve os objetos do banco Oracle, como packages, procedure, functions
 */
@SuppressWarnings("PMD.CyclomaticComplexity")
public enum ObjetosBancoOracleEnum {

	// functions
	AACC_VER_SIT_GRADE,
	AGHU_RN_CTHC_VER_DATAS,//O nome original da function é RN_CTHC_VER_DATAS, 
						   //foi preciso criar uma nova que a encapsula devido a problemas com o tipo de retorno da original (boolean).
	FFC_F_VALR_ACOM,
	MCIC_PAC_NOTIF_GMR,
	FATC_TIPO_LOGRADOURO_SUS,
	// procedures
	AIPP_FLAG_SUBSTITUI_PRONT,
	AELK_EXAME_PCT_AELP_GERA_EXAME_PCT,
	MAMP_ATU_IEO_OBITO,
	MAMP_CHECK_OUT_INT,
	MAMP_ATU_TRG_EMATEND,
	FATK_SUS_RN_RN_FATP_ATU_TRCNVMBC,
	AELK_EXAME_PCT_AELP_CANCELA_CIRURGIA,
	MCIK_LEITOS_MCIP_ALTERA_CONTROLE,
	MCIK_LEITOS_MCIP_INSERE_CONTROLE,
	AINK_INT_RN_RN_INTP_ATU_ALT_CNTA,
	AGHK_ATD_RN_RN_ATDP_CANC_EXME,
	FATK_CTH_RN_RN_CTHC_VER_DATAS,
	AGHK_ATD_RN_RN_ATDP_CANC_AMOSTRA,
	AINK_INT_RN_RN_INTP_ATU_ALT_MCI,
	MAMP_CHECK_OUT_ATU,
	RN_CTHC_ATU_LANCAUTI,
	AGHK_ATD_RN_RN_ATDP_ATU_INIC_ATD,
	AINK_INT_RN_RN_INTP_ATU_MOT_FAT,
	FATK_CTH_RN_RN_CTHP_ATU_DIAR_UTI,
	FFC_ALTERA_DATA,
	MPMP_GERA_LAUDO_AIN,
	RN_INTP_BLOQ_NEURO,
	FATK_CTH4_RN_UN_RN_CTHP_BUSCA_SANGUE,
	FATP_CTH_TROCA_CNV,
	FFC_CALCULO_CONTA,
	FFC_INTERFACE_MBC,
	FFC_F_VALR_ACOM_CNVN, 
	RAPC_VER_SERV_ATI_STARH,
	FATP_AGHU_CTH_P_T_C, // Permissão de troca de convênio na conta
	CSEC_VER_PERFIL_VINC,
	FATP_VER_ITEM_SOLIC,
	CSEP_REVOGA_PERFIS,
	CSEP_FORNECE_PERFIS,
	CSEP_AJUSTA_NT_EMAIL,
	RN_SERC_VER_PERM,
	RN_SERP_AVISO_ENCERRAMENTO,
	RN_SERP_ATUALIZA_LIDERES,
	RAPC_BUSCA_COD_STARH,
	RAPC_VESETEM_UNIMED,
	RAPC_FUNCAO_CRACHA,
	RN_SERP_VERIFICA_NT_EMAIL,
	RN_SERC_VER_PERFIL_VINC,
	RAPC_BUSCA_OCUPACAO,
	MAMK_INT_PARADA_MAMP_INT_PARADA,
	RN_FATP_INS_CENTRO_OBSTETRICO,
	AINP_ENCERRA_RONDA,
	PUT_USUARIO_AGHU,
	AIPK_TROCA_CONVENIO_AGHU_EVT_ON_INSERT,
	AELK_ISE_RN_RN_ISEP_ATU_REFLEXO,
	AELK_ISE_RN_RN_ISEP_ATU_EXME_ABS,
	AELK_ISE_RN_RN_ISEP_ATU_DOA_ABS,
	FATP_INTERFACE_AEL,
	AELK_ISE_RN_RN_ISEP_VER_PRIORIDA,
	AELK_ISE_RN_RN_ISEP_ATU_CCEL_LIB,
	AELK_ISE_RN_RN_ISEP_ATU_CX_POST,
	FFC_INTERFACE_AEL,
	AELK_ISE_RN_RN_ISEP_ATU_LAU_UNIC,
	RN_PPRP_DEL_UOP_PROT,
	AGHK_ATD_RN_RN_ATDP_GRAVA_MFP, 
	AGHK_ATD_RN_RN_ATDP_ATU_CIR_UPD, 
	FATK_PMR_RN_RN_PMRP_ATU_PAC_COD, 
	MPMP_GERA_ECE_QUIMIO, 
	AGHK_ATD_RN_2_RN_ATDP_TRANSF_AGHOS, 
	AGHK_ATD_RN_2_RN_ATDP_ALTA_AGHOS, 
	AGHK_ATD_RN_RN_ATDP_ATU_CIRURGIA, 
	AGHK_ATD_RN_RN_ATDP_ATU_AGEN_TRP,
	SCEK_RMS_RN_RN_RMSP_GERA_RM_PRCS,
	MPMP_GERA_PISTA_MCI,
	MPMP_GERA_ORDEM_ADM,
	MPMP_INCLUI_PRCR_ECE,
	MPMP_GERA_MVTO_ECE,
	RAPC_BUSCA_CRACHA_LIVRE_RONDA, 
	RAPP_ATU_CONTROLE_RONDA,
	AELK_POL_SUM_EXAMES_PEP_POL_SUM_DELETE_PEP,
	AELK_POL_SUM_EXAMES_PEP_POL_SUM_EXAMES_PEP,
	MBCK_CRG_RN2_RN_CRGP_CANC_QUIMIO,
	MBCK_CRG_RN2_RN_CRGP_ATU_COTA_PJQ,
	RN_CRGP_ATU_AGFA,
	INICIAR_CHAMADA_AGHU,
	ENCERRAR_CHAMADA_AGHU, 
	AGHK_ATD_RN_RN_ATDP_ATU_LIST_PAC,
	AGHK_ATD_RN_RN_ATDP_GERA_DIAG_CT, 
	AGHK_ATD_RN_RN_ATDP_GERA_APACHE, 
	ECEP_INSERE_ORDEM_LOCALIZACAO, 
	ECEP_ALTERA_ORDEM_LOCALIZACAO, 
	AGHK_ATD_RN_RN_ATDP_ATU_APACHE, 
	AGHK_ATD_RN_RN_ATDP_CA_EXME_AMB, 
	AGHK_ATD_RN_RN_ATDP_ATU_ALTA_SUM, 
	AGHK_ATD_RN_RN_ATDP_ATU_PAC_PROF, 
	AGHK_ATD_RN_2_RN_ATDP_ATU_PIM2,
	AINK_INT_RN_RN_INTP_ATU_INT_CNTA,
	AGHK_ATD_RN_RN_ATDP_VER_FIM_SUM,
	FATK_PMR_RN_RN_PMRP_TRC_ESP_ATD,
	AGHK_ATD_RN_RN_ATDP_ATU_PAC_COD,
	AIPK_PAC_ATU_RN_PACP_ATU_NASC,
	AINK_INT_RN_RN_INTP_ATU_CNV_EXME,
	AINK_INT_RN_RN_INTP_ATU_CNV_CIRG,
	AIPP_SUBS_PRONT_ATD,
	FFC_INTERFACE_EQP,
	TESTE_PERFORMACE_C3,
	TESTE_PERFORMACE_C2,
	FATK_AMB_RN_RN_FATP_ENC_ACO_NEW,
	FATK_AMB_RN_RN_FATP_ENC_EXM_NEW,
	FATK_AMB_RN_RN_FATP_ENC_PRE,
	FATK_AMB_RN_RN_FATP_ENC_FOT_NEW,
	FATK_SUS_RN_RN_FATP_ENC_SISCOLO,
	FATK_AMB_RN_RN_FATP_ENC_RAD_NEW,
	FATK_AMB_RN_RN_FATP_ENC_OTO_NEW,
	FATK_SUS_RN_RN_FATP_ENC_SISMAMA,
	FATK_AMB_RN_RN_FATP_ENC_APAC_NEF,
	FATK_AMB_RN_RN_FATP_ENC_APAC_QUI,
	FATK_PMR_RN_RN_PMRP_ATU_APAC_FUT,
	MAMK_TRG_RN_RN_TRGP_DEL_PAC_LIST,
	MBCP_CARRG_FICHA,
	SCOP_GERA_AFP_AUT,
	SCOP_GERA_AFP_AUT_AUTOMATICA,
	FFC_GERA_CONTA_INT, // Apesar da nomenclatura, é uma procedure do schema CONV
	EPEP_GERA_PISTA_MCI,
	EPEP_GERA_MVTO_ECE,
	EPEP_GERA_ORDEM_ECE,
	MAMK_TRG_RN_RN_TRGP_CHECK_OUT,
	MAMK_TRG_RN_RN_TRGP_DEL_RESUMO,
	MAMK_TRG_RN_RN_TRGP_DEL_INF_PAC,
	MAMK_TRG_RN_RN_TRGP_DEL_PLANO,
	EPEP_GERA_ITEM_ECE,
	FFC_INTERFACE_AAC_PRJ,
	FFC_F_ITEM_CONV_CSP,
	FFC_F_MATRICULA_PROF,
	FFC_F_COD_OPERADORA,
	FFC_F_BUSCA_SENHA,
	FFC_F_BUSCA_DATA_SENHA,
	RN_IAFP_GER_LI_SIAFI;
	
	@Override	
	@SuppressWarnings({"PMD.ExcessiveMethodLength", "PMD.NcssMethodCount"})
	public String toString() {
		switch (this) {
			case TESTE_PERFORMACE_C3: return "teste_performance_c3";
			case MAMK_TRG_RN_RN_TRGP_CHECK_OUT: return "MAMK_TRG_RN.RN_TRGP_CHECK_OUT";
			case MAMK_TRG_RN_RN_TRGP_DEL_RESUMO: return "MAMK_TRG_RN.RN_TRGP_DEL_RESUMO";
			case MAMK_TRG_RN_RN_TRGP_DEL_PLANO: return "MAMK_TRG_RN.RN_TRGP_DEL_PLANO";
			case MAMK_TRG_RN_RN_TRGP_DEL_PAC_LIST: return "MAMK_TRG_RN.RN_TRGP_DEL_PAC_LIST";
			case MAMK_TRG_RN_RN_TRGP_DEL_INF_PAC: return "MAMK_TRG_RN.RN_TRGP_DEL_INF_PAC";
			case TESTE_PERFORMACE_C2: return "teste_performance_c2"; 
			case MCIK_LEITOS_MCIP_ALTERA_CONTROLE: return "MCIK_LEITOS.MCIP_ALTERA_CONTROLE";
			case MCIK_LEITOS_MCIP_INSERE_CONTROLE: return "MCIK_LEITOS.MCIP_INSERE_CONTROLE";
			case AINK_INT_RN_RN_INTP_ATU_ALT_CNTA: return "AINK_INT_RN.RN_INTP_ATU_ALT_CNTA";
			case AGHK_ATD_RN_RN_ATDP_CANC_EXME: return "AGHK_ATD_RN.RN_ATDP_CANC_EXME";
			case FATK_CTH_RN_RN_CTHC_VER_DATAS: return "FATK_CTH_RN.RN_CTHC_VER_DATAS";
			case AGHK_ATD_RN_RN_ATDP_CANC_AMOSTRA: return "AGHK_ATD_RN.RN_ATDP_CANC_AMOSTRA";
			case AINK_INT_RN_RN_INTP_ATU_ALT_MCI: return "AINK_INT_RN.RN_INTP_ATU_ALT_MCI";
			case RN_CTHC_ATU_LANCAUTI: return "FATK_CTH4_RN.RN_CTHC_ATU_LANCAUTI";
			case AGHK_ATD_RN_RN_ATDP_ATU_INIC_ATD: return "AGHK_ATD_RN.RN_ATDP_ATU_INIC_ATD";
			case AINK_INT_RN_RN_INTP_ATU_MOT_FAT: return "AINK_INT_RN.RN_INTP_ATU_MOT_FAT";
			case FATK_CTH_RN_RN_CTHP_ATU_DIAR_UTI: return "FATK_CTH_RN.RN_CTHP_ATU_DIAR_UTI";
			case FFC_F_VALR_ACOM: return "FFC_F_VALR_ACOM";
			case FATK_CTH4_RN_UN_RN_CTHP_BUSCA_SANGUE: return "FATK_CTH4_RN_UN.RN_CTHP_BUSCA_SANGUE";
			case RAPC_VER_SERV_ATI_STARH: return "RAPC_VER_SERV_ATI_STARH";
			case CSEC_VER_PERFIL_VINC: return "CSEC_VER_PERFIL_VINC";
			case CSEP_REVOGA_PERFIS: return "CSEK_FORN_REVG.CSEP_REVOGA_PERFIS";
			case CSEP_FORNECE_PERFIS: return "CSEK_FORN_REVG.CSEP_FORNECE_PERFIS";
			case RN_SERC_VER_PERM: return "RAPK_SER_RN_AGHU.RN_SERC_VER_PERM";
			case RN_SERP_AVISO_ENCERRAMENTO: return "RAPK_SER_RN_AGHU.RN_SERP_AVISO_ENCERRAMENTO";
			case RN_SERP_ATUALIZA_LIDERES: return "RAPK_SER_RN_AGHU.RN_SERP_ATUALIZA_LIDERES";
			case RAPC_VESETEM_UNIMED: return "RAPC_VESETEM_UNIMED";
			case RN_SERP_VERIFICA_NT_EMAIL: return "RAPK_SER_RN_AGHU.RN_SERP_VERIFICA_NT_EMAIL";
			case RN_SERC_VER_PERFIL_VINC: return "RAPK_SER_RN_AGHU.RN_SERC_VER_PERFIL_VINC";
			case MAMK_INT_PARADA_MAMP_INT_PARADA: return "MAMK_INT_PARADA.MAMP_INT_PARADA";
			case RN_FATP_INS_CENTRO_OBSTETRICO: return "FATK_INTERFACE_MCO.RN_FATP_INS_CENTRO_OBSTETRICO";
			case PUT_USUARIO_AGHU: return "AGH_CONFIG.PUT_USUARIO_AGHU";
			case AIPK_TROCA_CONVENIO_AGHU_EVT_ON_INSERT: return "AIPK_TROCA_CONVENIO_AGHU.EVT_ON_INSERT";
			case AELK_ISE_RN_RN_ISEP_ATU_REFLEXO: return "AELK_ISE_RN.RN_ISEP_ATU_REFLEXO";
			case AELK_ISE_RN_RN_ISEP_ATU_EXME_ABS: return "AELK_ISE_RN.RN_ISEP_ATU_EXME_ABS";
			case AELK_ISE_RN_RN_ISEP_ATU_DOA_ABS: return "AELK_ISE_RN.RN_ISEP_ATU_DOA_ABS";
			case FATP_INTERFACE_AEL: return "FATP_INTERFACE_AEL";
			case AELK_ISE_RN_RN_ISEP_VER_PRIORIDA: return "AELK_ISE_RN.RN_ISEP_VER_PRIORIDA";
			case AELK_ISE_RN_RN_ISEP_ATU_CCEL_LIB: return "AELK_ISE_RN.RN_ISEP_ATU_CCEL_LIB";
			case AELK_ISE_RN_RN_ISEP_ATU_CX_POST: return "AELK_ISE_RN.RN_ISEP_ATU_CX_POST";
			case FFC_INTERFACE_AEL: return "FFC_INTERFACE_AEL";
			case AELK_ISE_RN_RN_ISEP_ATU_LAU_UNIC: return "AELK_ISE_RN.RN_ISEP_ATU_LAU_UNIC";
			case RN_PPRP_DEL_UOP_PROT: return "MPMK_PPR_RN.RN_PPRP_DEL_UOP_PROT";
			case AGHK_ATD_RN_RN_ATDP_GRAVA_MFP: return "AGHK_ATD_RN.RN_ATDP_GRAVA_MFP";
			case AGHK_ATD_RN_RN_ATDP_ATU_CIR_UPD: return "AGHK_ATD_RN.RN_ATDP_ATU_CIR_UPD";
			case FATK_PMR_RN_RN_PMRP_ATU_PAC_COD: return "FATK_PMR_RN.RN_PMRP_ATU_PAC_COD";
			case MPMP_GERA_ECE_QUIMIO: return "MPMP_GERA_ECE_QUIMIO";
			case SCEK_RMS_RN_RN_RMSP_GERA_RM_PRCS : return "SCEK_RMS_RN.RN_RMSP_GERA_RM_PRCS";
			case AGHK_ATD_RN_2_RN_ATDP_TRANSF_AGHOS: return "AGHK_ATD_RN_2.RN_ATDP_TRANSF_AGHOS";
			case AGHK_ATD_RN_2_RN_ATDP_ALTA_AGHOS: return "AGHK_ATD_RN_2.RN_ATDP_ALTA_AGHOS";
			case AGHK_ATD_RN_RN_ATDP_ATU_CIRURGIA: return "AGHK_ATD_RN.RN_ATDP_ATU_CIRURGIA";
			case AGHK_ATD_RN_RN_ATDP_ATU_AGEN_TRP: return "AGHK_ATD_RN.RN_ATDP_ATU_AGEN_TRP";
			case MPMP_GERA_PISTA_MCI: return "MPMP_GERA_PISTA_MCI";
			case MPMP_GERA_ORDEM_ADM: return "MPMP_GERA_ORDEM_ADM";
			case MPMP_INCLUI_PRCR_ECE:return "MPMP_INCLUI_PRCR_ECE";
			case MPMP_GERA_MVTO_ECE: return "MPMP_GERA_MVTO_ECE";
			case AELK_POL_SUM_EXAMES_PEP_POL_SUM_DELETE_PEP: return "AELK_POL_SUM_EXAMES_PEP.AELP_POL_SUM_DELETE_PEP";
			case AELK_POL_SUM_EXAMES_PEP_POL_SUM_EXAMES_PEP:return "AELK_POL_SUM_EXAMES_PEP.AELP_POL_SUM_EXAMES_PEP";
			case MCIC_PAC_NOTIF_GMR: return "MCIC_PAC_NOTIF_GMR";
			case FATC_TIPO_LOGRADOURO_SUS: return "FATC_TIPO_LOGRADOURO_SUS";
			case INICIAR_CHAMADA_AGHU: return "AGH_CONFIG.INICIAR_CHAMADA_AGHU";
			case ENCERRAR_CHAMADA_AGHU: return "AGH_CONFIG.ENCERRAR_CHAMADA_AGHU";
			case AGHK_ATD_RN_RN_ATDP_ATU_LIST_PAC: return "AGHK_ATD_RN.RN_ATDP_ATU_LIST_PAC";
			case AGHK_ATD_RN_RN_ATDP_GERA_DIAG_CT: return "AGHK_ATD_RN.RN_ATDP_GERA_DIAG_CT";
			case AGHK_ATD_RN_RN_ATDP_GERA_APACHE: return "AGHK_ATD_RN.RN_ATDP_GERA_APACHE";
			case ECEP_INSERE_ORDEM_LOCALIZACAO: return "ECEP_INSERE_ORDEM_LOCALIZACAO";
			case ECEP_ALTERA_ORDEM_LOCALIZACAO: return "ECEP_ALTERA_ORDEM_LOCALIZACAO";
			case AGHK_ATD_RN_RN_ATDP_ATU_APACHE: return "AGHK_ATD_RN.RN_ATDP_ATU_APACHE";
			case AGHK_ATD_RN_RN_ATDP_CA_EXME_AMB: return "AGHK_ATD_RN.RN_ATDP_CA_EXME_AMB";
			case AGHK_ATD_RN_RN_ATDP_ATU_ALTA_SUM: return "AGHK_ATD_RN.RN_ATDP_ATU_ALTA_SUM";
			case AGHK_ATD_RN_RN_ATDP_ATU_PAC_PROF: return "AGHK_ATD_RN.RN_ATDP_ATU_PAC_PROF";
			case AGHK_ATD_RN_2_RN_ATDP_ATU_PIM2: return "AGHK_ATD_RN_2.RN_ATDP_ATU_PIM2";
			case AINK_INT_RN_RN_INTP_ATU_INT_CNTA: return "AINK_INT_RN.RN_INTP_ATU_INT_CNTA";
			case AGHK_ATD_RN_RN_ATDP_VER_FIM_SUM: return "AGHK_ATD_RN.RN_ATDP_VER_FIM_SUM";
			case FATK_PMR_RN_RN_PMRP_TRC_ESP_ATD: return "FATK_PMR_RN.RN_PMRP_TRC_ESP_ATD";
			case AGHK_ATD_RN_RN_ATDP_ATU_PAC_COD: return "AGHK_ATD_RN.RN_ATDP_ATU_PAC_COD";
			case AIPK_PAC_ATU_RN_PACP_ATU_NASC: return "AIPK_PAC_ATU.RN_PACP_ATU_NASC";
			case AINK_INT_RN_RN_INTP_ATU_CNV_EXME: return "AINK_INT_RN.RN_INTP_ATU_CNV_EXME";
			case AINK_INT_RN_RN_INTP_ATU_CNV_CIRG: return "AINK_INT_RN.RN_INTP_ATU_CNV_CIRG";
			case MBCK_CRG_RN2_RN_CRGP_CANC_QUIMIO: return "MBCK_CRG_RN2.RN_CRGP_CANC_QUIMIO";
			case MBCK_CRG_RN2_RN_CRGP_ATU_COTA_PJQ: return  "MBCK_CRG_RN2.RN_CRGP_ATU_COTA_PJQ";
			case FFC_INTERFACE_EQP: return "FFC_INTERFACE_EQP";
			case FFC_INTERFACE_MBC: return "FFC_INTERFACE_MBC";
			case AELK_EXAME_PCT_AELP_GERA_EXAME_PCT: return "AELK_EXAME_PCT.AELP_GERA_EXAME_PCT";
			case FATK_AMB_RN_RN_FATP_ENC_ACO_NEW: return "FATK_AMB_RN.RN_FATP_ENC_ACO_NEW";
			case FATK_AMB_RN_RN_FATP_ENC_EXM_NEW: return "FATK_AMB_RN.RN_FATP_ENC_EXM_NEW";
			case FATK_AMB_RN_RN_FATP_ENC_PRE: return "FATK_AMB_RN.RN_FATP_ENC_PRE";
			case FATK_AMB_RN_RN_FATP_ENC_FOT_NEW: return "FATK_AMB_RN.RN_FATP_ENC_FOT_NEW";
			case FATK_SUS_RN_RN_FATP_ENC_SISCOLO: return "FATK_SUS_RN.RN_FATP_ENC_SISCOLO";
			case FATK_AMB_RN_RN_FATP_ENC_RAD_NEW: return "FATK_AMB_RN.RN_FATP_ENC_RAD_NEW";
			case FATK_AMB_RN_RN_FATP_ENC_OTO_NEW: return "FATK_AMB_RN.RN_FATP_ENC_OTO_NEW";
			case FATK_SUS_RN_RN_FATP_ENC_SISMAMA: return "FATK_SUS_RN.RN_FATP_ENC_SISMAMA";
			case FATK_AMB_RN_RN_FATP_ENC_APAC_NEF: return "FATK_AMB_RN.RN_FATP_ENC_APAC_NEF";
			case FATK_AMB_RN_RN_FATP_ENC_APAC_QUI: return "FATK_AMB_RN.RN_FATP_ENC_APAC_QUI";
			case FATK_PMR_RN_RN_PMRP_ATU_APAC_FUT: return "FATK_PMR_RN.RN_PMRP_ATU_APAC_FUT";
			case SCOP_GERA_AFP_AUT: return "SCOP_GERA_AFP_AUT";
			case SCOP_GERA_AFP_AUT_AUTOMATICA: return "SCOP_GERA_AFP_AUT_AUTOMATICA";
			case EPEP_GERA_PISTA_MCI: return "EPEP_GERA_PISTA_MCI";
			case EPEP_GERA_MVTO_ECE: return "EPEP_GERA_MVTO_ECE";
			case EPEP_GERA_ORDEM_ECE: return "EPEP_GERA_ORDEM_ECE";
			case EPEP_GERA_ITEM_ECE: return "EPEP_GERA_ITEM_ECE";
			case FFC_INTERFACE_AAC_PRJ: return "FFC_INTERFACE_AAC_PRJ";
			case FFC_F_ITEM_CONV_CSP: return "FFC_F_ITEM_CONV_CSP";
			case FFC_F_MATRICULA_PROF: return "FFC_F_MATRICULA_PROF";
			case FFC_F_COD_OPERADORA: return "FFC_F_COD_OPERADORA";
			case FFC_F_BUSCA_SENHA: return "FFC_F_BUSCA_SENHA";
			case FFC_F_BUSCA_DATA_SENHA: return "FFC_F_BUSCA_DATA_SENHA";
			case RN_IAFP_GER_LI_SIAFI: return "RN_IAFP_GER_LI_SIAFI";
			default: return this.name();
		}
	}

	
}
