package br.gov.mec.aghu.paciente.prontuarioonline.business;

public enum ParametrosPOLEnum {
	ACESSO_LIVRE_POL,
	ACESSO_COMISSAO_POL,
	ACESSO_ESPECIAL_POL,
	ACESSO_ADMIN_POL,
	ACESSO_MONITOR_PROJ_PESQ_POL,
	ACESSO_PESQUISADOR_PROJ_POL,
	PAGINA_ORIGEM, ACESSO_VER_FLUXOGRAMA,
	
	ACESSO_DOCS_DIGITALIZADOS_AMB_POL,
	ACESSO_DOCS_DIGITALIZADOS_EME_POL,
	ACESSO_DOCS_DIGITALIZADOS_EXA_POL,
	ACESSO_DOCS_DIGITALIZADOS_INT_POL,
	ACESSO_DOCS_DIGITALIZADOS_INATIVOS,
	
	ATIVA_DIGITALIZACAO_POL, 
	ATIVA_CERTIFICACAO_DIGITAL_POL, 
	DOCUMENTOS_CERTIFICADOS_POL;

	
}
