package br.gov.mec.aghu.sig.custos.processamento.business;

import br.gov.mec.aghu.core.exception.BusinessExceptionCode;

public enum ProcessamentoCustoExceptionCode implements BusinessExceptionCode {
	MENSAGEM_SERVIDOR_NAO_ENCONTRADO,
	MENSAGEM_ERRO_ENUM_NAO_UTILIZADO,
	MENSAGEM_UNIDADE_USO_SEM_FATOR_CONVERSAO,
	MENSAGEM_ERRO_INICIANDO_TRANSACAO_PROCESSAMENTO,
	MENSAGEM_ERRO_REINICIANDO_TRANSACAO_PROCESSAMENTO,
	MENSAGEM_ERRO_COMMIT_TRANSACAO_PROCESSAMENTO,
	MENSAGEM_ERRO_ROLLBACK_TRANSACAO_PROCESSAMENTO,
	MENSAGEM_ERRO_ETAPA_CONTAGEM_DIARIA,
	MENSAGEM_ERRO_ORQUESTRACAO,
	MENSAGEM_ERRO_ETAPA_PROCESSAMENTO_MENSAL,
	MENSAGEM_ABORTA_PROCESSAMENTO,
	MENSAGEM_ERRO_ATIVIDADE_PARAMETRIZADA_NAO_ENCONTRADA,
	MENSAGEM_ERRO_OBJETO_CUSTO_PARAMETRIZADO_NAO_ENCONTRADO,
	MENSAGEM_ERRO_BUSCA_PARAMETROS_COLETA_DIRECIONADORES,
	MENSAGEM_ERRO_BUSCA_DIRECIONADOR,
	MENSAGEM_ERRO_BUSCA_PARAMETROS_CONSUMO_INSUMOS,
	MENSAGEM_UNIDADE_FUNCIONAL_SEM_CC,
	MENSAGEM_SEM_ERRO,
	MENSAGEM_ERRO_BUSCA_PARAMETROS,
	MENSAGEM_ERRO_BUSCA_CATEGORIA_CONSUMO,
	MENSAGEM_ERRO_SERVICO_PATRIMONIO,
	MENSAGEM_ERRO_CLIENTE_SEM_VALOR,
	MENSAGEM_ERRO_DE_CC_OU_PHI_NO_OC;
}