package br.gov.mec.aghu.dominio;

import br.gov.mec.aghu.core.dominio.Dominio;

@SuppressWarnings({"PMD.CyclomaticComplexity"})
public enum DominioPontosParadaSolicitacao implements Dominio {
	
	SOLICITANTE(1),
	AUTORIZACAO_DA_CHEFIA(2),
	PLANEJAMENTO(3),
	GEM_AVALIACAO_TECNICA(4),
	SERVICO_ORCAMENTO(5),
	COMPRADOR_ENGENHARIA(6),
	ANALISE_TECNICA_E_CONTROLE_MATERIAIS(7),
	DESATIVADO_PARECER_TECNICO_USAR_PONTO_PARADA_7(8),
	GENF(9),
	VPA(10),
	COORDENACAO(11),
	LICITACOES(13),
	CALIBRADORES_PONTEIRAS_CONTROLES_E_SIMILARES(15),
	AREA_NEGOCIACAO_PROJETO_E_PESQUISA(26),
	GERACAO_AUTOMATICA(19),
	CONTRATO(20),
	ARQUIVO_MORTO(21),
	RECEBIMENTO_ALMOX(23),
	GPPG(25),
	SC_DIRETOS_ORTESE_PROTESE(27),
	EQUIPE_URGENCIAS(28),
	MATERIAIS_DA_RECREACAO_BRINQUEDOS_EM_MONTAGEM_DE_PROCESSO(29),
	COTACAO_DE_PRECO(30),
	FUNDO_FIXO(32),
	ABERTURA_DE_EDITAL(34),
	LISTA_VPM(36),
	LISTA_VPA(37),
	LISTA_GENF(38),
	GEM_AVALIACAO_DESCRICAO_USUARIO(40),
	USUARIO(44),
	AVALIACAO_TECNICA_CGTI(46),
	AREA_NEGOCIACAO_PLANEJAMENTO(24),
	CODIFICAR_MATERIAL(48),
	CGTI_SAU(50),
	TRIAGEM_GEM_ELETRONICA(56),
	TRIAGEM_GEM_PREDIAL(58),
	TRIAGEM_GEM_EDIFICACOES(59),
	TRIAGEM_GEM_MECANICA(60),
	TRIAGEM_GEM_SECAO_PREDIAL(62),
	AREA_NEGOCIACAO_MEDICAMENTOS(64),
	AREA_NEGOCIACAO_MED_HOSP_SIST_MON_INSTRUMENTAL(65),
	AREA_NEGOCIACAO_DIAGNOSTICO_E_ODONTO(66),
	AREA_NEGOCIACAO_EXP_INF_GRAF_LIMP_SEG_NUT_ROUP(67),
	AREA_NEGOCIACAO_ENG_GASES_COMB_EQUIP_SERV(68),
	ORTESE_PROTESE(70),
	AREA_NEGOCIACAO_DISPENSA_NUTR_ROUP(72),
	GENG_AN_TECNICA_EM_DESC_NAO_AUTORIZADO(74),
	ADM_ASSESSORIA_EM_AVALIACAO(75),
	TORNAR_ESTOCAVEL_ITEM(76),
	AREA_NEGOCIACAO_ORTESE_E_PROTESE(78),
	TRIAGEM_GEM_CMIC(80),
	EXEMPLO_INSERCAO(86);
	
	private int value;
	
	private DominioPontosParadaSolicitacao(int value){
		this.value = value;
	}

	@Override
	public int getCodigo() {
		return value;
	}

	@Override
	public String getDescricao() {
		switch(this){
		case SOLICITANTE: return "SOLICITANTE";
		case AUTORIZACAO_DA_CHEFIA: return "AUTORIZAÇÃO DA CHEFIA";
		case PLANEJAMENTO: return "PLANEJAMENTO";
		case GEM_AVALIACAO_TECNICA: return "GEM-AVALIAÇÃO TÉCNICA";
		case SERVICO_ORCAMENTO: return "SERVIÇO DE ORÇAMENTO";
		case COMPRADOR_ENGENHARIA: return "COMPRADOR ENGENHARIA";
		case ANALISE_TECNICA_E_CONTROLE_MATERIAIS: return "ANÁLISE TÉCNICA E CONTROLE DE MATERIAIS";
		case DESATIVADO_PARECER_TECNICO_USAR_PONTO_PARADA_7: return "DESATIVADO - PARECER TÉCNICO - USAR PONTO PARADA 7";
		case GENF: return "GENF";
		case VPA: return "VPA";
		case COORDENACAO: return "COORDENAÇÃO";
		case LICITACOES: return "LICITAÇÕES";
		case CALIBRADORES_PONTEIRAS_CONTROLES_E_SIMILARES: return "CALIBRADORES, PONTEIRAS, CONTROLES E SIMILARES";
		case AREA_NEGOCIACAO_PROJETO_E_PESQUISA: return "AREA NEGOCIAÇÃO PROJETO E PESQUISA";
		case GERACAO_AUTOMATICA: return "GERAÇÃO AUTOMÁTICA";
		case CONTRATO: return "CONTRATO";
		case ARQUIVO_MORTO: return "ARQUIVO MORTO";
		case RECEBIMENTO_ALMOX: return "RECEBIMENTO ALMOX";
		case GPPG: return "GPPG";
		case SC_DIRETOS_ORTESE_PROTESE: return "SC DIRETOS ORTESE E PROTESE";
		case EQUIPE_URGENCIAS: return "EQUIPE URGÊNCIAS";
		case MATERIAIS_DA_RECREACAO_BRINQUEDOS_EM_MONTAGEM_DE_PROCESSO: return "MATERIAIS DA RECREAÇÃO / BRINQUEDOS EM MONTAGEM DE PROCESSO";
		case COTACAO_DE_PRECO: return "COTAÇÃO DE PREÇO";
		case FUNDO_FIXO: return "FUNDO FIXO";
		case ABERTURA_DE_EDITAL: return "ABERTURA DE EDITAL";
		case LISTA_VPM: return "LISTA VPM";
		case LISTA_VPA: return "LISTA VPA";
		case LISTA_GENF: return "LISTA GENF";
		case GEM_AVALIACAO_DESCRICAO_USUARIO: return "GEM-AVALIAÇÃO DESCRIÇÃO USUARIO";
		case USUARIO: return "USUÁRIO";
		case AVALIACAO_TECNICA_CGTI: return "AVALIAÇÃO TÉCNICA CGTI";
		case AREA_NEGOCIACAO_PLANEJAMENTO: return "AREA NEGOCIAÇÃO / PLANEJAMENTO";
		case CODIFICAR_MATERIAL: return "CODIFICAR MATERIAL";
		case CGTI_SAU: return "CGTI/SAU";
		case TRIAGEM_GEM_ELETRONICA: return "TRIAGEM / GEM-ELETRÔNICA";
		case TRIAGEM_GEM_PREDIAL: return "TRIAGEM / GEM-PREDIAL";
		case TRIAGEM_GEM_EDIFICACOES: return "TRIAGEM / GEM-EDIFICAÇÕES";
		case TRIAGEM_GEM_MECANICA: return "TRIAGEM / GEM-MECÂNICA";
		case TRIAGEM_GEM_SECAO_PREDIAL: return "TRIAGEM - SEÇÃO PREDIAL";
		case AREA_NEGOCIACAO_MEDICAMENTOS: return "AREA NEGOCIAÇÃO / MEDICAMENTOS";
		case AREA_NEGOCIACAO_MED_HOSP_SIST_MON_INSTRUMENTAL: return "AREA NEGOCIAÇÃO  / MED.HOSP-SIST.MON-INSTRUMENTAL";
		case AREA_NEGOCIACAO_DIAGNOSTICO_E_ODONTO: return "AREA  NEGOCIAÇÃO / DIAGNOSTICO E ODONTO";
		case AREA_NEGOCIACAO_EXP_INF_GRAF_LIMP_SEG_NUT_ROUP: return "AREA NEGOCIAÇÃO / EXP.INF. GRAF.LIMP.SEG.NUT.ROUP";
		case AREA_NEGOCIACAO_ENG_GASES_COMB_EQUIP_SERV: return "AREA NEGOCIAÇÃO / ENG.GASES.COMB.EQUIP.SERV.";
		case ORTESE_PROTESE: return "ORTESE & PROTESE";
		case AREA_NEGOCIACAO_DISPENSA_NUTR_ROUP: return "AREA NEGOCIAÇÃO / DISPENSA NUTR.ROUP.";
		case GENG_AN_TECNICA_EM_DESC_NAO_AUTORIZADO: return "GENG/AN_TECNICA/EM-DESC-NÃO-AUTORIZADO";
		case TORNAR_ESTOCAVEL_ITEM: return "TORNAR ESTOCAVEL ITEM";
		case AREA_NEGOCIACAO_ORTESE_E_PROTESE: return "AREA NEGOCIAÇÃO / ÓRTESE E PRÓTESE";
		case TRIAGEM_GEM_CMIC: return "TRIAGEM / GEM - CMIC";
		case EXEMPLO_INSERCAO: return "EXEMPLO INSERCAO";

		default: return "";
		}
	}

}
