package br.gov.mec.aghu.view;

// Generated 28/09/2010 16:24:25 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacaoMedicamento;
import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * VAfaDescrMdtoId generated by hbm2java
 */
@Embeddable
public class VAfaDescrMdtoId implements EntityCompositeId {

	private static final long serialVersionUID = -6146623348305189407L;
	
	private Integer matCodigo;
	private String descricaoMat;
	private DominioSituacaoMedicamento indSituacao;
	private Boolean indPadronizacao;
	private String descricao;
	private Boolean indExigeObservacao;
	private String descricaoEditada;
	private String descLovEditada;
	private Boolean indDiluente;

	public VAfaDescrMdtoId() {
	}

	public VAfaDescrMdtoId(Integer matCodigo,
			String descricaoMat,
			DominioSituacaoMedicamento indSituacao, Date hrioInicioAdmSugerido,
			Boolean indPadronizacao,
			String descricao, 
			Boolean indExigeObservacao, String descricaoEditada,
			String descLovEditada, Boolean indDiluente) {
		this.matCodigo = matCodigo;
		this.descricaoMat = descricaoMat;
		this.indSituacao = indSituacao;
		this.indPadronizacao = indPadronizacao;
		this.descricao = descricao;
		this.indExigeObservacao = indExigeObservacao;
		this.descricaoEditada = descricaoEditada;
		this.descLovEditada = descLovEditada;
		this.indDiluente = indDiluente;
	}

	@Column(name = "MAT_CODIGO", precision = 6, scale = 0)
	public Integer getMatCodigo() {
		return this.matCodigo;
	}

	public void setMatCodigo(Integer matCodigo) {
		this.matCodigo = matCodigo;
	}


	@Column(name = "DESCRICAO_MAT", length = 60)
	@Length(max = 60)
	public String getDescricaoMat() {
		return this.descricaoMat;
	}

	public void setDescricaoMat(String descricaoMat) {
		this.descricaoMat = descricaoMat;
	}

	@Column(name = "IND_SITUACAO", length = 1)
	@Length(max = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacaoMedicamento getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacaoMedicamento indSituacao) {
		this.indSituacao = indSituacao;
	}



	@Column(name = "IND_PADRONIZACAO", length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndPadronizacao() {
		return this.indPadronizacao;
	}

	public void setIndPadronizacao(Boolean indPadronizacao) {
		this.indPadronizacao = indPadronizacao;
	}

	@Column(name = "DESCRICAO", length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_EXIGE_OBSERVACAO", length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndExigeObservacao() {
		return this.indExigeObservacao;
	}

	public void setIndExigeObservacao(Boolean indExigeObservacao) {
		this.indExigeObservacao = indExigeObservacao;
	}

	@Column(name = "DESCRICAO_EDITADA", length = 117)
	@Length(max = 117)
	public String getDescricaoEditada() {
		return this.descricaoEditada;
	}

	public void setDescricaoEditada(String descricaoEditada) {
		this.descricaoEditada = descricaoEditada;
	}

	@Column(name = "DESC_LOV_EDITADA", length = 117)
	@Length(max = 117)
	public String getDescLovEditada() {
		return this.descLovEditada;
	}

	public void setDescLovEditada(String descLovEditada) {
		this.descLovEditada = descLovEditada;
	}

	@Column(name = "IND_DILUENTE", length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndDiluente() {
		return this.indDiluente;
	}

	public void setIndDiluente(Boolean indDiluente) {
		this.indDiluente = indDiluente;
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getIndSituacao());
		umHashCodeBuilder.append(this.getDescricaoEditada());
		umHashCodeBuilder.append(this.getMatCodigo());
		umHashCodeBuilder.append(this.getDescricaoMat());
		umHashCodeBuilder.append(this.getIndPadronizacao());
		umHashCodeBuilder.append(this.getIndExigeObservacao());
		umHashCodeBuilder.append(this.getDescLovEditada());
		umHashCodeBuilder.append(this.getIndDiluente());
		umHashCodeBuilder.append(this.getDescricao());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof VAfaDescrMdtoId)) {
			return false;
		}
		VAfaDescrMdtoId other = (VAfaDescrMdtoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getIndSituacao(), other.getIndSituacao());
		umEqualsBuilder.append(this.getDescricaoEditada(), other.getDescricaoEditada());
		umEqualsBuilder.append(this.getMatCodigo(), other.getMatCodigo());
		umEqualsBuilder.append(this.getDescricaoMat(), other.getDescricaoMat());
		umEqualsBuilder.append(this.getIndPadronizacao(), other.getIndPadronizacao());
		umEqualsBuilder.append(this.getIndExigeObservacao(), other.getIndExigeObservacao());
		umEqualsBuilder.append(this.getDescLovEditada(), other.getDescLovEditada());
		umEqualsBuilder.append(this.getIndDiluente(), other.getIndDiluente());
		umEqualsBuilder.append(this.getDescricao(), other.getDescricao());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
