package br.gov.mec.aghu.view;

// Generated 01/10/2010 10:48:32 by Hibernate Tools 3.2.5.Beta

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.model.AfaFormaDosagem;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * VMpmDosagem generated by hbm2java
 */
@Entity
@Table(name = "V_MPM_DOSAGEM", schema = "AGH")
@Immutable
public class VMpmDosagem extends BaseEntityId<VMpmDosagemId> implements java.io.Serializable {

	private static final long serialVersionUID = -38194172625800535L;

	private VMpmDosagemId id;

	private AfaFormaDosagem formaDosagem;
	
	private String seqUnidade;
	private String descricaoUnidade;
	private Integer fdsUmmSeq;
	private Integer seqDosagem;

	
	public VMpmDosagem() {
	}

	public VMpmDosagem(VMpmDosagemId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "seqDosagem", column = @Column(name = "SEQ_DOSAGEM", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "seqMedicamento", column = @Column(name = "SEQ_MEDICAMENTO", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "fatorConversao", column = @Column(name = "FATOR_CONVERSAO", nullable = false, precision = 14, scale = 4)),
			@AttributeOverride(name = "indSituacao", column = @Column(name = "IND_SITUACAO", nullable = false, length = 1)),
			@AttributeOverride(name = "fdsIndUsualNpt", column = @Column(name = "FDS_IND_USUAL_NPT", nullable = false, length = 1))})
	public VMpmDosagemId getId() {
		return this.id;
	}

	public void setId(VMpmDosagemId id) {
		this.id = id;
	}

	@Column(name = "SEQ_UNIDADE", length = 5)
	@Length(max = 5)
	public String getSeqUnidade() {
		return this.seqUnidade;
	}

	public void setSeqUnidade(String seqUnidade) {
		this.seqUnidade = seqUnidade;
	}

	@Column(name = "DESCRICAO_UNIDADE", length = 60)
	@Length(max = 60)
	public String getDescricaoUnidade() {
		return this.descricaoUnidade;
	}

	public void setDescricaoUnidade(String descricaoUnidade) {
		this.descricaoUnidade = descricaoUnidade;
	}

	@Column(name = "FDS_UMM_SEQ", precision = 5, scale = 0)
	public Integer getFdsUmmSeq() {
		return this.fdsUmmSeq;
	}

	public void setFdsUmmSeq(Integer fdsUmmSeq) {
		this.fdsUmmSeq = fdsUmmSeq;
	}

	@ManyToOne
	@JoinColumn(name = "SEQ_DOSAGEM", referencedColumnName = "SEQ", insertable = false, updatable = false)
	public AfaFormaDosagem getFormaDosagem() {
		return formaDosagem;
	}

	public void setFormaDosagem(AfaFormaDosagem formaDosagem) {
		this.formaDosagem = formaDosagem;
	}
	
	@Column(name = "SEQ_DOSAGEM", insertable = false, updatable = false)
	public Integer getSeqDosagem() {
		return seqDosagem;
	}

	public void setSeqDosagem(Integer seqDosagem) {
		this.seqDosagem = seqDosagem;
	}
	
	@Transient
	public String getSiglaUnidadeMedidaMedica(){
		String str = null;
		if(this.formaDosagem.getUnidadeMedidaMedicas() != null && this.formaDosagem.getUnidadeMedidaMedicas().getDescricao() != null){
			str = StringUtils.abbreviate(this.formaDosagem.getUnidadeMedidaMedicas().getDescricao(), 5);
		}
		else if(this.seqUnidade != null){
			str = StringUtils.abbreviate(this.seqUnidade, 5);
		}
		return str;
	}

	public enum Fields {
		SEQ_DOSAGEM("id.seqDosagem"),
		SEQ_MEDICAMENTO("id.seqMedicamento"),
		SEQ_UNIDADE("seqUnidade"),
		DESCRICAO_UNIDADE("descricaoUnidade"),
		FATOR_CONVERSAO("id.fatorConversao"),
		IND_SITUACAO("id.indSituacao"),
		FDS_IND_USUAL_NPT("id.fdsIndUsualNpt"),
		FDS_UMM_SEQ("fdsUmmSeq"),
		FORMA_DOSAGEM("formaDosagem");
		
		String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}

	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof VMpmDosagem)) {
			return false;
		}
		VMpmDosagem other = (VMpmDosagem) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}

}
