package br.gov.mec.aghu.casca.exceptioncode;

import br.gov.mec.aghu.core.exception.BusinessExceptionCode;

public enum AplicacaoONExceptionCode implements BusinessExceptionCode {
	CASCA_MENSAGEM_APLICACAO_NAO_INFORMADA, CASCA_MENSAGEM_APLICACAO_JA_CADASTRADA, 
	CASCA_MENSAGEM_PARAMETRO_NAO_INFORMADO, CASCA_VIOLACAO_FK_APLICACAO, 
	CASCA_MENSAGEM_APLICACAO_SEM_CONTEXTO, CASCA_MENSAGEM_APLICACAO_SEM_SERVIDOR, 
	CASCA_MENSAGEM_APLICACAO_SEM_PORTA,CASCA_MENSAGEM_APLICACAO_SEM_NOME
	; 

}
