package br.gov.mec.aghu.casca.exceptioncode;

import br.gov.mec.aghu.core.exception.BusinessExceptionCode;

public enum PermissaoONExceptionCode implements BusinessExceptionCode {
	
	CASCA_MENSAGEM_PERMISSAO_NAO_INFORMADO, CASCA_MENSAGEM_PARAMETRO_NAO_INFORMADO
	, CASCA_MENSAGEM_SUCESSO_INCLUSAO_PERMISSAO, CASCA_MENSAGEM_PERMISSAO_EXISTENTE
	, CASCA_MENSAGEM_PERMISSAO_NAO_EXISTENTE, CASCA_VIOLACAO_FK_PERMISSAO, CASCA_MENSAGEM_ACTION_NAO_INFORMADA
	, CASCA_MENSAGEM_ACTION_RELACIONADA, CASCA_MENSAGEM_PERMISSAO_EXISTENTE_PERFIL
	, CASCA_MENSAGEM_COMPONENTE_EXISTENTE_PERMISSAO
	;


}
