package br.gov.mec.aghu.casca.exceptioncode;

import br.gov.mec.aghu.core.exception.BusinessExceptionCode;

public enum UsuarioONExceptionCode implements BusinessExceptionCode {
	
	CASCA_MENSAGEM_USUARIO_NAO_INFORMADO, CASCA_MENSAGEM_LOGIN_EXISTENTE
	, CASCA_MENSAGEM_USUARIO_NAO_ENCONTRADO, CASCA_MENSAGEM_PARAMETROS_NAO_INFORMADO
	, CASCA_MENSAGEM_USUARIO_NAO_LOGADO, CASCA_MENSAGEM_SENHA_FRACA, CASCA_MENSAGEM_USUARIO_INATIVO
	, CASCA_MENSAGEM_USUARIO_SEM_PERFIL, CASCA_MENSAGEM_HORA_DIFERENTE, ERRO_AUTENTICACAO
	;


}
