package br.gov.mec.controller;

import br.gov.mec.aghu.core.business.VariaveisSessao;


/**
 * Enum usada como chave para os atributos que ficarem no contexto de sessão do
 * AGHU.
 * 
 * @author gmneto
 */
public enum VariaveisSessaoEnum implements VariaveisSessao {
	
	MPMK_IME_RN_AUTO_EXCLUIR_PROCEDIMENTO_MEDICAMENTO_SOL, // MPMK_IME_RN.V_AUT_EXCLUIR_PRCR_MED_SOL
	ABSK_ISH_RN_AUTO_EXCLUIR_ITEM_HEMOTERAPICA, // ABSK_ISH_RN.V_AUT_EXCLUIR_ITEM_HEMO
	ABSK_ISJ_RN_AUTO_EXCLUIR_JUSTIFICATIVA_ITEM_HEMOTERAPICA, // ABSK_ISJ_RN.V_AUT_EXCLUIR_ITEM_HEMO
	ABSK_ABS_RN_ORIGEM, // ABSK_ABS_RN.P_ORIGEM
	FATK_CTH2_RN_UN_V_MAIOR_VALOR, // FATK_CTH2_RN_UN.V_MAIOR_VALOR
	FATK_CTH2_RN_UN_V_IDADE_BCO_UTI, // FATK_CTH2_RN_UN.V_IDADE_BCO_UTI
	FATK_CTH4_RN_UN_V_ATU_CTH_SSM_SOL, // FATK_CTH4_RN_UN.V_ATU_CTH_SSM_SOL
	FATK_DCS_RN_V_SUBST_PRONT_DCS, // fatk_dcs_rn.v_subst_pront_dcs
	SCEK_IPS_V_EXCLUIR_RMP, // SCEK_IPS.V_EXCLUIR_RMP
	FATK_IPC_RN_V_IPC_INCLUI, // fatk_ipc_rn.v_ipc_inclui
	INCONSISTENCIA_RELATORIO_FATURAMENTO,
	FATK_PMR_RN_V_PMR_JOURNAL, // fatk_pmr_rn.v_pmr_journal
	FATK_PMR_RN_V_PMR_ENCERRAMENTO, // fatk_pmr_rn.v_pmr_encerramento
	FATK_INTERFACE_AAC_V_EXEC_AGRUPAMENTO, // FATK_INTERFACE_AAC.v_exec_agrupamento
	MCOK_BSR_RN_V_VER_DT_ROMP, // MCOK_BSR_RN.V_VER_DT_ROMP
	MCOK_BAL_RN_V_VEIO_SUBS_GESTA_BAL, // MCOK_BAL_RN.V_VEIO_SUBS_GESTA_BAL
	MCOK_EFI_RN_V_VEIO_TROCA_PAC, // MCOK_EFI_RN.V_VEIO_TROCA_PAC
	MCOK_IDC_RN_V_VEIO_SUBS_GESTA_IDC, // MCOK_IDC_RN.V_VEIO_SUBS_GESTA_IDC
	MCOK_INN_RN_V_VEIO_TROCA_PAC, // MCOK_INN_RN.V_VEIO_TROCA_PAC
	MCOK_NAS_RN_V_VEIO_UPD_NAS, // MCOK_NAS_RN.V_VEIO_UPD_NAS
	MCOK_NAS_RN_V_VEIO_TROCA_PAC, // MCOK_NAS_RN.V_VEIO_TROCA_PAC
	MCOK_RNA_RN_V_VEIO_UPD_RNA, // MCOK_RNA_RN.V_VEIO_UPD_RNA
	MCOK_RNA_RN_V_VEIO_TROCA_PAC, // MCOK_RNA_RN.V_VEIO_TROCA_PAC
	MCOK_SNA_RN_V_VEIO_SUBS_GESTA, // MCOK_SNA_RN.V_VEIO_SUBS_GESTA
	AACK_PRH_RN_V_APAC_DIARIA, // aack_prh_rn.v_apac_diaria
	FATK_CAP_RN_V_CAP_ENCERRAMENTO, //FATK_CAP_RN.V_CAP_ENCERRAMENTO
	FATK_EPS_RN_V_EPS_ENCERRAMENTO, //FATK_EPS_RN.V_EPS_ENCERRAMENTO
	SCOK_ITL_V_CONFIRMA_GERA_CLASSIF, //scok_itl.v_confirma_gera_classif
	SCOK_LCT_RN_V_EXECUTA_ATU_PREV_ORC, //scok_lct_rn.v_executa_atu_prev_orc
	AACK_AAA_RN_V_PROTESE_AUDITIVA, //AACK_AAA_RN.V_PROTESE_AUDITIVA
	SCOK_ITL_V_EXCLUIR_LICITACOES, //scok_itl.v_excluir_licitacoes
	AEL_LISTA_DESENHOS_MASCARAS_EXAMES,
	AIPF_PRNTOL_ADMIN,
	AIP_PRONTUARIO_PACIENTE,
	POL_NODO_SELECIONADO,
	DADOS_PESO_ALTURA_PACIENTE,
	MBCK_AGD_RN_CONSISTE_HORARIO //MBCK_AGD_RN.consiste_horario
	;
	
	
}