package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AacConsultaPmpa generated by hbm2java
 */
@Entity
@Table(name = "AAC_CONSULTA_PMPAS", schema = "AGH")
public class AacConsultaPmpa extends BaseEntityId<AacConsultaPmpaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7512676320202755145L;
	private AacConsultaPmpaId id;

	public AacConsultaPmpa() {
	}

	public AacConsultaPmpa(AacConsultaPmpaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "espec", column = @Column(name = "ESPEC")),
			@AttributeOverride(name = "espaco1", column = @Column(name = "ESPACO1", length = 1)),
			@AttributeOverride(name = "unidade", column = @Column(name = "UNIDADE")),
			@AttributeOverride(name = "dataCons", column = @Column(name = "DATA_CONS", length = 29)),
			@AttributeOverride(name = "horaCons", column = @Column(name = "HORA_CONS", length = 29)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false)),
			@AttributeOverride(name = "tipo", column = @Column(name = "TIPO")),
			@AttributeOverride(name = "sit", column = @Column(name = "SIT")),
			@AttributeOverride(name = "paciente", column = @Column(name = "PACIENTE", length = 50)),
			@AttributeOverride(name = "dataNasc", column = @Column(name = "DATA_NASC", length = 29)),
			@AttributeOverride(name = "idAnos", column = @Column(name = "ID_ANOS")),
			@AttributeOverride(name = "idMeses", column = @Column(name = "ID_MESES")),
			@AttributeOverride(name = "nomeMae", column = @Column(name = "NOME_MAE", length = 50)),
			@AttributeOverride(name = "endPac", column = @Column(name = "END_PAC", length = 60)),
			@AttributeOverride(name = "nro", column = @Column(name = "NRO")),
			@AttributeOverride(name = "compl", column = @Column(name = "COMPL", length = 25)),
			@AttributeOverride(name = "bairro", column = @Column(name = "BAIRRO", length = 20)),
			@AttributeOverride(name = "cep", column = @Column(name = "CEP")),
			@AttributeOverride(name = "munic", column = @Column(name = "MUNIC", length = 35)),
			@AttributeOverride(name = "sigla", column = @Column(name = "SIGLA", length = 10)),
			@AttributeOverride(name = "sala", column = @Column(name = "SALA")),
			@AttributeOverride(name = "conNumero", column = @Column(name = "CON_NUMERO")),
			@AttributeOverride(name = "codCentral", column = @Column(name = "COD_CENTRAL")),
			@AttributeOverride(name = "sisPrenatal", column = @Column(name = "SIS_PRENATAL")),
			@AttributeOverride(name = "tipoArquivo", column = @Column(name = "TIPO_ARQUIVO")),
			@AttributeOverride(name = "postoSaude", column = @Column(name = "POSTO_SAUDE", length = 50)),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false)),
			@AttributeOverride(name = "criadoEm", column = @Column(name = "CRIADO_EM", length = 29)) })
	public AacConsultaPmpaId getId() {
		return this.id;
	}

	public void setId(AacConsultaPmpaId id) {
		this.id = id;
	}

	public enum Fields {

		ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
