package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AacConsCargaBull generated by hbm2java
 */
@Entity
@Table(name = "AAC_CONS_CARGA_BULL", schema = "AGH")
public class AacConsCargaBull extends BaseEntityId<AacConsCargaBullId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6654933443862150356L;
	private AacConsCargaBullId id;

	public AacConsCargaBull() {
	}

	public AacConsCargaBull(AacConsCargaBullId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "conNumero", column = @Column(name = "CON_NUMERO")),
			@AttributeOverride(name = "grdSeq", column = @Column(name = "GRD_SEQ")),
			@AttributeOverride(name = "dtConsulta", column = @Column(name = "DT_CONSULTA", length = 8)),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false)) })
	public AacConsCargaBullId getId() {
		return this.id;
	}

	public void setId(AacConsCargaBullId id) {
		this.id = id;
	}

	public enum Fields {

		ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
