package br.gov.mec.aghu.model;

// Generated 16/03/2011 16:07:52 by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AacTipoAgendamentos generated by hbm2java
 */
 
@Entity
@SequenceGenerator(name="aacTagSq1", sequenceName="AGH.AAC_TAG_SQ1", allocationSize = 1)
@Table(name = "AAC_TIPO_AGENDAMENTOS", schema = "AGH")
public class AacTipoAgendamento extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4153303568819019847L;
	private Short seq;
	private String descricao;
	private DominioSituacao situacao;
	private Date criadoEm;
	private RapServidores servidor;
	private Date alteradoEm;
	private RapServidores servidorAlterado;

	private Set<AacFormaAgendamento> formaAgendamento = new HashSet<AacFormaAgendamento>(
			0);
	private Set<AacFormaEspecialidade> formaEspecialidade = new HashSet<AacFormaEspecialidade>(
			0);

	
	public AacTipoAgendamento() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aacTagSq1")
	@Column(name = "SEQ", unique = true, nullable = false, precision = 3, scale = 0)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getSituacao() {
		return this.situacao;
	}

	public void setSituacao(DominioSituacao situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 7)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_ALTERADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_ALTERADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorAlterado() {
		return this.servidorAlterado;
	}
	
	public void setServidorAlterado(RapServidores servidorAlterado) {
		this.servidorAlterado = servidorAlterado;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAgendamento")
	public Set<AacFormaAgendamento> getFormaAgendamento() {
		return formaAgendamento;
	}

	public void setFormaAgendamento(Set<AacFormaAgendamento> formaAgendamento) {
		this.formaAgendamento = formaAgendamento;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAgendamento")
	public Set<AacFormaEspecialidade> getFormaEspecialidade() {
		return formaEspecialidade;
	}

	public void setFormaEspecialidade(Set<AacFormaEspecialidade> formaEspecialidade) {
		this.formaEspecialidade = formaEspecialidade;
	}
	
	public static enum Fields {
		SEQ("seq"), SITUACAO("situacao"), FORMA_AGENDAMENTO("formaAgendamento"),
		PAGADOR("formaAgendamento.pagador"), DESCRICAO("descricao");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seq == null) ? 0 : seq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		
		if (obj == null || !(obj instanceof AacTipoAgendamento)){		
			return false;
		}	
		AacTipoAgendamento other = (AacTipoAgendamento) obj;
		if (seq == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!seq.equals(other.getSeq())) {
			return false;
		}
		return true;
	}	
	
}
