package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

/**
 * AbsCadFonemaCandDoador generated by hbm2java
 */
@Entity
@Table(name = "ABS_CAD_FONEMAS_CAND_DOADORES", schema = "AGH")
public class AbsCadFonemaCandDoador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4759533412340679262L;
	private String fonema;
	private Integer version;
	private Long contador;
	private Set<AbsFonemaCandDoador> absFonemaCandDoadores = new HashSet<AbsFonemaCandDoador>(0);

	public AbsCadFonemaCandDoador() {
	}

	public AbsCadFonemaCandDoador(String fonema, Long contador) {
		this.fonema = fonema;
		this.contador = contador;
	}

	public AbsCadFonemaCandDoador(String fonema, Long contador, Set<AbsFonemaCandDoador> absFonemaCandDoadores) {
		this.fonema = fonema;
		this.contador = contador;
		this.absFonemaCandDoadores = absFonemaCandDoadores;
	}

	@Id
	@Column(name = "FONEMA", unique = true, nullable = false, length = 6)
	@Length(max = 6)
	public String getFonema() {
		return this.fonema;
	}

	public void setFonema(String fonema) {
		this.fonema = fonema;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "CONTADOR", nullable = false)
	public Long getContador() {
		return this.contador;
	}

	public void setContador(Long contador) {
		this.contador = contador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "absCadFonemaCandDoador")
	public Set<AbsFonemaCandDoador> getAbsFonemaCandDoadores() {
		return this.absFonemaCandDoadores;
	}

	public void setAbsFonemaCandDoadores(Set<AbsFonemaCandDoador> absFonemaCandDoadores) {
		this.absFonemaCandDoadores = absFonemaCandDoadores;
	}

	public enum Fields {

		FONEMA("fonema"),
		VERSION("version"),
		CONTADOR("contador"),
		ABS_FONEMA_CAND_DOADORES("absFonemaCandDoadores");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getFonema() == null) ? 0 : getFonema().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AbsCadFonemaCandDoador)) {
			return false;
		}
		AbsCadFonemaCandDoador other = (AbsCadFonemaCandDoador) obj;
		if (getFonema() == null) {
			if (other.getFonema() != null) {
				return false;
			}
		} else if (!getFonema().equals(other.getFonema())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
