package br.gov.mec.aghu.model;

// Generated 21/09/2010 19:23:57 by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.exception.BaseRuntimeException;
import br.gov.mec.aghu.core.exception.BusinessExceptionCode;
import br.gov.mec.aghu.core.persistence.BaseEntityCodigo;

/**
 * AbsComponentesSanguineos generated by hbm2java
 */

@Entity
@Table(name = "ABS_COMPONENTES_SANGUINEOS", schema = "AGH")
public class AbsComponenteSanguineo extends BaseEntityCodigo<String> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1797413799544712063L;
	private String codigo;
	private String descricao;
	private Boolean indIrradiado;
	private Boolean indAmostra;
	private Boolean indFiltrado;
	private Boolean indLavado;
	private RapServidores rapServidores;
	private DominioSituacao indSituacao;
	private Short nroDiasValidade;
	private Byte codTransfusao;
	private Byte codCedenciaBanco;
	private Byte codCedenciaIndustria;
	private Byte codAutotransfusao;
	private String informacoes;
	private Date criadoEm;
	private Boolean indPermitePrescricao;
	private Boolean indJustificativa;
	private String armazenarEm;
	private Boolean indPermitePool;
	private Boolean indEtiquetaDoacao;
	private String descricaoEtiqueta;
	private BigDecimal densidade;
	private Boolean indPermiteRefracionamento;
	private Boolean indAferese;
	private String mensSolicAferese;
	private Date tempo;
	private String avisoPrescricao;
	private Set<AbsItensSolHemoterapicas> absItensSolHemoterapicases = new HashSet<AbsItensSolHemoterapicas>(0);
	private List<AbsValidAmostrasComponentes> absValidAmostrasComponentes = new ArrayList<AbsValidAmostrasComponentes>(0);
	private List<MbcAgendaHemoterapia> agendaHemoterapias = new ArrayList<MbcAgendaHemoterapia>();
	private Set<FatProcedHospInternos> fatProcedHospInternos = new HashSet<FatProcedHospInternos>(0);
	
	private enum AbsComponenteSanguineoExceptionCode implements BusinessExceptionCode {
		AFERESE_INVALIDO
	}
	
	public AbsComponenteSanguineo() {
	}

	@SuppressWarnings({"PMD.ExcessiveParameterList"})
	public AbsComponenteSanguineo(String codigo, String descricao,
			Boolean indIrradiado, Boolean indAmostra, Boolean indFiltrado,
			Boolean indLavado, RapServidores rapServidores,
			DominioSituacao indSituacao, Short nroDiasValidade,
			Byte codTransfusao, Byte codCedenciaBanco,
			Byte codCedenciaIndustria, Byte codAutotransfusao,
			String informacoes, Date criadoEm, Boolean indPermitePrescricao,
			Boolean indJustificativa, String armazenarEm,
			Boolean indPermitePool, Boolean indEtiquetaDoacao,
			String descricaoEtiqueta, BigDecimal densidade,
			Boolean indPermiteRefracionamento, Boolean indAferese,
			String mensSolicAferese, Date tempo, String avisoPrescricao,
			Set<AbsItensSolHemoterapicas> absItensSolHemoterapicases,
			List<AbsValidAmostrasComponentes> absValidAmostrasComponentes) {
		super();
		this.codigo = codigo;
		this.descricao = descricao;
		this.indIrradiado = indIrradiado;
		this.indAmostra = indAmostra;
		this.indFiltrado = indFiltrado;
		this.indLavado = indLavado;
		this.rapServidores = rapServidores;
		this.indSituacao = indSituacao;
		this.nroDiasValidade = nroDiasValidade;
		this.codTransfusao = codTransfusao;
		this.codCedenciaBanco = codCedenciaBanco;
		this.codCedenciaIndustria = codCedenciaIndustria;
		this.codAutotransfusao = codAutotransfusao;
		this.informacoes = informacoes;
		this.criadoEm = criadoEm;
		this.indPermitePrescricao = indPermitePrescricao;
		this.indJustificativa = indJustificativa;
		this.armazenarEm = armazenarEm;
		this.indPermitePool = indPermitePool;
		this.indEtiquetaDoacao = indEtiquetaDoacao;
		this.descricaoEtiqueta = descricaoEtiqueta;
		this.densidade = densidade;
		this.indPermiteRefracionamento = indPermiteRefracionamento;
		this.indAferese = indAferese;
		this.mensSolicAferese = mensSolicAferese;
		this.tempo = tempo;
		this.avisoPrescricao = avisoPrescricao;
		this.absItensSolHemoterapicases = absItensSolHemoterapicases;
		this.absValidAmostrasComponentes = absValidAmostrasComponentes;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, length = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_IRRADIADO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndIrradiado() {
		return this.indIrradiado;
	}

	public void setIndIrradiado(Boolean indIrradiado) {
		this.indIrradiado = indIrradiado;
	}

	@Column(name = "IND_AMOSTRA", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAmostra() {
		return this.indAmostra;
	}

	public void setIndAmostra(Boolean indAmostra) {
		this.indAmostra = indAmostra;
	}

	@Column(name = "IND_FILTRADO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndFiltrado() {
		return this.indFiltrado;
	}

	public void setIndFiltrado(Boolean indFiltrado) {
		this.indFiltrado = indFiltrado;
	}

	@Column(name = "IND_LAVADO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndLavado() {
		return this.indLavado;
	}

	public void setIndLavado(Boolean indLavado) {
		this.indLavado = indLavado;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
		@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
		@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "NRO_DIAS_VALIDADE", precision = 4, scale = 0)
	public Short getNroDiasValidade() {
		return this.nroDiasValidade;
	}

	public void setNroDiasValidade(Short nroDiasValidade) {
		this.nroDiasValidade = nroDiasValidade;
	}

	@Column(name = "COD_TRANSFUSAO", precision = 2, scale = 0)
	public Byte getCodTransfusao() {
		return this.codTransfusao;
	}

	public void setCodTransfusao(Byte codTransfusao) {
		this.codTransfusao = codTransfusao;
	}

	@Column(name = "COD_CEDENCIA_BANCO", precision = 2, scale = 0)
	public Byte getCodCedenciaBanco() {
		return this.codCedenciaBanco;
	}

	public void setCodCedenciaBanco(Byte codCedenciaBanco) {
		this.codCedenciaBanco = codCedenciaBanco;
	}

	@Column(name = "COD_CEDENCIA_INDUSTRIA", precision = 2, scale = 0)
	public Byte getCodCedenciaIndustria() {
		return this.codCedenciaIndustria;
	}

	public void setCodCedenciaIndustria(Byte codCedenciaIndustria) {
		this.codCedenciaIndustria = codCedenciaIndustria;
	}

	@Column(name = "COD_AUTOTRANSFUSAO", precision = 2, scale = 0)
	public Byte getCodAutotransfusao() {
		return this.codAutotransfusao;
	}

	public void setCodAutotransfusao(Byte codAutotransfusao) {
		this.codAutotransfusao = codAutotransfusao;
	}
	
	@Lob
	@Type(type="text")
	@Column(name = "INFORMACOES")	
	public String getInformacoes() {
		return this.informacoes;
	}

	public void setInformacoes(String informacoes) {
		this.informacoes = informacoes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "IND_PERMITE_PRESCRICAO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndPermitePrescricao() {
		return this.indPermitePrescricao;
	}

	public void setIndPermitePrescricao(Boolean indPermitePrescricao) {
		this.indPermitePrescricao = indPermitePrescricao;
	}

	@Column(name = "IND_JUSTIFICATIVA", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndJustificativa() {
		return this.indJustificativa;
	}

	public void setIndJustificativa(Boolean indJustificativa) {
		this.indJustificativa = indJustificativa;
	}

	@Column(name = "ARMAZENAR_EM", length = 30)
	public String getArmazenarEm() {
		return this.armazenarEm;
	}

	public void setArmazenarEm(String armazenarEm) {
		this.armazenarEm = armazenarEm;
	}

	@Column(name = "IND_PERMITE_POOL", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndPermitePool() {
		return this.indPermitePool;
	}

	public void setIndPermitePool(Boolean indPermitePool) {
		this.indPermitePool = indPermitePool;
	}

	@Column(name = "IND_ETIQUETA_DOACAO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndEtiquetaDoacao() {
		return this.indEtiquetaDoacao;
	}

	public void setIndEtiquetaDoacao(Boolean indEtiquetaDoacao) {
		this.indEtiquetaDoacao = indEtiquetaDoacao;
	}

	@Column(name = "DESCRICAO_ETIQUETA", length = 15)
	public String getDescricaoEtiqueta() {
		return this.descricaoEtiqueta;
	}

	public void setDescricaoEtiqueta(String descricaoEtiqueta) {
		this.descricaoEtiqueta = descricaoEtiqueta;
	}

	@Column(name = "DENSIDADE", precision = 7, scale = 4)
	public BigDecimal getDensidade() {
		return this.densidade;
	}

	public void setDensidade(BigDecimal densidade) {
		this.densidade = densidade;
	}

	@Column(name = "IND_PERMITE_REFRACIONAMENTO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndPermiteRefracionamento() {
		return this.indPermiteRefracionamento;
	}

	public void setIndPermiteRefracionamento(Boolean indPermiteRefracionamento) {
		this.indPermiteRefracionamento = indPermiteRefracionamento;
	}

	@Column(name = "IND_AFERESE", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAferese() {
		return this.indAferese;
	}

	public void setIndAferese(Boolean indAferese) {
		this.indAferese = indAferese;
	}

	@Column(name = "MENS_SOLIC_AFERESE", length = 500)
	public String getMensSolicAferese() {
		return this.mensSolicAferese;
	}

	public void setMensSolicAferese(String mensSolicAferese) {
		this.mensSolicAferese = mensSolicAferese;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TEMPO", length = 7)
	public Date getTempo() {
		return this.tempo;
	}

	public void setTempo(Date tempo) {
		this.tempo = tempo;
	}
	
	@Column(name = "AVISO_PRESCRICAO", length = 500)
	public String getAvisoPrescricao() {
		return this.avisoPrescricao;
	}

	public void setAvisoPrescricao(String avisoPrescricao) {
		this.avisoPrescricao = avisoPrescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "componenteSanguineo")
	public Set<AbsItensSolHemoterapicas> getAbsItensSolHemoterapicases() {
		return this.absItensSolHemoterapicases;
	}

	public void setAbsItensSolHemoterapicases(
			Set<AbsItensSolHemoterapicas> absItensSolHemoterapicases) {
		this.absItensSolHemoterapicases = absItensSolHemoterapicases;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "componenteSanguineo")
	protected List<AbsValidAmostrasComponentes> getAbsValidAmostrasComponentes() {
		return absValidAmostrasComponentes;
	}

	protected void setAbsValidAmostrasComponentes(
			List<AbsValidAmostrasComponentes> absValidAmostrasComponentes) {
		this.absValidAmostrasComponentes = absValidAmostrasComponentes;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "componenteSanguineo")
	protected Set<FatProcedHospInternos> getFatProcedHospInternos() {
		return fatProcedHospInternos;
	}

	protected void setFatProcedHospInternos(Set<FatProcedHospInternos> fatProcedHospInternos) {
		this.fatProcedHospInternos = fatProcedHospInternos;
	}
	
	/**
	 * Função de validação dos dados antes que ocorra
	 * a persistência.
	 */
	@PrePersist
	@PreUpdate
	@SuppressWarnings("unused")
	private void valida() {
		
		// CONSTRAINT ABS_CSA_CK13
		if (!((this.indAferese != null && !this.indAferese && this.mensSolicAferese == null) || (this.indAferese != null && this.indAferese))) {
			throw new BaseRuntimeException(AbsComponenteSanguineoExceptionCode.AFERESE_INVALIDO);
		}
		
	}
	
	/**
	 * FIELDS
	 * @author bsoliveira
	 *
	 */
	public enum Fields {

		CODIGO("codigo"), DESCRICAO("descricao"), IND_IRRADIADO("indIrradiado"), IND_AMOSTRA("indAmostra"),
		IND_FILTRADO("indFiltrado"), IND_LAVADO("indLavado"), RAP_SERVIDORES("rapServidores"),  
		IND_SITUACAO("indSituacao"), NRO_DIAS_VALIDADE("nroDiasValidade"), COD_TRANSFUSAO("codTransfusao"),
		COD_CEDENCIA_BANCO("codCedenciaBanco"), COD_CEDENCIA_INDUSTRIA("codCedenciaIndustria"),
		COD_AUTOTRANSFUSAO("codAutotransfusao"), INFORMACOES("informacoes"), CRIADO_EM("criadoEm"), 
		IND_PERMITE_PRESCRICAO("indPermitePrescricao"), IND_JUSTIFICATIVA("indJustificativa"),
		ARMAZENAR_EM("armazenarEm"), IND_PERMITE_POOL("indPermitePool"), IND_ETIQUETA_DOACAO("indEtiquetaDoacao"),
		DESCRICAO_ETIQUETA("descricaoEtiqueta"), DENSIDADE("densidade"), IND_PERMITE_REFRACIONAMENTO("indPermiteRefracionamento"),
		IND_AFERESE("indAferese"), MENS_SOLIC_AFERESE("mensSolicAferese"), TEMPO("tempo"), 
		ABS_ITENS_SOL_HEMOTERAPICASES("absItensSolHemoterapicases"),
		AGENDA_HEMOTERAPIAS("agendaHemoterapias"),
		FAT_PROCED_HOSP_INTERNOS("fatProcedHospInternos");
				
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}

	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getCodigo() == null) ? 0 : getCodigo().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AbsComponenteSanguineo)) {
			return false;
		}
		AbsComponenteSanguineo other = (AbsComponenteSanguineo) obj;
		if (getCodigo() == null) {
			if (other.getCodigo() != null) {
				return false;
			}
		} else if (!getCodigo().equals(other.getCodigo())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "absComponenteSanguineo")
	public List<MbcAgendaHemoterapia> getAgendaHemoterapias() {
		return agendaHemoterapias;
	}

	public void setAgendaHemoterapias(List<MbcAgendaHemoterapia> agendaHemoterapia) {
		this.agendaHemoterapias = agendaHemoterapia;
	}

}
