package br.gov.mec.aghu.model;

// Generated 08/02/2010 17:25:25 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AbsSolicitacoesPorAmostra generated by hbm2java
 */
@Entity
@SequenceGenerator(name="absSpaSq1", sequenceName="AGH.ABS_SPA_SQ1", allocationSize = 1)
@Table(name = "ABS_SOLICITACOES_POR_AMOSTRA", schema = "AGH")
public class AbsSolicitacoesPorAmostra extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 486351413073111740L;
	private Integer seq;
	private AbsAmostrasPacientes amostraPaciente;
	private Integer sheAtdSeq;
	private Integer sheSeq;
	private Date criadoEm;
	private RapServidores rapServidores;
	private DominioSituacao indSituacao;

	public AbsSolicitacoesPorAmostra() {
	}

	public AbsSolicitacoesPorAmostra(Integer seq,
			AbsAmostrasPacientes amostraPaciente, Integer sheAtdSeq,
			Integer sheSeq, Date criadoEm, RapServidores rapServidores,
			DominioSituacao indSituacao) {
		this.seq = seq;
		this.amostraPaciente = amostraPaciente;
		this.sheAtdSeq = sheAtdSeq;
		this.sheSeq = sheSeq;
		this.criadoEm = criadoEm;
		this.rapServidores = rapServidores;
		this.indSituacao = indSituacao;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "absSpaSq1")
	@Column(name = "SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@JoinColumns( {
			@JoinColumn(name = "APA_PAC_CODIGO", referencedColumnName = "PAC_CODIGO", nullable = false),
			@JoinColumn(name = "APA_DTHR_AMOSTRA", referencedColumnName = "DTHR_AMOSTRA", nullable = false) })
	public AbsAmostrasPacientes getAmostraPaciente() {
		return this.amostraPaciente;
	}

	public void setAmostraPaciente(
			AbsAmostrasPacientes amostraPaciente) {
		this.amostraPaciente = amostraPaciente;
	}

	@Column(name = "SHE_ATD_SEQ", nullable = false, precision = 7, scale = 0)
	public Integer getSheAtdSeq() {
		return this.sheAtdSeq;
	}

	public void setSheAtdSeq(Integer sheAtdSeq) {
		this.sheAtdSeq = sheAtdSeq;
	}

	@Column(name = "SHE_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getSheSeq() {
		return this.sheSeq;
	}

	public void setSheSeq(Integer sheSeq) {
		this.sheSeq = sheSeq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	public enum Fields {
		PACIENTE_CODIGO("amostraPaciente.id.pacCodigo"), DATA_HORA_AMOSTRA("amostraPaciente.id.dthrAmostra");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}	
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AbsSolicitacoesPorAmostra)) {
			return false;
		}
		AbsSolicitacoesPorAmostra other = (AbsSolicitacoesPorAmostra) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
