package br.gov.mec.aghu.model;

// Generated 19/11/2010 14:11:30 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


import org.hibernate.annotations.Immutable;

import br.gov.mec.aghu.dominio.DominioResponsavelColeta;
import br.gov.mec.aghu.dominio.DominioSituacaoColeta;
import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * AbsSolicitacaoHemoterapicaJn generated by hbm2java
 */
@Entity
@Table(name = "ABS_SOLICIT_HEMOTERAPICAS_JN", schema = "AGH")
@SequenceGenerator(name = "absSheJnSeq", sequenceName = "AGH.ABS_SHE_JN_SEQ", allocationSize = 1)

@Immutable
public class AbsSolicitacaoHemoterapicaJn extends BaseJournal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 572811613721165015L;
	private Integer atdSeq;
	private Integer seq;
	private Date dthrCancelamentoColeta;
	private Short mccSeq;
	private Integer serMatriculaCancelaColeta;
	private Short serVinCodigoCancelaColeta;
	private DominioSituacaoColeta indSituacaoColeta;
	private DominioResponsavelColeta indResponsavelColeta;

	public AbsSolicitacaoHemoterapicaJn() {
	}
	
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "absSheJnSeq")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}


	@Column(name = "ATD_SEQ", nullable = false, precision = 7, scale = 0)
	public Integer getAtdSeq() {
		return this.atdSeq;
	}

	public void setAtdSeq(Integer atdSeq) {
		this.atdSeq = atdSeq;
	}

	@Column(name = "SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "DTHR_CANCELAMENTO_COLETA", length = 7)
	public Date getDthrCancelamentoColeta() {
		return this.dthrCancelamentoColeta;
	}

	public void setDthrCancelamentoColeta(Date dthrCancelamentoColeta) {
		this.dthrCancelamentoColeta = dthrCancelamentoColeta;
	}

	@Column(name = "MCC_SEQ", precision = 4, scale = 0)
	public Short getMccSeq() {
		return this.mccSeq;
	}

	public void setMccSeq(Short mccSeq) {
		this.mccSeq = mccSeq;
	}

	@Column(name = "SER_MATRICULA_CANCELA_COLETA", precision = 7, scale = 0)
	public Integer getSerMatriculaCancelaColeta() {
		return this.serMatriculaCancelaColeta;
	}

	public void setSerMatriculaCancelaColeta(Integer serMatriculaCancelaColeta) {
		this.serMatriculaCancelaColeta = serMatriculaCancelaColeta;
	}

	@Column(name = "SER_VIN_CODIGO_CANCELA_COLETA", precision = 3, scale = 0)
	public Short getSerVinCodigoCancelaColeta() {
		return this.serVinCodigoCancelaColeta;
	}

	public void setSerVinCodigoCancelaColeta(Short serVinCodigoCancelaColeta) {
		this.serVinCodigoCancelaColeta = serVinCodigoCancelaColeta;
	}

	@Column(name = "IND_SITUACAO_COLETA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacaoColeta getIndSituacaoColeta() {
		return this.indSituacaoColeta;
	}

	public void setIndSituacaoColeta(DominioSituacaoColeta indSituacaoColeta) {
		this.indSituacaoColeta = indSituacaoColeta;
	}

	@Column(name = "IND_RESPONSAVEL_COLETA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioResponsavelColeta getIndResponsavelColeta() {
		return this.indResponsavelColeta;
	}

	public void setIndResponsavelColeta(
			DominioResponsavelColeta indResponsavelColeta) {
		this.indResponsavelColeta = indResponsavelColeta;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeqJn() == null) ? 0 : getSeqJn().hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AbsSolicitacaoHemoterapicaJn other = (AbsSolicitacaoHemoterapicaJn) obj;
		if (getSeqJn() == null) {
			if (other.getSeqJn() != null) {
				return false;
			}
		} else if (!getSeqJn().equals(other.getSeqJn())) {
			return false;
		}
		return true;
	}

	public enum Fields {

		ATD_SEQ("atdSeq"),
		SEQ("seq"),
		DTHR_CANCELAMENTO_COLETA("dthrCancelamentoColeta"),
		MCC_SEQ("mccSeq"),
		SER_MATRICULA_CANCELA_COLETA("serMatriculaCancelaColeta"),
		SER_VIN_CODIGO_CANCELA_COLETA("serVinCodigoCancelaColeta"),
		IND_SITUACAO_COLETA("indSituacaoColeta"),
		IND_RESPONSAVEL_COLETA("indResponsavelColeta");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
