package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AbsTextoCartaId generated by hbm2java
 */
@Embeddable
public class AbsTextoCartaId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7192542360340185618L;
	private String tcaCodigo;
	private Short sequencia;

	public AbsTextoCartaId() {
	}

	public AbsTextoCartaId(String tcaCodigo, Short sequencia) {
		this.tcaCodigo = tcaCodigo;
		this.sequencia = sequencia;
	}

	@Column(name = "TCA_CODIGO", nullable = false, length = 3)
	@Length(max = 3)
	public String getTcaCodigo() {
		return this.tcaCodigo;
	}

	public void setTcaCodigo(String tcaCodigo) {
		this.tcaCodigo = tcaCodigo;
	}

	@Column(name = "SEQUENCIA", nullable = false)
	public Short getSequencia() {
		return this.sequencia;
	}

	public void setSequencia(Short sequencia) {
		this.sequencia = sequencia;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSequencia());
		umHashCodeBuilder.append(this.getTcaCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AbsTextoCartaId)) {
			return false;
		}
		AbsTextoCartaId other = (AbsTextoCartaId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSequencia(), other.getSequencia());
		umEqualsBuilder.append(this.getTcaCodigo(), other.getTcaCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
