package br.gov.mec.aghu.model;

// Generated 11/03/2011 16:57:37 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;

import br.gov.mec.aghu.dominio.DominioSituacaoAmostra;
import br.gov.mec.aghu.dominio.DominoOrigemMapaAmostraItemExame;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AelAmostraItemExames generated by hbm2java
 */

@Entity @Immutable
@Table(name = "AEL_AMOSTRA_ITEM_EXAMES", schema = "HIST")
public class AelAmostraItemExamesHist extends BaseEntityId<AelAmostraItemExamesId> implements java.io.Serializable {

	private static final long serialVersionUID = 918378066085679682L;
	private AelAmostraItemExamesId id;
	private AelAmostrasHist aelAmostras;
	private AelItemSolicExameHist aelItemSolicitacaoExames;
	private DominioSituacaoAmostra situacao;
	private AelEquipamentos aelEquipamentos;
	private Integer nroMapa;
	private Date alteradoEm;
	private RapServidores servidor;
	private Date dtImpMapa;
	private Boolean indEnviado;
	private AelEquipamentos aelEquipamentosExecutado;
	
	private DominoOrigemMapaAmostraItemExame origemMapa;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "iseSoeSeq", column = @Column(name = "ISE_SOE_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "iseSeqp", column = @Column(name = "ISE_SEQP", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "amoSoeSeq", column = @Column(name = "AMO_SOE_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "amoSeqp", column = @Column(name = "AMO_SEQP", nullable = false, precision = 7, scale = 0)) })
	public AelAmostraItemExamesId getId() {
		return this.id;
	}

	public void setId(AelAmostraItemExamesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "ISE_SOE_SEQ", referencedColumnName = "SOE_SEQ", insertable = false, updatable = false),
		@JoinColumn(name = "ISE_SEQP", referencedColumnName = "SEQP", insertable = false, updatable = false) })
	public AelItemSolicExameHist getAelItemSolicitacaoExames() {
		return this.aelItemSolicitacaoExames;
	}

	public void setAelItemSolicitacaoExames(AelItemSolicExameHist aelItemSolicitacaoExames) {
		this.aelItemSolicitacaoExames = aelItemSolicitacaoExames;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
	@JoinColumn(name = "AMO_SOE_SEQ", referencedColumnName = "SOE_SEQ", nullable = false, insertable = false, updatable = false),
	@JoinColumn(name = "AMO_SEQP", referencedColumnName = "SEQP", nullable = false, insertable = false, updatable = false) })
	public AelAmostrasHist getAelAmostras() {
		return this.aelAmostras;
	}

	public void setAelAmostras(AelAmostrasHist aelAmostras) {
		this.aelAmostras = aelAmostras;
	}

	@Column(name = "SITUACAO", nullable = true, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacaoAmostra getSituacao() {
		return this.situacao;
	}

	public void setSituacao(DominioSituacaoAmostra situacao) {
		this.situacao = situacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQU_SEQ")
	public AelEquipamentos getAelEquipamentos() {
		return this.aelEquipamentos;
	}

	public void setAelEquipamentos(AelEquipamentos aelEquipamentos) {
		this.aelEquipamentos = aelEquipamentos;
	}

	@Column(name = "NRO_MAPA", precision = 6, scale = 0)
	public Integer getNroMapa() {
		return this.nroMapa;
	}

	public void setNroMapa(Integer nroMapa) {
		this.nroMapa = nroMapa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 7)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = true),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = true) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_IMP_MAPA", length = 7)
	public Date getDtImpMapa() {
		return this.dtImpMapa;
	}

	public void setDtImpMapa(Date dtImpMapa) {
		this.dtImpMapa = dtImpMapa;
	}

	@Column(name = "IND_ENVIADO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndEnviado() {
		return this.indEnviado;
	}

	public void setIndEnviado(Boolean enviado) {
		this.indEnviado = enviado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQU_SEQ_EXECUTADO")
	public AelEquipamentos getAelEquipamentosExecutado() {
		return aelEquipamentosExecutado;
	}

	public void setAelEquipamentosExecutado(AelEquipamentos aelEquipamentosExecutado) {
		this.aelEquipamentosExecutado = aelEquipamentosExecutado;
	}

	@Column(name = "ORIGEM_MAPA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominoOrigemMapaAmostraItemExame getOrigemMapa() {
		return this.origemMapa;
	}

	public void setOrigemMapa(DominoOrigemMapaAmostraItemExame oo) {
		this.origemMapa = oo;
	}
	
	/**
	 * Validacoes do pre insert e pre update.
	 */
	@PrePersist
	@PreUpdate
	protected void validacoes() {
		if (this.getIndEnviado() == null) {
			this.setIndEnviado(Boolean.FALSE);
		}
	}
	
	public enum Fields {
		//AEL_AMOSTRAS("aelAmostras"),
		SITUACAO("situacao"),
		SOE_SEQ("id.iseSoeSeq"),
		SEQP("id.iseSeqp"),
		AMO_SOE_SEQ("id.amoSoeSeq"),
		AMO_SEQP("id.amoSeqp"),
		AEL_EQUIPAMENTOS("aelEquipamentos"),
		AEL_EQUIPAMENTOS_SEQ("aelEquipamentos.seq"),
		//ITEM_SOLICITACAO_EXAMES("aelItemSolicitacaoExames"),
		SERVIDOR("servidor"),
		NRO_MAPA("nroMapa"),
		ORIGEM_MAPA("origemMapa"),
		ALTERADO_EM("alteradoEm"),
		DT_IMP_MAPA("dtImpMapa"),
		IND_ENVIADO("indEnviado"),
		ID("id"),
		AEL_EQUIPAMENTO_EXECUTADO("aelEquipamentosExecutado"),
		ISE_SOE_SEQ("aelItemSolicitacaoExames.id.soeSeq"),
		ISE_SEQP("aelItemSolicitacaoExames.id.seqp");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelAmostraItemExamesHist)) {
			return false;
		}
		AelAmostraItemExamesHist other = (AelAmostraItemExamesHist) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
