package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AelCadDelineamento generated by hbm2java
 */
@Entity
@SequenceGenerator(name="aelClnSq1", sequenceName="AGH.AEL_CLN_SQ1", allocationSize = 1)
@Table(name = "AEL_CAD_DELINEAMENTOS", schema = "AGH")
public class AelCadDelineamento extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5431755289999413267L;
	private Short seq;
	private Integer version;
	private RapServidores rapServidores;
	private String descricao;
	private String indSituacao;
	private String indTemIntervencao;
	private Date criadoEm;
	
	// FIXME Implementar este relacionamento
//	private Set<AelProjetoPesquisas> aelProjetoPesquisases = new HashSet<AelProjetoPesquisas>(0);

	public AelCadDelineamento() {
	}

	public AelCadDelineamento(Short seq, RapServidores rapServidores, String descricao, String indSituacao, String indTemIntervencao,
			Date criadoEm) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.descricao = descricao;
		this.indSituacao = indSituacao;
		this.indTemIntervencao = indTemIntervencao;
		this.criadoEm = criadoEm;
	}

//	public AelCadDelineamento(Short seq, RapServidores rapServidores, String descricao, String indSituacao, String indTemIntervencao,
//			Date criadoEm, Set<AelProjetoPesquisas> aelProjetoPesquisases) {
//		this.seq = seq;
//		this.rapServidores = rapServidores;
//		this.descricao = descricao;
//		this.indSituacao = indSituacao;
//		this.indTemIntervencao = indTemIntervencao;
//		this.criadoEm = criadoEm;
//		this.aelProjetoPesquisases = aelProjetoPesquisases;
//	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aelClnSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(String indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "IND_TEM_INTERVENCAO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndTemIntervencao() {
		return this.indTemIntervencao;
	}

	public void setIndTemIntervencao(String indTemIntervencao) {
		this.indTemIntervencao = indTemIntervencao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aelCadDelineamento")
//	public Set<AelProjetoPesquisas> getAelProjetoPesquisases() {
//		return this.aelProjetoPesquisases;
//	}
//
//	public void setAelProjetoPesquisases(Set<AelProjetoPesquisas> aelProjetoPesquisases) {
//		this.aelProjetoPesquisases = aelProjetoPesquisases;
//	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		DESCRICAO("descricao"),
		IND_SITUACAO("indSituacao"),
		IND_TEM_INTERVENCAO("indTemIntervencao"),
		CRIADO_EM("criadoEm"),
//		AEL_PROJETO_PESQUISASES("aelProjetoPesquisases")
		;

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelCadDelineamento)) {
			return false;
		}
		AelCadDelineamento other = (AelCadDelineamento) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
