package br.gov.mec.aghu.model;

// Generated 11/05/2011 14:05:35 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import br.gov.mec.aghu.dominio.DominioSituacaoCartaColeta;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AelExtratoItemCartas generated by hbm2java
 */
@Entity
@Table(name = "AEL_EXTRATO_ITEM_CARTAS", schema = "AGH")
public class AelExtratoItemCartas extends BaseEntityId<AelExtratoItemCartasId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3893513587849779179L;
	private AelExtratoItemCartasId id;
	private AelItemSolicCartas aelItemSolicCartas;
	private Date dthrEvento;
	private DominioSituacaoCartaColeta situacao;
	private AelRetornoCarta motivoRetorno;
	private RapServidores servidor;


	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "iteIseSoeSeq", column = @Column(name = "ITE_ISE_SOE_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "iteIseSeqp", column = @Column(name = "ITE_ISE_SEQP", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "iteSeqp", column = @Column(name = "ITE_SEQP", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 3, scale = 0)) })
	public AelExtratoItemCartasId getId() {
		return this.id;
	}

	public void setId(AelExtratoItemCartasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "ITE_ISE_SEQP", referencedColumnName = "ISE_SEQP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ITE_ISE_SOE_SEQ", referencedColumnName = "ISE_SOE_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ITE_SEQP", referencedColumnName = "SEQP", nullable = false, insertable = false, updatable = false) })
	public AelItemSolicCartas getAelItemSolicCartas() {
		return this.aelItemSolicCartas;
	}

	public void setAelItemSolicCartas(AelItemSolicCartas aelItemSolicCartas) {
		this.aelItemSolicCartas = aelItemSolicCartas;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_EVENTO", nullable = false, length = 7)
	public Date getDthrEvento() {
		return this.dthrEvento;
	}

	public void setDthrEvento(Date dthrEvento) {
		this.dthrEvento = dthrEvento;
	}
	
	@Column(name = "SITUACAO", nullable = false, length = 2)
	@Enumerated(EnumType.STRING)
	public DominioSituacaoCartaColeta getSituacao() {
		return situacao;
	}

	public void setSituacao(DominioSituacaoCartaColeta situacao) {
		this.situacao = situacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RNO_SEQ")
	public AelRetornoCarta getMotivoRetorno() {
		return motivoRetorno;
	}

	public void setMotivoRetorno(AelRetornoCarta motivoRetorno) {
		this.motivoRetorno = motivoRetorno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}
	
	public enum Fields {

		AEL_ITEM_SOLIC_CARTAS("aelItemSolicCartas"),
		AEL_MOTIVO_RETORNO("motivoRetorno"),
		SERVIDOR("servidor");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelExtratoItemCartas)) {
			return false;
		}
		AelExtratoItemCartas other = (AelExtratoItemCartas) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
