package br.gov.mec.aghu.model;

// Generated 20/06/2011 14:50:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AelExamesQuestionarioId generated by hbm2java
 */
@Embeddable
public class AelExamesQuestionarioId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3712167648915924425L;
	private String emaExaSigla;
	private Integer emaManSeq;
	private Integer qtnSeq;

	public AelExamesQuestionarioId() {
	}

	public AelExamesQuestionarioId(String emaExaSigla, Integer emaManSeq, Integer qtnSeq) {
		this.emaExaSigla = emaExaSigla;
		this.emaManSeq = emaManSeq;
		this.qtnSeq = qtnSeq;
	}

	@Column(name = "EMA_EXA_SIGLA", nullable = false, length = 5)
	@Length(max = 5)
	public String getEmaExaSigla() {
		return this.emaExaSigla;
	}

	public void setEmaExaSigla(String emaExaSigla) {
		this.emaExaSigla = emaExaSigla;
	}

	@Column(name = "EMA_MAN_SEQ", nullable = false, precision = 5, scale = 0)
	public Integer getEmaManSeq() {
		return this.emaManSeq;
	}

	public void setEmaManSeq(Integer emaManSeq) {
		this.emaManSeq = emaManSeq;
	}

	@Column(name = "QTN_SEQ", nullable = false, precision = 5, scale = 0)
	public Integer getQtnSeq() {
		return this.qtnSeq;
	}

	public void setQtnSeq(Integer qtnSeq) {
		this.qtnSeq = qtnSeq;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof AelExamesQuestionarioId)) {
			return false;
		}
		AelExamesQuestionarioId castOther = (AelExamesQuestionarioId) other;

		return ((this.getEmaExaSigla() == castOther.getEmaExaSigla()) || (this
				.getEmaExaSigla() != null && castOther.getEmaExaSigla() != null && this
				.getEmaExaSigla().equals(castOther.getEmaExaSigla())))
				&& (this.getEmaManSeq() == castOther.getEmaManSeq())
				&& (this.getQtnSeq() == castOther.getQtnSeq());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEmaExaSigla() == null ? 0 : this.getEmaExaSigla()
						.hashCode());
		result = 37 * result + this.getEmaManSeq();
		result = 37 * result + this.getQtnSeq();
		return result;
	}

}
