package br.gov.mec.aghu.model;

// Generated 25/08/2011 13:21:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AelGrpTecnicaUnfExamesId generated by hbm2java
 */
@Embeddable
public class AelGrpTecnicaUnfExamesId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4931508881478463558L;
	private Integer grtSeq;
	private String ufeEmaExaSigla;
	private Integer ufeEmaManSeq;
	private Short ufeUnfSeq;

	public AelGrpTecnicaUnfExamesId() {
	}

	public AelGrpTecnicaUnfExamesId(Integer grtSeq, String ufeEmaExaSigla,
			Integer ufeEmaManSeq, Short ufeUnfSeq) {
		this.grtSeq = grtSeq;
		this.ufeEmaExaSigla = ufeEmaExaSigla;
		this.ufeEmaManSeq = ufeEmaManSeq;
		this.ufeUnfSeq = ufeUnfSeq;
	}

	@Column(name = "GRT_SEQ", nullable = false)
	public Integer getGrtSeq() {
		return this.grtSeq;
	}

	public void setGrtSeq(Integer grtSeq) {
		this.grtSeq = grtSeq;
	}

	@Column(name = "UFE_EMA_EXA_SIGLA", nullable = false, length = 5)
	@Length(max = 5)
	public String getUfeEmaExaSigla() {
		return this.ufeEmaExaSigla;
	}

	public void setUfeEmaExaSigla(String ufeEmaExaSigla) {
		this.ufeEmaExaSigla = ufeEmaExaSigla;
	}

	@Column(name = "UFE_EMA_MAN_SEQ", nullable = false)
	public Integer getUfeEmaManSeq() {
		return this.ufeEmaManSeq;
	}

	public void setUfeEmaManSeq(Integer ufeEmaManSeq) {
		this.ufeEmaManSeq = ufeEmaManSeq;
	}

	@Column(name = "UFE_UNF_SEQ", nullable = false)
	public Short getUfeUnfSeq() {
		return this.ufeUnfSeq;
	}

	public void setUfeUnfSeq(Short ufeUnfSeq) {
		this.ufeUnfSeq = ufeUnfSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getUfeUnfSeq());
		umHashCodeBuilder.append(this.getUfeEmaExaSigla());
		umHashCodeBuilder.append(this.getUfeEmaManSeq());
		umHashCodeBuilder.append(this.getGrtSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelGrpTecnicaUnfExamesId)) {
			return false;
		}
		AelGrpTecnicaUnfExamesId other = (AelGrpTecnicaUnfExamesId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getUfeUnfSeq(), other.getUfeUnfSeq());
		umEqualsBuilder.append(this.getUfeEmaExaSigla(), other.getUfeEmaExaSigla());
		umEqualsBuilder.append(this.getUfeEmaManSeq(), other.getUfeEmaManSeq());
		umEqualsBuilder.append(this.getGrtSeq(), other.getGrtSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
