package br.gov.mec.aghu.model;

// Generated 25/08/2011 13:21:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * AelGrpTecnicaUnfExamesJn generated by hbm2java
 */
@Entity
@SequenceGenerator(name = "aelTceJnSeq", sequenceName = "AGH.AEL_TCE_JN_SEQ", allocationSize = 1)
@Table(name = "AEL_GRP_TECNICA_UNF_EXAMES_JN", schema = "AGH")
@Immutable
public class AelGrpTecnicaUnfExamesJn extends BaseJournal {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6018813245136784033L;
	/*private Long seqJn;
	private String jnUser;
	private Date jnDateTime;
	private String jnOperation;*/
	private Integer grtSeq;
	private String ufeEmaExaSigla;
	private Integer ufeEmaManSeq;
	private Short ufeUnfSeq;

	public AelGrpTecnicaUnfExamesJn() {
	}

	public AelGrpTecnicaUnfExamesJn(Long seqJn, String jnUser, Date jnDateTime,
			String jnOperation, Integer grtSeq, String ufeEmaExaSigla,
			int ufeEmaManSeq, Short ufeUnfSeq) {
		/*this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.grtSeq = grtSeq;
		this.ufeEmaExaSigla = ufeEmaExaSigla;
		this.ufeEmaManSeq = ufeEmaManSeq;
		this.ufeUnfSeq = ufeUnfSeq;
	}
	
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aelTceJnSeq")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	
	/*
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	public Long getSeqJn() {
		return this.seqJn;
	}

	public void setSeqJn(Long seqJn) {
		this.seqJn = seqJn;
	}

	@Column(name = "JN_USER", nullable = false, length = 30)
	@Length(max = 30)
	public String getJnUser() {
		return this.jnUser;
	}

	public void setJnUser(String jnUser) {
		this.jnUser = jnUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JN_DATE_TIME", nullable = false, length = 29)
	public Date getJnDateTime() {
		return this.jnDateTime;
	}

	public void setJnDateTime(Date jnDateTime) {
		this.jnDateTime = jnDateTime;
	}

	@Column(name = "JN_OPERATION", nullable = false, length = 3)
	@Length(max = 3)
	public String getJnOperation() {
		return this.jnOperation;
	}

	public void setJnOperation(String jnOperation) {
		this.jnOperation = jnOperation;
	}
	*/

	@Column(name = "GRT_SEQ", nullable = false)
	public Integer getGrtSeq() {
		return this.grtSeq;
	}

	public void setGrtSeq(Integer grtSeq) {
		this.grtSeq = grtSeq;
	}

	@Column(name = "UFE_EMA_EXA_SIGLA", nullable = false, length = 5)
	@Length(max = 5)
	public String getUfeEmaExaSigla() {
		return this.ufeEmaExaSigla;
	}

	public void setUfeEmaExaSigla(String ufeEmaExaSigla) {
		this.ufeEmaExaSigla = ufeEmaExaSigla;
	}

	@Column(name = "UFE_EMA_MAN_SEQ", nullable = false)
	public Integer getUfeEmaManSeq() {
		return this.ufeEmaManSeq;
	}

	public void setUfeEmaManSeq(Integer ufeEmaManSeq) {
		this.ufeEmaManSeq = ufeEmaManSeq;
	}

	@Column(name = "UFE_UNF_SEQ", nullable = false)
	public Short getUfeUnfSeq() {
		return this.ufeUnfSeq;
	}

	public void setUfeUnfSeq(Short ufeUnfSeq) {
		this.ufeUnfSeq = ufeUnfSeq;
	}

	public enum Fields {

		/*SEQ_JN("seqJn"),
		JN_USER("jnUser"),
		JN_DATE_TIME("jnDateTime"),
		JN_OPERATION("jnOperation"),*/
		GRT_SEQ("grtSeq"),
		UFE_EMA_EXA_SIGLA("ufeEmaExaSigla"),
		UFE_EMA_MAN_SEQ("ufeEmaManSeq"),
		UFE_UNF_SEQ("ufeUnfSeq");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
