package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Type;

import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * AelKitMatPatologiaJn generated by hbm2java
 */
@Entity
@SequenceGenerator(name="aelInfjnSq1", sequenceName="AGH.AEL_INF_JN_SEQ", allocationSize = 1)
@Table(name = "AEL_INFORMACAO_CLINICA_APS_JN", schema = "AGH")
@Immutable
public class AelInformacaoClinicaAPJn extends BaseJournal {

	private static final long serialVersionUID = -7099494980033511032L;
	
	private Integer seq;
	private String informacaoClinica;
	private Date criadoEm;
	private AelExameAp aelExameAp;
	private RapServidores rapServidores;

	public AelInformacaoClinicaAPJn() {
	}

	public AelInformacaoClinicaAPJn(Integer seq, String informacaoClinica,
			Date criadoEm, AelExameAp aelExameAp, RapServidores rapServidores) {
		super();
		this.seq = seq;
		this.informacaoClinica = informacaoClinica;
		this.criadoEm = criadoEm;
		this.aelExameAp = aelExameAp;
		this.rapServidores = rapServidores;
	}

	@Override
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aelInfjnSq1")
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	public Integer getSeqJn() {
		return super.getSeqJn();
	}

	@Column(name = "SEQ", nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}
	
	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LUX_SEQ", nullable = false)
	public AelExameAp getAelExameAp() {
		return this.aelExameAp;
	}

	public void setAelExameAp(AelExameAp aelExameAp) {
		this.aelExameAp = aelExameAp;
	}

	@Column(name = "INFORMACAO_CLINICA", nullable = false)
	@Type(type="text")	
	@Lob
	public String getInformacaoClinica() {
		return informacaoClinica;
	}


	public void setInformacaoClinica(String informacaoClinica) {
		this.informacaoClinica = informacaoClinica;
	}
	
	public enum Fields {
		SEQ("seq"),
		RAP_SERVIDORES("rapServidores"),
		INFORMACAO_CLINICA("informacaoClinica"),
		CRIADO_EM("criadoEm"),
		AEL_EXAME_AP("aelExameAp");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}
	
}