package br.gov.mec.aghu.model;

// Generated 08/08/2013 16:44:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AelInformacaoColetasTemporarioApagarId generated by hbm2java
 */
@Embeddable
public class AelInformacaoColetaHistId implements EntityCompositeId {

	private static final long serialVersionUID = -1131682833092125073L;
	
	private Integer soeSeq;
	private Short seqp;

	public AelInformacaoColetaHistId() {
	}

	public AelInformacaoColetaHistId(Integer soeSeq, Short seqp) {
		this.soeSeq = soeSeq;
		this.seqp = seqp;
	}

	@Column(name = "soe_seq", nullable = false)
	public Integer getSoeSeq() {
		return this.soeSeq;
	}

	public void setSoeSeq(Integer soeSeq) {
		this.soeSeq = soeSeq;
	}

	@Column(name = "seqp", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}

	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getSoeSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelInformacaoColetaHistId)) {
			return false;
		}
		AelInformacaoColetaHistId other = (AelInformacaoColetaHistId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getSoeSeq(), other.getSoeSeq());
		return umEqualsBuilder.isEquals();
	}

}
