package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AelMdtoIngerido generated by hbm2java
 */
@Entity
@Table(name = "AEL_MDTO_INGERIDOS", schema = "AGH")
public class AelMdtoIngerido extends BaseEntityId<AelMdtoIngeridoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4165020931125636288L;
	private AelMdtoIngeridoId id;
	private Integer version;
	private AfaMedicamento afaMedicamento;
	private AelSolicitacaoExames aelSolicitacaoExames;
	private String descMdtoIngerido;

	public AelMdtoIngerido() {
	}

	public AelMdtoIngerido(AelMdtoIngeridoId id, AelSolicitacaoExames aelSolicitacaoExames) {
		this.id = id;
		this.aelSolicitacaoExames = aelSolicitacaoExames;
	}

	public AelMdtoIngerido(AelMdtoIngeridoId id, AfaMedicamento afaMedicamento, AelSolicitacaoExames aelSolicitacaoExames,
			String descMdtoIngerido) {
		this.id = id;
		this.afaMedicamento = afaMedicamento;
		this.aelSolicitacaoExames = aelSolicitacaoExames;
		this.descMdtoIngerido = descMdtoIngerido;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "soeSeq", column = @Column(name = "SOE_SEQ", nullable = false)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false)) })
	public AelMdtoIngeridoId getId() {
		return this.id;
	}

	public void setId(AelMdtoIngeridoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MED_MAT_CODIGO")
	public AfaMedicamento getAfaMedicamento() {
		return this.afaMedicamento;
	}

	public void setAfaMedicamento(AfaMedicamento afaMedicamento) {
		this.afaMedicamento = afaMedicamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOE_SEQ", nullable = false, insertable = false, updatable = false)
	public AelSolicitacaoExames getAelSolicitacaoExames() {
		return this.aelSolicitacaoExames;
	}

	public void setAelSolicitacaoExames(AelSolicitacaoExames aelSolicitacaoExames) {
		this.aelSolicitacaoExames = aelSolicitacaoExames;
	}

	@Column(name = "DESC_MDTO_INGERIDO", length = 100)
	@Length(max = 100)
	public String getDescMdtoIngerido() {
		return this.descMdtoIngerido;
	}

	public void setDescMdtoIngerido(String descMdtoIngerido) {
		this.descMdtoIngerido = descMdtoIngerido;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		AFA_MEDICAMENTO("afaMedicamento"),
		AEL_SOLICITACAO_EXAMES("aelSolicitacaoExames"),
		DESC_MDTO_INGERIDO("descMdtoIngerido");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelMdtoIngerido)) {
			return false;
		}
		AelMdtoIngerido other = (AelMdtoIngerido) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
