package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AelProjetoProcedimentoId generated by hbm2java
 */
@Embeddable
public class AelProjetoProcedimentoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4420344362212712973L;
	private Integer pjqSeq;
	private Integer pciSeq;

	public AelProjetoProcedimentoId() {
	}

	public AelProjetoProcedimentoId(Integer pjqSeq, Integer pciSeq) {
		this.pjqSeq = pjqSeq;
		this.pciSeq = pciSeq;
	}

	@Column(name = "PJQ_SEQ", nullable = false)
	public Integer getPjqSeq() {
		return this.pjqSeq;
	}

	public void setPjqSeq(Integer pjqSeq) {
		this.pjqSeq = pjqSeq;
	}

	@Column(name = "PCI_SEQ", nullable = false)
	public Integer getPciSeq() {
		return this.pciSeq;
	}

	public void setPciSeq(Integer pciSeq) {
		this.pciSeq = pciSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getPciSeq());
		umHashCodeBuilder.append(this.getPjqSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelProjetoProcedimentoId)) {
			return false;
		}
		AelProjetoProcedimentoId other = (AelProjetoProcedimentoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getPciSeq(), other.getPciSeq());
		umEqualsBuilder.append(this.getPjqSeq(), other.getPjqSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
