package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AelProjetoProcedimento generated by hbm2java
 */
@Entity
@Table(name = "AEL_PROJETO_PROCEDIMENTOS", schema = "AGH")
public class AelProjetoProcedimento extends BaseEntityId<AelProjetoProcedimentoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2599957806862533864L;
	private AelProjetoProcedimentoId id;
	private Integer version;
	private RapServidores rapServidores;
	private AelProjetoPesquisas aelProjetoPesquisas;
	private MbcProcedimentoCirurgicos mbcProcedimentoCirurgicos;
	private String numero;
	private Date dtInicio;
	private Date dtFim;
	private Short qtdeSolicitado;
	private Short qtdePermitido;
	private Double valor;
	private DominioSituacao situacao;
	private Date criadoEm;

	public AelProjetoProcedimento() {
	}

	public AelProjetoProcedimento(AelProjetoProcedimentoId id, RapServidores rapServidores, AelProjetoPesquisas aelProjetoPesquisas,
			MbcProcedimentoCirurgicos mbcProcedimentoCirurgicos, Date dtInicio, DominioSituacao situacao, Date criadoEm) {
		this.id = id;
		this.rapServidores = rapServidores;
		this.aelProjetoPesquisas = aelProjetoPesquisas;
		this.mbcProcedimentoCirurgicos = mbcProcedimentoCirurgicos;
		this.dtInicio = dtInicio;
		this.situacao = situacao;
		this.criadoEm = criadoEm;
	}

	public AelProjetoProcedimento(AelProjetoProcedimentoId id, RapServidores rapServidores, AelProjetoPesquisas aelProjetoPesquisas,
			MbcProcedimentoCirurgicos mbcProcedimentoCirurgicos, String numero, Date dtInicio, Date dtFim, Short qtdeSolicitado,
			Short qtdePermitido, Double valor, DominioSituacao situacao, Date criadoEm) {
		this.id = id;
		this.rapServidores = rapServidores;
		this.aelProjetoPesquisas = aelProjetoPesquisas;
		this.mbcProcedimentoCirurgicos = mbcProcedimentoCirurgicos;
		this.numero = numero;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
		this.qtdeSolicitado = qtdeSolicitado;
		this.qtdePermitido = qtdePermitido;
		this.valor = valor;
		this.situacao = situacao;
		this.criadoEm = criadoEm;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "pjqSeq", column = @Column(name = "PJQ_SEQ", nullable = false)),
			@AttributeOverride(name = "pciSeq", column = @Column(name = "PCI_SEQ", nullable = false)) })
	public AelProjetoProcedimentoId getId() {
		return this.id;
	}

	public void setId(AelProjetoProcedimentoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PJQ_SEQ", nullable = false, insertable = false, updatable = false)
	public AelProjetoPesquisas getAelProjetoPesquisas() {
		return this.aelProjetoPesquisas;
	}

	public void setAelProjetoPesquisas(AelProjetoPesquisas aelProjetoPesquisas) {
		this.aelProjetoPesquisas = aelProjetoPesquisas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PCI_SEQ", nullable = false, insertable = false, updatable = false)
	public MbcProcedimentoCirurgicos getMbcProcedimentoCirurgicos() {
		return this.mbcProcedimentoCirurgicos;
	}

	public void setMbcProcedimentoCirurgicos(MbcProcedimentoCirurgicos mbcProcedimentoCirurgicos) {
		this.mbcProcedimentoCirurgicos = mbcProcedimentoCirurgicos;
	}

	@Column(name = "NUMERO", length = 20)
	@Length(max = 20)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO", nullable = false, length = 29)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM", length = 29)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Column(name = "QTDE_SOLICITADO")
	public Short getQtdeSolicitado() {
		return this.qtdeSolicitado;
	}

	public void setQtdeSolicitado(Short qtdeSolicitado) {
		this.qtdeSolicitado = qtdeSolicitado;
	}

	@Column(name = "QTDE_PERMITIDO")
	public Short getQtdePermitido() {
		return this.qtdePermitido;
	}

	public void setQtdePermitido(Short qtdePermitido) {
		this.qtdePermitido = qtdePermitido;
	}

	@Column(name = "VALOR", precision = 17, scale = 17)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getSituacao() {
		return situacao;
	}
	
	public void setSituacao(DominioSituacao situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	public enum Fields {

		
		ID("id"),
		PJQ_SEQ("id.pjqSeq"),
		PCI_SEQ("id.pciSeq"),
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		AEL_PROJETO_PESQUISAS("aelProjetoPesquisas"),
		MBC_PROCEDIMENTO_CIRURGICOS("mbcProcedimentoCirurgicos"),
		NUMERO("numero"),
		DT_INICIO("dtInicio"),
		DT_FIM("dtFim"),
		QTDE_SOLICITADO("qtdeSolicitado"),
		QTDE_PERMITIDO("qtdePermitido"),
		VALOR("valor"),
		SITUACAO("situacao"),
		CRIADO_EM("criadoEm");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelProjetoProcedimento)) {
			return false;
		}
		AelProjetoProcedimento other = (AelProjetoProcedimento) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
