package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * AelProjetoEquipeJn generated by hbm2java
 */
@Entity
@Table(name = "AEL_PROJETO_EQUIPES_JN", schema = "AGH")
@Immutable
public class AelProjetoEquipeJn extends BaseJournal {

/**
	 * 
	 */
	private static final long serialVersionUID = 943266652938608486L;
	/* ATUALIZADOR JOURNALS - PROPERTIES	private Long seqJn;
	private String jnUser;
	private Date jnDateTime;
	private String jnOperation;*/
	private Integer pjqSeq;
	private Date dtInicio;
	private Date dtFim;
	private String funcao;
	private String indSituacao;
	private String email;
	private String telefone;
	private Date criadoEm;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Integer serMatriculaCriado;
	private Short serVinCodigoCriado;
	private String numero;
	private String indResponsavelUfrgs;

	public AelProjetoEquipeJn() {
	}

	public AelProjetoEquipeJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer pjqSeq, Integer serMatricula,
			Short serVinCodigo) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.pjqSeq = pjqSeq;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
	}

	public AelProjetoEquipeJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer pjqSeq, Date dtInicio, Date dtFim,
			String funcao, String indSituacao, String email, String telefone, Date criadoEm, Integer serMatricula, Short serVinCodigo,
			Integer serMatriculaCriado, Short serVinCodigoCriado, String numero, String indResponsavelUfrgs) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.pjqSeq = pjqSeq;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
		this.funcao = funcao;
		this.indSituacao = indSituacao;
		this.email = email;
		this.telefone = telefone;
		this.criadoEm = criadoEm;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.serMatriculaCriado = serMatriculaCriado;
		this.serVinCodigoCriado = serVinCodigoCriado;
		this.numero = numero;
		this.indResponsavelUfrgs = indResponsavelUfrgs;
	}

	// ATUALIZADOR JOURNALS - ID
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	//@GeneratedValue(strategy = GenerationType.AUTO, generator = "")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	// ATUALIZADOR JOURNALS - ID
	
/* ATUALIZADOR JOURNALS - Get / Set	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	public Long getSeqJn() {
		return this.seqJn;
	}

	public void setSeqJn(Long seqJn) {
		this.seqJn = seqJn;
	}

	@Column(name = "JN_USER", nullable = false, length = 30)
	@Length(max = 30)
	public String getJnUser() {
		return this.jnUser;
	}

	public void setJnUser(String jnUser) {
		this.jnUser = jnUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JN_DATE_TIME", nullable = false, length = 29)
	public Date getJnDateTime() {
		return this.jnDateTime;
	}

	public void setJnDateTime(Date jnDateTime) {
		this.jnDateTime = jnDateTime;
	}

	@Column(name = "JN_OPERATION", nullable = false, length = 3)
	@Length(max = 3)
	public String getJnOperation() {
		return this.jnOperation;
	}

	public void setJnOperation(String jnOperation) {
		this.jnOperation = jnOperation;
	}*/

	@Column(name = "PJQ_SEQ", nullable = false)
	public Integer getPjqSeq() {
		return this.pjqSeq;
	}

	public void setPjqSeq(Integer pjqSeq) {
		this.pjqSeq = pjqSeq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO", length = 29)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM", length = 29)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Column(name = "FUNCAO", length = 1)
	@Length(max = 1)
	public String getFuncao() {
		return this.funcao;
	}

	public void setFuncao(String funcao) {
		this.funcao = funcao;
	}

	@Column(name = "IND_SITUACAO", length = 1)
	@Length(max = 1)
	public String getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(String indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "EMAIL", length = 40)
	@Length(max = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TELEFONE", length = 20)
	@Length(max = 20)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "SER_MATRICULA_CRIADO")
	public Integer getSerMatriculaCriado() {
		return this.serMatriculaCriado;
	}

	public void setSerMatriculaCriado(Integer serMatriculaCriado) {
		this.serMatriculaCriado = serMatriculaCriado;
	}

	@Column(name = "SER_VIN_CODIGO_CRIADO")
	public Short getSerVinCodigoCriado() {
		return this.serVinCodigoCriado;
	}

	public void setSerVinCodigoCriado(Short serVinCodigoCriado) {
		this.serVinCodigoCriado = serVinCodigoCriado;
	}

	@Column(name = "NUMERO", length = 20)
	@Length(max = 20)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "IND_RESPONSAVEL_UFRGS", length = 1)
	@Length(max = 1)
	public String getIndResponsavelUfrgs() {
		return this.indResponsavelUfrgs;
	}

	public void setIndResponsavelUfrgs(String indResponsavelUfrgs) {
		this.indResponsavelUfrgs = indResponsavelUfrgs;
	}

	public enum Fields {

	/* ATUALIZADOR JOURNALS - Fields	SEQ_JN("seqJn"),
		JN_USER("jnUser"),
		JN_DATE_TIME("jnDateTime"),
		JN_OPERATION("jnOperation"),*/
		PJQ_SEQ("pjqSeq"),
		DT_INICIO("dtInicio"),
		DT_FIM("dtFim"),
		FUNCAO("funcao"),
		IND_SITUACAO("indSituacao"),
		EMAIL("email"),
		TELEFONE("telefone"),
		CRIADO_EM("criadoEm"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		SER_MATRICULA_CRIADO("serMatriculaCriado"),
		SER_VIN_CODIGO_CRIADO("serVinCodigoCriado"),
		NUMERO("numero"),
		IND_RESPONSAVEL_UFRGS("indResponsavelUfrgs");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
