package br.gov.mec.aghu.model;

// Generated 25/03/2011 09:58:56 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AelPermissaoUnidSolicsId generated by hbm2java
 */
@Embeddable
public class AelPermissaoUnidSolicId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7857984744734204848L;
	private String ufeEmaExaSigla;
	private Integer ufeEmaManSeq;
	private Short ufeUnfSeq;
	private Short unfSeq;

	public AelPermissaoUnidSolicId() {
	}

	public AelPermissaoUnidSolicId(String ufeEmaExaSigla, Integer ufeEmaManSeq,
			Short ufeUnfSeq, Short unfSeq) {
		this.ufeEmaExaSigla = ufeEmaExaSigla;
		this.ufeEmaManSeq = ufeEmaManSeq;
		this.ufeUnfSeq = ufeUnfSeq;
		this.unfSeq = unfSeq;
	}

	@Column(name = "ufe_ema_exa_sigla", nullable = false, length = 5)
	@Length(max = 5)
	public String getUfeEmaExaSigla() {
		return this.ufeEmaExaSigla;
	}

	public void setUfeEmaExaSigla(String ufeEmaExaSigla) {
		this.ufeEmaExaSigla = ufeEmaExaSigla;
	}

	@Column(name = "ufe_ema_man_seq", nullable = false)
	public Integer getUfeEmaManSeq() {
		return this.ufeEmaManSeq;
	}

	public void setUfeEmaManSeq(int ufeEmaManSeq) {
		this.ufeEmaManSeq = ufeEmaManSeq;
	}

	@Column(name = "ufe_unf_seq", nullable = false)
	public Short getUfeUnfSeq() {
		return this.ufeUnfSeq;
	}

	public void setUfeUnfSeq(Short ufeUnfSeq) {
		this.ufeUnfSeq = ufeUnfSeq;
	}

	@Column(name = "unf_seq", nullable = false)
	public Short getUnfSeq() {
		return this.unfSeq;
	}

	public void setUnfSeq(Short unfSeq) {
		this.unfSeq = unfSeq;
	}

	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof AelPermissaoUnidSolicId)) {
			return false;
		}
		AelPermissaoUnidSolicId castOther = (AelPermissaoUnidSolicId) other;

		return ((this.getUfeEmaExaSigla() == castOther.getUfeEmaExaSigla()) || (this
				.getUfeEmaExaSigla() != null
				&& castOther.getUfeEmaExaSigla() != null && this
				.getUfeEmaExaSigla().equals(castOther.getUfeEmaExaSigla())))
				&& (this.getUfeEmaManSeq().equals(castOther.getUfeEmaManSeq()))
				&& (this.getUfeUnfSeq().equals(castOther.getUfeUnfSeq()))
				&& (this.getUnfSeq().equals(castOther.getUnfSeq()));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUfeEmaExaSigla() == null ? 0 : this.getUfeEmaExaSigla()
						.hashCode());
		result = 37 * result + this.getUfeEmaManSeq();
		result = 37 * result + this.getUfeUnfSeq();
		result = 37 * result + this.getUnfSeq();
		return result;
	}

}
