package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * AelProjetoProtQuesitoJn generated by hbm2java
 */
@Entity
@Table(name = "AEL_PROJETO_PROT_QUESITOS_JN", schema = "AGH")
@Immutable
public class AelProjetoProtQuesitoJn extends BaseJournal {

/**
	 * 
	 */
	private static final long serialVersionUID = 8006086903962949481L;
	/* ATUALIZADOR JOURNALS - PROPERTIES	private Long seqJn;
	private String jnUser;
	private Date jnDateTime;
	private String jnOperation;*/
	private Integer ppoPjqSeq;
	private Short ppoSeqp;
	private Short seqp;
	private String questao;
	private Date dtInicio;
	private Date dtFim;
	private Short ordem;
	private Date criadoEm;
	private Integer serMatricula;
	private Short serVinCodigo;
	private String tipoDados;
	private String mascara;
	private Short gqtSeq;

	public AelProjetoProtQuesitoJn() {
	}

	public AelProjetoProtQuesitoJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer ppoPjqSeq, Short ppoSeqp,
			Short seqp) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.ppoPjqSeq = ppoPjqSeq;
		this.ppoSeqp = ppoSeqp;
		this.seqp = seqp;
	}

	public AelProjetoProtQuesitoJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer ppoPjqSeq, Short ppoSeqp,
			Short seqp, String questao, Date dtInicio, Date dtFim, Short ordem, Date criadoEm, Integer serMatricula,
			Short serVinCodigo, String tipoDados, String mascara, Short gqtSeq) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.ppoPjqSeq = ppoPjqSeq;
		this.ppoSeqp = ppoSeqp;
		this.seqp = seqp;
		this.questao = questao;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
		this.ordem = ordem;
		this.criadoEm = criadoEm;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.tipoDados = tipoDados;
		this.mascara = mascara;
		this.gqtSeq = gqtSeq;
	}

	// ATUALIZADOR JOURNALS - ID
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	//@GeneratedValue(strategy = GenerationType.AUTO, generator = "")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	// ATUALIZADOR JOURNALS - ID
	
/* ATUALIZADOR JOURNALS - Get / Set	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	public Long getSeqJn() {
		return this.seqJn;
	}

	public void setSeqJn(Long seqJn) {
		this.seqJn = seqJn;
	}

	@Column(name = "JN_USER", nullable = false, length = 30)
	@Length(max = 30)
	public String getJnUser() {
		return this.jnUser;
	}

	public void setJnUser(String jnUser) {
		this.jnUser = jnUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JN_DATE_TIME", nullable = false, length = 29)
	public Date getJnDateTime() {
		return this.jnDateTime;
	}

	public void setJnDateTime(Date jnDateTime) {
		this.jnDateTime = jnDateTime;
	}

	@Column(name = "JN_OPERATION", nullable = false, length = 3)
	@Length(max = 3)
	public String getJnOperation() {
		return this.jnOperation;
	}

	public void setJnOperation(String jnOperation) {
		this.jnOperation = jnOperation;
	}*/

	@Column(name = "PPO_PJQ_SEQ", nullable = false)
	public Integer getPpoPjqSeq() {
		return this.ppoPjqSeq;
	}

	public void setPpoPjqSeq(Integer ppoPjqSeq) {
		this.ppoPjqSeq = ppoPjqSeq;
	}

	@Column(name = "PPO_SEQP", nullable = false)
	public Short getPpoSeqp() {
		return this.ppoSeqp;
	}

	public void setPpoSeqp(Short ppoSeqp) {
		this.ppoSeqp = ppoSeqp;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}

	@Column(name = "QUESTAO", length = 120)
	@Length(max = 120)
	public String getQuestao() {
		return this.questao;
	}

	public void setQuestao(String questao) {
		this.questao = questao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO", length = 29)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM", length = 29)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Column(name = "ORDEM")
	public Short getOrdem() {
		return this.ordem;
	}

	public void setOrdem(Short ordem) {
		this.ordem = ordem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "SER_MATRICULA")
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO")
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "TIPO_DADOS", length = 1)
	@Length(max = 1)
	public String getTipoDados() {
		return this.tipoDados;
	}

	public void setTipoDados(String tipoDados) {
		this.tipoDados = tipoDados;
	}

	@Column(name = "MASCARA", length = 15)
	@Length(max = 15)
	public String getMascara() {
		return this.mascara;
	}

	public void setMascara(String mascara) {
		this.mascara = mascara;
	}

	@Column(name = "GQT_SEQ")
	public Short getGqtSeq() {
		return this.gqtSeq;
	}

	public void setGqtSeq(Short gqtSeq) {
		this.gqtSeq = gqtSeq;
	}

	public enum Fields {

	/* ATUALIZADOR JOURNALS - Fields	SEQ_JN("seqJn"),
		JN_USER("jnUser"),
		JN_DATE_TIME("jnDateTime"),
		JN_OPERATION("jnOperation"),*/
		PPO_PJQ_SEQ("ppoPjqSeq"),
		PPO_SEQP("ppoSeqp"),
		SEQP("seqp"),
		QUESTAO("questao"),
		DT_INICIO("dtInicio"),
		DT_FIM("dtFim"),
		ORDEM("ordem"),
		CRIADO_EM("criadoEm"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		TIPO_DADOS("tipoDados"),
		MASCARA("mascara"),
		GQT_SEQ("gqtSeq");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
