package br.gov.mec.aghu.model;

// Generated 25/01/2011 10:42:05 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSimNao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AelPedidosExames generated by hbm2java
 */
@SuppressWarnings({"PMD.AghuUsoIndevidoDaEnumDominioSimNaoEntity"})
@Entity
@SequenceGenerator(name="aelPexSq1", sequenceName="AGH.AEL_PEX_SQ1", allocationSize = 1)
@Table(name = "AEL_PEDIDOS_EXAMES", schema = "AGH")
public class AelPedidoExame extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -379971794077412222L;
	private Integer seq;
	private FatConvenioSaudePlano convenioSaudePlano;
	private AghAtendimentos atendimento;
	private String tipoPedido;
	private AghEspecialidades especialidade;
	private AacUnidFuncionalSalas unidadeFuncionalSala;
	private Date criadoEm;
	private AghProfEspecialidades profissionalEspecilidade;
	private AghEquipes equipe;
	private DominioSimNao indAgenda;
	private Date dthrConsulta;
	private RapServidores servidor;
	private Set<AelItemPedidoExame> aelItensPedidosExameses = new HashSet<AelItemPedidoExame>(
			0);

	public AelPedidoExame() {
	}

	public AelPedidoExame(Integer seq, FatConvenioSaudePlano convenioSaudePlano,
			AghAtendimentos atendimento, String tipoPedido, Date criadoEm) {
		this.seq = seq;
		this.convenioSaudePlano = convenioSaudePlano;
		this.atendimento = atendimento;
		this.tipoPedido = tipoPedido;
		this.criadoEm = criadoEm;
	}

	public AelPedidoExame(Integer seq, FatConvenioSaudePlano convenioSaudePlano,
			AghAtendimentos atendimento, String tipoPedido, AghEspecialidades especialidade, AacUnidFuncionalSalas unidadeFuncionalSala, 
			Date criadoEm, AghProfEspecialidades profissionalEspecilidade, AghEquipes equipe,
			DominioSimNao indAgenda, Date dthrConsulta, RapServidores servidor,
			Set<AelItemPedidoExame> aelItensPedidosExameses) {
		this.seq = seq;
		this.convenioSaudePlano = convenioSaudePlano;
		this.atendimento = atendimento;
		this.tipoPedido = tipoPedido;
		this.especialidade = especialidade;
		this.unidadeFuncionalSala = unidadeFuncionalSala;
		this.criadoEm = criadoEm;
		this.profissionalEspecilidade = profissionalEspecilidade;
		this.equipe = equipe;
		this.indAgenda = indAgenda;
		this.dthrConsulta = dthrConsulta;
		this.servidor = servidor;
		this.aelItensPedidosExameses = aelItensPedidosExameses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aelPexSq1")
	@Column(name = "SEQ", unique = true, nullable = false, precision = 7, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "CSP_SEQ", referencedColumnName = "SEQ", nullable = false),
			@JoinColumn(name = "CSP_CNV_CODIGO", referencedColumnName = "CNV_CODIGO", nullable = false) })
	public FatConvenioSaudePlano getConvenioSaudePlano() {
		return this.convenioSaudePlano;
	}

	public void setConvenioSaudePlano(FatConvenioSaudePlano cspCnvCodigo) {
		this.convenioSaudePlano = cspCnvCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATD_SEQ", nullable = false)
	public AghAtendimentos getAtendimento() {
		return this.atendimento;
	}

	public void setAtendimento(AghAtendimentos atendimento) {
		this.atendimento = atendimento;
	}

	@Column(name = "TIPO_PEDIDO", nullable = false, length = 1)
	@Length(max = 1)
	public String getTipoPedido() {
		return this.tipoPedido;
	}

	public void setTipoPedido(String tipoPedido) {
		this.tipoPedido = tipoPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESP_SEQ")
	public AghEspecialidades getEspecialidade() {
		return this.especialidade;
	}

	public void setEspecialidade(AghEspecialidades espSeq) {
		this.especialidade = espSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "USL_SALA", referencedColumnName = "SALA"),
			@JoinColumn(name = "USL_UNF_SEQ", referencedColumnName = "UNF_SEQ")})	
	public AacUnidFuncionalSalas getUnidadeFuncionalSala() {
		return unidadeFuncionalSala;
	}

	public void setUnidadeFuncionalSala(AacUnidFuncionalSalas unidadeFuncionalSala) {
		this.unidadeFuncionalSala = unidadeFuncionalSala;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "PRE_ESP_SEQ", referencedColumnName = "ESP_SEQ"),
			@JoinColumn(name = "PRE_SER_MATRICULA", referencedColumnName = "SER_MATRICULA"),
			@JoinColumn(name = "PRE_SER_VIN_CODIGO", referencedColumnName = "SER_VIN_CODIGO")})
	public AghProfEspecialidades getProfissionalEspecialidade() {
		return this.profissionalEspecilidade;
	}

	public void setProfissionalEspecialidade(AghProfEspecialidades preEspSeq) {
		this.profissionalEspecilidade = preEspSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQP_SEQ")
	public AghEquipes getEquipe() {
		return this.equipe;
	}

	public void setEquipe(AghEquipes eqpSeq) {
		this.equipe = eqpSeq;
	}

	@Column(name = "IND_AGENDA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getIndAgenda() {
		return this.indAgenda;
	}

	public void setIndAgenda(DominioSimNao indAgenda) {
		this.indAgenda = indAgenda;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHR_CONSULTA", length = 7)
	public Date getDthrConsulta() {
		return this.dthrConsulta;
	}

	public void setDthrConsulta(Date dthrConsulta) {
		this.dthrConsulta = dthrConsulta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO")})
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores serVinCodigo) {
		this.servidor = serVinCodigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aelPedidosExames")
	public Set<AelItemPedidoExame> getAelItensPedidosExameses() {
		return this.aelItensPedidosExameses;
	}

	public void setAelItensPedidosExameses(
			Set<AelItemPedidoExame> aelItensPedidosExameses) {
		this.aelItensPedidosExameses = aelItensPedidosExameses;
	}

	public enum Fields {
		
		SEQ("seq"), 
		ATENDIMENTO_SEQ("atendimento.seq"),
		USL_UNF_SEQ("unidadeFuncionalSala.id.unfSeq"),
		USL_SALA("unidadeFuncionalSala.id.sala");


		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelPedidoExame)) {
			return false;
		}
		AelPedidoExame other = (AelPedidoExame) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
