package br.gov.mec.aghu.model;

// Generated 20/06/2011 14:50:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AelQuestoesQuestionario generated by hbm2java
 */
@Entity
@Table(name = "AEL_QUESTOES_QUESTIONARIO", schema = "AGH")
public class AelQuestoesQuestionario extends BaseEntityId<AelQuestoesQuestionarioId> implements java.io.Serializable {

	private static final long serialVersionUID = 7556677047269462775L;
	
	private AelQuestoesQuestionarioId id;
	private AelQuestionarios aelQuestionarios;
	private DominioSituacao situacao;
	private Boolean obrigatorio;
	private Short ordem;
//	private Short grqSeq;
	private AelGrupoQuestao aelGrupoQuestao;
	private Date alteradoEm;
	private RapServidores servidor;
	private String validacao;
	private AelQuestao questao;
	private Integer version;


	public AelQuestoesQuestionario() {
	}

	public AelQuestoesQuestionario(AelQuestoesQuestionarioId id,
			AelQuestionarios aelQuestionarios, DominioSituacao situacao,
			Boolean obrigatorio) {
		this.id = id;
		this.aelQuestionarios = aelQuestionarios;
		this.situacao = situacao;
		this.obrigatorio = obrigatorio;
	}

	public AelQuestoesQuestionario(AelQuestoesQuestionarioId id,
			AelQuestionarios aelQuestionarios, DominioSituacao situacao,
			Boolean obrigatorio, Short ordem, AelGrupoQuestao aelGrupoQuestao, Date alteradoEm,
			RapServidores servidor, String validacao) {
		this.id = id;
		this.aelQuestionarios = aelQuestionarios;
		this.situacao = situacao;
		this.obrigatorio = obrigatorio;
		this.ordem = ordem;
//		this.grqSeq = grqSeq;
		this.aelGrupoQuestao = aelGrupoQuestao;
		this.alteradoEm = alteradoEm;
		this.servidor = servidor;
		this.validacao = validacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "qaoSeq", column = @Column(name = "QAO_SEQ", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "qtnSeq", column = @Column(name = "QTN_SEQ", nullable = false, precision = 5, scale = 0)) })
	public AelQuestoesQuestionarioId getId() {
		return this.id;
	}

	public void setId(AelQuestoesQuestionarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QTN_SEQ", nullable = false, insertable = false, updatable = false)
	public AelQuestionarios getAelQuestionarios() {
		return this.aelQuestionarios;
	}

	public void setAelQuestionarios(AelQuestionarios aelQuestionarios) {
		this.aelQuestionarios = aelQuestionarios;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QAO_SEQ", nullable = false, insertable = false, updatable = false)
	public AelQuestao getQuestao() {
		return this.questao;
	}

	public void setQuestao(AelQuestao questao) {
		this.questao = questao;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getSituacao() {
		return this.situacao;
	}

	public void setSituacao(DominioSituacao situacao) {
		this.situacao = situacao;
	}
	
	@Column(name = "IND_OBRIGATORIO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getObrigatorio() {
		return this.obrigatorio;
	}

	public void setObrigatorio(Boolean obrigatorio) {
		this.obrigatorio = obrigatorio;
	}

	@Column(name = "ORDEM", precision = 3, scale = 0)
	public Short getOrdem() {
		return this.ordem;
	}

	public void setOrdem(Short ordem) {
		this.ordem = ordem;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRQ_SEQ")
	public AelGrupoQuestao getAelGrupoQuestao() {
		return aelGrupoQuestao;
	}
	
	public void setAelGrupoQuestao(AelGrupoQuestao aelGrupoQuestao) {
		this.aelGrupoQuestao = aelGrupoQuestao;
	}
	
	
//	@Column(name = "GRQ_SEQ", precision = 3, scale = 0)
//	public Short getGrqSeq() {
//		return this.grqSeq;
//	}
//
//	public void setGrqSeq(Short grqSeq) {
//		this.grqSeq = grqSeq;
//	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 7)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
		@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false)})
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Column(name = "VALIDACAO", length = 20)
	public String getValidacao() {
		return this.validacao;
	}

	public void setValidacao(String validacao) {
		this.validacao = validacao;
	}
	

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	
	public enum Fields {
		IND_SITUACAO("situacao"),
		SEQ_QUESTAO("id.qaoSeq"),
		SEQ_QUESTIONARIO("id.qtnSeq"),
		GRUPO_QUESTAO("aelGrupoQuestao"),
		QUESTAO("questao"),
		ORDEM("ordem"),
		VALOR_VALIDO_QUESTOES("questao.aelValorValidoQuestaos")
		;
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
		
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelQuestoesQuestionario)) {
			return false;
		}
		AelQuestoesQuestionario other = (AelQuestoesQuestionario) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####
	

}
