package br.gov.mec.aghu.model;

// Generated 20/06/2011 14:50:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AelQuestionarios generated by hbm2java
 */
@Entity
@SequenceGenerator(name="aelQtnSq1", sequenceName="AGH.AEL_QTN_SQ1", allocationSize = 1)
@Table(name = "AEL_QUESTIONARIOS", schema = "AGH")
public class AelQuestionarios extends BaseEntitySeq<Integer> implements java.io.Serializable {

	private static final long serialVersionUID = 4997973011563511078L;
	
	private Integer seq;
	private String descricao;
	private Byte nroVias;
	private DominioSituacao situacao;
	private Date criadoEm;
	private Date alteradoEm;
	private RapServidores servidor;
	private RapServidores servidorAlterado;
	private Set<AelExamesQuestionario> aelExamesQuestionarios = new HashSet<AelExamesQuestionario>(
			0);
	private Set<AelQuestionariosConvUnid> aelQuestionariosConvUnids = new HashSet<AelQuestionariosConvUnid>(
			0);
	private Set<AelQuestoesQuestionario> aelQuestoesQuestionarios = new HashSet<AelQuestoesQuestionario>(
			0);

	public AelQuestionarios() {
	}

	public AelQuestionarios(Integer seq, String descricao, Byte nroVias,
			DominioSituacao situacao, Date criadoEm, RapServidores servidor) {
		this.seq = seq;
		this.descricao = descricao;
		this.nroVias = nroVias;
		this.situacao = situacao;
		this.criadoEm = criadoEm;
		this.servidor = servidor;
	}

	public AelQuestionarios(Integer seq, String descricao, Byte nroVias,
			DominioSituacao situacao, Date criadoEm, Date alteradoEm, 
			Set<AelExamesQuestionario> aelExamesQuestionarios,
			Set<AelQuestionariosConvUnid> aelQuestionariosConvUnids,
			Set<AelQuestoesQuestionario> aelQuestoesQuestionarios,
			RapServidores servidor, RapServidores servidorAlterado) {
		this.seq = seq;
		this.descricao = descricao;
		this.nroVias = nroVias;
		this.situacao = situacao;
		this.criadoEm = criadoEm;
		this.alteradoEm = alteradoEm;
		this.servidor = servidor;
		this.servidorAlterado = servidorAlterado;
		this.aelExamesQuestionarios = aelExamesQuestionarios;
		this.aelQuestionariosConvUnids = aelQuestionariosConvUnids;
		this.aelQuestoesQuestionarios = aelQuestoesQuestionarios;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aelQtnSq1")
	@Column(name = "SEQ", unique = true, nullable = false, precision = 5, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 100)
	@Length(max = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "NRO_VIAS", nullable = false, precision = 2, scale = 0)
	public Byte getNroVias() {
		return this.nroVias;
	}

	public void setNroVias(Byte nroVias) {
		this.nroVias = nroVias;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getSituacao() {
		return this.situacao;
	}

	public void setSituacao(DominioSituacao situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
		@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false)})
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 7)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_ALTERADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_ALTERADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorAlterado() {
		return this.servidorAlterado;
	}

	public void setServidorAlterado(RapServidores servidor) {
		this.servidorAlterado = servidor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aelQuestionarios")
	public Set<AelExamesQuestionario> getAelExamesQuestionarios() {
		return this.aelExamesQuestionarios;
	}

	public void setAelExamesQuestionarios(
			Set<AelExamesQuestionario> aelExamesQuestionarios) {
		this.aelExamesQuestionarios = aelExamesQuestionarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aelQuestionarios")
	public Set<AelQuestionariosConvUnid> getAelQuestionariosConvUnids() {
		return this.aelQuestionariosConvUnids;
	}

	public void setAelQuestionariosConvUnids(
			Set<AelQuestionariosConvUnid> aelQuestionariosConvUnids) {
		this.aelQuestionariosConvUnids = aelQuestionariosConvUnids;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aelQuestionarios")
	public Set<AelQuestoesQuestionario> getAelQuestoesQuestionarios() {
		return this.aelQuestoesQuestionarios;
	}

	public void setAelQuestoesQuestionarios(
			Set<AelQuestoesQuestionario> aelQuestoesQuestionarios) {
		this.aelQuestoesQuestionarios = aelQuestoesQuestionarios;
	}
	
	public enum Fields {
		SEQ("seq"),
		DESCRICAO("descricao"),
		NRO_VIAS("nroVias"),
		IND_SITUACAO("situacao"),
		QUESTOES_QUESTIONARIOS("aelQuestoesQuestionarios"),
		QUESTIONARIOS_CONV_UNIDS("aelQuestionariosConvUnids"),
		AEL_EXAMES_QUESTIONARIO("aelExamesQuestionarios"),
		;
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
		
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelQuestionarios)) {
			return false;
		}
		AelQuestionarios other = (AelQuestionarios) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
