package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AelRetornoCarta generated by hbm2java
 */
@Entity
@SequenceGenerator(name="aelRnoSq1", sequenceName="AGH.AEL_RNO_SQ1", allocationSize = 1)
@Table(name = "AEL_RETORNO_CARTAS", schema = "AGH")
public class AelRetornoCarta extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2636136185855648073L;
	private Integer seq;
	private Integer version;
	private RapServidores servidor;
	private String descricao;
	private Boolean indCancelaExame;
	private DominioSituacao indSituacao;
	private Boolean indAvisaSolicitante;
	private Date criadoEm;
	
	// FIXME Implementar este relacionamento
//	private Set<AelItemSolicCartas> aelItemSolicCartases = new HashSet<AelItemSolicCartas>(0);
	
	// FIXME Implementar este relacionamento
//	private Set<AelExtratoItemCartas> aelExtratoItemCartases = new HashSet<AelExtratoItemCartas>(0);

	public AelRetornoCarta() {
	}

	public AelRetornoCarta(Integer seq, RapServidores servidor, String descricao, Boolean indCancelaExame, DominioSituacao indSituacao,
			Date criadoEm) {
		this.seq = seq;
		this.servidor = servidor;
		this.descricao = descricao;
		this.indCancelaExame = indCancelaExame;
		this.indSituacao = indSituacao;
		this.criadoEm = criadoEm;
	}

//	public AelRetornoCarta(Integer seq, RapServidores rapServidores, String descricao, String indCancelaExame, String indSituacao,
//			String indAvisaSolicitante, Date criadoEm, Set<AelItemSolicCartas> aelItemSolicCartases,
//			Set<AelExtratoItemCartas> aelExtratoItemCartases) {
//		this.seq = seq;
//		this.rapServidores = rapServidores;
//		this.descricao = descricao;
//		this.indCancelaExame = indCancelaExame;
//		this.indSituacao = indSituacao;
//		this.indAvisaSolicitante = indAvisaSolicitante;
//		this.criadoEm = criadoEm;
//		this.aelItemSolicCartases = aelItemSolicCartases;
//		this.aelExtratoItemCartases = aelExtratoItemCartases;
//	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aelRnoSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 120)
	@Length(max = 120)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_CANCELA_EXAME", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndCancelaExame() {
		return this.indCancelaExame;
	}

	public void setIndCancelaExame(Boolean indCancelaExame) {
		this.indCancelaExame = indCancelaExame;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "IND_AVISA_SOLICITANTE", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAvisaSolicitante() {
		return this.indAvisaSolicitante;
	}

	public void setIndAvisaSolicitante(Boolean indAvisaSolicitante) {
		this.indAvisaSolicitante = indAvisaSolicitante;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aelRetornoCarta")
//	public Set<AelItemSolicCartas> getAelItemSolicCartases() {
//		return this.aelItemSolicCartases;
//	}
//
//	public void setAelItemSolicCartases(Set<AelItemSolicCartas> aelItemSolicCartases) {
//		this.aelItemSolicCartases = aelItemSolicCartases;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aelRetornoCarta")
//	public Set<AelExtratoItemCartas> getAelExtratoItemCartases() {
//		return this.aelExtratoItemCartases;
//	}
//
//	public void setAelExtratoItemCartases(Set<AelExtratoItemCartas> aelExtratoItemCartases) {
//		this.aelExtratoItemCartases = aelExtratoItemCartases;
//	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		RAP_SERVIDORES("servidor"),
		DESCRICAO("descricao"),
		IND_CANCELA_EXAME("indCancelaExame"),
		IND_SITUACAO("indSituacao"),
		IND_AVISA_SOLICITANTE("indAvisaSolicitante"),
		CRIADO_EM("criadoEm"),
//		AEL_ITEM_SOLIC_CARTASES("aelItemSolicCartases"),
//		AEL_EXTRATO_ITEM_CARTASES("aelExtratoItemCartases")
		;

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelRetornoCarta)) {
			return false;
		}
		AelRetornoCarta other = (AelRetornoCarta) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
