package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AelSumarioMascCampoEditId generated by hbm2java
 */
@Embeddable
public class AelSumarioMascCampoEditId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5302237787470431989L;
	private Integer ordemRelatorio;
	private Integer nroLinha;
	private Integer nroCampoEdit;
	private String descricao;
	private Integer version;

	public AelSumarioMascCampoEditId() {
	}

	public AelSumarioMascCampoEditId(Integer ordemRelatorio, Integer nroLinha, Integer nroCampoEdit, Integer version) {
		this.ordemRelatorio = ordemRelatorio;
		this.nroLinha = nroLinha;
		this.nroCampoEdit = nroCampoEdit;
		this.version = version;
	}

	public AelSumarioMascCampoEditId(Integer ordemRelatorio, Integer nroLinha, Integer nroCampoEdit, String descricao, Integer version) {
		this.ordemRelatorio = ordemRelatorio;
		this.nroLinha = nroLinha;
		this.nroCampoEdit = nroCampoEdit;
		this.descricao = descricao;
		this.version = version;
	}

	@Column(name = "ORDEM_RELATORIO", nullable = false)
	public Integer getOrdemRelatorio() {
		return this.ordemRelatorio;
	}

	public void setOrdemRelatorio(Integer ordemRelatorio) {
		this.ordemRelatorio = ordemRelatorio;
	}

	@Column(name = "NRO_LINHA", nullable = false)
	public Integer getNroLinha() {
		return this.nroLinha;
	}

	public void setNroLinha(Integer nroLinha) {
		this.nroLinha = nroLinha;
	}

	@Column(name = "NRO_CAMPO_EDIT", nullable = false)
	public Integer getNroCampoEdit() {
		return this.nroCampoEdit;
	}

	public void setNroCampoEdit(Integer nroCampoEdit) {
		this.nroCampoEdit = nroCampoEdit;
	}

	@Column(name = "DESCRICAO")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getVersion());
		umHashCodeBuilder.append(this.getDescricao());
		umHashCodeBuilder.append(this.getOrdemRelatorio());
		umHashCodeBuilder.append(this.getNroLinha());
		umHashCodeBuilder.append(this.getNroCampoEdit());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelSumarioMascCampoEditId)) {
			return false;
		}
		AelSumarioMascCampoEditId other = (AelSumarioMascCampoEditId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getVersion(), other.getVersion());
		umEqualsBuilder.append(this.getDescricao(), other.getDescricao());
		umEqualsBuilder.append(this.getOrdemRelatorio(), other.getOrdemRelatorio());
		umEqualsBuilder.append(this.getNroLinha(), other.getNroLinha());
		umEqualsBuilder.append(this.getNroCampoEdit(), other.getNroCampoEdit());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
