package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AelTmpBullInt generated by hbm2java
 */
@Entity
@Table(name = "AEL_TMP_BULL_INT", schema = "AGH")
public class AelTmpBullInt extends BaseEntityId<AelTmpBullIntId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7280600098493382297L;
	private AelTmpBullIntId id;
	private Integer version;
	private AelUnfExecutaExames aelUnfExecutaExames;
	private Integer codExme;

	public AelTmpBullInt() {
	}

	public AelTmpBullInt(AelUnfExecutaExames aelUnfExecutaExames, Integer codExme) {
		this.aelUnfExecutaExames = aelUnfExecutaExames;
		this.codExme = codExme;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "exaSigla", column = @Column(name = "EXA_SIGLA", nullable = false, length = 5)),
			@AttributeOverride(name = "manSeq", column = @Column(name = "MAN_SEQ", nullable = false)),
			@AttributeOverride(name = "unfSeq", column = @Column(name = "UNF_SEQ", nullable = false)) })
	public AelTmpBullIntId getId() {
		return this.id;
	}

	public void setId(AelTmpBullIntId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public AelUnfExecutaExames getAelUnfExecutaExames() {
		return this.aelUnfExecutaExames;
	}

	public void setAelUnfExecutaExames(AelUnfExecutaExames aelUnfExecutaExames) {
		this.aelUnfExecutaExames = aelUnfExecutaExames;
	}

	@Column(name = "COD_EXME", nullable = false)
	public Integer getCodExme() {
		return this.codExme;
	}

	public void setCodExme(Integer codExme) {
		this.codExme = codExme;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		AEL_UNF_EXECUTA_EXAMES("aelUnfExecutaExames"),
		COD_EXME("codExme"),
		EXA_SIGLA("id.exaSigla"),
		MAN_SEQ("id.manSeq");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelTmpBullInt)) {
			return false;
		}
		AelTmpBullInt other = (AelTmpBullInt) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
