package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AelValorValidoQuesitoId generated by hbm2java
 */
@Embeddable
public class AelValorValidoQuesitoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7462811639012317388L;
	private Integer ppqPpoPjqSeq;
	private Short ppqPpoSeqp;
	private Short ppqSeqp;
	private Short seqp;

	public AelValorValidoQuesitoId() {
	}

	public AelValorValidoQuesitoId(Integer ppqPpoPjqSeq, Short ppqPpoSeqp, Short ppqSeqp, Short seqp) {
		this.ppqPpoPjqSeq = ppqPpoPjqSeq;
		this.ppqPpoSeqp = ppqPpoSeqp;
		this.ppqSeqp = ppqSeqp;
		this.seqp = seqp;
	}

	@Column(name = "PPQ_PPO_PJQ_SEQ", nullable = false)
	public Integer getPpqPpoPjqSeq() {
		return this.ppqPpoPjqSeq;
	}

	public void setPpqPpoPjqSeq(Integer ppqPpoPjqSeq) {
		this.ppqPpoPjqSeq = ppqPpoPjqSeq;
	}

	@Column(name = "PPQ_PPO_SEQP", nullable = false)
	public Short getPpqPpoSeqp() {
		return this.ppqPpoSeqp;
	}

	public void setPpqPpoSeqp(Short ppqPpoSeqp) {
		this.ppqPpoSeqp = ppqPpoSeqp;
	}

	@Column(name = "PPQ_SEQP", nullable = false)
	public Short getPpqSeqp() {
		return this.ppqSeqp;
	}

	public void setPpqSeqp(Short ppqSeqp) {
		this.ppqSeqp = ppqSeqp;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getPpqPpoPjqSeq());
		umHashCodeBuilder.append(this.getPpqPpoSeqp());
		umHashCodeBuilder.append(this.getPpqSeqp());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelValorValidoQuesitoId)) {
			return false;
		}
		AelValorValidoQuesitoId other = (AelValorValidoQuesitoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getPpqPpoPjqSeq(), other.getPpqPpoPjqSeq());
		umEqualsBuilder.append(this.getPpqPpoSeqp(), other.getPpqPpoSeqp());
		umEqualsBuilder.append(this.getPpqSeqp(), other.getPpqSeqp());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
