package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AelValorValidoQuestaoId generated by hbm2java
 */
@Embeddable
public class AelValorValidoQuestaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7991782307953579174L;
	private Integer qaoSeq;
	private Short seqp;

	public AelValorValidoQuestaoId() {
	}

	public AelValorValidoQuestaoId(Integer qaoSeq, Short seqp) {
		this.qaoSeq = qaoSeq;
		this.seqp = seqp;
	}

	@Column(name = "QAO_SEQ", nullable = false)
	public Integer getQaoSeq() {
		return this.qaoSeq;
	}

	public void setQaoSeq(Integer qaoSeq) {
		this.qaoSeq = qaoSeq;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getQaoSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AelValorValidoQuestaoId)) {
			return false;
		}
		AelValorValidoQuestaoId other = (AelValorValidoQuestaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getQaoSeq(), other.getQaoSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
