package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AesGrupoTrabalhoId generated by hbm2java
 */
@Embeddable
public class AesGrupoTrabalhoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2734500830871597905L;
	private Integer areCodigo;
	private Integer cctCodigo;
	private String tgtCodigo;

	public AesGrupoTrabalhoId() {
	}

	public AesGrupoTrabalhoId(Integer areCodigo, Integer cctCodigo, String tgtCodigo) {
		this.areCodigo = areCodigo;
		this.cctCodigo = cctCodigo;
		this.tgtCodigo = tgtCodigo;
	}

	@Column(name = "ARE_CODIGO", nullable = false)
	public Integer getAreCodigo() {
		return this.areCodigo;
	}

	public void setAreCodigo(Integer areCodigo) {
		this.areCodigo = areCodigo;
	}

	@Column(name = "CCT_CODIGO", nullable = false)
	public Integer getCctCodigo() {
		return this.cctCodigo;
	}

	public void setCctCodigo(Integer cctCodigo) {
		this.cctCodigo = cctCodigo;
	}

	@Column(name = "TGT_CODIGO", nullable = false, length = 5)
	@Length(max = 5)
	public String getTgtCodigo() {
		return this.tgtCodigo;
	}

	public void setTgtCodigo(String tgtCodigo) {
		this.tgtCodigo = tgtCodigo;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getCctCodigo());
		umHashCodeBuilder.append(this.getAreCodigo());
		umHashCodeBuilder.append(this.getTgtCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AesGrupoTrabalhoId)) {
			return false;
		}
		AesGrupoTrabalhoId other = (AesGrupoTrabalhoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getCctCodigo(), other.getCctCodigo());
		umEqualsBuilder.append(this.getAreCodigo(), other.getAreCodigo());
		umEqualsBuilder.append(this.getTgtCodigo(), other.getTgtCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
