package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AesJustifHoraExcedId generated by hbm2java
 */
@Embeddable
public class AesJustifHoraExcedId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 273236632818220314L;
	private Integer eheSerMatricula;
	private Short eheSerVinCodigo;
	private Short eheSequencia;
	private Short jhoCodigo;

	public AesJustifHoraExcedId() {
	}

	public AesJustifHoraExcedId(Integer eheSerMatricula, Short eheSerVinCodigo, Short eheSequencia, Short jhoCodigo) {
		this.eheSerMatricula = eheSerMatricula;
		this.eheSerVinCodigo = eheSerVinCodigo;
		this.eheSequencia = eheSequencia;
		this.jhoCodigo = jhoCodigo;
	}

	@Column(name = "EHE_SER_MATRICULA", nullable = false)
	public Integer getEheSerMatricula() {
		return this.eheSerMatricula;
	}

	public void setEheSerMatricula(Integer eheSerMatricula) {
		this.eheSerMatricula = eheSerMatricula;
	}

	@Column(name = "EHE_SER_VIN_CODIGO", nullable = false)
	public Short getEheSerVinCodigo() {
		return this.eheSerVinCodigo;
	}

	public void setEheSerVinCodigo(Short eheSerVinCodigo) {
		this.eheSerVinCodigo = eheSerVinCodigo;
	}

	@Column(name = "EHE_SEQUENCIA", nullable = false)
	public Short getEheSequencia() {
		return this.eheSequencia;
	}

	public void setEheSequencia(Short eheSequencia) {
		this.eheSequencia = eheSequencia;
	}

	@Column(name = "JHO_CODIGO", nullable = false)
	public Short getJhoCodigo() {
		return this.jhoCodigo;
	}

	public void setJhoCodigo(Short jhoCodigo) {
		this.jhoCodigo = jhoCodigo;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getEheSerMatricula());
		umHashCodeBuilder.append(this.getEheSerVinCodigo());
		umHashCodeBuilder.append(this.getEheSequencia());
		umHashCodeBuilder.append(this.getJhoCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AesJustifHoraExcedId)) {
			return false;
		}
		AesJustifHoraExcedId other = (AesJustifHoraExcedId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getEheSerMatricula(), other.getEheSerMatricula());
		umEqualsBuilder.append(this.getEheSerVinCodigo(), other.getEheSerVinCodigo());
		umEqualsBuilder.append(this.getEheSequencia(), other.getEheSequencia());
		umEqualsBuilder.append(this.getJhoCodigo(), other.getJhoCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
