package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AesModificacaoEscEncerrada generated by hbm2java
 */
@Entity
@Table(name = "AES_MODIFICACOES_ESC_ENCERRADA", schema = "AGH")
public class AesModificacaoEscEncerrada extends BaseEntityId<AesModificacaoEscEncerradaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1263520679622595575L;
	private AesModificacaoEscEncerradaId id;
	private Integer version;
	private AesRegime aesRegime;
	private RapServidores rapServidores;
	private AesSituacaoEscala aesSituacaoEscala;
	private Date data;
	private String autzGrh;
	private String observacao;
	private Date criadoEm;

	public AesModificacaoEscEncerrada() {
	}

	public AesModificacaoEscEncerrada(AesModificacaoEscEncerradaId id, AesRegime aesRegime, RapServidores rapServidores,
			Date data, String autzGrh) {
		this.id = id;
		this.aesRegime = aesRegime;
		this.rapServidores = rapServidores;
		this.data = data;
		this.autzGrh = autzGrh;
	}

	public AesModificacaoEscEncerrada(AesModificacaoEscEncerradaId id, AesRegime aesRegime, RapServidores rapServidores,
			AesSituacaoEscala aesSituacaoEscala, Date data, String autzGrh, String observacao, Date criadoEm) {
		this.id = id;
		this.aesRegime = aesRegime;
		this.rapServidores = rapServidores;
		this.aesSituacaoEscala = aesSituacaoEscala;
		this.data = data;
		this.autzGrh = autzGrh;
		this.observacao = observacao;
		this.criadoEm = criadoEm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "regSerMatricula", column = @Column(name = "REG_SER_MATRICULA", nullable = false)),
			@AttributeOverride(name = "regSerVinCodigo", column = @Column(name = "REG_SER_VIN_CODIGO", nullable = false)),
			@AttributeOverride(name = "regSeq", column = @Column(name = "REG_SEQ", nullable = false)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false)) })
	public AesModificacaoEscEncerradaId getId() {
		return this.id;
	}

	public void setId(AesModificacaoEscEncerradaId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "REG_SER_MATRICULA", referencedColumnName = "SER_MATRICULA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "REG_SER_VIN_CODIGO", referencedColumnName = "SER_VIN_CODIGO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "REG_SEQ", referencedColumnName = "SEQ", nullable = false, insertable = false, updatable = false) })
	public AesRegime getAesRegime() {
		return this.aesRegime;
	}

	public void setAesRegime(AesRegime aesRegime) {
		this.aesRegime = aesRegime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SES_SEQ")
	public AesSituacaoEscala getAesSituacaoEscala() {
		return this.aesSituacaoEscala;
	}

	public void setAesSituacaoEscala(AesSituacaoEscala aesSituacaoEscala) {
		this.aesSituacaoEscala = aesSituacaoEscala;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA", nullable = false, length = 29)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "AUTZ_GRH", nullable = false, length = 1)
	@Length(max = 1)
	public String getAutzGrh() {
		return this.autzGrh;
	}

	public void setAutzGrh(String autzGrh) {
		this.autzGrh = autzGrh;
	}

	@Column(name = "OBSERVACAO", length = 150)
	@Length(max = 150)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		AES_REGIMES("aesRegime"),
		RAP_SERVIDORES("rapServidores"),
		AES_SITUACOES_ESCALA("aesSituacaoEscala"),
		DATA("data"),
		AUTZ_GRH("autzGrh"),
		OBSERVACAO("observacao"),
		CRIADO_EM("criadoEm");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AesModificacaoEscEncerrada)) {
			return false;
		}
		AesModificacaoEscEncerrada other = (AesModificacaoEscEncerrada) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
