package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AesSubstituicaoEscala generated by hbm2java
 */
@Entity
@Table(name = "AES_SUBSTITUICOES_ESCALA", schema = "AGH")
public class AesSubstituicaoEscala extends BaseEntityId<AesSubstituicaoEscalaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7445881465926921484L;
	private AesSubstituicaoEscalaId id;
	private Integer version;
	private AesEscala aesEscalasByAesSubEscFk2;
	private AesEscala aesEscalasByAesSubEscFk1;

	public AesSubstituicaoEscala() {
	}

	public AesSubstituicaoEscala(AesSubstituicaoEscalaId id, AesEscala aesEscalasByAesSubEscFk2, AesEscala aesEscalasByAesSubEscFk1) {
		this.id = id;
		this.aesEscalasByAesSubEscFk2 = aesEscalasByAesSubEscFk2;
		this.aesEscalasByAesSubEscFk1 = aesEscalasByAesSubEscFk1;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "serMatriculaSubstitui", column = @Column(name = "SER_MATRICULA_SUBSTITUI", nullable = false)),
			@AttributeOverride(name = "serVinCodigoSubstitui", column = @Column(name = "SER_VIN_CODIGO_SUBSTITUI", nullable = false)),
			@AttributeOverride(name = "regSeqSubstitui", column = @Column(name = "REG_SEQ_SUBSTITUI", nullable = false)),
			@AttributeOverride(name = "seqSubstitui", column = @Column(name = "SEQ_SUBSTITUI", nullable = false)),
			@AttributeOverride(name = "serMatriculaSubstituido", column = @Column(name = "SER_MATRICULA_SUBSTITUIDO", nullable = false)),
			@AttributeOverride(name = "serVinCodigoSubstituido", column = @Column(name = "SER_VIN_CODIGO_SUBSTITUIDO", nullable = false)),
			@AttributeOverride(name = "regSeqSubstituido", column = @Column(name = "REG_SEQ_SUBSTITUIDO", nullable = false)),
			@AttributeOverride(name = "seqSubstituido", column = @Column(name = "SEQ_SUBSTITUIDO", nullable = false)) })
	public AesSubstituicaoEscalaId getId() {
		return this.id;
	}

	public void setId(AesSubstituicaoEscalaId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SER_MATRICULA_SUBSTITUIDO", referencedColumnName = "REG_SER_MATRICULA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SER_VIN_CODIGO_SUBSTITUIDO", referencedColumnName = "REG_SER_VIN_CODIGO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "REG_SEQ_SUBSTITUIDO", referencedColumnName = "REG_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SEQ_SUBSTITUIDO", referencedColumnName = "SEQ", nullable = false, insertable = false, updatable = false) })
	public AesEscala getAesEscalasByAesSubEscFk2() {
		return this.aesEscalasByAesSubEscFk2;
	}

	public void setAesEscalasByAesSubEscFk2(AesEscala aesEscalasByAesSubEscFk2) {
		this.aesEscalasByAesSubEscFk2 = aesEscalasByAesSubEscFk2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SER_MATRICULA_SUBSTITUI", referencedColumnName = "REG_SER_MATRICULA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SER_VIN_CODIGO_SUBSTITUI", referencedColumnName = "REG_SER_VIN_CODIGO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "REG_SEQ_SUBSTITUI", referencedColumnName = "REG_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SEQ_SUBSTITUI", referencedColumnName = "SEQ", nullable = false, insertable = false, updatable = false) })
	public AesEscala getAesEscalasByAesSubEscFk1() {
		return this.aesEscalasByAesSubEscFk1;
	}

	public void setAesEscalasByAesSubEscFk1(AesEscala aesEscalasByAesSubEscFk1) {
		this.aesEscalasByAesSubEscFk1 = aesEscalasByAesSubEscFk1;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		AES_ESCALAS_BY_AES_SUB_ESC_FK2("aesEscalasByAesSubEscFk2"),
		AES_ESCALAS_BY_AES_SUB_ESC_FK1("aesEscalasByAesSubEscFk1");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AesSubstituicaoEscala)) {
			return false;
		}
		AesSubstituicaoEscala other = (AesSubstituicaoEscala) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
