package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AesSituacaoEscala generated by hbm2java
 */
@Entity
@SequenceGenerator(name="aesSesSq1", sequenceName="AGH.AES_SES_SQ1", allocationSize = 1)
@Table(name = "AES_SITUACOES_ESCALA", schema = "AGH", uniqueConstraints = @UniqueConstraint(columnNames = { "tsi_codigo", "cta_codigo" }))
public class AesSituacaoEscala extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7991137260465175885L;
	private Integer seq;
	private Integer version;
	private AesTipoSituacao aesTipoSituacao;
	private RapClassificacaoTiposAfastamento rapClassificacaoTiposAfastamento;
	private String indPermDigitar;
	private String indPermUserAlterar;
	private String indPermManterHistorico;
	private String indDeveSerHistorico;
	private Set<AesRegimeSituacao> aesRegimeSituacaos = new HashSet<AesRegimeSituacao>(0);
	private Set<AesModificacaoEscEncerrada> aesModificacaoEscEncerradas = new HashSet<AesModificacaoEscEncerrada>(0);
	private Set<AesEscala> aesEscalaes = new HashSet<AesEscala>(0);

	public AesSituacaoEscala() {
	}

	public AesSituacaoEscala(Integer seq) {
		this.seq = seq;
	}

	public AesSituacaoEscala(Integer seq, AesTipoSituacao aesTipoSituacao, RapClassificacaoTiposAfastamento rapClassificacaoTiposAfastamento,
			String indPermDigitar, String indPermUserAlterar, String indPermManterHistorico, String indDeveSerHistorico,
			Set<AesRegimeSituacao> aesRegimeSituacaos, Set<AesModificacaoEscEncerrada> aesModificacaoEscEncerradas,
			Set<AesEscala> aesEscalaes) {
		this.seq = seq;
		this.aesTipoSituacao = aesTipoSituacao;
		this.rapClassificacaoTiposAfastamento = rapClassificacaoTiposAfastamento;
		this.indPermDigitar = indPermDigitar;
		this.indPermUserAlterar = indPermUserAlterar;
		this.indPermManterHistorico = indPermManterHistorico;
		this.indDeveSerHistorico = indDeveSerHistorico;
		this.aesRegimeSituacaos = aesRegimeSituacaos;
		this.aesModificacaoEscEncerradas = aesModificacaoEscEncerradas;
		this.aesEscalaes = aesEscalaes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aesSesSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSI_CODIGO")
	public AesTipoSituacao getAesTipoSituacao() {
		return this.aesTipoSituacao;
	}

	public void setAesTipoSituacao(AesTipoSituacao aesTipoSituacao) {
		this.aesTipoSituacao = aesTipoSituacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTA_CODIGO")
	public RapClassificacaoTiposAfastamento getRapClassificacaoTiposAfastamento() {
		return this.rapClassificacaoTiposAfastamento;
	}

	public void setRapClassificacaoTiposAfastamento(RapClassificacaoTiposAfastamento rapClassificacaoTiposAfastamento) {
		this.rapClassificacaoTiposAfastamento = rapClassificacaoTiposAfastamento;
	}

	@Column(name = "IND_PERM_DIGITAR", length = 1)
	@Length(max = 1)
	public String getIndPermDigitar() {
		return this.indPermDigitar;
	}

	public void setIndPermDigitar(String indPermDigitar) {
		this.indPermDigitar = indPermDigitar;
	}

	@Column(name = "IND_PERM_USER_ALTERAR", length = 1)
	@Length(max = 1)
	public String getIndPermUserAlterar() {
		return this.indPermUserAlterar;
	}

	public void setIndPermUserAlterar(String indPermUserAlterar) {
		this.indPermUserAlterar = indPermUserAlterar;
	}

	@Column(name = "IND_PERM_MANTER_HISTORICO", length = 1)
	@Length(max = 1)
	public String getIndPermManterHistorico() {
		return this.indPermManterHistorico;
	}

	public void setIndPermManterHistorico(String indPermManterHistorico) {
		this.indPermManterHistorico = indPermManterHistorico;
	}

	@Column(name = "IND_DEVE_SER_HISTORICO", length = 1)
	@Length(max = 1)
	public String getIndDeveSerHistorico() {
		return this.indDeveSerHistorico;
	}

	public void setIndDeveSerHistorico(String indDeveSerHistorico) {
		this.indDeveSerHistorico = indDeveSerHistorico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aesSituacaoEscala")
	public Set<AesRegimeSituacao> getAesRegimeSituacaos() {
		return this.aesRegimeSituacaos;
	}

	public void setAesRegimeSituacaos(Set<AesRegimeSituacao> aesRegimeSituacaos) {
		this.aesRegimeSituacaos = aesRegimeSituacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aesSituacaoEscala")
	public Set<AesModificacaoEscEncerrada> getAesModificacaoEscEncerradas() {
		return this.aesModificacaoEscEncerradas;
	}

	public void setAesModificacaoEscEncerradas(Set<AesModificacaoEscEncerrada> aesModificacaoEscEncerradas) {
		this.aesModificacaoEscEncerradas = aesModificacaoEscEncerradas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aesSituacaoEscala")
	public Set<AesEscala> getAesEscalaes() {
		return this.aesEscalaes;
	}

	public void setAesEscalaes(Set<AesEscala> aesEscalaes) {
		this.aesEscalaes = aesEscalaes;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		AES_TIPOS_SITUACAO("aesTipoSituacao"),
		RAP_CLASSIFICACAO_TIPOS_AFASTAMENTO("rapClassificacaoTiposAfastamento"),
		IND_PERM_DIGITAR("indPermDigitar"),
		IND_PERM_USER_ALTERAR("indPermUserAlterar"),
		IND_PERM_MANTER_HISTORICO("indPermManterHistorico"),
		IND_DEVE_SER_HISTORICO("indDeveSerHistorico"),
		AES_REGIME_SITUACAOS("aesRegimeSituacaos"),
		AES_MODIFICACAO_ESC_ENCERRADAS("aesModificacaoEscEncerradas"),
		AES_ESCALAES("aesEscalaes");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AesSituacaoEscala)) {
			return false;
		}
		AesSituacaoEscala other = (AesSituacaoEscala) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
