package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AesTmpSaldoConversao generated by hbm2java
 */
@Entity
@Table(name = "AES_TMP_SALDO_CONVERSAO", schema = "AGH")
public class AesTmpSaldoConversao extends BaseEntityId<AesTmpSaldoConversaoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6916693091168956430L;
	private AesTmpSaldoConversaoId id;
	private Integer version;
	private Integer minSaldo;
	private Integer minEhe;
	private String total;
	private String sinal;

	public AesTmpSaldoConversao() {
	}

	public AesTmpSaldoConversao(AesTmpSaldoConversaoId id) {
		this.id = id;
	}

	public AesTmpSaldoConversao(AesTmpSaldoConversaoId id, Integer minSaldo, Integer minEhe, String total, String sinal) {
		this.id = id;
		this.minSaldo = minSaldo;
		this.minEhe = minEhe;
		this.total = total;
		this.sinal = sinal;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "serMatricula", column = @Column(name = "SER_MATRICULA", nullable = false)),
			@AttributeOverride(name = "serVinCodigo", column = @Column(name = "SER_VIN_CODIGO", nullable = false)) })
	public AesTmpSaldoConversaoId getId() {
		return this.id;
	}

	public void setId(AesTmpSaldoConversaoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "MIN_SALDO")
	public Integer getMinSaldo() {
		return this.minSaldo;
	}

	public void setMinSaldo(Integer minSaldo) {
		this.minSaldo = minSaldo;
	}

	@Column(name = "MIN_EHE")
	public Integer getMinEhe() {
		return this.minEhe;
	}

	public void setMinEhe(Integer minEhe) {
		this.minEhe = minEhe;
	}

	@Column(name = "TOTAL", length = 6)
	@Length(max = 6)
	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	@Column(name = "SINAL", length = 1)
	@Length(max = 1)
	public String getSinal() {
		return this.sinal;
	}

	public void setSinal(String sinal) {
		this.sinal = sinal;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		MIN_SALDO("minSaldo"),
		MIN_EHE("minEhe"),
		TOTAL("total"),
		SINAL("sinal");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AesTmpSaldoConversao)) {
			return false;
		}
		AesTmpSaldoConversao other = (AesTmpSaldoConversao) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
