package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioIndicadorExterno;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AfaComposicaoItemPreparo generated by hbm2java
 */
@Entity
@Table(name = "AFA_COMPOS_ITEM_PREPAROS", schema = "AGH")
public class AfaComposicaoItemPreparo extends BaseEntityId<AfaComposicaoItemPreparoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9056269358624416995L;
	private AfaComposicaoItemPreparoId id;
	private Integer version;
	private RapServidores rapServidoresByAfaCpoSerFk2;
	private RapServidores rapServidoresByAfaCpoSerFk1;
	private AfaItemPreparoMdto afaItemPreparoMdto;
	private AfaMedicamento afaMedicamento;
	private AfaFormaDosagem afaFormaDosagem;
	private Date criadoEm;
	private Double qtdePreparada;
	private Float volumeMl;
	private String indQsp;
	private String descricaoEtiqueta;
	private Date alteradoEm;
	private Short ordemVisualizacao;
	private String lote;
	private DominioIndicadorExterno indExterno;
	
	// FIXME Implementar este relacionamento
//	private Set<AfaDispensacaoMdtos> afaDispensacaoMdtoses = new HashSet<AfaDispensacaoMdtos>(0);

	public AfaComposicaoItemPreparo() {
	}

	public AfaComposicaoItemPreparo(AfaComposicaoItemPreparoId id, RapServidores rapServidoresByAfaCpoSerFk1,
			AfaItemPreparoMdto afaItemPreparoMdto, AfaMedicamento afaMedicamento, AfaFormaDosagem afaFormaDosagem,
			Date criadoEm, Double qtdePreparada, String indQsp, String descricaoEtiqueta) {
		this.id = id;
		this.rapServidoresByAfaCpoSerFk1 = rapServidoresByAfaCpoSerFk1;
		this.afaItemPreparoMdto = afaItemPreparoMdto;
		this.afaMedicamento = afaMedicamento;
		this.afaFormaDosagem = afaFormaDosagem;
		this.criadoEm = criadoEm;
		this.qtdePreparada = qtdePreparada;
		this.indQsp = indQsp;
		this.descricaoEtiqueta = descricaoEtiqueta;
	}

	public AfaComposicaoItemPreparo(AfaComposicaoItemPreparoId id, RapServidores rapServidoresByAfaCpoSerFk2,
			RapServidores rapServidoresByAfaCpoSerFk1, AfaItemPreparoMdto afaItemPreparoMdto, AfaMedicamento afaMedicamento,
			AfaFormaDosagem afaFormaDosagem, Date criadoEm, Double qtdePreparada, Float volumeMl, String indQsp,
			String descricaoEtiqueta, Date alteradoEm, Short ordemVisualizacao, String lote
//			, Set<AfaDispensacaoMdtos> afaDispensacaoMdtoses
			) {
		this.id = id;
		this.rapServidoresByAfaCpoSerFk2 = rapServidoresByAfaCpoSerFk2;
		this.rapServidoresByAfaCpoSerFk1 = rapServidoresByAfaCpoSerFk1;
		this.afaItemPreparoMdto = afaItemPreparoMdto;
		this.afaMedicamento = afaMedicamento;
		this.afaFormaDosagem = afaFormaDosagem;
		this.criadoEm = criadoEm;
		this.qtdePreparada = qtdePreparada;
		this.volumeMl = volumeMl;
		this.indQsp = indQsp;
		this.descricaoEtiqueta = descricaoEtiqueta;
		this.alteradoEm = alteradoEm;
		this.ordemVisualizacao = ordemVisualizacao;
		this.lote = lote;
//		this.afaDispensacaoMdtoses = afaDispensacaoMdtoses;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "itoSeqp", column = @Column(name = "ITO_SEQP", nullable = false)),
			@AttributeOverride(name = "itoPtoSeq", column = @Column(name = "ITO_PTO_SEQ", nullable = false)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false)) })
	public AfaComposicaoItemPreparoId getId() {
		return this.id;
	}

	public void setId(AfaComposicaoItemPreparoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA_ALTERADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_ALTERADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getRapServidoresByAfaCpoSerFk2() {
		return this.rapServidoresByAfaCpoSerFk2;
	}

	public void setRapServidoresByAfaCpoSerFk2(RapServidores rapServidoresByAfaCpoSerFk2) {
		this.rapServidoresByAfaCpoSerFk2 = rapServidoresByAfaCpoSerFk2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidoresByAfaCpoSerFk1() {
		return this.rapServidoresByAfaCpoSerFk1;
	}

	public void setRapServidoresByAfaCpoSerFk1(RapServidores rapServidoresByAfaCpoSerFk1) {
		this.rapServidoresByAfaCpoSerFk1 = rapServidoresByAfaCpoSerFk1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ITO_SEQP", referencedColumnName = "SEQP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ITO_PTO_SEQ", referencedColumnName = "PTO_SEQ", nullable = false, insertable = false, updatable = false) })
	public AfaItemPreparoMdto getAfaItemPreparoMdto() {
		return this.afaItemPreparoMdto;
	}

	public void setAfaItemPreparoMdto(AfaItemPreparoMdto afaItemPreparoMdto) {
		this.afaItemPreparoMdto = afaItemPreparoMdto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MED_MAT_CODIGO", nullable = false)
	public AfaMedicamento getAfaMedicamento() {
		return this.afaMedicamento;
	}

	public void setAfaMedicamento(AfaMedicamento afaMedicamento) {
		this.afaMedicamento = afaMedicamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FDS_SEQ", nullable = false)
	public AfaFormaDosagem getAfaFormaDosagem() {
		return this.afaFormaDosagem;
	}

	public void setAfaFormaDosagem(AfaFormaDosagem afaFormaDosagem) {
		this.afaFormaDosagem = afaFormaDosagem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "QTDE_PREPARADA", nullable = false, precision = 17, scale = 17)
	public Double getQtdePreparada() {
		return this.qtdePreparada;
	}

	public void setQtdePreparada(Double qtdePreparada) {
		this.qtdePreparada = qtdePreparada;
	}

	@Column(name = "VOLUME_ML", precision = 8, scale = 8)
	public Float getVolumeMl() {
		return this.volumeMl;
	}

	public void setVolumeMl(Float volumeMl) {
		this.volumeMl = volumeMl;
	}

	@Column(name = "IND_QSP", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndQsp() {
		return this.indQsp;
	}

	public void setIndQsp(String indQsp) {
		this.indQsp = indQsp;
	}

	@Column(name = "DESCRICAO_ETIQUETA", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricaoEtiqueta() {
		return this.descricaoEtiqueta;
	}

	public void setDescricaoEtiqueta(String descricaoEtiqueta) {
		this.descricaoEtiqueta = descricaoEtiqueta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 29)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@Column(name = "ORDEM_VISUALIZACAO")
	public Short getOrdemVisualizacao() {
		return this.ordemVisualizacao;
	}

	public void setOrdemVisualizacao(Short ordemVisualizacao) {
		this.ordemVisualizacao = ordemVisualizacao;
	}

	@Column(name = "LOTE", length = 20)
	@Length(max = 20)
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}
	
	

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "afaComposicaoItemPreparo")
//	public Set<AfaDispensacaoMdtos> getAfaDispensacaoMdtoses() {
//		return this.afaDispensacaoMdtoses;
//	}
//
//	public void setAfaDispensacaoMdtoses(Set<AfaDispensacaoMdtos> afaDispensacaoMdtoses) {
//		this.afaDispensacaoMdtoses = afaDispensacaoMdtoses;
//	}


	public enum Fields {

		ID("id"),
		VERSION("version"),
		RAP_SERVIDORES_BY_AFA_CPO_SER_FK2("rapServidoresByAfaCpoSerFk2"),
		RAP_SERVIDORES_BY_AFA_CPO_SER_FK1("rapServidoresByAfaCpoSerFk1"),
		AFA_ITEM_PREPARO_MDTOS("afaItemPreparoMdto"),
		AFA_MEDICAMENTO("afaMedicamento"),
		AFA_FORMA_DOSAGEM("afaFormaDosagem"),
		CRIADO_EM("criadoEm"),
		QTDE_PREPARADA("qtdePreparada"),
		VOLUME_ML("volumeMl"),
		IND_QSP("indQsp"),
		DESCRICAO_ETIQUETA("descricaoEtiqueta"),
		ALTERADO_EM("alteradoEm"),
		ORDEM_VISUALIZACAO("ordemVisualizacao"),
		LOTE("lote"),
		ITO_PTO_SEQ("id.itoPtoSeq"),
		ITO_SEQP("id.itoSeqp"),
		SEQP("id.seqp"),
		IND_EXTERNO("indExterno")
//		AFA_DISPENSACAO_MDTOSES("afaDispensacaoMdtoses")
		;

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

	@Column(name = "IND_EXTERNO", nullable = true, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioIndicadorExterno getIndExterno() {
		return indExterno;
	}

	public void setIndExterno(DominioIndicadorExterno indExterno) {
		this.indExterno = indExterno;
	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AfaComposicaoItemPreparo)) {
			return false;
		}
		AfaComposicaoItemPreparo other = (AfaComposicaoItemPreparo) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
