package br.gov.mec.aghu.model;

// Generated 27/04/2011 12:34:12 by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


import org.hibernate.annotations.Immutable;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.dominio.DominioTipoEquivalentesMedicamento;
import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * AfaMdtoEquivalentesJn generated by hbm2java
 */

@Entity
@Table(name = "AFA_MDTO_EQUIVALENTES_JN", schema = "AGH")
@SequenceGenerator(name = "afaMeqjJnSeq", sequenceName = "AGH.AFA_MEQ_jn_seq", allocationSize = 1)
@Immutable
public class AfaMedicamentoEquivalenteJn extends BaseJournal implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 261413852849918863L;
	private Integer medMatCodigo;
	private Integer medMatCodigoEquivalente;
	private Date criadoEm;
	private DominioSituacao indSituacao;
	private Integer serMatricula;
	private Short serVinCodigo;
	private DominioTipoEquivalentesMedicamento tipo;
	
	//Transient
	private String nomeResponsavel;
	private String medMatCodigoEquivalenteUmmDescricao;
	private String medMatCodigoEquivalenteDescricao;
	private BigDecimal medMatCodigoEquivalenteConcentracao;


	public AfaMedicamentoEquivalenteJn() {
	}
	
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "afaMeqjJnSeq")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}

	@Column(name = "MED_MAT_CODIGO", nullable = false)
	public Integer getMedMatCodigo() {
		return this.medMatCodigo;
	}

	public void setMedMatCodigo(Integer medMatCodigo) {
		this.medMatCodigo = medMatCodigo;
	}

	@Column(name = "MED_MAT_CODIGO_EQUIVALENTE", nullable = false)
	public Integer getMedMatCodigoEquivalente() {
		return this.medMatCodigoEquivalente;
	}

	public void setMedMatCodigoEquivalente(Integer medMatCodigoEquivalente) {
		this.medMatCodigoEquivalente = medMatCodigoEquivalente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "TIPO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioTipoEquivalentesMedicamento getTipo() {
		return tipo;
	}

	public void setTipo(DominioTipoEquivalentesMedicamento tipo) {
		this.tipo = tipo;
	}
	
	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}
	
	public enum Fields {

		MED_MAT_CODIGO("medMatCodigo"),
		DATA_ALTERACAO("dataAlteracao");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}

	@Transient
	public String getNomeResponsavel() {
		return nomeResponsavel;
	}

	public void setNomeResponsavel(String nomeResponsavel) {
		this.nomeResponsavel = nomeResponsavel;
	}

	@Transient
	public String getMedMatCodigoEquivalenteDescricao() {
		return medMatCodigoEquivalenteDescricao;
	}

	public void setMedMatCodigoEquivalenteDescricao(
			String medMatCodigoEquivalenteDescricao) {
		this.medMatCodigoEquivalenteDescricao = medMatCodigoEquivalenteDescricao;
	}

	@Transient
	public String getMedMatCodigoEquivalenteUmmDescricao() {
		return medMatCodigoEquivalenteUmmDescricao;
	}

	public void setMedMatCodigoEquivalenteUmmDescricao(
			String medMatCodigoEquivalenteUmmDescricao) {
		this.medMatCodigoEquivalenteUmmDescricao = medMatCodigoEquivalenteUmmDescricao;
	}

	@Transient
	public BigDecimal getMedMatCodigoEquivalenteConcentracao() {
		return medMatCodigoEquivalenteConcentracao;
	}

	public void setMedMatCodigoEquivalenteConcentracao(
			BigDecimal medMatCodigoEquivalenteConcentracao) {
		this.medMatCodigoEquivalenteConcentracao = medMatCodigoEquivalenteConcentracao;
	}

}
