package br.gov.mec.aghu.model;

// Generated 17/04/2012 13:55:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioFormaIdentificacaoCaixaPostal;
import br.gov.mec.aghu.dominio.DominioTipoMensagemExame;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AghCaixaPostais generated by hbm2java
 */
@Entity
@SequenceGenerator(name="aghCtxSq1", sequenceName="AGH.AGH_CXT_SQ1", allocationSize = 1)
@Table(name = "AGH_CAIXA_POSTAIS", schema = "AGH")
public class AghCaixaPostal extends BaseEntitySeq<Long> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1582371804045926426L;
	private Long seq;
	private Integer version;
	private Date dthrInicio;
	private Date dthrFim;
	private DominioTipoMensagemExame tipoMensagem;
	private Boolean acaoObrigatoria;
	private String mensagem;
	private Date criadoEm;
	private DominioFormaIdentificacaoCaixaPostal formaIdentificacao;
	private String nomeRotina;
	private String atributoVisual;
	private String mostraPortal;
	private String urlAcao;
	private String tituloAbaAcao;
	
	private Set<AghCaixaPostalAplicacao> aghCaixaPostalAplicacao = new HashSet<AghCaixaPostalAplicacao>(0);
	private Set<AghCaixaPostalServidor> caixaPostalServidores = new HashSet<AghCaixaPostalServidor>(0);

	public AghCaixaPostal() {
	}

	public AghCaixaPostal(Long seq, Date dthrInicio, DominioTipoMensagemExame tipoMensagem,
			Boolean acaoObrigatoria, String mensagem, Date criadoEm,
			DominioFormaIdentificacaoCaixaPostal formaIdentificacao) {
		this.seq = seq;
		this.dthrInicio = dthrInicio;
		this.tipoMensagem = tipoMensagem;
		this.acaoObrigatoria = acaoObrigatoria;
		this.mensagem = mensagem;
		this.criadoEm = criadoEm;
		this.formaIdentificacao = formaIdentificacao;
	}

	public AghCaixaPostal(Long seq, Date dthrInicio, Date dthrFim,
			DominioTipoMensagemExame tipoMensagem, Boolean acaoObrigatoria, String mensagem,
			Date criadoEm, DominioFormaIdentificacaoCaixaPostal formaIdentificacao, String nomeRotina,
			String atributoVisual, String mostraPortal,
			Set<AghCaixaPostalAplicacao> aghCaixaPostalAplicacao) {
		this.seq = seq;
		this.dthrInicio = dthrInicio;
		this.dthrFim = dthrFim;
		this.tipoMensagem = tipoMensagem;
		this.acaoObrigatoria = acaoObrigatoria;
		this.mensagem = mensagem;
		this.criadoEm = criadoEm;
		this.formaIdentificacao = formaIdentificacao;
		this.nomeRotina = nomeRotina;
		this.atributoVisual = atributoVisual;
		this.mostraPortal = mostraPortal;
		this.aghCaixaPostalAplicacao = aghCaixaPostalAplicacao;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aghCtxSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Long getSeq() {
		return this.seq;
	}

	public void setSeq(Long seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_INICIO", nullable = false, length = 29)
	public Date getDthrInicio() {
		return this.dthrInicio;
	}

	public void setDthrInicio(Date dthrInicio) {
		this.dthrInicio = dthrInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FIM", length = 29)
	public Date getDthrFim() {
		return this.dthrFim;
	}

	public void setDthrFim(Date dthrFim) {
		this.dthrFim = dthrFim;
	}

	@Column(name = "TIPO_MENSAGEM", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioTipoMensagemExame getTipoMensagem() {
		return this.tipoMensagem;
	}

	public void setTipoMensagem(DominioTipoMensagemExame tipoMensagem) {
		this.tipoMensagem = tipoMensagem;
	}

	@Column(name = "ACAO_OBRIGATORIA", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getAcaoObrigatoria() {
		return this.acaoObrigatoria;
	}

	public void setAcaoObrigatoria(Boolean acaoObrigatoria) {
		this.acaoObrigatoria = acaoObrigatoria;
	}

	@Column(name = "MENSAGEM", nullable = false, length = 4000)
	@Length(max = 4000)
	public String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "FORMA_IDENTIFICACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioFormaIdentificacaoCaixaPostal getFormaIdentificacao() {
		return this.formaIdentificacao;
	}

	public void setFormaIdentificacao(DominioFormaIdentificacaoCaixaPostal formaIdentificacao) {
		this.formaIdentificacao = formaIdentificacao;
	}

	@Column(name = "NOME_ROTINA", length = 500)
	@Length(max = 500)
	public String getNomeRotina() {
		return this.nomeRotina;
	}

	public void setNomeRotina(String nomeRotina) {
		this.nomeRotina = nomeRotina;
	}

	@Column(name = "ATRIBUTO_VISUAL", length = 50)
	@Length(max = 50)
	public String getAtributoVisual() {
		return this.atributoVisual;
	}

	public void setAtributoVisual(String atributoVisual) {
		this.atributoVisual = atributoVisual;
	}

	@Column(name = "MOSTRA_PORTAL", length = 1)
	@Length(max = 1)
	public String getMostraPortal() {
		return this.mostraPortal;
	}

	public void setMostraPortal(String mostraPortal) {
		this.mostraPortal = mostraPortal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aghCaixaPostal")
	public Set<AghCaixaPostalAplicacao> getAghCaixaPostalAplicacao() {
		return this.aghCaixaPostalAplicacao;
	}

	public void setAghCaixaPostalAplicacao(
			Set<AghCaixaPostalAplicacao> aghCaixaPostalAplicacao) {
		this.aghCaixaPostalAplicacao = aghCaixaPostalAplicacao;
	}
	
	@Column(name = "URL_ACAO", length = 2500)
	@Length(max = 2500)
	public String getUrlAcao() {
		return urlAcao;
	}

	public void setUrlAcao(String urlAcao) {
		this.urlAcao = urlAcao;
	}

	@Column(name = "TITULO_ABA_ACAO", length = 200)
	@Length(max = 200)
	public String getTituloAbaAcao() {
		return tituloAbaAcao;
	}

	public void setTituloAbaAcao(String tituloAbaAcao) {
		this.tituloAbaAcao = tituloAbaAcao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caixaPostal")
	public Set<AghCaixaPostalServidor> getCaixaPostalServidores() {
		return caixaPostalServidores;
	}

	public void setCaixaPostalServidores(
			Set<AghCaixaPostalServidor> caixaPostalServidores) {
		this.caixaPostalServidores = caixaPostalServidores;
	}


	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		DTHR_INICIO("dthrInicio"),
		DTHR_FIM("dthrFim"),
		TIPO_MENSAGEM("tipoMensagem"),
		ACAO_OBRIGATORIA("acaoObrigatoria"),
		MENSAGEM("mensagem"),
		CRIADO_EM("criadoEm"),
		FORMA_IDENTIFICACAO("formaIdentificacao"),
		NOME_ROTINA("nomeRotina"),
		ATRIBUTO_VISUAL("atributoVisual"),
		URL_ACAO ("urlAcao"),
		TITULO_ABA_ACAO ("tituloAbaAcao"),
		MOSTRA_PORTAL("mostraPortal"),
		CAIXA_POSTAL_SERVIDORES("caixaPostalServidores");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AghCaixaPostal)) {
			return false;
		}
		AghCaixaPostal other = (AghCaixaPostal) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
