package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AghCriptoStatusId generated by hbm2java
 */
@Embeddable
public class AghCriptoStatusId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4318803352138270744L;
	private Integer seq;
	private String procedure;
	private String tabela;
	private Date dtRegistro;
	private String mensagem;

	public AghCriptoStatusId() {
	}

	public AghCriptoStatusId(Integer seq, String procedure, String tabela, Date dtRegistro, String mensagem) {
		this.seq = seq;
		this.procedure = procedure;
		this.tabela = tabela;
		this.dtRegistro = dtRegistro;
		this.mensagem = mensagem;
	}

	@Column(name = "SEQ")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "PROCEDURE", length = 50)
	@Length(max = 50)
	public String getProcedure() {
		return this.procedure;
	}

	public void setProcedure(String procedure) {
		this.procedure = procedure;
	}

	@Column(name = "TABELA", length = 50)
	@Length(max = 50)
	public String getTabela() {
		return this.tabela;
	}

	public void setTabela(String tabela) {
		this.tabela = tabela;
	}

	@Column(name = "DT_REGISTRO", length = 29)
	public Date getDtRegistro() {
		return this.dtRegistro;
	}

	public void setDtRegistro(Date dtRegistro) {
		this.dtRegistro = dtRegistro;
	}

	@Column(name = "MENSAGEM", length = 500)
	@Length(max = 500)
	public String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeq());
		umHashCodeBuilder.append(this.getTabela());
		umHashCodeBuilder.append(this.getMensagem());
		umHashCodeBuilder.append(this.getProcedure());
		umHashCodeBuilder.append(this.getDtRegistro());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AghCriptoStatusId)) {
			return false;
		}
		AghCriptoStatusId other = (AghCriptoStatusId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeq(), other.getSeq());
		umEqualsBuilder.append(this.getTabela(), other.getTabela());
		umEqualsBuilder.append(this.getMensagem(), other.getMensagem());
		umEqualsBuilder.append(this.getProcedure(), other.getProcedure());
		umEqualsBuilder.append(this.getDtRegistro(), other.getDtRegistro());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
