package br.gov.mec.aghu.model;

// Generated 27/04/2010 20:20:23 by Hibernate Tools 3.2.5.Beta

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AghCaractEspecialidades generated by hbm2java
 */

@Entity
@Table(name = "AGH_CARACT_ESPECIALIDADES", schema = "AGH")
public class AghCaractEspecialidades extends BaseEntityId<AghCaractEspecialidadesId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5322366400951150184L;

	private AghCaractEspecialidadesId id;
	
	private AghEspecialidades especialidade;
	private Integer version;

	public AghCaractEspecialidades() {
	}

	public AghCaractEspecialidades(AghCaractEspecialidadesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "espSeq", column = @Column(name = "ESP_SEQ", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "caracteristica", column = @Column(name = "CARACTERISTICA", nullable = false, length = 30)) })
	public AghCaractEspecialidadesId getId() {
		return this.id;
	}

	public void setId(AghCaractEspecialidadesId id) {
		this.id = id;
		if(id != null && id.getEspSeq() == null && especialidade != null && especialidade.getSeq() != null){
			this.id.setEspSeq(especialidade.getSeq());
		}
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	
	/**
	 * @return the especialidade
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESP_SEQ", nullable = false, insertable = false, updatable = false)
	public AghEspecialidades getEspecialidade() {
		return especialidade;
	}

	/**
	 * @param especialidade the especialidade to set
	 */
	public void setEspecialidade(AghEspecialidades especialidade) {
		this.especialidade = especialidade;
	}

	public enum Fields {

		CODIGO("id.espSeq"), CARACTERISTICA("id.caracteristica"),ESPECIALIDADE("especialidade"), ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}

	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AghCaractEspecialidades other = (AghCaractEspecialidades) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
