package br.gov.mec.aghu.model;

// Generated 22/06/2011 08:48:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntity;

/**
 * AghMicrocomputador generated by hbm2java
 */

@Entity
@Table(name = "AGH_MICROCOMPUTADORES", schema = "AGH")
public class AghMicrocomputador implements BaseEntity {

	private static final long serialVersionUID = 905723921922343222L;

	private String nome;
	private String versaoAgh;
	private String observacao;
	private String impressoraMatricial;
	private String impressoraGrafica;
	private AghUnidadesFuncionais aghUnidadesFuncionais;
	private AacUnidFuncionalSalas aacUnidFuncionalSala;
	private Integer codCli;
	private Integer codUni;
	private Integer codEst;
	private Integer codLoc;
	private Short ramal;
	private Boolean prioridade;
	private String usuario;
	private String ip;
	private String ponto;
	private Integer codCr;
	private String grupo;
	private Integer codAss;
	private Boolean ativo;
	private Date criadoEm;
	private String impressoraPadrao;
	private RapServidores servidor;
	private Boolean multiploLogon;
	private Boolean driverPdf;
	private AelSalasExecutorasExames aelSalasExecutorasExames;
	private String impressoraEtiquetas;
	private Set<AghCaractMicrocomputador> cacteristicasMicrocomputador;

	public AghMicrocomputador() {
	}

	public AghMicrocomputador(String nome, String versaoAgh,
			Boolean driverPdf) {
		this.nome = nome;
		this.versaoAgh = versaoAgh;
		this.driverPdf = driverPdf;
	}

	@SuppressWarnings({"PMD.ExcessiveParameterList"})
	public AghMicrocomputador(String nome, String versaoAgh, String observacao,
			String impressoraMatricial, String impressoraGrafica,
			AghUnidadesFuncionais aghUnidadesFuncionais,
			AacUnidFuncionalSalas aacUnidFuncionalSala, Integer codCli,
			Integer codUni, Integer codEst, Integer codLoc, Short ramal,
			Boolean prioridade, String usuario, String ip, String ponto,
			Integer codCr, String grupo, Integer codAss, Boolean ativo,
			Date criadoEm, String impressoraPadrao, RapServidores servidor,
			Boolean multiploLogon, Boolean driverPdf, AelSalasExecutorasExames aelSalasExecutorasExames,
			String impressoraEtiquetas) {
		super();
		this.nome = nome;
		this.versaoAgh = versaoAgh;
		this.observacao = observacao;
		this.impressoraMatricial = impressoraMatricial;
		this.impressoraGrafica = impressoraGrafica;
		this.aghUnidadesFuncionais = aghUnidadesFuncionais;
		this.aacUnidFuncionalSala = aacUnidFuncionalSala;
		this.codCli = codCli;
		this.codUni = codUni;
		this.codEst = codEst;
		this.codLoc = codLoc;
		this.ramal = ramal;
		this.prioridade = prioridade;
		this.usuario = usuario;
		this.ip = ip;
		this.ponto = ponto;
		this.codCr = codCr;
		this.grupo = grupo;
		this.codAss = codAss;
		this.ativo = ativo;
		this.criadoEm = criadoEm;
		this.impressoraPadrao = impressoraPadrao;
		this.servidor = servidor;
		this.multiploLogon = multiploLogon;
		this.driverPdf = driverPdf;
		this.aelSalasExecutorasExames = aelSalasExecutorasExames;
		this.impressoraEtiquetas = impressoraEtiquetas;
	}

	@Id
	@Column(name = "NOME", unique = true, nullable = false, updatable = false, length = 50)
	@Length(max = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "VERSAO_AGH", nullable = false, length = 10)
	@Length(max = 10)
	public String getVersaoAgh() {
		return this.versaoAgh;
	}

	public void setVersaoAgh(String versaoAgh) {
		this.versaoAgh = versaoAgh;
	}

	@Column(name = "OBSERVACAO", length = 240)
	@Length(max = 240)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "IMPRESSORA_MATRICIAL", length = 60)
	@Length(max = 60)
	public String getImpressoraMatricial() {
		return this.impressoraMatricial;
	}

	public void setImpressoraMatricial(String impressoraMatricial) {
		this.impressoraMatricial = impressoraMatricial;
	}

	@Column(name = "IMPRESSORA_GRAFICA", length = 60)
	@Length(max = 60)
	public String getImpressoraGrafica() {
		return this.impressoraGrafica;
	}

	public void setImpressoraGrafica(String impressoraGrafica) {
		this.impressoraGrafica = impressoraGrafica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNF_SEQ")
	public AghUnidadesFuncionais getAghUnidadesFuncionais() {
		return this.aghUnidadesFuncionais;
	}

	public void setAghUnidadesFuncionais(AghUnidadesFuncionais aghUnidadesFuncionais) {
		this.aghUnidadesFuncionais = aghUnidadesFuncionais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "USL_UNF_SEQ", referencedColumnName = "UNF_SEQ"),
			@JoinColumn(name = "USL_SALA", referencedColumnName = "SALA") })
	public AacUnidFuncionalSalas getAacUnidFuncionalSala() {
		return this.aacUnidFuncionalSala;
	}

	public void setAacUnidFuncionalSala(
			AacUnidFuncionalSalas aacUnidFuncionalSala) {
		this.aacUnidFuncionalSala = aacUnidFuncionalSala;
	}

	@Column(name = "COD_CLI", precision = 8, scale = 0)
	public Integer getCodCli() {
		return this.codCli;
	}

	public void setCodCli(Integer codCli) {
		this.codCli = codCli;
	}

	@Column(name = "COD_UNI", precision = 8, scale = 0)
	public Integer getCodUni() {
		return this.codUni;
	}

	public void setCodUni(Integer codUni) {
		this.codUni = codUni;
	}

	@Column(name = "COD_EST", precision = 8, scale = 0)
	public Integer getCodEst() {
		return this.codEst;
	}

	public void setCodEst(Integer codEst) {
		this.codEst = codEst;
	}

	@Column(name = "COD_LOC", precision = 8, scale = 0)
	public Integer getCodLoc() {
		return this.codLoc;
	}

	public void setCodLoc(Integer codLoc) {
		this.codLoc = codLoc;
	}

	@Column(name = "RAMAL", precision = 4, scale = 0)
	public Short getRamal() {
		return this.ramal;
	}

	public void setRamal(Short ramal) {
		this.ramal = ramal;
	}
	
	@Column(name = "PRIORIDADE", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(Boolean prioridade) {
		this.prioridade = prioridade;
	}

	@Column(name = "USUARIO", length = 40)
	@Length(max = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "IP", length = 16)
	@Length(max = 16)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "PONTO", length = 15)
	@Length(max = 15)
	public String getPonto() {
		return this.ponto;
	}

	public void setPonto(String ponto) {
		this.ponto = ponto;
	}

	@Column(name = "COD_CR", precision = 8, scale = 0)
	public Integer getCodCr() {
		return this.codCr;
	}

	public void setCodCr(Integer codCr) {
		this.codCr = codCr;
	}

	@Column(name = "GRUPO", length = 20)
	@Length(max = 20)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "COD_ASS", precision = 8, scale = 0)
	public Integer getCodAss() {
		return this.codAss;
	}

	public void setCodAss(Integer codAss) {
		this.codAss = codAss;
	}

	@Column(name = "ATIVO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "IMPRESSORA_PADRAO", length = 60)
	@Length(max = 60)
	public String getImpressoraPadrao() {
		return this.impressoraPadrao;
	}

	public void setImpressoraPadrao(String impressoraPadrao) {
		this.impressoraPadrao = impressoraPadrao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Column(name = "IND_MULTIPLO_LOGON", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")	
	public Boolean getMultiploLogon() {
		return multiploLogon;
	}
	public void setMultiploLogon(Boolean multiploLogon) {
		this.multiploLogon = multiploLogon;
	}

	@Column(name = "IND_DRIVER_PDF", nullable=false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")	
	public Boolean getDriverPdf() {
		return driverPdf;
	}
	public void setDriverPdf(Boolean driverPdf) {
		this.driverPdf = driverPdf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SEE_UNF_SEQ", referencedColumnName = "UNF_SEQ"),
			@JoinColumn(name = "SEE_SEQP", referencedColumnName = "SEQP") })
	public AelSalasExecutorasExames getAelSalasExecutorasExames() {
		return this.aelSalasExecutorasExames;
	}

	public void setAelSalasExecutorasExames(
			AelSalasExecutorasExames aelSalasExecutorasExames) {
		this.aelSalasExecutorasExames = aelSalasExecutorasExames;
	}

	@Column(name = "IMPRESSORA_ETIQUETAS", length = 60)
	@Length(max = 60)
	public String getImpressoraEtiquetas() {
		return this.impressoraEtiquetas;
	}

	public void setImpressoraEtiquetas(String impressoraEtiquetas) {
		this.impressoraEtiquetas = impressoraEtiquetas;
	}
	
	@OneToMany(mappedBy = "microcomputador")
	public Set<AghCaractMicrocomputador> getCacteristicasMicrocomputador() {
		return this.cacteristicasMicrocomputador;
	}

	public void setCacteristicasMicrocomputador(
			Set<AghCaractMicrocomputador> cacteristicasMicrocomputador) {
		this.cacteristicasMicrocomputador = cacteristicasMicrocomputador;
	}

	public enum Fields {
		USL_UNF_SEQ("aacUnidFuncionalSala.id.unfSeq"),
		USL_SALA("aacUnidFuncionalSala.id.sala"),
		UNIDFUNCIONALSALA("aacUnidFuncionalSala"),
		NOME("nome"),
		CARACTERISTICAS("cacteristicasMicrocomputador"),
		ATIVO("ativo"),
		RAMAL("ramal"),
		PRIORIDADE("prioridade"),
		PONTO("ponto"),
		USUARIO("usuario"),
		IP("ip"),
		IMPRESSORA_MATRICIAL("impressoraMatricial"),
		IMPRESSORA_PADRAO("impressoraPadrao"),
		IMPRESSORA_ETIQUETAS("impressoraEtiquetas"),
		OBSERVACAO("observacao"),
		UNIDADE_FUNCIONAL("aghUnidadesFuncionais"),
		SALA_EXECUTORA_EXAMES("aelSalasExecutorasExames");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getNome() == null) ? 0 : getNome().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AghMicrocomputador)) {
			return false;
		}
		AghMicrocomputador other = (AghMicrocomputador) obj;
		if (getNome() == null) {
			if (other.getNome() != null) {
				return false;
			}
		} else if (!getNome().equals(other.getNome())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
