package br.gov.mec.aghu.model;

// Generated 11/01/2010 12:19:57 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AghOrigemEventos generated by hbm2java
 */
@Entity
@Table(name = "AGH_ORIGEM_EVENTOS", schema = "AGH")
@SequenceGenerator(name="aghOriEveSq1", sequenceName="AGH_OEV_SQ1", allocationSize = 1)
public class AghOrigemEventos extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2157384671551350649L;
	private Short seq;
	private String descricao;
	private Set<AipSolicitantesProntuario> solicitantesProntuarios = new HashSet<AipSolicitantesProntuario>(
			0);
	
	private Integer version;

	public AghOrigemEventos() {
	}

	public AghOrigemEventos(Short seq, String descricao) {
		this.seq = seq;
		this.descricao = descricao;
	}

	public AghOrigemEventos(Short seq, String descricao,
			Set<AipSolicitantesProntuario> aipSolicitantesProntuarios) {
		this.seq = seq;
		this.descricao = descricao;
		this.solicitantesProntuarios = aipSolicitantesProntuarios;
	}

	@Id
	@Column(name = "SEQ", nullable = false, precision = 2, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aghOriEveSq1")
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "origemEventos")
	public Set<AipSolicitantesProntuario> getSolicitantesProntuarios() {
		return this.solicitantesProntuarios;
	}

	public void setSolicitantesProntuarios(
			Set<AipSolicitantesProntuario> aipSolicitantesProntuarios) {
		this.solicitantesProntuarios = aipSolicitantesProntuarios;
	}
	
	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public enum Fields {
		SEQ("seq"), DESCRICAO("descricao");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seq == null) ? 0 : seq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AghOrigemEventos)) {
			return false;
		}
		AghOrigemEventos other = (AghOrigemEventos) obj;
		if (seq == null) {
			if (other.seq != null) {
				return false;
			}
		} else if (!seq.equals(other.seq)) {
			return false;
		}
		return true;
	}

}