package br.gov.mec.aghu.model;

// Generated 14/04/2010 17:43:36 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AghProfissionaisEspConvenioId generated by hbm2java
 */
@Embeddable

public class AghProfissionaisEspConvenioId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7681164806317647956L;
	private Short cnvCodigo;
	private Integer preSerMatricula;
	private Short preSerVinCodigo;
	private Short preEspSeq;

	public AghProfissionaisEspConvenioId() {
	}

	public AghProfissionaisEspConvenioId(Short cnvCodigo,
			Integer preSerMatricula, Short preSerVinCodigo, Short preEspSeq) {

		this.cnvCodigo = cnvCodigo;
		this.preSerMatricula = preSerMatricula;
		this.preSerVinCodigo = preSerVinCodigo;
		this.preEspSeq = preEspSeq;
	}

	@Column(name = "CNV_CODIGO")
	public Short getCnvCodigo() {
		return this.cnvCodigo;
	}

	public void setCnvCodigo(Short cnvCodigo) {
		this.cnvCodigo = cnvCodigo;
	}

	@Column(name = "PRE_SER_MATRICULA")
	public Integer getPreSerMatricula() {
		return preSerMatricula;
	}

	public void setPreSerMatricula(Integer preSerMatricula) {
		this.preSerMatricula = preSerMatricula;
	}

	@Column(name = "PRE_SER_VIN_CODIGO")
	public Short getPreSerVinCodigo() {
		return preSerVinCodigo;
	}

	public void setPreSerVinCodigo(Short preSerVinCodigo) {
		this.preSerVinCodigo = preSerVinCodigo;
	}

	@Column(name = "PRE_ESP_SEQ")
	public Short getPreEspSeq() {
		return preEspSeq;
	}

	public void setPreEspSeq(Short preEspSeq) {
		this.preEspSeq = preEspSeq;
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getPreEspSeq());
		umHashCodeBuilder.append(this.getPreSerMatricula());
		umHashCodeBuilder.append(this.getPreSerVinCodigo());
		umHashCodeBuilder.append(this.getCnvCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AghProfissionaisEspConvenioId)) {
			return false;
		}
		AghProfissionaisEspConvenioId other = (AghProfissionaisEspConvenioId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getPreEspSeq(), other.getPreEspSeq());
		umEqualsBuilder.append(this.getPreSerMatricula(), other.getPreSerMatricula());
		umEqualsBuilder.append(this.getPreSerVinCodigo(), other.getPreSerVinCodigo());
		umEqualsBuilder.append(this.getCnvCodigo(), other.getCnvCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
