package br.gov.mec.aghu.model;

// Generated 30/04/2010 18:41:41 by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AinAcompanhantesInternacao generated by hbm2java
 */
@Entity
@Table(name = "AIN_ACOMPANHANTES_INTERNACAO", schema = "AGH")

public class AinAcompanhantesInternacao extends BaseEntityId<AinAcompanhantesInternacaoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4910319103265058554L;
	private AinAcompanhantesInternacaoId id;
	private RapServidores servidor;
	private Date criadoEm;
	private Date dataHoraInicio;
	private Date dataHoraFim;
	private String nome;
	private String rg;

	private AinInternacao internacao;

	private Set<AinCrachaAcompanhantes> crachaAcompanhantes = new HashSet<AinCrachaAcompanhantes>(
			0);

	public AinAcompanhantesInternacao() {
	}

	public AinAcompanhantesInternacao(AinAcompanhantesInternacaoId id,
			RapServidores servidor, Date criadoEm, Date dataHoraInicio) {
		this.id = id;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
		this.dataHoraInicio = dataHoraInicio;
	}

	public AinAcompanhantesInternacao(AinAcompanhantesInternacaoId id,
			RapServidores servidor, Date criadoEm, Date dataHoraInicio,
			Date dataHoraFim, String nome, String rg) {
		this.id = id;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
		this.dataHoraInicio = dataHoraInicio;
		this.dataHoraFim = dataHoraFim;
		this.nome = nome;
		this.rg =  rg;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "intSeq", column = @Column(name = "INT_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false, precision = 2, scale = 0)) })
	public AinAcompanhantesInternacaoId getId() {
		return this.id;
	}

	public void setId(AinAcompanhantesInternacaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_INICIO", nullable = false, length = 7)
	public Date getDataHoraInicio() {
		return this.dataHoraInicio;
	}

	public void setDataHoraInicio(Date dataHoraInicio) {
		this.dataHoraInicio = dataHoraInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTHR_FIM", length = 7)
	public Date getDataHoraFim() {
		return this.dataHoraFim;
	}

	public void setDataHoraFim(Date dataHoraFim) {
		this.dataHoraFim = dataHoraFim;
	}

	@Column(name = "NOME", length = 50)
	@Length(max = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome == null ? null : nome.toUpperCase();
	}

	@Column(name = "RG", length = 20)
	@Length(max = 20)
	public String getRg() {
		return rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INT_SEQ", insertable = false, updatable = false)
	public AinInternacao getInternacao() {
		return this.internacao;
	}

	public AinInternacao setInternacao(AinInternacao internacao) {
		return this.internacao = internacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acompanhanteInternacao")
	public Set<AinCrachaAcompanhantes> getCrachaAcompanhantes() {
		return crachaAcompanhantes;
	}

	public void setCrachaAcompanhantes(
			Set<AinCrachaAcompanhantes> crachaAcompanhantes) {
		this.crachaAcompanhantes = crachaAcompanhantes;
	}

	public enum Fields {
		INT_SEQ("id.intSeq"), DT_HR_FIM("dataHoraFim"), SEQ("id.seq");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AinAcompanhantesInternacao)) {
			return false;
		}
		AinAcompanhantesInternacao other = (AinAcompanhantesInternacao) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
