package br.gov.mec.aghu.model;

// Generated 13/08/2013 15:34:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AipAvisoAgendamentoCirurgia generated by hbm2java
 */
@Entity
@SequenceGenerator(name="aipAacSq1", sequenceName="AGH.AIP_AAC_SQ1", allocationSize = 1)
@Table(name = "AIP_AVISO_AGENDAMENTO_CIRURGIA", schema = "AGH")
public class AipAvisoAgendamentoCirurgia extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4177066696119407768L;
	private Integer seq;
	private Integer version;
	private MbcCirurgias mbcCirurgias;
	private RapServidores rapServidores;
	private RapServidores rapServidoresRecebido;
	private Date criadoEm;
	private Date dthrRecebido;
	private String status;

	public AipAvisoAgendamentoCirurgia() {
	}

	public AipAvisoAgendamentoCirurgia(Integer seq, MbcCirurgias mbcCirurgias, RapServidores rapServidores,
			RapServidores rapServidoresRecebido, Date criadoEm, Date dthrRecebido,
			String status) {
		this.seq = seq;
		this.mbcCirurgias = mbcCirurgias;
		this.rapServidores = rapServidores;
		this.rapServidoresRecebido = rapServidoresRecebido;
		this.criadoEm = criadoEm;
		this.dthrRecebido = dthrRecebido;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aipAacSq1")
	@Column(name = "SEQ", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRG_SEQ", nullable = false)
	public MbcCirurgias getMbcCirurgias() {
		return this.mbcCirurgias;
	}

	public void setMbcCirurgias(MbcCirurgias mbcCirurgias) {
		this.mbcCirurgias = mbcCirurgias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA_RECEBIDO", referencedColumnName = "MATRICULA", nullable = true),
			@JoinColumn(name = "SER_VIN_CODIGO_RECEBIDO", referencedColumnName = "VIN_CODIGO", nullable = true) })
	public RapServidores getRapServidoresRecebido() {
		return this.rapServidoresRecebido;
	}

	public void setRapServidoresRecebido(RapServidores rapServidoresRecebido) {
		this.rapServidoresRecebido = rapServidoresRecebido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_RECEBIDO", nullable = true, length = 29)
	public Date getDthrRecebido() {
		return this.dthrRecebido;
	}

	public void setDthrRecebido(Date dthrRecebido) {
		this.dthrRecebido = dthrRecebido;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	@Length(max = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	public enum Fields {

		SEQ("seq"),
		MBC_CIRURGIAS("mbcCirurgias"),
		MBC_CIRURGIAS_SEQ("mbcCirurgias.seq"),
		RAP_SERVIDORES("rapServidores"),
		CRIADO_EM("criadoEm"),
		DTHR_RECEBIDO("dthrRecebido"),
		STATUS("status");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
