package br.gov.mec.aghu.model;

// Generated 11/01/2010 12:19:57 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSimNao;
import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.dominio.DominioTodosUltimo;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * AipSolicitantesProntuario generated by hbm2java
 */
@SuppressWarnings({"PMD.AghuUsoIndevidoDaEnumDominioSimNaoEntity"})
@Entity
@SequenceGenerator(name = "aipSopSeq", sequenceName = "AGH.AIP_SOP_SQ1", allocationSize = 1)
@Table(name = "AIP_SOLICITANTES_PRONTUARIO", schema = "AGH")

public class AipSolicitantesProntuario extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3584178365081497178L;
	private Short seq;
	private AghUnidadesFuncionais unidadesFuncionais;
	private AipFinalidadesMovimentacao finalidadesMovimentacao;
	private AghOrigemEventos origemEventos;
	private String descricao;
	private Boolean exigeResponsavel;
	private DominioSimNao separacaoPrevia;
	private DominioSimNao retorno;
	private DominioTodosUltimo volumesManuseados;
	private DominioSituacao indSituacao;
	private DominioSimNao mensagemSamis;
	private Integer version;

	public AipSolicitantesProntuario() {
	}

	public AipSolicitantesProntuario(Short seq, Boolean exigeResponsavel,
			DominioSimNao separacaoPrevia, DominioSimNao retorno,
			DominioTodosUltimo volumesManuseados, DominioSituacao indSituacao,
			DominioSimNao mensagemSamis) {
		this.seq = seq;
		this.exigeResponsavel = exigeResponsavel;
		this.separacaoPrevia = separacaoPrevia;
		this.retorno = retorno;
		this.volumesManuseados = volumesManuseados;
		this.indSituacao = indSituacao;
		this.mensagemSamis = mensagemSamis;
	}

	public AipSolicitantesProntuario(Short seq,
			AghUnidadesFuncionais unidadesFuncionais,
			AipFinalidadesMovimentacao finalidadesMovimentacao,
			AghOrigemEventos origemEventos, String descricao,
			Boolean exigeResponsavel, DominioSimNao separacaoPrevia,
			DominioSimNao retorno, DominioTodosUltimo volumesManuseados,
			DominioSituacao indSituacao, DominioSimNao mensagemSamis) {
		this.seq = seq;
		this.unidadesFuncionais = unidadesFuncionais;
		this.finalidadesMovimentacao = finalidadesMovimentacao;
		this.origemEventos = origemEventos;
		this.descricao = descricao;
		this.exigeResponsavel = exigeResponsavel;
		this.separacaoPrevia = separacaoPrevia;
		this.retorno = retorno;
		this.volumesManuseados = volumesManuseados;
		this.indSituacao = indSituacao;
		this.mensagemSamis = mensagemSamis;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aipSopSeq")
	@Column(name = "SEQ", nullable = false, precision = 4, scale = 0)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNF_SEQ")
	public AghUnidadesFuncionais getUnidadesFuncionais() {
		return this.unidadesFuncionais;
	}

	public void setUnidadesFuncionais(AghUnidadesFuncionais unidadesFuncionais) {
		this.unidadesFuncionais = unidadesFuncionais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FMV_SEQ")
	public AipFinalidadesMovimentacao getFinalidadesMovimentacao() {
		return this.finalidadesMovimentacao;
	}

	public void setFinalidadesMovimentacao(
			AipFinalidadesMovimentacao finalidadesMovimentacao) {
		this.finalidadesMovimentacao = finalidadesMovimentacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OEV_SEQ")
	public AghOrigemEventos getOrigemEventos() {
		return this.origemEventos;
	}

	public void setOrigemEventos(AghOrigemEventos origemEventos) {
		this.origemEventos = origemEventos;
	}

	@Column(name = "DESCRICAO", length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

    @Column(name = "EXIGE_RESPONSAVEL", nullable = false)
    @org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getExigeResponsavel() {
		return this.exigeResponsavel;
	}

	public void setExigeResponsavel(Boolean exigeResponsavel) {
		this.exigeResponsavel = exigeResponsavel;
	}

	@Column(name = "SEPARACAO_PREVIA", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getSeparacaoPrevia() {
		return this.separacaoPrevia;
	}

	public void setSeparacaoPrevia(DominioSimNao separacaoPrevia) {
		this.separacaoPrevia = separacaoPrevia;
	}

	@Column(name = "RETORNO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getRetorno() {
		return this.retorno;
	}

	public void setRetorno(DominioSimNao retorno) {
		this.retorno = retorno;
	}

	@Column(name = "VOLUMES_MANUSEADOS", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioTodosUltimo getVolumesManuseados() {
		return this.volumesManuseados;
	}

	public void setVolumesManuseados(DominioTodosUltimo volumesManuseados) {
		this.volumesManuseados = volumesManuseados;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "MENSAGEM_SAMIS", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getMensagemSamis() {
		return this.mensagemSamis;
	}

	public void setMensagemSamis(DominioSimNao mensagemSamis) {
		this.mensagemSamis = mensagemSamis;
	}
	
	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * Campo sintético criado para mapear diretamente este dominio booleano em
	 * um componente selectOne
	 * 
	 * @return
	 */
	@Transient
	public boolean isSeparacaoPreviaCheckBox() {
		if (this.separacaoPrevia != null && this.separacaoPrevia.isSim()) {
			return Boolean.TRUE;
		} else {
			return Boolean.FALSE;
		}
	}

	@Transient
	public void setSeparacaoPreviaCheckBox(boolean separacaoPrevia) {
		if (separacaoPrevia) {
			this.separacaoPrevia = DominioSimNao.S;
		} else {
			this.separacaoPrevia = DominioSimNao.N;
		}
	}

	/**
	 * Campo sintético criado para mapear diretamente este dominio booleano em
	 * um componente selectOne
	 * 
	 * @return
	 */
	@Transient
	public boolean isRetornoCheckBox() {
		if (this.retorno != null && this.retorno.isSim()) {
			return Boolean.TRUE;
		} else {
			return Boolean.FALSE;
		}
	}

	@Transient
	public void setRetornoCheckBox(boolean retorno) {
		if (retorno) {
			this.retorno = DominioSimNao.S;
		} else {
			this.retorno = DominioSimNao.N;
		}
	}

	/**
	 * Campo sintético criado para mapear diretamente este dominio booleano em
	 * um componente selectOne
	 * 
	 * @return
	 */
	@Transient
	public boolean isMensagemSamisCheckBox() {
		if (this.mensagemSamis != null && this.mensagemSamis.isSim()) {
			return Boolean.TRUE;
		} else {
			return Boolean.FALSE;
		}
	}

	@Transient
	public void setMensagemSamisCheckBox(boolean mensagemSamis) {
		if (mensagemSamis) {
			this.mensagemSamis = DominioSimNao.S;
		} else {
			this.mensagemSamis = DominioSimNao.N;
		}
	}

	/**
	 * Campo sintético criado para mapear diretamente este dominio booleano em
	 * um componente selectOneCheckBox
	 * 
	 * @return
	 */
	@Transient
	public boolean isIndSituacaoCheckBox() {
		if (this.indSituacao != null && this.indSituacao.isAtivo()) {
			return Boolean.TRUE;
		} else {
			return Boolean.FALSE;
		}
	}

	@Transient
	public void setIndSituacaoCheckBox(boolean indSituacao) {
		if (indSituacao) {
			this.indSituacao = DominioSituacao.A;
		} else {
			this.indSituacao = DominioSituacao.I;
		}
	}

	public enum Fields {

		SEQ("seq"),

		UNIDADES_FUNCIONAIS("unidadesFuncionais"),

		UNIDADES_FUNCIONAIS_SEQ("unidadesFuncionais.seq"),
		
		UNIDADES_FUNCIONAIS_ANDAR("unidadesFuncionais.andar"),
		
		UNIDADES_FUNCIONAIS_DESCRICAO("unidadesFuncionais.descricao"),
		
		UNIDADES_FUNCIONAIS_IND_ALA("unidadesFuncionais.indAla"),
		
		FINALIDADES_MOVIMENTACAO("finalidadesMovimentacao"),

		FINALIDADES_MOVIMENTACAO_CODIGO("finalidadesMovimentacao.codigo"),

		ORIGEM_EVENTOS("origemEventos"),

		ORIGEM_EVENTOS_SEQ("origemEventos.seq"),
		
		ORIGEM_EVENTOS_DESCRICAO("origemEventos.descricao"),

		EXIGE_RESPONSAVEL("exigeResponsavel"),

		SEPARACAO_PREVIA("separacaoPrevia"),

		RETORNO("retorno"),

		VOLUMES_MANUSEADOS("volumesManuseados"),

		MENSAGEM_SAMIS("mensagemSamis"),

		IND_SITUACAO("indSituacao"),

		DESCRICAO("descricao");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AipSolicitantesProntuario)) {
			return false;
		}
		AipSolicitantesProntuario other = (AipSolicitantesProntuario) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
