package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AnuHorarioMamadeiraId generated by hbm2java
 */
@Embeddable
public class AnuHorarioMamadeiraId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5238256199390025202L;
	private Integer dmaAtdSeq;
	private Integer dmaSeq;
	private Integer seq;

	public AnuHorarioMamadeiraId() {
	}

	public AnuHorarioMamadeiraId(Integer dmaAtdSeq, Integer dmaSeq, Integer seq) {
		this.dmaAtdSeq = dmaAtdSeq;
		this.dmaSeq = dmaSeq;
		this.seq = seq;
	}

	@Column(name = "DMA_ATD_SEQ", nullable = false)
	public Integer getDmaAtdSeq() {
		return this.dmaAtdSeq;
	}

	public void setDmaAtdSeq(Integer dmaAtdSeq) {
		this.dmaAtdSeq = dmaAtdSeq;
	}

	@Column(name = "DMA_SEQ", nullable = false)
	public Integer getDmaSeq() {
		return this.dmaSeq;
	}

	public void setDmaSeq(Integer dmaSeq) {
		this.dmaSeq = dmaSeq;
	}

	@Column(name = "SEQ", nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeq());
		umHashCodeBuilder.append(this.getDmaAtdSeq());
		umHashCodeBuilder.append(this.getDmaSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AnuHorarioMamadeiraId)) {
			return false;
		}
		AnuHorarioMamadeiraId other = (AnuHorarioMamadeiraId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeq(), other.getSeq());
		umEqualsBuilder.append(this.getDmaAtdSeq(), other.getDmaAtdSeq());
		umEqualsBuilder.append(this.getDmaSeq(), other.getDmaSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
