package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * AnuLeiteMamadeiraId generated by hbm2java
 */
@Embeddable
public class AnuLeiteMamadeiraId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 374415978344223420L;
	private Integer dmaAtdSeq;
	private Integer dmaSeq;
	private Short tleSeq;
	private Integer seq;

	public AnuLeiteMamadeiraId() {
	}

	public AnuLeiteMamadeiraId(Integer dmaAtdSeq, Integer dmaSeq, Short tleSeq, Integer seq) {
		this.dmaAtdSeq = dmaAtdSeq;
		this.dmaSeq = dmaSeq;
		this.tleSeq = tleSeq;
		this.seq = seq;
	}

	@Column(name = "DMA_ATD_SEQ", nullable = false)
	public Integer getDmaAtdSeq() {
		return this.dmaAtdSeq;
	}

	public void setDmaAtdSeq(Integer dmaAtdSeq) {
		this.dmaAtdSeq = dmaAtdSeq;
	}

	@Column(name = "DMA_SEQ", nullable = false)
	public Integer getDmaSeq() {
		return this.dmaSeq;
	}

	public void setDmaSeq(Integer dmaSeq) {
		this.dmaSeq = dmaSeq;
	}

	@Column(name = "TLE_SEQ", nullable = false)
	public Short getTleSeq() {
		return this.tleSeq;
	}

	public void setTleSeq(Short tleSeq) {
		this.tleSeq = tleSeq;
	}

	@Column(name = "SEQ", nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeq());
		umHashCodeBuilder.append(this.getDmaAtdSeq());
		umHashCodeBuilder.append(this.getDmaSeq());
		umHashCodeBuilder.append(this.getTleSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AnuLeiteMamadeiraId)) {
			return false;
		}
		AnuLeiteMamadeiraId other = (AnuLeiteMamadeiraId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeq(), other.getSeq());
		umEqualsBuilder.append(this.getDmaAtdSeq(), other.getDmaAtdSeq());
		umEqualsBuilder.append(this.getDmaSeq(), other.getDmaSeq());
		umEqualsBuilder.append(this.getTleSeq(), other.getTleSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
