package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * AnuTmpQuadroDieta generated by hbm2java
 */
@Entity
@Table(name = "ANU_TMP_QUADRO_DIETAS", schema = "AGH")
public class AnuTmpQuadroDieta extends BaseEntityId<AnuTmpQuadroDietaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 383805842740458995L;
	private AnuTmpQuadroDietaId id;
	private Integer version;
	private AnuGrupoQuadroDieta anuGrupoQuadroDieta;
	private AghUnidadesFuncionais aghUnidadesFuncionais;
	private Integer total;

	public AnuTmpQuadroDieta() {
	}

	public AnuTmpQuadroDieta(AnuTmpQuadroDietaId id, AnuGrupoQuadroDieta anuGrupoQuadroDieta,
			AghUnidadesFuncionais aghUnidadesFuncionais, Integer total) {
		this.id = id;
		this.anuGrupoQuadroDieta = anuGrupoQuadroDieta;
		this.aghUnidadesFuncionais = aghUnidadesFuncionais;
		this.total = total;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "sessao", column = @Column(name = "SESSAO", nullable = false, length = 20)),
			@AttributeOverride(name = "gqdSeq", column = @Column(name = "GQD_SEQ", nullable = false)),
			@AttributeOverride(name = "unfSeq", column = @Column(name = "UNF_SEQ", nullable = false)) })
	public AnuTmpQuadroDietaId getId() {
		return this.id;
	}

	public void setId(AnuTmpQuadroDietaId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GQD_SEQ", nullable = false, insertable = false, updatable = false)
	public AnuGrupoQuadroDieta getAnuGrupoQuadroDieta() {
		return this.anuGrupoQuadroDieta;
	}

	public void setAnuGrupoQuadroDieta(AnuGrupoQuadroDieta anuGrupoQuadroDieta) {
		this.anuGrupoQuadroDieta = anuGrupoQuadroDieta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNF_SEQ", nullable = false, insertable = false, updatable = false)
	public AghUnidadesFuncionais getAghUnidadesFuncionais() {
		return this.aghUnidadesFuncionais;
	}

	public void setAghUnidadesFuncionais(AghUnidadesFuncionais aghUnidadesFuncionais) {
		this.aghUnidadesFuncionais = aghUnidadesFuncionais;
	}

	@Column(name = "TOTAL", nullable = false)
	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		ANU_GRUPO_QUADRO_DIETAS("anuGrupoQuadroDieta"),
		AGH_UNIDADES_FUNCIONAIS("aghUnidadesFuncionais"),
		TOTAL("total");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AnuTmpQuadroDieta)) {
			return false;
		}
		AnuTmpQuadroDieta other = (AnuTmpQuadroDieta) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
