package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * CceResultadoContagemId generated by hbm2java
 */
@Embeddable
public class CceResultadoContagemId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1627601617588957616L;
	private Integer id;
	private Short ord;
	private String resultados;
	private String term;
	private Integer version;

	public CceResultadoContagemId() {
	}

	public CceResultadoContagemId(Integer id, Short ord, String resultados, String term, Integer version) {
		this.id = id;
		this.ord = ord;
		this.resultados = resultados;
		this.term = term;
		this.version = version;
	}

	@Column(name = "ID", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ORD", nullable = false)
	public Short getOrd() {
		return this.ord;
	}

	public void setOrd(Short ord) {
		this.ord = ord;
	}

	@Column(name = "RESULTADOS", nullable = false, length = 2000)
	@Length(max = 2000)
	public String getResultados() {
		return this.resultados;
	}

	public void setResultados(String resultados) {
		this.resultados = resultados;
	}

	@Column(name = "TERM", nullable = false, length = 1)
	@Length(max = 1)
	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getId());
		umHashCodeBuilder.append(this.getVersion());
		umHashCodeBuilder.append(this.getOrd());
		umHashCodeBuilder.append(this.getTerm());
		umHashCodeBuilder.append(this.getResultados());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof CceResultadoContagemId)) {
			return false;
		}
		CceResultadoContagemId other = (CceResultadoContagemId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getId(), other.getId());
		umEqualsBuilder.append(this.getVersion(), other.getVersion());
		umEqualsBuilder.append(this.getOrd(), other.getOrd());
		umEqualsBuilder.append(this.getTerm(), other.getTerm());
		umEqualsBuilder.append(this.getResultados(), other.getResultados());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
