package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * CheckUsedOfRbs generated by hbm2java
 */
@Entity
@Table(name = "CHECK_USED_OF_RBS", schema = "AGH")
public class CheckUsedOfRbs extends BaseEntityId<CheckUsedOfRbsId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7268222665837597855L;
	private CheckUsedOfRbsId id;

	public CheckUsedOfRbs() {
	}

	public CheckUsedOfRbs(CheckUsedOfRbsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "myDate", column = @Column(name = "MY_DATE", length = 29)),
			@AttributeOverride(name = "name", column = @Column(name = "NAME", nullable = false, length = 30)),
			@AttributeOverride(name = "extents", column = @Column(name = "EXTENTS", precision = 17, scale = 17)),
			@AttributeOverride(name = "maxExtents", column = @Column(name = "MAX_EXTENTS", precision = 17, scale = 17)),
			@AttributeOverride(name = "rssize", column = @Column(name = "RSSIZE", precision = 17, scale = 17)),
			@AttributeOverride(name = "optsize", column = @Column(name = "OPTSIZE", precision = 17, scale = 17)),
			@AttributeOverride(name = "username", column = @Column(name = "USERNAME", nullable = false, length = 30)),
			@AttributeOverride(name = "sid", column = @Column(name = "SID", precision = 17, scale = 17)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 8)),
			@AttributeOverride(name = "machine", column = @Column(name = "MACHINE", length = 64)),
			@AttributeOverride(name = "sqlText", column = @Column(name = "SQL_TEXT", length = 1000)) })
	public CheckUsedOfRbsId getId() {
		return this.id;
	}

	public void setId(CheckUsedOfRbsId id) {
		this.id = id;
	}

	public enum Fields {

		ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof CheckUsedOfRbs)) {
			return false;
		}
		CheckUsedOfRbs other = (CheckUsedOfRbs) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
