package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * CsePerfilCcusto generated by hbm2java
 */
@Entity
@Table(name = "CSE_PERFIL_CCUSTOS", schema = "AGH")
public class CsePerfilCcusto extends BaseEntityId<CsePerfilCcustoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5569914797507857301L;
	private CsePerfilCcustoId id;
	private Integer version;
	private FccCentroCustos fccCentroCustos;
	private String indPropaga;

	public CsePerfilCcusto() {
	}

	public CsePerfilCcusto(CsePerfilCcustoId id, FccCentroCustos fccCentroCustos) {
		this.id = id;
		this.fccCentroCustos = fccCentroCustos;
	}

	public CsePerfilCcusto(CsePerfilCcustoId id, FccCentroCustos fccCentroCustos, String indPropaga) {
		this.id = id;
		this.fccCentroCustos = fccCentroCustos;
		this.indPropaga = indPropaga;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "perNome", column = @Column(name = "PER_NOME", nullable = false, length = 30)),
			@AttributeOverride(name = "cctCodigo", column = @Column(name = "CCT_CODIGO", nullable = false)) })
	public CsePerfilCcustoId getId() {
		return this.id;
	}

	public void setId(CsePerfilCcustoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CCT_CODIGO", nullable = false, insertable = false, updatable = false)
	public FccCentroCustos getFccCentroCustos() {
		return this.fccCentroCustos;
	}

	public void setFccCentroCustos(FccCentroCustos fccCentroCustos) {
		this.fccCentroCustos = fccCentroCustos;
	}

	@Column(name = "IND_PROPAGA", length = 1)
	@Length(max = 1)
	public String getIndPropaga() {
		return this.indPropaga;
	}

	public void setIndPropaga(String indPropaga) {
		this.indPropaga = indPropaga;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		FCC_CENTRO_CUSTOS("fccCentroCustos"),
		PER_NOME("id.perNome"),
		IND_PROPAGA("indPropaga");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof CsePerfilCcusto)) {
			return false;
		}
		CsePerfilCcusto other = (CsePerfilCcusto) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
