package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * DbaEnderecoPublicoId generated by hbm2java
 */
@Embeddable
public class DbaEnderecoPublicoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5669252436773296075L;
	private Short seq;
	private String nomeComercial;
	private String endereco;
	private Integer numero;
	private String cidade;
	private String bairro;
	private String ufSigla;
	private Integer cep;
	private Integer version;

	public DbaEnderecoPublicoId() {
	}

	public DbaEnderecoPublicoId(Short seq, Integer version) {
		this.seq = seq;
		this.version = version;
	}

	public DbaEnderecoPublicoId(Short seq, String nomeComercial, String endereco, Integer numero, String cidade, String bairro,
			String ufSigla, Integer cep, Integer version) {
		this.seq = seq;
		this.nomeComercial = nomeComercial;
		this.endereco = endereco;
		this.numero = numero;
		this.cidade = cidade;
		this.bairro = bairro;
		this.ufSigla = ufSigla;
		this.cep = cep;
		this.version = version;
	}

	@Column(name = "SEQ", nullable = false)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Column(name = "NOME_COMERCIAL", length = 100)
	@Length(max = 100)
	public String getNomeComercial() {
		return this.nomeComercial;
	}

	public void setNomeComercial(String nomeComercial) {
		this.nomeComercial = nomeComercial;
	}

	@Column(name = "ENDERECO", length = 60)
	@Length(max = 60)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "NUMERO")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "CIDADE", length = 60)
	@Length(max = 60)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "BAIRRO", length = 20)
	@Length(max = 20)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "UF_SIGLA", length = 2)
	@Length(max = 2)
	public String getUfSigla() {
		return this.ufSigla;
	}

	public void setUfSigla(String ufSigla) {
		this.ufSigla = ufSigla;
	}

	@Column(name = "CEP")
	public Integer getCep() {
		return this.cep;
	}

	public void setCep(Integer cep) {
		this.cep = cep;
	}

	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getVersion());
		umHashCodeBuilder.append(this.getSeq());
		umHashCodeBuilder.append(this.getNumero());
		umHashCodeBuilder.append(this.getCep());
		umHashCodeBuilder.append(this.getBairro());
		umHashCodeBuilder.append(this.getCidade());
		umHashCodeBuilder.append(this.getUfSigla());
		umHashCodeBuilder.append(this.getEndereco());
		umHashCodeBuilder.append(this.getNomeComercial());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof DbaEnderecoPublicoId)) {
			return false;
		}
		DbaEnderecoPublicoId other = (DbaEnderecoPublicoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getVersion(), other.getVersion());
		umEqualsBuilder.append(this.getSeq(), other.getSeq());
		umEqualsBuilder.append(this.getNumero(), other.getNumero());
		umEqualsBuilder.append(this.getCep(), other.getCep());
		umEqualsBuilder.append(this.getBairro(), other.getBairro());
		umEqualsBuilder.append(this.getCidade(), other.getCidade());
		umEqualsBuilder.append(this.getUfSigla(), other.getUfSigla());
		umEqualsBuilder.append(this.getEndereco(), other.getEndereco());
		umEqualsBuilder.append(this.getNomeComercial(), other.getNomeComercial());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
