package br.gov.mec.aghu.model;

// Generated 17/10/2011 14:21:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * EpeDataItemSumariosId generated by hbm2java
 */
@Embeddable
public class EpeDataItemSumarioId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 427071619065916196L;
	private Integer apaAtdSeq;
	private Integer apaSeq;
	private Integer isuSeq;
	private Integer seqp;

	public EpeDataItemSumarioId() {
	}

	public EpeDataItemSumarioId(Integer apaAtdSeq, Integer apaSeq, Integer isuSeq, Integer seqp) {
		this.apaAtdSeq = apaAtdSeq;
		this.apaSeq = apaSeq;
		this.isuSeq = isuSeq;
		this.seqp = seqp;
	}

	@Column(name = "APA_ATD_SEQ", nullable = false, precision = 9, scale = 0)
	public Integer getApaAtdSeq() {
		return this.apaAtdSeq;
	}

	public void setApaAtdSeq(Integer apaAtdSeq) {
		this.apaAtdSeq = apaAtdSeq;
	}

	@Column(name = "APA_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getApaSeq() {
		return this.apaSeq;
	}

	public void setApaSeq(Integer apaSeq) {
		this.apaSeq = apaSeq;
	}

	@Column(name = "ISU_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getIsuSeq() {
		return this.isuSeq;
	}

	public void setIsuSeq(Integer isuSeq) {
		this.isuSeq = isuSeq;
	}

	@Column(name = "SEQP", nullable = false, precision = 5, scale = 0)
	public Integer getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Integer seqp) {
		this.seqp = seqp;
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getApaSeq());
		umHashCodeBuilder.append(this.getIsuSeq());
		umHashCodeBuilder.append(this.getApaAtdSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof EpeDataItemSumarioId)) {
			return false;
		}
		EpeDataItemSumarioId other = (EpeDataItemSumarioId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getApaSeq(), other.getApaSeq());
		umEqualsBuilder.append(this.getIsuSeq(), other.getIsuSeq());
		umEqualsBuilder.append(this.getApaAtdSeq(), other.getApaAtdSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}