package br.gov.mec.aghu.model;

// Generated 17/10/2011 14:21:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * EpeFatRelDiagnosticosId generated by hbm2java
 */
@Embeddable
public class EpeFatRelDiagnosticoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6064443248021775183L;
	private Short dgnSnbGnbSeq;
	private Short dgnSnbSequencia;
	private Short dgnSequencia;
	private Short freSeq;

	public EpeFatRelDiagnosticoId() {
	}

	public EpeFatRelDiagnosticoId(Short dgnSnbGnbSeq, Short dgnSnbSequencia,
			Short dgnSequencia, Short freSeq) {
		this.dgnSnbGnbSeq = dgnSnbGnbSeq;
		this.dgnSnbSequencia = dgnSnbSequencia;
		this.dgnSequencia = dgnSequencia;
		this.freSeq = freSeq;
	}

	@Column(name = "DGN_SNB_GNB_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getDgnSnbGnbSeq() {
		return this.dgnSnbGnbSeq;
	}

	public void setDgnSnbGnbSeq(Short dgnSnbGnbSeq) {
		this.dgnSnbGnbSeq = dgnSnbGnbSeq;
	}


	@Column(name = "DGN_SNB_SEQUENCIA", nullable = false, precision = 3, scale = 0)
	public Short getDgnSnbSequencia() {
		return this.dgnSnbSequencia;
	}

	public void setDgnSnbSequencia(Short dgnSnbSequencia) {
		this.dgnSnbSequencia = dgnSnbSequencia;
	}

	@Column(name = "DGN_SEQUENCIA", nullable = false, precision = 4, scale = 0)
	public Short getDgnSequencia() {
		return this.dgnSequencia;
	}

	public void setDgnSequencia(Short dgnSequencia) {
		this.dgnSequencia = dgnSequencia;
	}

	@Column(name = "FRE_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getFreSeq() {
		return this.freSeq;
	}

	public void setFreSeq(Short freSeq) {
		this.freSeq = freSeq;
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getDgnSnbGnbSeq());
		umHashCodeBuilder.append(this.getDgnSnbSequencia());
		umHashCodeBuilder.append(this.getDgnSequencia());
		umHashCodeBuilder.append(this.getFreSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof EpeFatRelDiagnosticoId)) {
			return false;
		}
		EpeFatRelDiagnosticoId other = (EpeFatRelDiagnosticoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getDgnSnbGnbSeq(), other.getDgnSnbGnbSeq());
		umEqualsBuilder.append(this.getDgnSnbSequencia(), other.getDgnSnbSequencia());
		umEqualsBuilder.append(this.getDgnSequencia(), other.getDgnSequencia());
		umEqualsBuilder.append(this.getFreSeq(), other.getFreSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
