package br.gov.mec.aghu.model;

// Generated 08/02/2010 17:25:25 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * FatCandidatosApacOtorrino generated by hbm2java
 */

@Entity
@SequenceGenerator(name="fatCaotSq1", sequenceName="AGH.FAT_CAOT_SQ1", allocationSize = 1)
@Table(name = "FAT_CANDIDATOS_APAC_OTORRINO", schema = "AGH")
public class FatCandidatosApacOtorrino extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 450664209484374102L;
	private Integer seq;
	private FatProcedHospInternos procedimentoHospitalarInterno;
	private FatProcedAmbRealizado procedimentoAmbRealizado;
	private FatProcedHospInternos procedimentoHospitalarSugerido;
	private String origem;
	private Date dtEvento;
	private DominioSituacao indSituacao;
	private Integer conNumero;
	private Integer crgSeq;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Short eqpSeq;
	private Integer pacCodigo;
	private Date criadoEm;
	private Date alteradoEm;
	private Integer serMatriculaIncluido;
	private Short serVinCodigoIncluido;
	
	private RapServidores servidorAlterado;
	
	private String candidato;
	private Integer cidSeq;
	private String indEntrega;
	private String indReposicao;
	private AipPacientes paciente;

	public FatCandidatosApacOtorrino() {
	}

	public FatCandidatosApacOtorrino(Integer seq, String origem, Date dtEvento,
			DominioSituacao indSituacao, Integer pacCodigo, Date criadoEm,
			Integer serMatriculaIncluido, Short serVinCodigoIncluido,
			String candidato, String indEntrega) {
		this.seq = seq;
		this.origem = origem;
		this.dtEvento = dtEvento;
		this.indSituacao = indSituacao;
		this.pacCodigo = pacCodigo;
		this.criadoEm = criadoEm;
		this.serMatriculaIncluido = serMatriculaIncluido;
		this.serVinCodigoIncluido = serVinCodigoIncluido;
		this.candidato = candidato;
		this.indEntrega = indEntrega;
	}

	public FatCandidatosApacOtorrino(Integer seq,
			FatProcedHospInternos procedHospInterno,
			FatProcedAmbRealizado procedAmbRealizado,
			FatProcedHospInternos procedHospInternoSugerido,
			String origem, Date dtEvento, DominioSituacao indSituacao, 
			Integer conNumero, Integer crgSeq, Integer serMatricula,
			Short serVinCodigo, Short eqpSeq, Integer pacCodigo, Date criadoEm,
			Date alteradoEm, Integer serMatriculaIncluido,
			Short serVinCodigoIncluido, Integer serMatriculaAlterado,
			Short serVinCodigoAlterado, String candidato, Integer cidSeq,
			String indEntrega, String indReposicao) {
		this.seq = seq;
		this.procedimentoAmbRealizado = procedAmbRealizado;
		this.procedimentoHospitalarInterno = procedHospInterno;
		this.procedimentoHospitalarSugerido = procedHospInternoSugerido;
		this.origem = origem;
		this.dtEvento = dtEvento;
		this.indSituacao = indSituacao;
		this.conNumero = conNumero;
		this.crgSeq = crgSeq;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.eqpSeq = eqpSeq;
		this.pacCodigo = pacCodigo;
		this.criadoEm = criadoEm;
		this.alteradoEm = alteradoEm;
		this.serMatriculaIncluido = serMatriculaIncluido;
		this.serVinCodigoIncluido = serVinCodigoIncluido;
		this.candidato = candidato;
		this.cidSeq = cidSeq;
		this.indEntrega = indEntrega;
		this.indReposicao = indReposicao;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fatCaotSq1")
	@Column(name = "SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PMR_SEQ")
	public FatProcedAmbRealizado getProcedimentoAmbRealizado() {
		return procedimentoAmbRealizado;
	}

	public void setProcedimentoAmbRealizado(
			FatProcedAmbRealizado procedimentoAmbRealizado) {
		this.procedimentoAmbRealizado = procedimentoAmbRealizado;
	}

	@Column(name = "ORIGEM", nullable = false, length = 3)
	@Length(max = 3)
	public String getOrigem() {
		return this.origem;
	}

	public void setOrigem(String origem) {
		this.origem = origem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DT_EVENTO", nullable = false, length = 7)
	public Date getDtEvento() {
		return this.dtEvento;
	}

	public void setDtEvento(Date dtEvento) {
		this.dtEvento = dtEvento;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHI_SEQ")
	public FatProcedHospInternos getProcedimentoHospitalarInterno() {
		return procedimentoHospitalarInterno;
	}

	public void setProcedimentoHospitalarInterno(
			FatProcedHospInternos procedimentoHospitalarInterno) {
		this.procedimentoHospitalarInterno = procedimentoHospitalarInterno;
	}

	@Column(name = "CON_NUMERO", precision = 8, scale = 0)
	public Integer getConNumero() {
		return this.conNumero;
	}

	public void setConNumero(Integer conNumero) {
		this.conNumero = conNumero;
	}

	@Column(name = "CRG_SEQ", precision = 8, scale = 0)
	public Integer getCrgSeq() {
		return this.crgSeq;
	}

	public void setCrgSeq(Integer crgSeq) {
		this.crgSeq = crgSeq;
	}

	@Column(name = "SER_MATRICULA", precision = 7, scale = 0)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", precision = 3, scale = 0)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "EQP_SEQ", precision = 4, scale = 0)
	public Short getEqpSeq() {
		return this.eqpSeq;
	}

	public void setEqpSeq(Short eqpSeq) {
		this.eqpSeq = eqpSeq;
	}

	@Column(name = "PAC_CODIGO", nullable = false, precision = 8, scale = 0)
	public Integer getPacCodigo() {
		return this.pacCodigo;
	}

	public void setPacCodigo(Integer pacCodigo) {
		this.pacCodigo = pacCodigo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ALTERADO_EM", length = 7)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@Column(name = "SER_MATRICULA_INCLUIDO", nullable = false, precision = 7, scale = 0)
	public Integer getSerMatriculaIncluido() {
		return this.serMatriculaIncluido;
	}

	public void setSerMatriculaIncluido(Integer serMatriculaIncluido) {
		this.serMatriculaIncluido = serMatriculaIncluido;
	}

	@Column(name = "SER_VIN_CODIGO_INCLUIDO", nullable = false, precision = 3, scale = 0)
	public Short getSerVinCodigoIncluido() {
		return this.serVinCodigoIncluido;
	}

	public void setSerVinCodigoIncluido(Short serVinCodigoIncluido) {
		this.serVinCodigoIncluido = serVinCodigoIncluido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_ALTERADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_ALTERADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorAlterado() {
		return servidorAlterado;
	}

	public void setServidorAlterado(RapServidores servidorAlterado) {
		this.servidorAlterado = servidorAlterado;
	}

	@Column(name = "CANDIDATO", nullable = false, length = 45)
	@Length(max = 45)
	public String getCandidato() {
		return this.candidato;
	}

	public void setCandidato(String candidato) {
		this.candidato = candidato;
	}

	@Column(name = "CID_SEQ", precision = 5, scale = 0)
	public Integer getCidSeq() {
		return this.cidSeq;
	}

	public void setCidSeq(Integer cidSeq) {
		this.cidSeq = cidSeq;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAC_CODIGO", nullable = false, updatable = false, insertable = false)
	public AipPacientes getPaciente() {
		return this.paciente;
	}

	public void setPaciente(AipPacientes paciente) {
		this.paciente = paciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHI_SEQ_SUGERIDO")
	public FatProcedHospInternos getProcedimentoHospitalarSugerido() {
		return procedimentoHospitalarSugerido;
	}

	public void setProcedimentoHospitalarSugerido(
			FatProcedHospInternos procedimentoHospitalarSugerido) {
		this.procedimentoHospitalarSugerido = procedimentoHospitalarSugerido;
	}

	@Column(name = "IND_ENTREGA", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndEntrega() {
		return this.indEntrega;
	}

	public void setIndEntrega(String indEntrega) {
		this.indEntrega = indEntrega;
	}

	@Column(name = "IND_REPOSICAO", length = 1)
	@Length(max = 1)
	public String getIndReposicao() {
		return this.indReposicao;
	}

	public void setIndReposicao(String indReposicao) {
		this.indReposicao = indReposicao;
	}

	public enum Fields {
		PAC_CODIGO("pacCodigo"),
		PROCEDIMENTO_AMB_REALIZADO("procedimentoAmbRealizado"),
		PMR_SEQ("procedimentoAmbRealizado.seq"),
		SITUACAO("indSituacao"),
		CANDIDATO("candidato"),
		PRODCEDIMENTO_HOSPITALAR_SUGERIDO("procedimentoHospitalarSugerido"),
		PHI_SEQ_SUGERIDO("procedimentoHospitalarSugerido.seq"),
		CRIADO_EM("criadoEm"),
		PROCED_HOSP_INTERNO("procedimentoHospitalarInterno"),
		PHI_SEQ("procedimentoHospitalarInterno.seq"),
		SEQ("seq"), PACIENTE("paciente"),
		DT_EVENTO("dtEvento");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FatCandidatosApacOtorrino)) {
			return false;
		}
		FatCandidatosApacOtorrino other = (FatCandidatosApacOtorrino) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
