package br.gov.mec.aghu.model;

// Generated 29/04/2010 10:40:51 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.Cascade;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * FatContasInternacao generated by hbm2java
 */
@Entity
@Table(name = "FAT_CONTAS_INTERNACAO", schema = "AGH")
@SequenceGenerator(name = "fatContasInternacaoSeq", sequenceName = "AGH.FAT_COI_SQ1", allocationSize = 1)
public class FatContasInternacao extends BaseEntitySeq<Integer> implements java.io.Serializable {
	private static final long serialVersionUID = -7871813636678051740L;
	
	private Integer seq;
	private FatContasHospitalares contaHospitalar;
	private AinInternacao internacao;
	private FatDadosContaSemInt dadosContaSemInt;
	private Integer version;

	public FatContasInternacao() {
	}

	public FatContasInternacao(Integer seq,
			FatContasHospitalares contaHospitalar) {
		this.seq = seq;
		this.contaHospitalar = contaHospitalar;
	}

	public FatContasInternacao(Integer seq,
			FatContasHospitalares contaHospitalar,
			AinInternacao internacao, FatDadosContaSemInt dadosContaSemInt) {
		this.seq = seq;
		this.contaHospitalar = contaHospitalar;
		this.internacao = internacao;
		this.dadosContaSemInt = dadosContaSemInt;
	}

	@Id
	@Column(name = "SEQ", nullable = false, precision = 8, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fatContasInternacaoSeq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTH_SEQ", nullable = false)
	@Cascade( {org.hibernate.annotations.CascadeType.PERSIST})
	public FatContasHospitalares getContaHospitalar() {
		return this.contaHospitalar;
	}

	public void setContaHospitalar(
			FatContasHospitalares contaHospitalar) {
		this.contaHospitalar = contaHospitalar;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DCS_SEQ")
	public FatDadosContaSemInt getDadosContaSemInt() {
		return dadosContaSemInt;
	}

	public void setDadosContaSemInt(FatDadosContaSemInt dadosContaSemInt) {
		this.dadosContaSemInt = dadosContaSemInt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INT_SEQ")
	public AinInternacao getInternacao() {
		return internacao;
	}

	public void setInternacao(AinInternacao internacao) {
		this.internacao = internacao;
	}
	
	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seq == null) ? 0 : seq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FatContasInternacao other = (FatContasInternacao) obj;
		if (seq == null) {
			if (other.seq != null) {
				return false;
			}
		} else if (!seq.equals(other.seq)) {
			return false;
		}
		return true;
	}
	
	public enum Fields {
		INTERNACAO("internacao"), 
		INT_SEQ("internacao.seq"),
		SEQ("seq"), CONTA_HOSPITALAR_SITUACAO("contaHospitalar.indSituacao"), 
		CONTA_HOSPITALAR_DT_INT_ADM("contaHospitalar.dataInternacaoAdministrativa"), 
		FAT_CONTAS_HOSPITALARES("contaHospitalar"), 
		FAT_CONTAS_HOSPITALARES_SEQ("contaHospitalar.seq"), 
		DADOS_CONTA_SEM_INT("dadosContaSemInt"),
		DCS_SEQ("dadosContaSemInt" + "." + FatDadosContaSemInt.Fields.SEQ.toString()), 
		CTH_SEQ("contaHospitalar.seq");
		;		

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}
	
}
