package br.gov.mec.aghu.model;

// Generated 15/03/2011 13:46:58 by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioModoCobranca;
import br.gov.mec.aghu.dominio.DominioTipoItemConta;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * FatCamposMedicoAuditAih generated by hbm2java
 */
@Entity
@Table(name = "FAT_CAMPOS_MEDICO_AUDIT_AIH", schema = "AGH")
public class FatCampoMedicoAuditAih extends BaseEntityId<FatCampoMedicoAuditAihId> implements java.io.Serializable {
	private static final long serialVersionUID = 8488497224742657770L;
	
	private FatCampoMedicoAuditAihId id;
	private FatEspelhoAih fatEspelhoAih;
	private Date criadoEm;
	private String alteradoPor;
	private Date alteradoEm;
	private String criadoPor;
	private FatItensProcedHospitalar itemProcedimentoHospilatar;
	private Integer pontosAnestesista;
	private Integer pontosCirurgiao;
	private Integer pontosSadt;
	private Date dataPrevia;
	private BigDecimal valorAnestesista;
	private BigDecimal valorProcedimento;
	private BigDecimal valorSadt;
	private BigDecimal valorServHosp;
	private BigDecimal valorServProf;
	private DominioTipoItemConta indConsistente;
	private DominioModoCobranca indModoCobranca;
	private Long iphCodSus;
	private Integer version;

	public FatCampoMedicoAuditAih() {
	}

	public FatCampoMedicoAuditAih(FatCampoMedicoAuditAihId id,
			FatEspelhoAih fatEspelhoAih, FatItensProcedHospitalar itemProcedimentoHospilatar) {
		this.id = id;
		this.fatEspelhoAih = fatEspelhoAih;
		this.itemProcedimentoHospilatar = itemProcedimentoHospilatar;
	}

	public FatCampoMedicoAuditAih(FatCampoMedicoAuditAihId id,
			FatEspelhoAih fatEspelhoAih, Date criadoEm, String alteradoPor,
			Date alteradoEm, String criadoPor, FatItensProcedHospitalar itemProcedimentoHospilatar,
			Integer pontosAnestesista, Integer pontosCirurgiao,
			Integer pontosSadt, Date dataPrevia, BigDecimal valorAnestesista,
			BigDecimal valorProcedimento, BigDecimal valorSadt,
			BigDecimal valorServHosp, BigDecimal valorServProf,
			DominioTipoItemConta indConsistente, DominioModoCobranca indModoCobranca, Long iphCodSus) {
		this.id = id;
		this.fatEspelhoAih = fatEspelhoAih;
		this.criadoEm = criadoEm;
		this.alteradoPor = alteradoPor;
		this.alteradoEm = alteradoEm;
		this.criadoPor = criadoPor;
		this.itemProcedimentoHospilatar = itemProcedimentoHospilatar;
		this.pontosAnestesista = pontosAnestesista;
		this.pontosCirurgiao = pontosCirurgiao;
		this.pontosSadt = pontosSadt;
		this.dataPrevia = dataPrevia;
		this.valorAnestesista = valorAnestesista;
		this.valorProcedimento = valorProcedimento;
		this.valorSadt = valorSadt;
		this.valorServHosp = valorServHosp;
		this.valorServProf = valorServProf;
		this.indConsistente = indConsistente;
		this.indModoCobranca = indModoCobranca;
		this.iphCodSus = iphCodSus;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "eaiSeq", column = @Column(name = "EAI_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "eaiCthSeq", column = @Column(name = "EAI_CTH_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 2, scale = 0)) })
	public FatCampoMedicoAuditAihId getId() {
		return this.id;
	}

	public void setId(FatCampoMedicoAuditAihId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "EAI_CTH_SEQ", referencedColumnName = "CTH_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "EAI_SEQ", referencedColumnName = "SEQP", nullable = false, insertable = false, updatable = false) })	
	public FatEspelhoAih getFatEspelhoAih() {
		return this.fatEspelhoAih;
	}

	public void setFatEspelhoAih(FatEspelhoAih fatEspelhoAih) {
		this.fatEspelhoAih = fatEspelhoAih;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "ALTERADO_POR", length = 30)
	@Length(max = 30)
	public String getAlteradoPor() {
		return this.alteradoPor;
	}

	public void setAlteradoPor(String alteradoPor) {
		this.alteradoPor = alteradoPor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ALTERADO_EM", length = 7)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@Column(name = "CRIADO_POR", length = 30)
	@Length(max = 30)
	public String getCriadoPor() {
		return this.criadoPor;
	}

	public void setCriadoPor(String criadoPor) {
		this.criadoPor = criadoPor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
		@JoinColumn(name = "IPH_SEQ", referencedColumnName = "SEQ", nullable = false),
		@JoinColumn(name = "IPH_PHO_SEQ", referencedColumnName = "PHO_SEQ", nullable = false)})
	public FatItensProcedHospitalar getItemProcedimentoHospilatar() {
		return itemProcedimentoHospilatar;
	}

	public void setItemProcedimentoHospilatar(
			FatItensProcedHospitalar itemProcedimentoHospilatar) {
		this.itemProcedimentoHospilatar = itemProcedimentoHospilatar;
	}

	@Column(name = "PONTOS_ANESTESISTA", precision = 5, scale = 0)
	public Integer getPontosAnestesista() {
		return this.pontosAnestesista;
	}

	public void setPontosAnestesista(Integer pontosAnestesista) {
		this.pontosAnestesista = pontosAnestesista;
	}

	@Column(name = "PONTOS_CIRURGIAO", precision = 5, scale = 0)
	public Integer getPontosCirurgiao() {
		return this.pontosCirurgiao;
	}

	public void setPontosCirurgiao(Integer pontosCirurgiao) {
		this.pontosCirurgiao = pontosCirurgiao;
	}

	@Column(name = "PONTOS_SADT", precision = 5, scale = 0)
	public Integer getPontosSadt() {
		return this.pontosSadt;
	}

	public void setPontosSadt(Integer pontosSadt) {
		this.pontosSadt = pontosSadt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_PREVIA", length = 7)
	public Date getDataPrevia() {
		return this.dataPrevia;
	}

	public void setDataPrevia(Date dataPrevia) {
		this.dataPrevia = dataPrevia;
	}

	@Column(name = "VALOR_ANESTESISTA", precision = 14)
	public BigDecimal getValorAnestesista() {
		return this.valorAnestesista;
	}

	public void setValorAnestesista(BigDecimal valorAnestesista) {
		this.valorAnestesista = valorAnestesista;
	}

	@Column(name = "VALOR_PROCEDIMENTO", precision = 14)
	public BigDecimal getValorProcedimento() {
		return this.valorProcedimento;
	}

	public void setValorProcedimento(BigDecimal valorProcedimento) {
		this.valorProcedimento = valorProcedimento;
	}

	@Column(name = "VALOR_SADT", precision = 14)
	public BigDecimal getValorSadt() {
		return this.valorSadt;
	}

	public void setValorSadt(BigDecimal valorSadt) {
		this.valorSadt = valorSadt;
	}

	@Column(name = "VALOR_SERV_HOSP", precision = 14)
	public BigDecimal getValorServHosp() {
		return this.valorServHosp;
	}

	public void setValorServHosp(BigDecimal valorServHosp) {
		this.valorServHosp = valorServHosp;
	}

	@Column(name = "VALOR_SERV_PROF", precision = 14)
	public BigDecimal getValorServProf() {
		return this.valorServProf;
	}

	public void setValorServProf(BigDecimal valorServProf) {
		this.valorServProf = valorServProf;
	}

	@Column(name = "IND_CONSISTENTE", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioTipoItemConta getIndConsistente() {
		return this.indConsistente;
	}

	public void setIndConsistente(DominioTipoItemConta indConsistente) {
		this.indConsistente = indConsistente;
	}

	@Column(name = "IND_MODO_COBRANCA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioModoCobranca getIndModoCobranca() {
		return this.indModoCobranca;
	}

	public void setIndModoCobranca(DominioModoCobranca indModoCobranca) {
		this.indModoCobranca = indModoCobranca;
	}

	@Column(name = "IPH_COD_SUS", precision = 10, scale = 0)
	public Long getIphCodSus() {
		return this.iphCodSus;
	}

	public void setIphCodSus(Long iphCodSus) {
		this.iphCodSus = iphCodSus;
	}
	
	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FatCampoMedicoAuditAih other = (FatCampoMedicoAuditAih) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

	public enum Fields {
		
		EAI_CTH_SEQ("id.eaiCthSeq"),
		EAI_SEQ("id.eaiSeq"),
		SEQP("id.seqp"),
		DATA_PREVIA("dataPrevia"),
		IPH_COD_SUS("iphCodSus"),
		IND_CONSISTENTE("indConsistente"),
		IND_MODO_COBRANCA("indModoCobranca"),
		VALOR_ANEST("valorAnestesista"),
		VALOR_PROCED("valorProcedimento"),
		VALOR_SADT("valorSadt"),
		VALOR_SERV_HOSP("valorServHosp"),
		VALOR_SERV_PROF("valorServProf"),
		IPH_SEQ("itemProcedimentoHospilatar.id.seq"),
		IPH_PHO_SEQ("itemProcedimentoHospilatar.id.phoSeq"),
		IPH("itemProcedimentoHospilatar")
		;
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
		
	}
	
}
