package br.gov.mec.aghu.model;

// Generated 15/03/2011 13:46:58 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * FatExcCaraterInternacoesId generated by hbm2java
 */
@Embeddable
public class FatExcCaraterInternacaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7752709039583581018L;
	private String ufSigla;
	private Integer iphSeq;
	private Short iphPhoSeq;

	public FatExcCaraterInternacaoId() {
	}

	public FatExcCaraterInternacaoId(String ufSigla, Integer iphSeq,
			Short iphPhoSeq) {
		this.ufSigla = ufSigla;
		this.iphSeq = iphSeq;
		this.iphPhoSeq = iphPhoSeq;
	}

	@Column(name = "UF_SIGLA", nullable = false, length = 2)
	@Length(max = 2)
	public String getUfSigla() {
		return this.ufSigla;
	}

	public void setUfSigla(String ufSigla) {
		this.ufSigla = ufSigla;
	}

	@Column(name = "IPH_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getIphSeq() {
		return this.iphSeq;
	}

	public void setIphSeq(Integer iphSeq) {
		this.iphSeq = iphSeq;
	}

	@Column(name = "IPH_PHO_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getIphPhoSeq() {
		return this.iphPhoSeq;
	}

	public void setIphPhoSeq(Short iphPhoSeq) {
		this.iphPhoSeq = iphPhoSeq;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((iphPhoSeq == null) ? 0 : iphPhoSeq.hashCode());
		result = prime * result + ((iphSeq == null) ? 0 : iphSeq.hashCode());
		result = prime * result + ((ufSigla == null) ? 0 : ufSigla.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FatExcCaraterInternacaoId other = (FatExcCaraterInternacaoId) obj;
		if (iphPhoSeq == null) {
			if (other.iphPhoSeq != null) {
				return false;
			}
		} else if (!iphPhoSeq.equals(other.iphPhoSeq)) {
			return false;
		}
		if (iphSeq == null) {
			if (other.iphSeq != null) {
				return false;
			}
		} else if (!iphSeq.equals(other.iphSeq)) {
			return false;
		}
		if (ufSigla == null) {
			if (other.ufSigla != null) {
				return false;
			}
		} else if (!ufSigla.equals(other.ufSigla)) {
			return false;
		}
		return true;
	}

}
