package br.gov.mec.aghu.model;

// Generated 15/03/2011 13:46:58 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * FatExcCnvGrpItensProc generated by hbm2java
 */
@Entity
@SequenceGenerator(name="fatEgiSeq", sequenceName="AGH.FAT_EGI_SEQ", allocationSize = 1)
@Table(name = "FAT_EXC_CNV_GRP_ITENS_PROC", schema = "AGH", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PHI_SEQ", "IPH_PHO_SEQ", "IPH_SEQ", "IPH_PHO_SEQ_REALIZADO",
		"IPH_SEQ_REALIZADO", "CPG_CPH_CSP_SEQ", "CPG_CPH_CSP_CNV_CODIGO",
		"CPG_CPH_PHO_SEQ", "CPG_GRC_SEQ", "TTR_CODIGO" }))
public class FatExcCnvGrpItemProc extends BaseEntitySeq<Integer> implements java.io.Serializable {
	private static final long serialVersionUID = 4416539006635520823L;
	
	private Integer seq;
	private Integer phiSeq;//TODO remover e refatorar onde esta sendo usado.
	private Short iphPhoSeq;//TODO remover e refatorar onde esta sendo usado.
	private Integer iphSeq;//TODO remover e refatorar onde esta sendo usado.
	private Short iphPhoSeqRealizado;//TODO remover e refatorar onde esta sendo usado.
	private Integer iphSeqRealizado;//TODO remover e refatorar onde esta sendo usado.
	private Byte cpgCphCspSeq;
	private Short cpgCphCspCnvCodigo;
	private Short cpgCphPhoSeq;
	private Short cpgGrcSeq;
	private String criadoPor;
	private Date criadoEm;
	private String alteradoPor;
	private Date alteradoEm;
	private String ttrCodigo;
	private Boolean indExigeNotaFiscal;
	
	private FatTipoTransplante fatTipoTransplante;
	private FatProcedHospInternos procedimentoHospitalarInterno;
	private FatItensProcedHospitalar itemProcedimentoHospitalar;
	private FatItensProcedHospitalar itemProcedimentoHospitalarRealizado;
	private Integer version;
	
	public FatExcCnvGrpItemProc() {
		
	}

	
	public FatExcCnvGrpItemProc(Integer seq, Integer phiSeq, Short iphPhoSeq,
			Integer iphSeq, Short iphPhoSeqRealizado, Integer iphSeqRealizado,
			Byte cpgCphCspSeq, Short cpgCphCspCnvCodigo, Short cpgCphPhoSeq,
			Short cpgGrcSeq, String criadoPor, Date criadoEm,
			String alteradoPor, Date alteradoEm, String ttrCodigo,
			Boolean indExigeNotaFiscal) {
		this.seq = seq;
		this.phiSeq = phiSeq;
		this.iphPhoSeq = iphPhoSeq;
		this.iphSeq = iphSeq;
		this.iphPhoSeqRealizado = iphPhoSeqRealizado;
		this.iphSeqRealizado = iphSeqRealizado;
		this.cpgCphCspSeq = cpgCphCspSeq;
		this.cpgCphCspCnvCodigo = cpgCphCspCnvCodigo;
		this.cpgCphPhoSeq = cpgCphPhoSeq;
		this.cpgGrcSeq = cpgGrcSeq;
		this.criadoPor = criadoPor;
		this.criadoEm = criadoEm;
		this.alteradoPor = alteradoPor;
		this.alteradoEm = alteradoEm;
		this.ttrCodigo = ttrCodigo;
		this.indExigeNotaFiscal = indExigeNotaFiscal;
	}
	
	public FatExcCnvGrpItemProc(Short iphPhoSeq, Integer iphSeq) {
		super();
		this.iphPhoSeq = iphPhoSeq;
		this.iphSeq = iphSeq;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fatEgiSeq")
	@Column(name = "SEQ", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	
	@Column(name = "PHI_SEQ", nullable = false, precision = 6, scale = 0)
	public Integer getPhiSeq() {
		return this.phiSeq;
	}

	public void setPhiSeq(Integer phiSeq) {
		this.phiSeq = phiSeq;
	}

	@Column(name = "IPH_PHO_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getIphPhoSeq() {
		return this.iphPhoSeq;
	}

	public void setIphPhoSeq(Short iphPhoSeq) {
		this.iphPhoSeq = iphPhoSeq;
	}

	@Column(name = "IPH_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getIphSeq() {
		return this.iphSeq;
	}

	public void setIphSeq(Integer iphSeq) {
		this.iphSeq = iphSeq;
	}

	@Column(name = "IPH_PHO_SEQ_REALIZADO", nullable = false, precision = 4, scale = 0)
	public Short getIphPhoSeqRealizado() {
		return this.iphPhoSeqRealizado;
	}

	public void setIphPhoSeqRealizado(Short iphPhoSeqRealizado) {
		this.iphPhoSeqRealizado = iphPhoSeqRealizado;
	}

	@Column(name = "IPH_SEQ_REALIZADO", nullable = false, precision = 8, scale = 0)
	public Integer getIphSeqRealizado() {
		return this.iphSeqRealizado;
	}

	public void setIphSeqRealizado(Integer iphSeqRealizado) {
		this.iphSeqRealizado = iphSeqRealizado;
	}

	@Column(name = "CPG_CPH_CSP_SEQ", nullable = false, precision = 2, scale = 0)
	public Byte getCpgCphCspSeq() {
		return this.cpgCphCspSeq;
	}

	public void setCpgCphCspSeq(Byte cpgCphCspSeq) {
		this.cpgCphCspSeq = cpgCphCspSeq;
	}

	@Column(name = "CPG_CPH_CSP_CNV_CODIGO", nullable = false, precision = 3, scale = 0)
	public Short getCpgCphCspCnvCodigo() {
		return this.cpgCphCspCnvCodigo;
	}

	public void setCpgCphCspCnvCodigo(Short cpgCphCspCnvCodigo) {
		this.cpgCphCspCnvCodigo = cpgCphCspCnvCodigo;
	}

	@Column(name = "CPG_CPH_PHO_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getCpgCphPhoSeq() {
		return this.cpgCphPhoSeq;
	}

	public void setCpgCphPhoSeq(Short cpgCphPhoSeq) {
		this.cpgCphPhoSeq = cpgCphPhoSeq;
	}

	@Column(name = "CPG_GRC_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getCpgGrcSeq() {
		return this.cpgGrcSeq;
	}

	public void setCpgGrcSeq(Short cpgGrcSeq) {
		this.cpgGrcSeq = cpgGrcSeq;
	}

	@Column(name = "CRIADO_POR", nullable = false, length = 30)
	@Length(max = 30)
	public String getCriadoPor() {
		return this.criadoPor;
	}

	public void setCriadoPor(String criadoPor) {
		this.criadoPor = criadoPor;
	}

	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "ALTERADO_POR", length = 30)
	@Length(max = 30)
	public String getAlteradoPor() {
		return this.alteradoPor;
	}

	public void setAlteradoPor(String alteradoPor) {
		this.alteradoPor = alteradoPor;
	}

	@Column(name = "ALTERADO_EM", length = 7)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@Column(name = "TTR_CODIGO", length = 10)
	@Length(max = 10)
	public String getTtrCodigo() {
		return this.ttrCodigo;
	}

	public void setTtrCodigo(String ttrCodigo) {
		this.ttrCodigo = ttrCodigo;
	}

	@Column(name = "IND_EXIGE_NOTA_FISCAL", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndExigeNotaFiscal() {
		return this.indExigeNotaFiscal;
	}

	public void setIndExigeNotaFiscal(Boolean indExigeNotaFiscal) {
		this.indExigeNotaFiscal = indExigeNotaFiscal;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TTR_CODIGO", insertable = false, updatable = false)
	public FatTipoTransplante getFatTipoTransplante() {
		return this.fatTipoTransplante;
	}

	public void setFatTipoTransplante(FatTipoTransplante fatTipoTransplante) {
		this.fatTipoTransplante = fatTipoTransplante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHI_SEQ", nullable = false, insertable = false, updatable = false)
	public FatProcedHospInternos getProcedimentoHospitalarInterno() {
		return procedimentoHospitalarInterno;
	}

	public void setProcedimentoHospitalarInterno(
			FatProcedHospInternos procedimentoHospitalarInterno) {
		this.procedimentoHospitalarInterno = procedimentoHospitalarInterno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "IPH_PHO_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "IPH_SEQ", nullable = false, insertable = false, updatable = false) })
	public FatItensProcedHospitalar getItemProcedimentoHospitalar() {
		return itemProcedimentoHospitalar;
	}

	public void setItemProcedimentoHospitalar(FatItensProcedHospitalar itemProcedimentoHospitalar) {
		this.itemProcedimentoHospitalar = itemProcedimentoHospitalar;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
		@JoinColumn(name = "IPH_PHO_SEQ_REALIZADO", nullable = false, insertable = false, updatable = false),
		@JoinColumn(name = "IPH_SEQ_REALIZADO", nullable = false, insertable = false, updatable = false) })
	public FatItensProcedHospitalar getItemProcedimentoHospitalarRealizado() {
		return itemProcedimentoHospitalarRealizado;
	}


	public void setItemProcedimentoHospitalarRealizado(
			FatItensProcedHospitalar itemProcedimentoHospitalarRealizado) {
		this.itemProcedimentoHospitalarRealizado = itemProcedimentoHospitalarRealizado;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seq == null) ? 0 : seq.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FatExcCnvGrpItemProc other = (FatExcCnvGrpItemProc) obj;
		if (seq == null) {
			if (other.seq != null) {
				return false;
			}
		} else if (!seq.equals(other.seq)) {
			return false;
		}
		return true;
	}



	public enum Fields {
		
		SEQ("seq"),
		CPG_CPH_PHO_SEQ("cpgCphPhoSeq"),
		PHI_SEQ("phiSeq"),
		IPH_PHO_SEQ("iphPhoSeq"),
		IPH_SEQ("iphSeq"),
		IPH_PHO_SEQ_REALIZADO("iphPhoSeqRealizado"),
		IPH_SEQ_REALIZADO("iphSeqRealizado"),
		CPG_CPH_CSP_SEQ("cpgCphCspSeq"),
		CPG_CPH_CSP_CNV_CODIGO("cpgCphCspCnvCodigo"),
		CPG_GRC_SEQ("cpgGrcSeq"),
		CRIADO_POR("criadoPor"),
		CRIADO_EM("criadoEm"),
		ALTERADO_POR("alteradoPor"),
		ALTERADO_EM("alteradoEm"),
		TTR_CODIGO("ttrCodigo"),
		IND_EXIGE_NOTA_FISCAL("indExigeNotaFiscal"),
		ITEM_PROCEDIMENTO_HOSPITALAR("itemProcedimentoHospitalar"),
		ITEM_PROCEDIMENTO_HOSPITALAR_REALIZADO("itemProcedimentoHospitalarRealizado"),
		FAT_TIPO_TRANSPLANTE("fatTipoTransplante")
		;

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}
}
