package br.gov.mec.aghu.model;

// Generated 15/03/2011 13:46:58 by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * FatItensEspelhosContaApacId generated by hbm2java
 */
@Embeddable
public class FatItemEspelhoContaApacId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7531530262543284492L;
	private Byte atvProfissional;
	private Long capAtmNumero;
	private Short capIcaSeqp;
	private Byte capSeqp;
	private Boolean indConsistente;
	private Short iphPhoSeq;
	private Integer iphSeq;
	private Long procedimentoHosp;
	private Integer quantidade;
	private Boolean seqpContinuacao;
	private BigDecimal vlrAnestes;
	private BigDecimal vlrProc;
	private BigDecimal vlrSadt;
	private BigDecimal vlrServHosp;
	private BigDecimal vlrServProf;
	private Integer fccSeq;
	private Integer fcfSeq;
	private String indTeto;
	private String codAtvProf;

	public FatItemEspelhoContaApacId() {
	}

	public FatItemEspelhoContaApacId(Byte atvProfissional, Long capAtmNumero,
			Short capIcaSeqp, Byte capSeqp, Boolean indConsistente,
			Short iphPhoSeq, Integer iphSeq, Long procedimentoHosp,
			Integer quantidade, Boolean seqpContinuacao, BigDecimal vlrAnestes,
			BigDecimal vlrProc, BigDecimal vlrSadt, BigDecimal vlrServHosp,
			BigDecimal vlrServProf, Integer fccSeq, Integer fcfSeq,
			String indTeto, String codAtvProf) {
		this.atvProfissional = atvProfissional;
		this.capAtmNumero = capAtmNumero;
		this.capIcaSeqp = capIcaSeqp;
		this.capSeqp = capSeqp;
		this.indConsistente = indConsistente;
		this.iphPhoSeq = iphPhoSeq;
		this.iphSeq = iphSeq;
		this.procedimentoHosp = procedimentoHosp;
		this.quantidade = quantidade;
		this.seqpContinuacao = seqpContinuacao;
		this.vlrAnestes = vlrAnestes;
		this.vlrProc = vlrProc;
		this.vlrSadt = vlrSadt;
		this.vlrServHosp = vlrServHosp;
		this.vlrServProf = vlrServProf;
		this.fccSeq = fccSeq;
		this.fcfSeq = fcfSeq;
		this.indTeto = indTeto;
		this.codAtvProf = codAtvProf;
	}

	@Column(name = "ATV_PROFISSIONAL", precision = 2, scale = 0)
	public Byte getAtvProfissional() {
		return this.atvProfissional;
	}

	public void setAtvProfissional(Byte atvProfissional) {
		this.atvProfissional = atvProfissional;
	}

	@Column(name = "CAP_ATM_NUMERO", precision = 13, scale = 0)
	public Long getCapAtmNumero() {
		return this.capAtmNumero;
	}

	public void setCapAtmNumero(Long capAtmNumero) {
		this.capAtmNumero = capAtmNumero;
	}

	@Column(name = "CAP_ICA_SEQP", precision = 3, scale = 0)
	public Short getCapIcaSeqp() {
		return this.capIcaSeqp;
	}

	public void setCapIcaSeqp(Short capIcaSeqp) {
		this.capIcaSeqp = capIcaSeqp;
	}

	@Column(name = "CAP_SEQP", precision = 2, scale = 0)
	public Byte getCapSeqp() {
		return this.capSeqp;
	}

	public void setCapSeqp(Byte capSeqp) {
		this.capSeqp = capSeqp;
	}

	@Column(name = "IND_CONSISTENTE", length = 1)
	@org.hibernate.annotations.Type( type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndConsistente() {
		return this.indConsistente;
	}

	public void setIndConsistente(final Boolean indConsistente) {
		this.indConsistente = indConsistente;
	}

	@Column(name = "IPH_PHO_SEQ", precision = 4, scale = 0)
	public Short getIphPhoSeq() {
		return this.iphPhoSeq;
	}

	public void setIphPhoSeq(Short iphPhoSeq) {
		this.iphPhoSeq = iphPhoSeq;
	}

	@Column(name = "IPH_SEQ", precision = 8, scale = 0)
	public Integer getIphSeq() {
		return this.iphSeq;
	}

	public void setIphSeq(Integer iphSeq) {
		this.iphSeq = iphSeq;
	}

	@Column(name = "PROCEDIMENTO_HOSP", precision = 10, scale = 0)
	public Long getProcedimentoHosp() {
		return this.procedimentoHosp;
	}

	public void setProcedimentoHosp(Long procedimentoHosp) {
		this.procedimentoHosp = procedimentoHosp;
	}

	@Column(name = "QUANTIDADE", precision = 6, scale = 0)
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "SEQP_CONTINUACAO", precision = 1, scale = 0)
	public Boolean getSeqpContinuacao() {
		return this.seqpContinuacao;
	}

	public void setSeqpContinuacao(Boolean seqpContinuacao) {
		this.seqpContinuacao = seqpContinuacao;
	}

	@Column(name = "VLR_ANESTES", precision = 14)
	public BigDecimal getVlrAnestes() {
		return this.vlrAnestes;
	}

	public void setVlrAnestes(BigDecimal vlrAnestes) {
		this.vlrAnestes = vlrAnestes;
	}

	@Column(name = "VLR_PROC", precision = 14)
	public BigDecimal getVlrProc() {
		return this.vlrProc;
	}

	public void setVlrProc(BigDecimal vlrProc) {
		this.vlrProc = vlrProc;
	}

	@Column(name = "VLR_SADT", precision = 14)
	public BigDecimal getVlrSadt() {
		return this.vlrSadt;
	}

	public void setVlrSadt(BigDecimal vlrSadt) {
		this.vlrSadt = vlrSadt;
	}

	@Column(name = "VLR_SERV_HOSP", precision = 14)
	public BigDecimal getVlrServHosp() {
		return this.vlrServHosp;
	}

	public void setVlrServHosp(BigDecimal vlrServHosp) {
		this.vlrServHosp = vlrServHosp;
	}

	@Column(name = "VLR_SERV_PROF", precision = 14)
	public BigDecimal getVlrServProf() {
		return this.vlrServProf;
	}

	public void setVlrServProf(BigDecimal vlrServProf) {
		this.vlrServProf = vlrServProf;
	}

	@Column(name = "FCC_SEQ", precision = 5, scale = 0)
	public Integer getFccSeq() {
		return this.fccSeq;
	}

	public void setFccSeq(Integer fccSeq) {
		this.fccSeq = fccSeq;
	}

	@Column(name = "FCF_SEQ", precision = 5, scale = 0)
	public Integer getFcfSeq() {
		return this.fcfSeq;
	}

	public void setFcfSeq(Integer fcfSeq) {
		this.fcfSeq = fcfSeq;
	}

	@Column(name = "IND_TETO", length = 1)
	@Length(max = 1)
	public String getIndTeto() {
		return this.indTeto;
	}

	public void setIndTeto(String indTeto) {
		this.indTeto = indTeto;
	}

	@Column(name = "COD_ATV_PROF", length = 6)
	@Length(max = 6)
	public String getCodAtvProf() {
		return this.codAtvProf;
	}

	public void setCodAtvProf(String codAtvProf) {
		this.codAtvProf = codAtvProf;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof FatItemEspelhoContaApacId)) {
			return false;
		}
		FatItemEspelhoContaApacId castOther = (FatItemEspelhoContaApacId) other;

		return ((this.getAtvProfissional() == castOther.getAtvProfissional()) || (this
				.getAtvProfissional() != null
				&& castOther.getAtvProfissional() != null && this
				.getAtvProfissional().equals(castOther.getAtvProfissional())))
				&& ((this.getCapAtmNumero() == castOther.getCapAtmNumero()) || (this
						.getCapAtmNumero() != null
						&& castOther.getCapAtmNumero() != null && this
						.getCapAtmNumero().equals(castOther.getCapAtmNumero())))
				&& ((this.getCapIcaSeqp() == castOther.getCapIcaSeqp()) || (this
						.getCapIcaSeqp() != null
						&& castOther.getCapIcaSeqp() != null && this
						.getCapIcaSeqp().equals(castOther.getCapIcaSeqp())))
				&& ((this.getCapSeqp() == castOther.getCapSeqp()) || (this
						.getCapSeqp() != null
						&& castOther.getCapSeqp() != null && this.getCapSeqp()
						.equals(castOther.getCapSeqp())))
				&& ((this.getIndConsistente() == castOther.getIndConsistente()) || (this
						.getIndConsistente() != null
						&& castOther.getIndConsistente() != null && this
						.getIndConsistente().equals(
								castOther.getIndConsistente())))
				&& ((this.getIphPhoSeq() == castOther.getIphPhoSeq()) || (this
						.getIphPhoSeq() != null
						&& castOther.getIphPhoSeq() != null && this
						.getIphPhoSeq().equals(castOther.getIphPhoSeq())))
				&& ((this.getIphSeq() == castOther.getIphSeq()) || (this
						.getIphSeq() != null
						&& castOther.getIphSeq() != null && this.getIphSeq()
						.equals(castOther.getIphSeq())))
				&& ((this.getProcedimentoHosp() == castOther
						.getProcedimentoHosp()) || (this.getProcedimentoHosp() != null
						&& castOther.getProcedimentoHosp() != null && this
						.getProcedimentoHosp().equals(
								castOther.getProcedimentoHosp())))
				&& ((this.getQuantidade() == castOther.getQuantidade()) || (this
						.getQuantidade() != null
						&& castOther.getQuantidade() != null && this
						.getQuantidade().equals(castOther.getQuantidade())))
				&& ((this.getSeqpContinuacao() == castOther
						.getSeqpContinuacao()) || (this.getSeqpContinuacao() != null
						&& castOther.getSeqpContinuacao() != null && this
						.getSeqpContinuacao().equals(
								castOther.getSeqpContinuacao())))
				&& ((this.getVlrAnestes() == castOther.getVlrAnestes()) || (this
						.getVlrAnestes() != null
						&& castOther.getVlrAnestes() != null && this
						.getVlrAnestes().equals(castOther.getVlrAnestes())))
				&& ((this.getVlrProc() == castOther.getVlrProc()) || (this
						.getVlrProc() != null
						&& castOther.getVlrProc() != null && this.getVlrProc()
						.equals(castOther.getVlrProc())))
				&& ((this.getVlrSadt() == castOther.getVlrSadt()) || (this
						.getVlrSadt() != null
						&& castOther.getVlrSadt() != null && this.getVlrSadt()
						.equals(castOther.getVlrSadt())))
				&& ((this.getVlrServHosp() == castOther.getVlrServHosp()) || (this
						.getVlrServHosp() != null
						&& castOther.getVlrServHosp() != null && this
						.getVlrServHosp().equals(castOther.getVlrServHosp())))
				&& ((this.getVlrServProf() == castOther.getVlrServProf()) || (this
						.getVlrServProf() != null
						&& castOther.getVlrServProf() != null && this
						.getVlrServProf().equals(castOther.getVlrServProf())))
				&& ((this.getFccSeq() == castOther.getFccSeq()) || (this
						.getFccSeq() != null
						&& castOther.getFccSeq() != null && this.getFccSeq()
						.equals(castOther.getFccSeq())))
				&& ((this.getFcfSeq() == castOther.getFcfSeq()) || (this
						.getFcfSeq() != null
						&& castOther.getFcfSeq() != null && this.getFcfSeq()
						.equals(castOther.getFcfSeq())))
				&& ((this.getIndTeto() == castOther.getIndTeto()) || (this
						.getIndTeto() != null
						&& castOther.getIndTeto() != null && this.getIndTeto()
						.equals(castOther.getIndTeto())))
				&& ((this.getCodAtvProf() == castOther.getCodAtvProf()) || (this
						.getCodAtvProf() != null
						&& castOther.getCodAtvProf() != null && this
						.getCodAtvProf().equals(castOther.getCodAtvProf())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAtvProfissional() == null ? 0 : this.getAtvProfissional()
						.hashCode());
		result = 37
				* result
				+ (getCapAtmNumero() == null ? 0 : this.getCapAtmNumero()
						.hashCode());
		result = 37
				* result
				+ (getCapIcaSeqp() == null ? 0 : this.getCapIcaSeqp()
						.hashCode());
		result = 37 * result
				+ (getCapSeqp() == null ? 0 : this.getCapSeqp().hashCode());
		result = 37
				* result
				+ (getIndConsistente() == null ? 0 : this.getIndConsistente()
						.hashCode());
		result = 37 * result
				+ (getIphPhoSeq() == null ? 0 : this.getIphPhoSeq().hashCode());
		result = 37 * result
				+ (getIphSeq() == null ? 0 : this.getIphSeq().hashCode());
		result = 37
				* result
				+ (getProcedimentoHosp() == null ? 0 : this
						.getProcedimentoHosp().hashCode());
		result = 37
				* result
				+ (getQuantidade() == null ? 0 : this.getQuantidade()
						.hashCode());
		result = 37
				* result
				+ (getSeqpContinuacao() == null ? 0 : this.getSeqpContinuacao()
						.hashCode());
		result = 37
				* result
				+ (getVlrAnestes() == null ? 0 : this.getVlrAnestes()
						.hashCode());
		result = 37 * result
				+ (getVlrProc() == null ? 0 : this.getVlrProc().hashCode());
		result = 37 * result
				+ (getVlrSadt() == null ? 0 : this.getVlrSadt().hashCode());
		result = 37
				* result
				+ (getVlrServHosp() == null ? 0 : this.getVlrServHosp()
						.hashCode());
		result = 37
				* result
				+ (getVlrServProf() == null ? 0 : this.getVlrServProf()
						.hashCode());
		result = 37 * result
				+ (getFccSeq() == null ? 0 : this.getFccSeq().hashCode());
		result = 37 * result
				+ (getFcfSeq() == null ? 0 : this.getFcfSeq().hashCode());
		result = 37 * result
				+ (getIndTeto() == null ? 0 : this.getIndTeto().hashCode());
		result = 37
				* result
				+ (getCodAtvProf() == null ? 0 : this.getCodAtvProf()
						.hashCode());
		return result;
	}

}
