package br.gov.mec.aghu.model;

// Generated 18/05/2010 18:15:07 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * FatPeriodosEmissao generated by hbm2java
 */

@Entity
@Table(name = "FAT_PERIODOS_EMISSAO", schema = "AGH")
public class FatPeriodosEmissao extends BaseEntityId<FatPeriodosEmissaoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8909172498818595820L;
	private FatPeriodosEmissaoId id;
	private Integer diaInicio;
	private Integer diaFim;
	private Integer diaSemana;

	/**
	 * convenioSaudePlano
	 */
	private FatConvenioSaudePlano convenioSaudePlano;
	private Integer version;

	public FatPeriodosEmissao() {
	}

	public FatPeriodosEmissao(FatPeriodosEmissaoId id) {
		this.id = id;
	}

	public FatPeriodosEmissao(FatPeriodosEmissaoId id, Integer diaInicio,
			Integer diaFim, Integer diaSemana) {
		this.id = id;
		this.diaInicio = diaInicio;
		this.diaFim = diaFim;
		this.diaSemana = diaSemana;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "cspSeq", column = @Column(name = "CSP_SEQ", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "cspCnvCodigo", column = @Column(name = "CSP_CNV_CODIGO", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false, precision = 2, scale = 0)) })
	public FatPeriodosEmissaoId getId() {
		return this.id;
	}

	public void setId(FatPeriodosEmissaoId id) {
		this.id = id;
	}

	@Column(name = "DIA_INICIO", precision = 2, scale = 0)
	public Integer getDiaInicio() {
		return this.diaInicio;
	}

	public void setDiaInicio(Integer diaInicio) {
		this.diaInicio = diaInicio;
	}

	@Column(name = "DIA_FIM", precision = 2, scale = 0)
	public Integer getDiaFim() {
		return this.diaFim;
	}

	public void setDiaFim(Integer diaFim) {
		this.diaFim = diaFim;
	}

	@Column(name = "DIA_SEMANA", precision = 1, scale = 0)
	public Integer getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(Integer diaSemana) {
		this.diaSemana = diaSemana;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "CSP_CNV_CODIGO", referencedColumnName = "CNV_CODIGO", insertable = false, updatable = false),
			@JoinColumn(name = "CSP_SEQ", referencedColumnName = "SEQ", insertable = false, updatable = false) })
	public FatConvenioSaudePlano getConvenioSaudePlano() {
		return this.convenioSaudePlano;
	}

	public void setConvenioSaudePlano(FatConvenioSaudePlano convenioSaudePlano) {
		this.convenioSaudePlano = convenioSaudePlano;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public enum Fields {

		SEQ("id.seq"),

		CNV_CODIGO("convenioSaudePlano.id.cnvCodigo"),
		
		CONVENIO_SAUDE_PLANO("convenioSaudePlano");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((diaFim == null) ? 0 : diaFim.hashCode());
		result = prime * result
				+ ((diaInicio == null) ? 0 : diaInicio.hashCode());
		result = prime * result
				+ ((diaSemana == null) ? 0 : diaSemana.hashCode());
		// result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FatPeriodosEmissao other = (FatPeriodosEmissao) obj;
		if (diaFim == null) {
			if (other.diaFim != null) {
				return false;
			}
		} else if (!diaFim.equals(other.diaFim)) {
			return false;
		}
		if (diaInicio == null) {
			if (other.diaInicio != null) {
				return false;
			}
		} else if (!diaInicio.equals(other.diaInicio)) {
			return false;
		}
		if (diaSemana == null) {
			if (other.diaSemana != null) {
				return false;
			}
		} else if (!diaSemana.equals(other.diaSemana)) {
			return false;
		}
		// if (id == null) {
		// if (other.id != null)
		// return false;
		// } else if (!id.equals(other.id))
		// return false;
		return true;
	}

}
