package br.gov.mec.aghu.model;

// Generated 13/05/2010 14:04:30 by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;



import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.dominio.DominioTipoNutricaoParenteral;
import br.gov.mec.aghu.dominio.DominioTipoOperacaoConversao;

/**
 * FatProcedHospInternos generated by hbm2java
 */
@Entity
@Table(name = "FAT_PROCED_HOSP_INTERNOS", schema = "AGH")
@SequenceGenerator(name="fatPhiSq1", sequenceName="AGH.FAT_PHI_SQ1", allocationSize = 1)
@Inheritance(strategy=InheritanceType.TABLE_PER_CLASS)
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.TRANSACTIONAL)
//TODO Este POJO deveria ter sido excluido pois a tabela não existe no banco postgres, mas a mesma ainda é usada no AGHU. #28853
public class FatProcedHospInternos extends FatProcedHospInternosPai implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2818763270863957098L;

	
	public FatProcedHospInternos() {
		super();
	}
	
	public FatProcedHospInternos(Integer seq) {
		this.seq = seq;
	}

	public FatProcedHospInternos(Integer seq, String descricao, DominioSituacao situacao) {
		super(seq, descricao, situacao);
	}
	
	@SuppressWarnings({"PMD.ExcessiveParameterList"})
	public FatProcedHospInternos(
			Integer seq,
			FatProcedHospInternos fatProcedHospInternos,
			String descricao,
			String orientacoesFaturamento,
			DominioSituacao situacao,
			ScoMaterial matCodigo,
			MbcProcedimentoCirurgicos procedimentoCirurgico,
			MpmProcedEspecialDiversos procedimentoEspecialDiverso,
			String csaCodigo,
			String pheCodigo,
			RapServidores servidor,
			Date criadoEm,
			AelExames emaExaSigla,
			Integer emaManSeq,
			Boolean componenteIrradiado,
			DominioTipoNutricaoParenteral tipoNutrParenteral,
			Boolean indOrigemPresc,
			DominioTipoOperacaoConversao tipoOperConversao,
			BigDecimal fatorConversao,
			Short euuSeq,
			Integer cduSeq,
			Short cuiSeq,
			MamItemMedicacao itemMedicacao,
			MamItemExame itemExame,
			Integer tidSeq,
			Boolean indUtilizaKit,
			DominioTipoNutricaoParenteral tipoNutricaoEnteral,
			Set<FatItemContaHospitalar> fatItensContaHospitalares,
			Set<FatExcCnvGrpItemProc> fatExcCnvGrpItemProcs,
			Set<FatProcedHospInternos> fatProcedHospInternoses,
			Set<FatContasHospitalares> fatContasHospitalaresesForPhiSeq,
			Set<FatConvGrupoItemProced> fatConvGrupoItemProceds,
			Set<FatContasHospitalares> fatContasHospitalaresesForPhiSeqRealizado,
			Set<FatCandidatosApacOtorrino> fatCandidatosApacOtorrinosForPhiSeqSugerido,
			Set<FatCandidatosApacOtorrino> fatCandidatosApacOtorrinosForPhiSeq,
			Set<FatResumoApacs> fatResumoApacses,
			Set<FatProcedHospIntCid> fatProcedHospIntCids,
			Set<FatAgrupItemConta> fatAgrupItemContas,
			Set<FatProcedAmbRealizado> fatProcedAmbRealizadoses,
			Set<FatItemContaApac> fatItemContaApacs,
			Set<FatResumoItemApac> fatResumoItemApacs,
			Set<FatProcedTratamento> fatProcedTratamentoses,
			Set<FatItemCtaAtend> fatItemCtaAtendses,
			Set<FatAtendimentoApacProcHosp> fatAtendimentoApacProcHosps,
			Set<VFatAssociacaoProcedimento> vwFatAssociacaoProcedimento) {
		
		super( seq, fatProcedHospInternos, descricao, orientacoesFaturamento, situacao, matCodigo, procedimentoCirurgico,
			   procedimentoEspecialDiverso, csaCodigo, pheCodigo, servidor, criadoEm, emaExaSigla, emaManSeq, componenteIrradiado, 
			   tipoNutrParenteral, indOrigemPresc, tipoOperConversao, fatorConversao, euuSeq, cduSeq, cuiSeq, itemMedicacao, itemExame, 
			   tidSeq, indUtilizaKit, tipoNutricaoEnteral, fatItensContaHospitalares, fatExcCnvGrpItemProcs, 
			   fatProcedHospInternoses, fatContasHospitalaresesForPhiSeq, fatConvGrupoItemProceds, 
			   fatContasHospitalaresesForPhiSeqRealizado, fatCandidatosApacOtorrinosForPhiSeqSugerido, fatCandidatosApacOtorrinosForPhiSeq, 
			   fatResumoApacses, fatProcedHospIntCids, fatAgrupItemContas, 
			   fatProcedAmbRealizadoses, fatItemContaApacs, fatResumoItemApacs, fatProcedTratamentoses, fatItemCtaAtendses, 
			   fatAtendimentoApacProcHosps,vwFatAssociacaoProcedimento
			 );
	}
	
	@Id
	@Column(name = "SEQ", unique = true, nullable = false, precision = 6)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fatPhiSq1")
	@Override
	public Integer getSeq() {
		return super.getSeq();
	}	

	
	
	
	
	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FatProcedHospInternos)) {
			return false;
		}
		FatProcedHospInternos other = (FatProcedHospInternos) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
