package br.gov.mec.aghu.model;

// Generated 15/03/2011 13:46:58 by Hibernate Tools 3.2.5.Beta

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * FatRetornaAihs generated by hbm2java
 */
@Entity
@Table(name = "FAT_RETORNA_AIHS", schema = "AGH")
public class FatRetornaAih extends BaseEntityId<FatRetornaAihId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4889073394525688107L;
	private FatRetornaAihId id;
	private Integer version;

	public FatRetornaAih() {
	}

	public FatRetornaAih(FatRetornaAihId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "nroLaudo", column = @Column(name = "NRO_LAUDO", precision = 13, scale = 0)),
			@AttributeOverride(name = "cthSeq", column = @Column(name = "CTH_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "nroCpfAuditor", column = @Column(name = "NRO_CPF_AUDITOR", precision = 13, scale = 0)),
			@AttributeOverride(name = "nroAih", column = @Column(name = "NRO_AIH", precision = 13, scale = 0)),
			@AttributeOverride(name = "dtEmissaoAih", column = @Column(name = "DT_EMISSAO_AIH", length = 7)),
			@AttributeOverride(name = "codSusAut", column = @Column(name = "COD_SUS_AUT", precision = 10, scale = 0)),
			@AttributeOverride(name = "indTipoLaudo", column = @Column(name = "IND_TIPO_LAUDO", length = 1)),
			@AttributeOverride(name = "codSusCma1", column = @Column(name = "COD_SUS_CMA1", precision = 10, scale = 0)),
			@AttributeOverride(name = "codSusCma2", column = @Column(name = "COD_SUS_CMA2", precision = 8, scale = 0)),
			@AttributeOverride(name = "codSusCma3", column = @Column(name = "COD_SUS_CMA3", precision = 8, scale = 0)),
			@AttributeOverride(name = "codSusCma4", column = @Column(name = "COD_SUS_CMA4", precision = 8, scale = 0)),
			@AttributeOverride(name = "codSusCma5", column = @Column(name = "COD_SUS_CMA5", precision = 8, scale = 0)), 
			@AttributeOverride(name = "nroCnsAuditor", column = @Column(name = "NRO_CNS_AUDITOR", precision = 15, scale = 0)) 
			})
			
	public FatRetornaAihId getId() {
		return this.id;
	}

	public void setId(FatRetornaAihId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FatRetornaAih other = (FatRetornaAih) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

	public enum Fields {

		ID("id"),
		IND_TIPO_LAUDO("id.indTipoLaudo")
		;

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
