package br.gov.mec.aghu.model;

// Generated 15/03/2011 13:46:58 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * FatRetornaAihsId generated by hbm2java
 */
@Embeddable
public class FatRetornaAihId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1202306396570991056L;
	private Long nroLaudo;
	private Integer cthSeq;
	private Long nroCpfAuditor;
	private Long nroAih;
	private Date dtEmissaoAih;
	private Long codSusAut;
	private String indTipoLaudo;
	private Long codSusCma1;
	private Integer codSusCma2;
	private Integer codSusCma3;
	private Integer codSusCma4;
	private Integer codSusCma5;
	private Long nroCnsAuditor;

	public FatRetornaAihId() {
	}

	public FatRetornaAihId(Integer cthSeq) {
		this.cthSeq = cthSeq;
	}

	public FatRetornaAihId(Long nroLaudo, Integer cthSeq, Long nroCpfAuditor,
			Long nroAih, Date dtEmissaoAih, Long codSusAut,
			String indTipoLaudo, Long codSusCma1, Integer codSusCma2,
			Integer codSusCma3, Integer codSusCma4, Integer codSusCma5) {
		this.nroLaudo = nroLaudo;
		this.cthSeq = cthSeq;
		this.nroCpfAuditor = nroCpfAuditor;
		this.nroAih = nroAih;
		this.dtEmissaoAih = dtEmissaoAih;
		this.codSusAut = codSusAut;
		this.indTipoLaudo = indTipoLaudo;
		this.codSusCma1 = codSusCma1;
		this.codSusCma2 = codSusCma2;
		this.codSusCma3 = codSusCma3;
		this.codSusCma4 = codSusCma4;
		this.codSusCma5 = codSusCma5;
	}

	@Column(name = "NRO_LAUDO", precision = 13, scale = 0)
	public Long getNroLaudo() {
		return this.nroLaudo;
	}

	public void setNroLaudo(Long nroLaudo) {
		this.nroLaudo = nroLaudo;
	}

	@Column(name = "CTH_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getCthSeq() {
		return this.cthSeq;
	}

	public void setCthSeq(Integer cthSeq) {
		this.cthSeq = cthSeq;
	}

	@Column(name = "NRO_CPF_AUDITOR", precision = 13, scale = 0)
	public Long getNroCpfAuditor() {
		return this.nroCpfAuditor;
	}

	public void setNroCpfAuditor(Long nroCpfAuditor) {
		this.nroCpfAuditor = nroCpfAuditor;
	}

	@Column(name = "NRO_AIH", precision = 13, scale = 0)
	public Long getNroAih() {
		return this.nroAih;
	}

	public void setNroAih(Long nroAih) {
		this.nroAih = nroAih;
	}

	@Column(name = "DT_EMISSAO_AIH", length = 7)
	public Date getDtEmissaoAih() {
		return this.dtEmissaoAih;
	}

	public void setDtEmissaoAih(Date dtEmissaoAih) {
		this.dtEmissaoAih = dtEmissaoAih;
	}

	@Column(name = "COD_SUS_AUT", precision = 10, scale = 0)
	public Long getCodSusAut() {
		return this.codSusAut;
	}

	public void setCodSusAut(Long codSusAut) {
		this.codSusAut = codSusAut;
	}

	@Column(name = "IND_TIPO_LAUDO", length = 1)
	@Length(max = 1)
	public String getIndTipoLaudo() {
		return this.indTipoLaudo;
	}

	public void setIndTipoLaudo(String indTipoLaudo) {
		this.indTipoLaudo = indTipoLaudo;
	}

	@Column(name = "COD_SUS_CMA1", precision = 10, scale = 0)
	public Long getCodSusCma1() {
		return this.codSusCma1;
	}

	public void setCodSusCma1(Long codSusCma1) {
		this.codSusCma1 = codSusCma1;
	}

	@Column(name = "COD_SUS_CMA2", precision = 8, scale = 0)
	public Integer getCodSusCma2() {
		return this.codSusCma2;
	}

	public void setCodSusCma2(Integer codSusCma2) {
		this.codSusCma2 = codSusCma2;
	}

	@Column(name = "COD_SUS_CMA3", precision = 8, scale = 0)
	public Integer getCodSusCma3() {
		return this.codSusCma3;
	}

	public void setCodSusCma3(Integer codSusCma3) {
		this.codSusCma3 = codSusCma3;
	}

	@Column(name = "COD_SUS_CMA4", precision = 8, scale = 0)
	public Integer getCodSusCma4() {
		return this.codSusCma4;
	}

	public void setCodSusCma4(Integer codSusCma4) {
		this.codSusCma4 = codSusCma4;
	}

	@Column(name = "COD_SUS_CMA5", precision = 8, scale = 0)
	public Integer getCodSusCma5() {
		return this.codSusCma5;
	}

	public void setCodSusCma5(Integer codSusCma5) {
		this.codSusCma5 = codSusCma5;
	}
	
	@Column(name = "NRO_CNS_AUDITOR", precision = 15, scale = 0)
	public Long getNroCnsAuditor() {
		return nroCnsAuditor;
	}

	public void setNroCnsAuditor(Long nroCnsAuditor) {
		this.nroCnsAuditor = nroCnsAuditor;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getCthSeq());
		umHashCodeBuilder.append(this.getNroLaudo());
		umHashCodeBuilder.append(this.getNroCpfAuditor());
		umHashCodeBuilder.append(this.getNroAih());
		umHashCodeBuilder.append(this.getDtEmissaoAih());
		umHashCodeBuilder.append(this.getCodSusAut());
		umHashCodeBuilder.append(this.getIndTipoLaudo());
		umHashCodeBuilder.append(this.getCodSusCma1());
		umHashCodeBuilder.append(this.getCodSusCma2());
		umHashCodeBuilder.append(this.getCodSusCma3());
		umHashCodeBuilder.append(this.getCodSusCma4());
		umHashCodeBuilder.append(this.getCodSusCma5());
		umHashCodeBuilder.append(this.getNroCnsAuditor());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FatRetornaAihId)) {
			return false;
		}
		FatRetornaAihId other = (FatRetornaAihId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getCthSeq(), other.getCthSeq());
		umEqualsBuilder.append(this.getNroLaudo(), other.getNroLaudo());
		umEqualsBuilder.append(this.getNroCpfAuditor(), other.getNroCpfAuditor());
		umEqualsBuilder.append(this.getNroAih(), other.getNroAih());
		umEqualsBuilder.append(this.getDtEmissaoAih(), other.getDtEmissaoAih());
		umEqualsBuilder.append(this.getCodSusAut(), other.getCodSusAut());
		umEqualsBuilder.append(this.getIndTipoLaudo(), other.getIndTipoLaudo());
		umEqualsBuilder.append(this.getCodSusCma1(), other.getCodSusCma1());
		umEqualsBuilder.append(this.getCodSusCma2(), other.getCodSusCma2());
		umEqualsBuilder.append(this.getCodSusCma3(), other.getCodSusCma3());
		umEqualsBuilder.append(this.getCodSusCma4(), other.getCodSusCma4());
		umEqualsBuilder.append(this.getCodSusCma5(), other.getCodSusCma5());
		umEqualsBuilder.append(this.getNroCnsAuditor(), other.getNroCnsAuditor());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
