package br.gov.mec.aghu.model;

// Generated 15/03/2011 13:46:58 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * FatTiposClassifSecSaude generated by hbm2java
 */
@Entity
@SequenceGenerator(name="fatTcsSq1", sequenceName="AGH.FAT_TCS_SQ1", allocationSize = 1)
@Table(name = "FAT_TIPOS_CLASSIF_SEC_SAUDE", schema = "AGH")
public class FatTipoClassifSecSaude extends BaseEntitySeq<Byte> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6537145242654311034L;
	private Byte seq;
	private String descricao;
	private DominioSituacao indSituacaoRegistro;
	private String codigoSus;
	private String arquivoDcih;
	private Set<FatDocumentoCobrancaAihs> fatDocumentoCobrancaAihses = new HashSet<FatDocumentoCobrancaAihs>(0);
	private Integer version;

	public FatTipoClassifSecSaude() {
	}

	public FatTipoClassifSecSaude(Byte seq, String descricao, String codigoSus) {
		this.seq = seq;
		this.descricao = descricao;
		this.codigoSus = codigoSus;
	}

	public FatTipoClassifSecSaude(Byte seq, String descricao,
			DominioSituacao indSituacaoRegistro, String codigoSus, String arquivoDcih,
			Set<FatDocumentoCobrancaAihs> fatDocumentoCobrancaAihses) {
		this.seq = seq;
		this.descricao = descricao;
		this.indSituacaoRegistro = indSituacaoRegistro;
		this.codigoSus = codigoSus;
		this.arquivoDcih = arquivoDcih;
		this.fatDocumentoCobrancaAihses = fatDocumentoCobrancaAihses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fatTcsSq1")
	@Column(name = "SEQ", unique = true, nullable = false, precision = 2, scale = 0)
	public Byte getSeq() {
		return this.seq;
	}

	public void setSeq(Byte seq) {
		this.seq = seq;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 50)
	@Length(max = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_SITUACAO_REGISTRO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacaoRegistro() {
		return this.indSituacaoRegistro;
	}

	public void setIndSituacaoRegistro(DominioSituacao indSituacaoRegistro) {
		this.indSituacaoRegistro = indSituacaoRegistro;
	}

	@Column(name = "CODIGO_SUS", nullable = false, length = 1)
	@Length(max = 1)
	public String getCodigoSus() {
		return this.codigoSus;
	}

	public void setCodigoSus(String codigoSus) {
		this.codigoSus = codigoSus;
	}

	@Column(name = "ARQUIVO_DCIH", length = 15)
	@Length(max = 15)
	public String getArquivoDcih() {
		return this.arquivoDcih;
	}

	public void setArquivoDcih(String arquivoDcih) {
		this.arquivoDcih = arquivoDcih;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fatTipoClassifSecSaude")
	public Set<FatDocumentoCobrancaAihs> getFatDocumentoCobrancaAihses() {
		return this.fatDocumentoCobrancaAihses;
	}

	public void setFatDocumentoCobrancaAihses(
			Set<FatDocumentoCobrancaAihs> fatDocumentoCobrancaAihses) {
		this.fatDocumentoCobrancaAihses = fatDocumentoCobrancaAihses;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seq == null) ? 0 : seq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
		if (obj == null){
			return false;
		}
		if (getClass() != obj.getClass()){
			return false;
		}
		FatTipoClassifSecSaude other = (FatTipoClassifSecSaude) obj;
		if (seq == null) {
			if (other.seq != null){
				return false;
			}
		} else if (!seq.equals(other.seq)){
			return false;
		}
		return true;
	}

	public enum Fields {

		CODIGO_SUS("codigoSus"), 
		IND_SITUACAO_REGISTRO("indSituacaoRegistro")
		;

		private String fields;

		private Fields(final String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}

	}

}
