package br.gov.mec.aghu.model;

// Generated 08/07/2010 17:22:27 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * FatTiposAih generated by hbm2java
 */
@Entity
@SequenceGenerator(name="fatTahSq1", sequenceName="AGH.FAT_TAH_SQ1", allocationSize = 1)
@Table(name = "FAT_TIPOS_AIH", schema = "AGH")

public class FatTipoAih extends BaseEntitySeq<Byte> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2478089090659841252L;
	private Byte seq;
	private String descricao;
	private Short codigoSus;
	private DominioSituacao situacaoRegistro;
	private Integer version;

	public FatTipoAih() {
	}

	public FatTipoAih(Byte seq, String descricao) {
		this.seq = seq;
		this.descricao = descricao;
	}

	public FatTipoAih(Byte seq, String descricao, Short codigoSus,
			DominioSituacao situacaoRegistro) {
		this.seq = seq;
		this.descricao = descricao;
		this.codigoSus = codigoSus;
		this.situacaoRegistro = situacaoRegistro;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fatTahSq1")
	@Column(name = "SEQ", nullable = false, precision = 2, scale = 0)
	public Byte getSeq() {
		return this.seq;
	}

	public void setSeq(Byte seq) {
		this.seq = seq;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 50)
	@Length(max = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "CODIGO_SUS", precision = 1, scale = 0)
	public Short getCodigoSus() {
		return this.codigoSus;
	}

	public void setCodigoSus(Short codigoSus) {
		this.codigoSus = codigoSus;
	}

	@Column(name = "IND_SITUACAO_REGISTRO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getSituacaoRegistro() {
		return this.situacaoRegistro;
	}

	public void setSituacaoRegistro(DominioSituacao situacaoRegistro) {
		this.situacaoRegistro = situacaoRegistro;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seq == null) ? 0 : seq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
		if (obj == null){
			return false;
		}
		if (getClass() != obj.getClass()){
			return false;
		}
		FatTipoAih other = (FatTipoAih) obj;
		if (seq == null) {
			if (other.seq != null){
				return false;
			}
		} else if (!seq.equals(other.seq)){
			return false;
		}
		return true;
	}

	public enum Fields {
		
		SEQ("seq"),
		CODIGO_SUS("codigoSus"),
		DESCRICAO("descricao"),
		SITUACAO_REGISTRO("situacaoRegistro");	

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}

}
