package br.gov.mec.aghu.model;

// Generated 15/03/2011 13:46:58 by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * FatValoresContaHospitalar generated by hbm2java
 */
@Entity
@Table(name = "FAT_VALORES_CONTA_HOSPITALAR", schema = "AGH")
public class FatValorContaHospitalar extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2173611108259609744L;
	private Integer cthSeq;
	private FatContasHospitalares contaHospitalar;
	private BigDecimal valorShOpm;
	private BigDecimal valorSpOpm;
	private BigDecimal valorSadtOpm;
	private BigDecimal valorShUti;
	private BigDecimal valorSpUti;
	private BigDecimal valorSadtUti;
	private BigDecimal valorShUtie;
	private BigDecimal valorSpUtie;
	private BigDecimal valorSadtUtie;
	private BigDecimal valorShAcomp;
	private BigDecimal valorSpAcomp;
	private BigDecimal valorSadtAcomp;
	private BigDecimal valorShRn;
	private BigDecimal valorSpRn;
	private BigDecimal valorSadtRn;
	private BigDecimal valorShHemat;
	private BigDecimal valorSpHemat;
	private BigDecimal valorSadtHemat;
	private BigDecimal valorShTransp;
	private BigDecimal valorSpTransp;
	private BigDecimal valorSadtTransp;
	private BigDecimal valorProcOpm;
	private Integer version;

	public FatValorContaHospitalar() {
	}

	public FatValorContaHospitalar(FatContasHospitalares contaHospitalar, BigDecimal valorShOpm,
			BigDecimal valorSpOpm, BigDecimal valorSadtOpm,
			BigDecimal valorShUti, BigDecimal valorSpUti,
			BigDecimal valorSadtUti, BigDecimal valorShUtie,
			BigDecimal valorSpUtie, BigDecimal valorSadtUtie,
			BigDecimal valorShAcomp, BigDecimal valorSpAcomp,
			BigDecimal valorSadtAcomp, BigDecimal valorShRn,
			BigDecimal valorSpRn, BigDecimal valorSadtRn,
			BigDecimal valorShHemat, BigDecimal valorSpHemat,
			BigDecimal valorSadtHemat, BigDecimal valorShTransp,
			BigDecimal valorSpTransp, BigDecimal valorSadtTransp,
			BigDecimal valorProcOpm) {
		this.contaHospitalar = contaHospitalar;
		this.valorShOpm = valorShOpm;
		this.valorSpOpm = valorSpOpm;
		this.valorSadtOpm = valorSadtOpm;
		this.valorShUti = valorShUti;
		this.valorSpUti = valorSpUti;
		this.valorSadtUti = valorSadtUti;
		this.valorShUtie = valorShUtie;
		this.valorSpUtie = valorSpUtie;
		this.valorSadtUtie = valorSadtUtie;
		this.valorShAcomp = valorShAcomp;
		this.valorSpAcomp = valorSpAcomp;
		this.valorSadtAcomp = valorSadtAcomp;
		this.valorShRn = valorShRn;
		this.valorSpRn = valorSpRn;
		this.valorSadtRn = valorSadtRn;
		this.valorShHemat = valorShHemat;
		this.valorSpHemat = valorSpHemat;
		this.valorSadtHemat = valorSadtHemat;
		this.valorShTransp = valorShTransp;
		this.valorSpTransp = valorSpTransp;
		this.valorSadtTransp = valorSadtTransp;
		this.valorProcOpm = valorProcOpm;
	}

	@Id
	@Column(name = "CTH_SEQ", unique = true, nullable = false, precision = 8, scale = 0)
	public Integer getCthSeq() {
		return this.cthSeq;
	}

	public void setCthSeq(Integer cthSeq) {
		this.cthSeq = cthSeq;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public FatContasHospitalares getContaHospitalar() {
		return contaHospitalar;
	}

	public void setContaHospitalar(FatContasHospitalares contaHospitalar) {
		this.contaHospitalar = contaHospitalar;
	}

	@Column(name = "VALOR_SH_OPM", nullable = false, precision = 14)
	public BigDecimal getValorShOpm() {
		return this.valorShOpm;
	}

	public void setValorShOpm(BigDecimal valorShOpm) {
		this.valorShOpm = valorShOpm;
	}

	@Column(name = "VALOR_SP_OPM", nullable = false, precision = 14)
	public BigDecimal getValorSpOpm() {
		return this.valorSpOpm;
	}

	public void setValorSpOpm(BigDecimal valorSpOpm) {
		this.valorSpOpm = valorSpOpm;
	}

	@Column(name = "VALOR_SADT_OPM", nullable = false, precision = 14)
	public BigDecimal getValorSadtOpm() {
		return this.valorSadtOpm;
	}

	public void setValorSadtOpm(BigDecimal valorSadtOpm) {
		this.valorSadtOpm = valorSadtOpm;
	}

	@Column(name = "VALOR_SH_UTI", nullable = false, precision = 14)
	public BigDecimal getValorShUti() {
		return this.valorShUti;
	}

	public void setValorShUti(BigDecimal valorShUti) {
		this.valorShUti = valorShUti;
	}

	@Column(name = "VALOR_SP_UTI", nullable = false, precision = 14)
	public BigDecimal getValorSpUti() {
		return this.valorSpUti;
	}

	public void setValorSpUti(BigDecimal valorSpUti) {
		this.valorSpUti = valorSpUti;
	}

	@Column(name = "VALOR_SADT_UTI", nullable = false, precision = 14)
	public BigDecimal getValorSadtUti() {
		return this.valorSadtUti;
	}

	public void setValorSadtUti(BigDecimal valorSadtUti) {
		this.valorSadtUti = valorSadtUti;
	}

	@Column(name = "VALOR_SH_UTIE", nullable = false, precision = 14)
	public BigDecimal getValorShUtie() {
		return this.valorShUtie;
	}

	public void setValorShUtie(BigDecimal valorShUtie) {
		this.valorShUtie = valorShUtie;
	}

	@Column(name = "VALOR_SP_UTIE", nullable = false, precision = 14)
	public BigDecimal getValorSpUtie() {
		return this.valorSpUtie;
	}

	public void setValorSpUtie(BigDecimal valorSpUtie) {
		this.valorSpUtie = valorSpUtie;
	}

	@Column(name = "VALOR_SADT_UTIE", nullable = false, precision = 14)
	public BigDecimal getValorSadtUtie() {
		return this.valorSadtUtie;
	}

	public void setValorSadtUtie(BigDecimal valorSadtUtie) {
		this.valorSadtUtie = valorSadtUtie;
	}

	@Column(name = "VALOR_SH_ACOMP", nullable = false, precision = 14)
	public BigDecimal getValorShAcomp() {
		return this.valorShAcomp;
	}

	public void setValorShAcomp(BigDecimal valorShAcomp) {
		this.valorShAcomp = valorShAcomp;
	}

	@Column(name = "VALOR_SP_ACOMP", nullable = false, precision = 14)
	public BigDecimal getValorSpAcomp() {
		return this.valorSpAcomp;
	}

	public void setValorSpAcomp(BigDecimal valorSpAcomp) {
		this.valorSpAcomp = valorSpAcomp;
	}

	@Column(name = "VALOR_SADT_ACOMP", nullable = false, precision = 14)
	public BigDecimal getValorSadtAcomp() {
		return this.valorSadtAcomp;
	}

	public void setValorSadtAcomp(BigDecimal valorSadtAcomp) {
		this.valorSadtAcomp = valorSadtAcomp;
	}

	@Column(name = "VALOR_SH_RN", nullable = false, precision = 14)
	public BigDecimal getValorShRn() {
		return this.valorShRn;
	}

	public void setValorShRn(BigDecimal valorShRn) {
		this.valorShRn = valorShRn;
	}

	@Column(name = "VALOR_SP_RN", nullable = false, precision = 14)
	public BigDecimal getValorSpRn() {
		return this.valorSpRn;
	}

	public void setValorSpRn(BigDecimal valorSpRn) {
		this.valorSpRn = valorSpRn;
	}

	@Column(name = "VALOR_SADT_RN", nullable = false, precision = 14)
	public BigDecimal getValorSadtRn() {
		return this.valorSadtRn;
	}

	public void setValorSadtRn(BigDecimal valorSadtRn) {
		this.valorSadtRn = valorSadtRn;
	}

	@Column(name = "VALOR_SH_HEMAT", nullable = false, precision = 14)
	public BigDecimal getValorShHemat() {
		return this.valorShHemat;
	}

	public void setValorShHemat(BigDecimal valorShHemat) {
		this.valorShHemat = valorShHemat;
	}

	@Column(name = "VALOR_SP_HEMAT", nullable = false, precision = 14)
	public BigDecimal getValorSpHemat() {
		return this.valorSpHemat;
	}

	public void setValorSpHemat(BigDecimal valorSpHemat) {
		this.valorSpHemat = valorSpHemat;
	}

	@Column(name = "VALOR_SADT_HEMAT", nullable = false, precision = 14)
	public BigDecimal getValorSadtHemat() {
		return this.valorSadtHemat;
	}

	public void setValorSadtHemat(BigDecimal valorSadtHemat) {
		this.valorSadtHemat = valorSadtHemat;
	}

	@Column(name = "VALOR_SH_TRANSP", nullable = false, precision = 14)
	public BigDecimal getValorShTransp() {
		return this.valorShTransp;
	}

	public void setValorShTransp(BigDecimal valorShTransp) {
		this.valorShTransp = valorShTransp;
	}

	@Column(name = "VALOR_SP_TRANSP", nullable = false, precision = 14)
	public BigDecimal getValorSpTransp() {
		return this.valorSpTransp;
	}

	public void setValorSpTransp(BigDecimal valorSpTransp) {
		this.valorSpTransp = valorSpTransp;
	}

	@Column(name = "VALOR_SADT_TRANSP", nullable = false, precision = 14)
	public BigDecimal getValorSadtTransp() {
		return this.valorSadtTransp;
	}

	public void setValorSadtTransp(BigDecimal valorSadtTransp) {
		this.valorSadtTransp = valorSadtTransp;
	}

	@Column(name = "VALOR_PROC_OPM", nullable = false, precision = 14)
	public BigDecimal getValorProcOpm() {
		return this.valorProcOpm;
	}

	public void setValorProcOpm(BigDecimal valorProcOpm) {
		this.valorProcOpm = valorProcOpm;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cthSeq == null) ? 0 : cthSeq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
		if (obj == null){
			return false;
		}
		if (getClass() != obj.getClass()){
			return false;
		}
		FatValorContaHospitalar other = (FatValorContaHospitalar) obj;
		if (cthSeq == null) {
			if (other.cthSeq != null){
				return false;
			}
		} else if (!cthSeq.equals(other.cthSeq)){
			return false;
		}
		return true;
	}

	public enum Fields {
			
		 CTH_SEQ("cthSeq")
		,CONTA_HOSPITALAR("contaHospitalar")
		,VALOR_SH_UTI("valorShUti")
		,VALOR_SP_UTI("valorSpUti")
		,VALOR_SADT_UTI("valorSadtUti")
		,VALOR_SH_ACOMP("valorShAcomp")
		,VALOR_SP_ACOMP("valorSpAcomp")
		,VALOR_SADT_ACOMP("valorSadtAcomp")
		,VALOR_SADT_UTIE("valorSadtUtie")
		,VALOR_SADT_RN("valorSadtRn")
		,VALOR_SADT_TRANSP("valorSadtTransp");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
		
	}
	 
 @Transient public Integer getSeq(){ return this.getCthSeq();} 
 public void setSeq(Integer seq){ this.setCthSeq(seq);}
}
