package br.gov.mec.aghu.model;

// Generated 04/02/2010 16:45:57 by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioArea;
import br.gov.mec.aghu.dominio.DominioSimNao;
import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.dominio.DominioTipoDespesa;
import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * FccCentroCustosJn generated by hbm2java
 */
@SuppressWarnings({"PMD.AghuUsoIndevidoDaEnumDominioSimNaoEntity"})
@Entity
@Table(name = "FCC_CENTRO_CUSTOS_JN", schema = "AGH")
@SequenceGenerator(name = "fccCctJnSeq", sequenceName = "AGH.FCC_CCT_JN_SEQ", allocationSize = 1)

@Immutable
public class FccCentroCustosJn extends BaseJournal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7169294359030994880L;
	private Integer codigo;
	private String descricao;
	private Short gccCodigo;
	private DominioSimNao indAbsentSmo;
	private FccCentroCustos centroCusto;
	private DominioSituacao indSituacao;
	private DominioSimNao indSolicitaCompra;
	private DominioSimNao indAvaliacaoTecnica;
	private DominioSimNao indAprovaSolicitacao;
	private String ccustRh;
	private Short nroVagas;
	private RapServidores servidor;
	private Integer cotaHoraExtra;
	private DominioArea indArea;
	private String nomeReduzido;
	private String organogramaCf;
	private String registroFuncionamento;
	private String logradouro;
	private Integer nroLogradouro;
	private String complLogradouro;
	private Integer cep;
	private String bairro;
	private AipCidades cidade;
	private Short dddFone;
	private Long fone;
	private Short dddFax;
	private Long fax;
	private String caixaPostal;
	private String email;
	private String homePage;
	private DominioTipoDespesa indTipoDespesa;
	private Short peso;
	private BigDecimal area;
	private FcuGrupoCentroCustos fcuGrupoCentroCusto;
	private String funcaoCracha;

	public FccCentroCustosJn() {
	}
	
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fccCctJnSeq")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}

	@Column(name = "CODIGO", nullable = false, precision = 6, scale = 0)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRICAO", length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "GCC_CODIGO", precision = 3, scale = 0)
	public Short getGccCodigo() {
		return gccCodigo;
	}

	public void setGccCodigo(Short gccCodigo) {
		this.gccCodigo = gccCodigo;
	}

	@Column(name = "IND_ABSENT_SMO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getIndAbsentSmo() {
		return this.indAbsentSmo;
	}

	public void setIndAbsentSmo(DominioSimNao indAbsentSmo) {
		this.indAbsentSmo = indAbsentSmo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CCT_SUPERIOR")
	public FccCentroCustos getCentroCusto() {
		return this.centroCusto;
	}

	public void setCentroCusto(FccCentroCustos centroCusto) {
		this.centroCusto = centroCusto;
	}

	@Column(name = "IND_SITUACAO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "IND_SOLICITA_COMPRA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getIndSolicitaCompra() {
		return this.indSolicitaCompra;
	}

	public void setIndSolicitaCompra(DominioSimNao indSolicitaCompra) {
		this.indSolicitaCompra = indSolicitaCompra;
	}

	@Column(name = "IND_AVALIACAO_TECNICA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getIndAvaliacaoTecnica() {
		return this.indAvaliacaoTecnica;
	}

	public void setIndAvaliacaoTecnica(DominioSimNao indAvaliacaoTecnica) {
		this.indAvaliacaoTecnica = indAvaliacaoTecnica;
	}

	@Column(name = "IND_APROVA_SOLICITACAO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getIndAprovaSolicitacao() {
		return this.indAprovaSolicitacao;
	}

	public void setIndAprovaSolicitacao(DominioSimNao indAprovaSolicitacao) {
		this.indAprovaSolicitacao = indAprovaSolicitacao;
	}

	@Column(name = "CCUST_RH", length = 12)
	@Length(max = 12)
	public String getCcustRh() {
		return this.ccustRh;
	}

	public void setCcustRh(String ccustRh) {
		this.ccustRh = ccustRh;
	}

	@Column(name = "NRO_VAGAS", precision = 3, scale = 0)
	public Short getNroVagas() {
		return this.nroVagas;
	}

	public void setNroVagas(Short nroVagas) {
		this.nroVagas = nroVagas;
	}

	@JoinColumns({
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO") })
	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Column(name = "COTA_HORA_EXTRA", precision = 5, scale = 0)
	public Integer getCotaHoraExtra() {
		return this.cotaHoraExtra;
	}

	public void setCotaHoraExtra(Integer cotaHoraExtra) {
		this.cotaHoraExtra = cotaHoraExtra;
	}

	@Column(name = "IND_AREA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioArea getIndArea() {
		return this.indArea;
	}

	public void setIndArea(DominioArea indArea) {
		this.indArea = indArea;
	}

	@Column(name = "NOME_REDUZIDO", length = 15)
	@Length(max = 15)
	public String getNomeReduzido() {
		return this.nomeReduzido;
	}

	public void setNomeReduzido(String nomeReduzido) {
		this.nomeReduzido = nomeReduzido;
	}

	@Column(name = "ORGANOGRAMA_CF", length = 25)
	@Length(max = 25)
	public String getOrganogramaCf() {
		return this.organogramaCf;
	}

	public void setOrganogramaCf(String organogramaCf) {
		this.organogramaCf = organogramaCf;
	}

	@Column(name = "REGISTRO_FUNCIONAMENTO", length = 20)
	@Length(max = 20)
	public String getRegistroFuncionamento() {
		return this.registroFuncionamento;
	}

	public void setRegistroFuncionamento(String registroFuncionamento) {
		this.registroFuncionamento = registroFuncionamento;
	}

	@Column(name = "LOGRADOURO", length = 60)
	@Length(max = 60)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "NRO_LOGRADOURO", precision = 5, scale = 0)
	public Integer getNroLogradouro() {
		return this.nroLogradouro;
	}

	public void setNroLogradouro(Integer nroLogradouro) {
		this.nroLogradouro = nroLogradouro;
	}

	@Column(name = "COMPL_LOGRADOURO", length = 20)
	@Length(max = 20)
	public String getComplLogradouro() {
		return this.complLogradouro;
	}

	public void setComplLogradouro(String complLogradouro) {
		this.complLogradouro = complLogradouro;
	}

	@Column(name = "CEP", precision = 8, scale = 0)
	public Integer getCep() {
		return this.cep;
	}

	public void setCep(Integer cep) {
		this.cep = cep;
	}

	@Column(name = "BAIRRO", length = 20)
	@Length(max = 20)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDD_CODIGO", referencedColumnName = "CODIGO")
	public AipCidades getCidade() {
		return this.cidade;
	}

	public void setCidade(AipCidades cidade) {
		this.cidade = cidade;
	}

	@Column(name = "DDD_FONE", precision = 4, scale = 0)
	public Short getDddFone() {
		return this.dddFone;
	}

	public void setDddFone(Short dddFone) {
		this.dddFone = dddFone;
	}

	@Column(name = "FONE", precision = 10, scale = 0)
	public Long getFone() {
		return this.fone;
	}

	public void setFone(Long fone) {
		this.fone = fone;
	}

	@Column(name = "DDD_FAX", precision = 4, scale = 0)
	public Short getDddFax() {
		return this.dddFax;
	}

	public void setDddFax(Short dddFax) {
		this.dddFax = dddFax;
	}

	@Column(name = "FAX", precision = 10, scale = 0)
	public Long getFax() {
		return this.fax;
	}

	public void setFax(Long fax) {
		this.fax = fax;
	}

	@Column(name = "CAIXA_POSTAL", length = 10)
	@Length(max = 10)
	public String getCaixaPostal() {
		return this.caixaPostal;
	}

	public void setCaixaPostal(String caixaPostal) {
		this.caixaPostal = caixaPostal;
	}

	@Column(name = "EMAIL", length = 50)
	@Length(max = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "HOME_PAGE", length = 50)
	@Length(max = 50)
	public String getHomePage() {
		return this.homePage;
	}

	public void setHomePage(String homePage) {
		this.homePage = homePage;
	}

	@Column(name = "IND_TIPO_DESPESA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioTipoDespesa getIndTipoDespesa() {
		return this.indTipoDespesa;
	}

	public void setIndTipoDespesa(DominioTipoDespesa indTipoDespesa) {
		this.indTipoDespesa = indTipoDespesa;
	}

	@Column(name = "PESO", precision = 3, scale = 0)
	public Short getPeso() {
		return this.peso;
	}

	public void setPeso(Short peso) {
		this.peso = peso;
	}

	@Column(name = "AREA", precision = 7)
	public BigDecimal getArea() {
		return this.area;
	}

	public void setArea(BigDecimal area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GCC_SEQ", referencedColumnName = "SEQ")
	public FcuGrupoCentroCustos getFcuGrupoCentroCusto() {
		return this.fcuGrupoCentroCusto;
	}

	public void setFcuGrupoCentroCusto(FcuGrupoCentroCustos fcuGrupoCentroCusto) {
		this.fcuGrupoCentroCusto = fcuGrupoCentroCusto;
	}

	@Column(name = "FUNCAO_CRACHA", length = 25)
	@Length(max = 25)
	public String getFuncaoCracha() {
		return this.funcaoCracha;
	}

	public void setFuncaoCracha(String funcaoCracha) {
		this.funcaoCracha = funcaoCracha;
	}
	
	public enum Fields {
		CODIGO("codigo");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}

	
}
