package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


/**
 * FcpCompetenciaSistemaSiafi generated by hbm2java
 */
@Entity
@Table(name = "FCP_COMPETENCIAS_SISTEMA_SIAFI", schema = "AGH")
public class FcpCompetenciaSistemaSiafi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9044623547532816180L;
	private Date dtCompetencia;
	private Integer version;
	private Date dtInicio;
	private Date dtFim;
	private Boolean encerrado;
	private Date dtLimiteEntrada;

	public FcpCompetenciaSistemaSiafi() {
	}

	public FcpCompetenciaSistemaSiafi(Date dtCompetencia, Date dtInicio, Date dtFim, Boolean encerrado, Date dtLimiteEntrada) {
		this.dtCompetencia = dtCompetencia;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
		this.encerrado = encerrado;
		this.dtLimiteEntrada = dtLimiteEntrada;
	}

	@Id
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_COMPETENCIA", unique = true, nullable = false, length = 29)
	public Date getDtCompetencia() {
		return this.dtCompetencia;
	}

	public void setDtCompetencia(Date dtCompetencia) {
		this.dtCompetencia = dtCompetencia;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO", nullable = false, length = 29)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM", nullable = false, length = 29)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Column(name = "IND_ENCERRADO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getEncerrado() {
		return this.encerrado;
	}

	public void setEncerrado(Boolean encerrado) {
		this.encerrado = encerrado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_LIMITE_ENTRADA", nullable = false, length = 29)
	public Date getDtLimiteEntrada() {
		return this.dtLimiteEntrada;
	}

	public void setDtLimiteEntrada(Date dtLimiteEntrada) {
		this.dtLimiteEntrada = dtLimiteEntrada;
	}

	public enum Fields {

		DT_COMPETENCIA("dtCompetencia"),
		VERSION("version"),
		DT_INICIO("dtInicio"),
		DT_FIM("dtFim"),
		ENCERRADO("encerrado"),
		DT_LIMITE_ENTRADA("dtLimiteEntrada");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getDtCompetencia() == null) ? 0 : getDtCompetencia().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FcpCompetenciaSistemaSiafi)) {
			return false;
		}
		FcpCompetenciaSistemaSiafi other = (FcpCompetenciaSistemaSiafi) obj;
		if (getDtCompetencia() == null) {
			if (other.getDtCompetencia() != null) {
				return false;
			}
		} else if (!getDtCompetencia().equals(other.getDtCompetencia())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
