package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * FcuAtividade generated by hbm2java
 */
@Entity
@SequenceGenerator(name="fcuAtiSq1", sequenceName="AGH.FCU_ATI_SQ1", allocationSize = 1)
@Table(name = "FCU_ATIVIDADES", schema = "AGH")
public class FcuAtividade extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -839206331388295168L;
	private Short seq;
	private Integer version;
	private FcuGrupoAtividade fcuGrupoAtividade;
	private String indSituacao;
	private Date criadoEm;
	private String descricao;
	private Short drcSeq;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Set<FcuAtividadeEspecif> fcuAtividadeEspecifes = new HashSet<FcuAtividadeEspecif>(0);
	private Set<FcuProducaoPaciente> fcuProducaoPacientees = new HashSet<FcuProducaoPaciente>(0);

	public FcuAtividade() {
	}

	public FcuAtividade(Short seq, FcuGrupoAtividade fcuGrupoAtividade, Short drcSeq, Integer serMatricula, Short serVinCodigo) {
		this.seq = seq;
		this.fcuGrupoAtividade = fcuGrupoAtividade;
		this.drcSeq = drcSeq;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
	}

	public FcuAtividade(Short seq, FcuGrupoAtividade fcuGrupoAtividade, String indSituacao, Date criadoEm, String descricao,
			Short drcSeq, Integer serMatricula, Short serVinCodigo, Set<FcuAtividadeEspecif> fcuAtividadeEspecifes,
			Set<FcuProducaoPaciente> fcuProducaoPacientees) {
		this.seq = seq;
		this.fcuGrupoAtividade = fcuGrupoAtividade;
		this.indSituacao = indSituacao;
		this.criadoEm = criadoEm;
		this.descricao = descricao;
		this.drcSeq = drcSeq;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.fcuAtividadeEspecifes = fcuAtividadeEspecifes;
		this.fcuProducaoPacientees = fcuProducaoPacientees;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fcuAtiSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GAT_SEQ", nullable = false)
	public FcuGrupoAtividade getFcuGrupoAtividade() {
		return this.fcuGrupoAtividade;
	}

	public void setFcuGrupoAtividade(FcuGrupoAtividade fcuGrupoAtividade) {
		this.fcuGrupoAtividade = fcuGrupoAtividade;
	}

	@Column(name = "IND_SITUACAO", length = 1)
	@Length(max = 1)
	public String getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(String indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "DESCRICAO", length = 45)
	@Length(max = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "DRC_SEQ", nullable = false)
	public Short getDrcSeq() {
		return this.drcSeq;
	}

	public void setDrcSeq(Short drcSeq) {
		this.drcSeq = drcSeq;
	}

	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcuAtividade")
	public Set<FcuAtividadeEspecif> getFcuAtividadeEspecifes() {
		return this.fcuAtividadeEspecifes;
	}

	public void setFcuAtividadeEspecifes(Set<FcuAtividadeEspecif> fcuAtividadeEspecifes) {
		this.fcuAtividadeEspecifes = fcuAtividadeEspecifes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcuAtividade")
	public Set<FcuProducaoPaciente> getFcuProducaoPacientees() {
		return this.fcuProducaoPacientees;
	}

	public void setFcuProducaoPacientees(Set<FcuProducaoPaciente> fcuProducaoPacientees) {
		this.fcuProducaoPacientees = fcuProducaoPacientees;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		FCU_GRUPO_ATIVIDADES("fcuGrupoAtividade"),
		IND_SITUACAO("indSituacao"),
		CRIADO_EM("criadoEm"),
		DESCRICAO("descricao"),
		DRC_SEQ("drcSeq"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		FCU_ATIVIDADE_ESPECIFES("fcuAtividadeEspecifes"),
		FCU_PRODUCAO_PACIENTEES("fcuProducaoPacientees");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FcuAtividade)) {
			return false;
		}
		FcuAtividade other = (FcuAtividade) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
