package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * FcuCustoDireto generated by hbm2java
 */
@Entity
@SequenceGenerator(name="fcuCdrSq1", sequenceName="AGH.FCU_CDR_SQ1", allocationSize = 1)
@Table(name = "FCU_CUSTO_DIRETOS", schema = "AGH")
public class FcuCustoDireto extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2091759970973290561L;
	private Short seq;
	private Integer version;
	private RapServidores rapServidores;
	private String descricao;
	private String situacao;
	private Date criadoEm;
	private Set<FcuComposicaoCustoDireto> fcuComposicaoCustoDiretoes = new HashSet<FcuComposicaoCustoDireto>(0);

	public FcuCustoDireto() {
	}

	public FcuCustoDireto(Short seq, RapServidores rapServidores) {
		this.seq = seq;
		this.rapServidores = rapServidores;
	}

	public FcuCustoDireto(Short seq, RapServidores rapServidores, String descricao, String situacao, Date criadoEm,
			Set<FcuComposicaoCustoDireto> fcuComposicaoCustoDiretoes) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.descricao = descricao;
		this.situacao = situacao;
		this.criadoEm = criadoEm;
		this.fcuComposicaoCustoDiretoes = fcuComposicaoCustoDiretoes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "fcuCdrSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@Column(name = "DESCRICAO", length = 100)
	@Length(max = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "SITUACAO", length = 1)
	@Length(max = 1)
	public String getSituacao() {
		return this.situacao;
	}

	public void setSituacao(String situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fcuCustoDireto")
	public Set<FcuComposicaoCustoDireto> getFcuComposicaoCustoDiretoes() {
		return this.fcuComposicaoCustoDiretoes;
	}

	public void setFcuComposicaoCustoDiretoes(Set<FcuComposicaoCustoDireto> fcuComposicaoCustoDiretoes) {
		this.fcuComposicaoCustoDiretoes = fcuComposicaoCustoDiretoes;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		DESCRICAO("descricao"),
		SITUACAO("situacao"),
		CRIADO_EM("criadoEm"),
		FCU_COMPOSICAO_CUSTO_DIRETOES("fcuComposicaoCustoDiretoes");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FcuCustoDireto)) {
			return false;
		}
		FcuCustoDireto other = (FcuCustoDireto) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
