package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * FcuGatUnidExecutoraId generated by hbm2java
 */
@Embeddable
public class FcuGatUnidExecutoraId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -507126289489603050L;
	private Short unfSeq;
	private Short gatSeq;

	public FcuGatUnidExecutoraId() {
	}

	public FcuGatUnidExecutoraId(Short unfSeq, Short gatSeq) {
		this.unfSeq = unfSeq;
		this.gatSeq = gatSeq;
	}

	@Column(name = "UNF_SEQ", nullable = false)
	public Short getUnfSeq() {
		return this.unfSeq;
	}

	public void setUnfSeq(Short unfSeq) {
		this.unfSeq = unfSeq;
	}

	@Column(name = "GAT_SEQ", nullable = false)
	public Short getGatSeq() {
		return this.gatSeq;
	}

	public void setGatSeq(Short gatSeq) {
		this.gatSeq = gatSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getUnfSeq());
		umHashCodeBuilder.append(this.getGatSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FcuGatUnidExecutoraId)) {
			return false;
		}
		FcuGatUnidExecutoraId other = (FcuGatUnidExecutoraId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getUnfSeq(), other.getUnfSeq());
		umEqualsBuilder.append(this.getGatSeq(), other.getGatSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
