package br.gov.mec.aghu.model;

// Generated 31/10/2011 19:51:48 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntityCodigo;

/**
 * FsoGruposNaturezaDespesa generated by hbm2java
 */
@Entity
@Table(name = "FSO_GRUPOS_NATUREZA_DESPESA", schema = "AGH")
public class FsoGrupoNaturezaDespesa extends BaseEntityCodigo<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -59230497459099168L;
	private Integer codigo;
	private String descricao;
	private DominioSituacao indSituacao;
	private Integer version;

	public FsoGrupoNaturezaDespesa() {
	}

	public FsoGrupoNaturezaDespesa(Integer codigo, String descricao,
			DominioSituacao indSituacao) {
		this.codigo = codigo;
		this.descricao = descricao;
		this.indSituacao = indSituacao;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, precision = 6, scale = 0)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}
	
	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public enum Fields {
		CODIGO("codigo"),
		DESCRICAO("descricao"),
		IND_SITUACAO("indSituacao");

		private String field;
		
		private Fields(String field) {
			this.field = field;
		}
		
		@Override
		public String toString() {
			return this.field;
		}
	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getCodigo() == null) ? 0 : getCodigo().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FsoGrupoNaturezaDespesa)) {
			return false;
		}
		FsoGrupoNaturezaDespesa other = (FsoGrupoNaturezaDespesa) obj;
		if (getCodigo() == null) {
			if (other.getCodigo() != null) {
				return false;
			}
		} else if (!getCodigo().equals(other.getCodigo())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
