package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * FsoProgTrabalhoXFonteRec generated by hbm2java
 */
@Entity
@Table(name = "FSO_PROG_TRABALHO_X_FONTE_REC", schema = "AGH")
public class FsoProgTrabalhoXFonteRec extends BaseEntityId<FsoProgTrabalhoXFonteRecId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1696879829015436256L;
	private FsoProgTrabalhoXFonteRecId id;
	private Integer version;
	private FsoProgramaTrabalho fsoProgramaTrabalho;
	private FsoFontesRecursoFinanc fsoFontesRecursoFinanc;
	private FsoGrupoNaturezaDespesa fsoGrupoNaturezaDespesa;
	private FsoConveniosFinanceiro fsoConveniosFinanceiro;
	private Short esferaOrcamentaria;
	private String indPreferencial;
	private String indPlanoInterno;
	private String indAcaoOrcamentaria;
	private String indEnsino;
	private String nivelEtapaEnsino;
	private String unidGestoraResponsavel;

	public FsoProgTrabalhoXFonteRec() {
	}

	public FsoProgTrabalhoXFonteRec(FsoProgTrabalhoXFonteRecId id, FsoProgramaTrabalho fsoProgramaTrabalho,
			FsoFontesRecursoFinanc fsoFontesRecursoFinanc, FsoGrupoNaturezaDespesa fsoGrupoNaturezaDespesa,
			FsoConveniosFinanceiro fsoConveniosFinanceiro) {
		this.id = id;
		this.fsoProgramaTrabalho = fsoProgramaTrabalho;
		this.fsoFontesRecursoFinanc = fsoFontesRecursoFinanc;
		this.fsoGrupoNaturezaDespesa = fsoGrupoNaturezaDespesa;
		this.fsoConveniosFinanceiro = fsoConveniosFinanceiro;
	}

	public FsoProgTrabalhoXFonteRec(FsoProgTrabalhoXFonteRecId id, FsoProgramaTrabalho fsoProgramaTrabalho,
			FsoFontesRecursoFinanc fsoFontesRecursoFinanc, FsoGrupoNaturezaDespesa fsoGrupoNaturezaDespesa,
			FsoConveniosFinanceiro fsoConveniosFinanceiro, Short esferaOrcamentaria, String indPreferencial, String indPlanoInterno,
			String indAcaoOrcamentaria, String indEnsino, String nivelEtapaEnsino, String unidGestoraResponsavel) {
		this.id = id;
		this.fsoProgramaTrabalho = fsoProgramaTrabalho;
		this.fsoFontesRecursoFinanc = fsoFontesRecursoFinanc;
		this.fsoGrupoNaturezaDespesa = fsoGrupoNaturezaDespesa;
		this.fsoConveniosFinanceiro = fsoConveniosFinanceiro;
		this.esferaOrcamentaria = esferaOrcamentaria;
		this.indPreferencial = indPreferencial;
		this.indPlanoInterno = indPlanoInterno;
		this.indAcaoOrcamentaria = indAcaoOrcamentaria;
		this.indEnsino = indEnsino;
		this.nivelEtapaEnsino = nivelEtapaEnsino;
		this.unidGestoraResponsavel = unidGestoraResponsavel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "frfCodigo", column = @Column(name = "FRF_CODIGO", nullable = false)),
			@AttributeOverride(name = "cvfCodigo", column = @Column(name = "CVF_CODIGO", nullable = false)),
			@AttributeOverride(name = "gndCodigo", column = @Column(name = "GND_CODIGO", nullable = false)),
			@AttributeOverride(name = "ptbCodigo", column = @Column(name = "PTB_CODIGO", nullable = false, precision = 131089, scale = 0)) })
	public FsoProgTrabalhoXFonteRecId getId() {
		return this.id;
	}

	public void setId(FsoProgTrabalhoXFonteRecId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTB_CODIGO", nullable = false, insertable = false, updatable = false)
	public FsoProgramaTrabalho getFsoProgramaTrabalho() {
		return this.fsoProgramaTrabalho;
	}

	public void setFsoProgramaTrabalho(FsoProgramaTrabalho fsoProgramaTrabalho) {
		this.fsoProgramaTrabalho = fsoProgramaTrabalho;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FRF_CODIGO", nullable = false, insertable = false, updatable = false)
	public FsoFontesRecursoFinanc getFsoFontesRecursoFinanc() {
		return this.fsoFontesRecursoFinanc;
	}

	public void setFsoFontesRecursoFinanc(FsoFontesRecursoFinanc fsoFontesRecursoFinanc) {
		this.fsoFontesRecursoFinanc = fsoFontesRecursoFinanc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GND_CODIGO", nullable = false, insertable = false, updatable = false)
	public FsoGrupoNaturezaDespesa getFsoGrupoNaturezaDespesa() {
		return this.fsoGrupoNaturezaDespesa;
	}

	public void setFsoGrupoNaturezaDespesa(FsoGrupoNaturezaDespesa fsoGrupoNaturezaDespesa) {
		this.fsoGrupoNaturezaDespesa = fsoGrupoNaturezaDespesa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CVF_CODIGO", nullable = false, insertable = false, updatable = false)
	public FsoConveniosFinanceiro getFsoConveniosFinanceiro() {
		return this.fsoConveniosFinanceiro;
	}

	public void setFsoConveniosFinanceiro(FsoConveniosFinanceiro fsoConveniosFinanceiro) {
		this.fsoConveniosFinanceiro = fsoConveniosFinanceiro;
	}

	@Column(name = "ESFERA_ORCAMENTARIA")
	public Short getEsferaOrcamentaria() {
		return this.esferaOrcamentaria;
	}

	public void setEsferaOrcamentaria(Short esferaOrcamentaria) {
		this.esferaOrcamentaria = esferaOrcamentaria;
	}

	@Column(name = "IND_PREFERENCIAL", length = 1)
	@Length(max = 1)
	public String getIndPreferencial() {
		return this.indPreferencial;
	}

	public void setIndPreferencial(String indPreferencial) {
		this.indPreferencial = indPreferencial;
	}

	@Column(name = "IND_PLANO_INTERNO", length = 1)
	@Length(max = 1)
	public String getIndPlanoInterno() {
		return this.indPlanoInterno;
	}

	public void setIndPlanoInterno(String indPlanoInterno) {
		this.indPlanoInterno = indPlanoInterno;
	}

	@Column(name = "IND_ACAO_ORCAMENTARIA", length = 4)
	@Length(max = 4)
	public String getIndAcaoOrcamentaria() {
		return this.indAcaoOrcamentaria;
	}

	public void setIndAcaoOrcamentaria(String indAcaoOrcamentaria) {
		this.indAcaoOrcamentaria = indAcaoOrcamentaria;
	}

	@Column(name = "IND_ENSINO", length = 1)
	@Length(max = 1)
	public String getIndEnsino() {
		return this.indEnsino;
	}

	public void setIndEnsino(String indEnsino) {
		this.indEnsino = indEnsino;
	}

	@Column(name = "NIVEL_ETAPA_ENSINO", length = 1)
	@Length(max = 1)
	public String getNivelEtapaEnsino() {
		return this.nivelEtapaEnsino;
	}

	public void setNivelEtapaEnsino(String nivelEtapaEnsino) {
		this.nivelEtapaEnsino = nivelEtapaEnsino;
	}

	@Column(name = "UNID_GESTORA_RESPONSAVEL", length = 6)
	@Length(max = 6)
	public String getUnidGestoraResponsavel() {
		return this.unidGestoraResponsavel;
	}

	public void setUnidGestoraResponsavel(String unidGestoraResponsavel) {
		this.unidGestoraResponsavel = unidGestoraResponsavel;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		FSO_PROGRAMA_TRABALHO("fsoProgramaTrabalho"),
		FSO_FONTES_RECURSO_FINANC("fsoFontesRecursoFinanc"),
		FSO_GRUPO_NATUREZA_DESPESA("fsoGrupoNaturezaDespesa"),
		FSO_CONVENIOS_FINANCEIRO("fsoConveniosFinanceiro"),
		ESFERA_ORCAMENTARIA("esferaOrcamentaria"),
		IND_PREFERENCIAL("indPreferencial"),
		IND_PLANO_INTERNO("indPlanoInterno"),
		IND_ACAO_ORCAMENTARIA("indAcaoOrcamentaria"),
		IND_ENSINO("indEnsino"),
		NIVEL_ETAPA_ENSINO("nivelEtapaEnsino"),
		UNID_GESTORA_RESPONSAVEL("unidGestoraResponsavel");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FsoProgTrabalhoXFonteRec)) {
			return false;
		}
		FsoProgTrabalhoXFonteRec other = (FsoProgTrabalhoXFonteRec) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
