package br.gov.mec.aghu.model;

// Generated 01/12/2011 14:28:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * FsoPrevisoesOrcamentariasId generated by hbm2java
 */
@Embeddable
public class FsoPrevisaoOrcamentariaId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5890864134370851918L;

	private Date exoExercicio;
	private BigDecimal ptbCodigo;
	private Integer gndCodigo;
	private Short seqp;

	public FsoPrevisaoOrcamentariaId() {
	}

	public FsoPrevisaoOrcamentariaId(Date exoExercicio, BigDecimal ptbCodigo,
			Integer gndCodigo, Short seqp) {
		this.exoExercicio = exoExercicio;
		this.ptbCodigo = ptbCodigo;
		this.gndCodigo = gndCodigo;
		this.seqp = seqp;
	}

	@Column(name = "EXO_EXERCICIO", nullable = false, length = 7)
	public Date getExoExercicio() {
		return this.exoExercicio;
	}

	public void setExoExercicio(Date exoExercicio) {
		this.exoExercicio = exoExercicio;
	}

	@Column(name = "PTB_CODIGO", nullable = false, precision = 30, scale = 0)
	public BigDecimal getPtbCodigo() {
		return this.ptbCodigo;
	}

	public void setPtbCodigo(BigDecimal ptbCodigo) {
		this.ptbCodigo = ptbCodigo;
	}

	@Column(name = "GND_CODIGO", nullable = false, precision = 6, scale = 0)
	public Integer getGndCodigo() {
		return this.gndCodigo;
	}

	public void setGndCodigo(Integer gndCodigo) {
		this.gndCodigo = gndCodigo;
	}

	@Column(name = "SEQP", nullable = false, precision = 3, scale = 0)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getExoExercicio());
		umHashCodeBuilder.append(this.getGndCodigo());
		umHashCodeBuilder.append(this.getPtbCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FsoPrevisaoOrcamentariaId)) {
			return false;
		}
		FsoPrevisaoOrcamentariaId other = (FsoPrevisaoOrcamentariaId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getExoExercicio(), other.getExoExercicio());
		umEqualsBuilder.append(this.getGndCodigo(), other.getGndCodigo());
		umEqualsBuilder.append(this.getPtbCodigo(), other.getPtbCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
