package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * FsoProgTrabalhoXFonteRecId generated by hbm2java
 */
@Embeddable
public class FsoProgTrabalhoXFonteRecId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2932074084007511735L;
	private Long frfCodigo;
	private Short cvfCodigo;
	private Integer gndCodigo;
	private BigDecimal ptbCodigo;

	public FsoProgTrabalhoXFonteRecId() {
	}

	public FsoProgTrabalhoXFonteRecId(Long frfCodigo, Short cvfCodigo, Integer gndCodigo, BigDecimal ptbCodigo) {
		this.frfCodigo = frfCodigo;
		this.cvfCodigo = cvfCodigo;
		this.gndCodigo = gndCodigo;
		this.ptbCodigo = ptbCodigo;
	}

	@Column(name = "FRF_CODIGO", nullable = false)
	public Long getFrfCodigo() {
		return this.frfCodigo;
	}

	public void setFrfCodigo(Long frfCodigo) {
		this.frfCodigo = frfCodigo;
	}

	@Column(name = "CVF_CODIGO", nullable = false)
	public Short getCvfCodigo() {
		return this.cvfCodigo;
	}

	public void setCvfCodigo(Short cvfCodigo) {
		this.cvfCodigo = cvfCodigo;
	}

	@Column(name = "GND_CODIGO", nullable = false)
	public Integer getGndCodigo() {
		return this.gndCodigo;
	}

	public void setGndCodigo(Integer gndCodigo) {
		this.gndCodigo = gndCodigo;
	}

	@Column(name = "PTB_CODIGO", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPtbCodigo() {
		return this.ptbCodigo;
	}

	public void setPtbCodigo(BigDecimal ptbCodigo) {
		this.ptbCodigo = ptbCodigo;
	}






	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getCvfCodigo());
		umHashCodeBuilder.append(this.getGndCodigo());
		umHashCodeBuilder.append(this.getFrfCodigo());
		umHashCodeBuilder.append(this.getPtbCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FsoProgTrabalhoXFonteRecId)) {
			return false;
		}
		FsoProgTrabalhoXFonteRecId other = (FsoProgTrabalhoXFonteRecId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getCvfCodigo(), other.getCvfCodigo());
		umEqualsBuilder.append(this.getGndCodigo(), other.getGndCodigo());
		umEqualsBuilder.append(this.getFrfCodigo(), other.getFrfCodigo());
		umEqualsBuilder.append(this.getPtbCodigo(), other.getPtbCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
