package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * FsoRelacionaFonte generated by hbm2java
 */
@Entity
@Table(name = "FSO_RELACIONA_FONTES", schema = "AGH")
public class FsoRelacionaFonte extends BaseEntityId<FsoRelacionaFonteId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7310980280282145189L;
	private FsoRelacionaFonteId id;
	private Integer version;
	private FsoFontesRecursoFinanc fsoFontesRecursoFinanc;
	private RapServidores rapServidores;
	private Date criadoEm;
	private Date alteradoEm;

	public FsoRelacionaFonte() {
	}

	public FsoRelacionaFonte(FsoRelacionaFonteId id, FsoFontesRecursoFinanc fsoFontesRecursoFinanc, RapServidores rapServidores,
			Date criadoEm) {
		this.id = id;
		this.fsoFontesRecursoFinanc = fsoFontesRecursoFinanc;
		this.rapServidores = rapServidores;
		this.criadoEm = criadoEm;
	}

	public FsoRelacionaFonte(FsoRelacionaFonteId id, FsoFontesRecursoFinanc fsoFontesRecursoFinanc, RapServidores rapServidores,
			Date criadoEm, Date alteradoEm) {
		this.id = id;
		this.fsoFontesRecursoFinanc = fsoFontesRecursoFinanc;
		this.rapServidores = rapServidores;
		this.criadoEm = criadoEm;
		this.alteradoEm = alteradoEm;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "frfCodigo", column = @Column(name = "FRF_CODIGO", nullable = false)),
			@AttributeOverride(name = "gcsCdEstab", column = @Column(name = "GCS_CD_ESTAB", nullable = false, length = 16)),
			@AttributeOverride(name = "gcsCdFinConta", column = @Column(name = "GCS_CD_FIN_CONTA", nullable = false, length = 22)) })
	public FsoRelacionaFonteId getId() {
		return this.id;
	}

	public void setId(FsoRelacionaFonteId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FRF_CODIGO", nullable = false, insertable = false, updatable = false)
	public FsoFontesRecursoFinanc getFsoFontesRecursoFinanc() {
		return this.fsoFontesRecursoFinanc;
	}

	public void setFsoFontesRecursoFinanc(FsoFontesRecursoFinanc fsoFontesRecursoFinanc) {
		this.fsoFontesRecursoFinanc = fsoFontesRecursoFinanc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 29)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		FSO_FONTES_RECURSO_FINANC("fsoFontesRecursoFinanc"),
		RAP_SERVIDORES("rapServidores"),
		CRIADO_EM("criadoEm"),
		ALTERADO_EM("alteradoEm");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FsoRelacionaFonte)) {
			return false;
		}
		FsoRelacionaFonte other = (FsoRelacionaFonte) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
