package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * GpPatespCaraq generated by hbm2java
 */
@Entity
@Table(name = "GP_PATESP_CARAQ", schema = "AGH")
public class GpPatespCaraq extends BaseEntityId<GpPatespCaraqId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8314493922756773205L;
	private GpPatespCaraqId id;

	public GpPatespCaraq() {
	}

	public GpPatespCaraq(GpPatespCaraqId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "cdEmpresa", column = @Column(name = "CD_EMPRESA", length = 16)),
			@AttributeOverride(name = "cdPatctaConta", column = @Column(name = "CD_PATCTA_CONTA", length = 20)),
			@AttributeOverride(name = "cdPatbcBem", column = @Column(name = "CD_PATBC_BEM", length = 15)),
			@AttributeOverride(name = "cdPatbcInc", column = @Column(name = "CD_PATBC_INC", length = 4)),
			@AttributeOverride(name = "inTr", column = @Column(name = "IN_TR")),
			@AttributeOverride(name = "dsPatbcBem", column = @Column(name = "DS_PATBC_BEM", length = 254)),
			@AttributeOverride(name = "scPatbcBem", column = @Column(name = "SC_PATBC_BEM", length = 20)),
			@AttributeOverride(name = "dtAquisicao", column = @Column(name = "DT_AQUISICAO", length = 29)),
			@AttributeOverride(name = "cdPatfisEspecie", column = @Column(name = "CD_PATFIS_ESPECIE", length = 20)),
			@AttributeOverride(name = "cdPessoaResp", column = @Column(name = "CD_PESSOA_RESP", length = 22)),
			@AttributeOverride(name = "cdPatfisSituac", column = @Column(name = "CD_PATFIS_SITUAC", length = 10)),
			@AttributeOverride(name = "cdUnmed", column = @Column(name = "CD_UNMED", length = 10)),
			@AttributeOverride(name = "qtItens", column = @Column(name = "QT_ITENS")),
			@AttributeOverride(name = "cdPessoaForn", column = @Column(name = "CD_PESSOA_FORN", length = 22)),
			@AttributeOverride(name = "anDoc", column = @Column(name = "AN_DOC", length = 15)),
			@AttributeOverride(name = "cdPais", column = @Column(name = "CD_PAIS", length = 10)),
			@AttributeOverride(name = "cdReqCompra", column = @Column(name = "CD_REQ_COMPRA", length = 20)),
			@AttributeOverride(name = "cdPedCompra", column = @Column(name = "CD_PED_COMPRA", length = 20)),
			@AttributeOverride(name = "cdPatsegArisco", column = @Column(name = "CD_PATSEG_ARISCO", length = 20)),
			@AttributeOverride(name = "cdEstab", column = @Column(name = "CD_ESTAB", length = 16)),
			@AttributeOverride(name = "cdEof01", column = @Column(name = "CD_EOF_01", length = 30)),
			@AttributeOverride(name = "cdEof02", column = @Column(name = "CD_EOF_02", length = 30)),
			@AttributeOverride(name = "cdEof03", column = @Column(name = "CD_EOF_03", length = 30)),
			@AttributeOverride(name = "cdEof04", column = @Column(name = "CD_EOF_04", length = 30)),
			@AttributeOverride(name = "cdEof05", column = @Column(name = "CD_EOF_05", length = 30)),
			@AttributeOverride(name = "cdEof06", column = @Column(name = "CD_EOF_06", length = 30)),
			@AttributeOverride(name = "cdEof07", column = @Column(name = "CD_EOF_07", length = 30)),
			@AttributeOverride(name = "cdEof08", column = @Column(name = "CD_EOF_08", length = 30)),
			@AttributeOverride(name = "cdEof09", column = @Column(name = "CD_EOF_09", length = 30)),
			@AttributeOverride(name = "cdCampoFlex01", column = @Column(name = "CD_CAMPO_FLEX_01", length = 20)),
			@AttributeOverride(name = "cdCampoFlex02", column = @Column(name = "CD_CAMPO_FLEX_02", length = 20)),
			@AttributeOverride(name = "cdCampoFlex03", column = @Column(name = "CD_CAMPO_FLEX_03", length = 20)),
			@AttributeOverride(name = "cdCampoFlex04", column = @Column(name = "CD_CAMPO_FLEX_04", length = 20)),
			@AttributeOverride(name = "cdCampoFlex05", column = @Column(name = "CD_CAMPO_FLEX_05", length = 20)),
			@AttributeOverride(name = "cdCampoFlex06", column = @Column(name = "CD_CAMPO_FLEX_06", length = 20)),
			@AttributeOverride(name = "inNatureza", column = @Column(name = "IN_NATUREZA", length = 2)),
			@AttributeOverride(name = "cdUnmonSerie", column = @Column(name = "CD_UNMON_SERIE", length = 5)),
			@AttributeOverride(name = "vlVoUmc", column = @Column(name = "VL_VO_UMC", precision = 17, scale = 17)),
			@AttributeOverride(name = "vlHist", column = @Column(name = "VL_HIST", precision = 17, scale = 17)),
			@AttributeOverride(name = "dtContabil", column = @Column(name = "DT_CONTABIL", length = 29)),
			@AttributeOverride(name = "dtConvMa", column = @Column(name = "DT_CONV_MA", length = 29)),
			@AttributeOverride(name = "inCalcUma", column = @Column(name = "IN_CALC_UMA", length = 1)),
			@AttributeOverride(name = "vlVoUma", column = @Column(name = "VL_VO_UMA", precision = 17, scale = 17)),
			@AttributeOverride(name = "inCalcCm", column = @Column(name = "IN_CALC_CM", length = 1)),
			@AttributeOverride(name = "cdPatgenHMov", column = @Column(name = "CD_PATGEN_H_MOV", length = 10)),
			@AttributeOverride(name = "inNumAuto", column = @Column(name = "IN_NUM_AUTO", length = 1)),
			@AttributeOverride(name = "vlIcms", column = @Column(name = "VL_ICMS", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtAreaCorte", column = @Column(name = "QT_AREA_CORTE", precision = 17, scale = 17)),
			@AttributeOverride(name = "inAtuNumauto", column = @Column(name = "IN_ATU_NUMAUTO", length = 1)),
			@AttributeOverride(name = "inInfAlpis", column = @Column(name = "IN_INF_ALPIS", length = 1)),
			@AttributeOverride(name = "ftAlpis", column = @Column(name = "FT_ALPIS", precision = 17, scale = 17)),
			@AttributeOverride(name = "inInfCofins", column = @Column(name = "IN_INF_COFINS", length = 1)),
			@AttributeOverride(name = "ftCofins", column = @Column(name = "FT_COFINS", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtCopiasGer", column = @Column(name = "QT_COPIAS_GER")),
			@AttributeOverride(name = "inRatVlVo", column = @Column(name = "IN_RAT_VL_VO", length = 1)),
			@AttributeOverride(name = "cdPatfisDspdr", column = @Column(name = "CD_PATFIS_DSPDR", length = 10)),
			@AttributeOverride(name = "vlDifalqIcms", column = @Column(name = "VL_DIFALQ_ICMS", precision = 17, scale = 17)),
			@AttributeOverride(name = "inCopias", column = @Column(name = "IN_COPIAS", length = 1)),
			@AttributeOverride(name = "inNumBem", column = @Column(name = "IN_NUM_BEM", length = 1)),
			@AttributeOverride(name = "inNacDefPiscof", column = @Column(name = "IN_NAC_DEF_PISCOF", length = 4)),
			@AttributeOverride(name = "inDprDefPiscof", column = @Column(name = "IN_DPR_DEF_PISCOF", length = 4)),
			@AttributeOverride(name = "vlPis", column = @Column(name = "VL_PIS", precision = 17, scale = 17)),
			@AttributeOverride(name = "vlCofins", column = @Column(name = "VL_COFINS", precision = 17, scale = 17)),
			@AttributeOverride(name = "inTemcrdPiscof", column = @Column(name = "IN_TEMCRD_PISCOF", length = 1)),
			@AttributeOverride(name = "verid", column = @Column(name = "VERID")) })
	public GpPatespCaraqId getId() {
		return this.id;
	}

	public void setId(GpPatespCaraqId id) {
		this.id = id;
	}

	public enum Fields {

		ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GpPatespCaraq)) {
			return false;
		}
		GpPatespCaraq other = (GpPatespCaraq) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
