package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * LocalEquip generated by hbm2java
 */
@Entity
@Table(name = "LOCAL_EQUIP", schema = "AGH")
public class LocalEquip extends BaseEntityId<LocalEquipId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5074689957357637682L;
	private LocalEquipId id;

	public LocalEquip() {
	}

	public LocalEquip(LocalEquipId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "codLeq", column = @Column(name = "COD_LEQ", precision = 17, scale = 17)),
			@AttributeOverride(name = "descrLeq", column = @Column(name = "DESCR_LEQ", length = 40)),
			@AttributeOverride(name = "ativo", column = @Column(name = "ATIVO", length = 1)) })
	public LocalEquipId getId() {
		return this.id;
	}

	public void setId(LocalEquipId id) {
		this.id = id;
	}

	public enum Fields {

		ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof LocalEquip)) {
			return false;
		}
		LocalEquip other = (LocalEquip) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
