package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * LogBuscaResultadoId generated by hbm2java
 */
@Embeddable
public class LogBuscaResultadoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 225510914619021198L;
	private Integer seq;
	private Integer iseSoeSeq;
	private Short iseSeqp;
	private String pclVelEmaExaSigla;
	private Integer pclVelEmaManSeq;
	private Integer pclVelSeqp;
	private Integer pclCalSeq;
	private Integer pclSeqp;
	private Integer seqp;
	private Long valor;
	private Integer rcdGtcSeq;
	private Integer rcdSeqp;
	private Integer cacSeq;

	public LogBuscaResultadoId() {
	}

	public LogBuscaResultadoId(Integer seq, Integer iseSoeSeq, Short iseSeqp, String pclVelEmaExaSigla, Integer pclVelEmaManSeq,
			Integer pclVelSeqp, Integer pclCalSeq, Integer pclSeqp, Integer seqp, Long valor, Integer rcdGtcSeq, Integer rcdSeqp,
			Integer cacSeq) {
		this.seq = seq;
		this.iseSoeSeq = iseSoeSeq;
		this.iseSeqp = iseSeqp;
		this.pclVelEmaExaSigla = pclVelEmaExaSigla;
		this.pclVelEmaManSeq = pclVelEmaManSeq;
		this.pclVelSeqp = pclVelSeqp;
		this.pclCalSeq = pclCalSeq;
		this.pclSeqp = pclSeqp;
		this.seqp = seqp;
		this.valor = valor;
		this.rcdGtcSeq = rcdGtcSeq;
		this.rcdSeqp = rcdSeqp;
		this.cacSeq = cacSeq;
	}

	@Column(name = "SEQ")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "ISE_SOE_SEQ")
	public Integer getIseSoeSeq() {
		return this.iseSoeSeq;
	}

	public void setIseSoeSeq(Integer iseSoeSeq) {
		this.iseSoeSeq = iseSoeSeq;
	}

	@Column(name = "ISE_SEQP")
	public Short getIseSeqp() {
		return this.iseSeqp;
	}

	public void setIseSeqp(Short iseSeqp) {
		this.iseSeqp = iseSeqp;
	}

	@Column(name = "PCL_VEL_EMA_EXA_SIGLA", length = 5)
	@Length(max = 5)
	public String getPclVelEmaExaSigla() {
		return this.pclVelEmaExaSigla;
	}

	public void setPclVelEmaExaSigla(String pclVelEmaExaSigla) {
		this.pclVelEmaExaSigla = pclVelEmaExaSigla;
	}

	@Column(name = "PCL_VEL_EMA_MAN_SEQ")
	public Integer getPclVelEmaManSeq() {
		return this.pclVelEmaManSeq;
	}

	public void setPclVelEmaManSeq(Integer pclVelEmaManSeq) {
		this.pclVelEmaManSeq = pclVelEmaManSeq;
	}

	@Column(name = "PCL_VEL_SEQP")
	public Integer getPclVelSeqp() {
		return this.pclVelSeqp;
	}

	public void setPclVelSeqp(Integer pclVelSeqp) {
		this.pclVelSeqp = pclVelSeqp;
	}

	@Column(name = "PCL_CAL_SEQ")
	public Integer getPclCalSeq() {
		return this.pclCalSeq;
	}

	public void setPclCalSeq(Integer pclCalSeq) {
		this.pclCalSeq = pclCalSeq;
	}

	@Column(name = "PCL_SEQP")
	public Integer getPclSeqp() {
		return this.pclSeqp;
	}

	public void setPclSeqp(Integer pclSeqp) {
		this.pclSeqp = pclSeqp;
	}

	@Column(name = "SEQP")
	public Integer getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Integer seqp) {
		this.seqp = seqp;
	}

	@Column(name = "VALOR")
	public Long getValor() {
		return this.valor;
	}

	public void setValor(Long valor) {
		this.valor = valor;
	}

	@Column(name = "RCD_GTC_SEQ")
	public Integer getRcdGtcSeq() {
		return this.rcdGtcSeq;
	}

	public void setRcdGtcSeq(Integer rcdGtcSeq) {
		this.rcdGtcSeq = rcdGtcSeq;
	}

	@Column(name = "RCD_SEQP")
	public Integer getRcdSeqp() {
		return this.rcdSeqp;
	}

	public void setRcdSeqp(Integer rcdSeqp) {
		this.rcdSeqp = rcdSeqp;
	}

	@Column(name = "CAC_SEQ")
	public Integer getCacSeq() {
		return this.cacSeq;
	}

	public void setCacSeq(Integer cacSeq) {
		this.cacSeq = cacSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeq());
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getValor());
		umHashCodeBuilder.append(this.getIseSoeSeq());
		umHashCodeBuilder.append(this.getIseSeqp());
		umHashCodeBuilder.append(this.getCacSeq());
		umHashCodeBuilder.append(this.getRcdGtcSeq());
		umHashCodeBuilder.append(this.getRcdSeqp());
		umHashCodeBuilder.append(this.getPclVelEmaExaSigla());
		umHashCodeBuilder.append(this.getPclVelEmaManSeq());
		umHashCodeBuilder.append(this.getPclVelSeqp());
		umHashCodeBuilder.append(this.getPclCalSeq());
		umHashCodeBuilder.append(this.getPclSeqp());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof LogBuscaResultadoId)) {
			return false;
		}
		LogBuscaResultadoId other = (LogBuscaResultadoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeq(), other.getSeq());
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getValor(), other.getValor());
		umEqualsBuilder.append(this.getIseSoeSeq(), other.getIseSoeSeq());
		umEqualsBuilder.append(this.getIseSeqp(), other.getIseSeqp());
		umEqualsBuilder.append(this.getCacSeq(), other.getCacSeq());
		umEqualsBuilder.append(this.getRcdGtcSeq(), other.getRcdGtcSeq());
		umEqualsBuilder.append(this.getRcdSeqp(), other.getRcdSeqp());
		umEqualsBuilder.append(this.getPclVelEmaExaSigla(), other.getPclVelEmaExaSigla());
		umEqualsBuilder.append(this.getPclVelEmaManSeq(), other.getPclVelEmaManSeq());
		umEqualsBuilder.append(this.getPclVelSeqp(), other.getPclVelSeqp());
		umEqualsBuilder.append(this.getPclCalSeq(), other.getPclCalSeq());
		umEqualsBuilder.append(this.getPclSeqp(), other.getPclSeqp());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
