package br.gov.mec.aghu.model;

// Generated 07/05/2010 10:12:13 by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MamAreaAtuacoes generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mamAraSq1", sequenceName="AGH.MAM_ARA_SQ1", allocationSize = 1)
@Table(name = "MAM_AREA_ATUACOES", schema = "AGH")

public class MamAreaAtuacao extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7754086087549564268L;
	private Integer seq;
	private AipLogradouros logradouro;
	private RapServidores servidor;
	private Integer codigoMunicipalLogradouro;
	private String descricaoLogradouro;
	private DominioSituacao situacao;
	private Date criadoEm;
	private Set<MamAreaAtuacaoNumero> areaAtuacaoNumeros = new HashSet<MamAreaAtuacaoNumero>(
			0);

	public MamAreaAtuacao() {
	}

	public MamAreaAtuacao(Integer seq, RapServidores servidor,
			String descricaoLogradouro, DominioSituacao situacao, Date criadoEm) {
		this.seq = seq;
		this.servidor = servidor;
		this.descricaoLogradouro = descricaoLogradouro;
		this.situacao = situacao;
		this.criadoEm = criadoEm;
	}

	public MamAreaAtuacao(Integer seq, AipLogradouros logradouro,
			RapServidores servidor, Integer codigoMunicipalLogradouro,
			String descricaoLogradouro, DominioSituacao situacao, Date criadoEm,
			Set<MamAreaAtuacaoNumero> areaAtuacaoNumeros) {
		this.seq = seq;
		this.logradouro = logradouro;
		this.servidor = servidor;
		this.codigoMunicipalLogradouro = codigoMunicipalLogradouro;
		this.descricaoLogradouro = descricaoLogradouro;
		this.situacao = situacao;
		this.criadoEm = criadoEm;
		this.areaAtuacaoNumeros = areaAtuacaoNumeros;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mamAraSq1")
	@Column(name = "SEQ", nullable = false, precision = 5, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LGR_CODIGO")
	public AipLogradouros getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(AipLogradouros logradouro) {
		this.logradouro = logradouro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Column(name = "COD_MUNICIPAL_LOGRADOURO", precision = 8, scale = 0)
	public Integer getCodigoMunicipalLogradouro() {
		return this.codigoMunicipalLogradouro;
	}

	public void setCodigoMunicipalLogradouro(Integer codigoMunicipalLogradouro) {
		this.codigoMunicipalLogradouro = codigoMunicipalLogradouro;
	}

	@Column(name = "DESCRICAO_LOGRADOURO", nullable = false, length = 100)
	@Length(max = 100)
	public String getDescricaoLogradouro() {
		return this.descricaoLogradouro;
	}

	public void setDescricaoLogradouro(String descricaoLogradouro) {
		this.descricaoLogradouro = descricaoLogradouro;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getSituacao() {
		return this.situacao;
	}

	public void setSituacao(DominioSituacao situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaAtuacao")
	public Set<MamAreaAtuacaoNumero> getAreaAtuacaoNumeros() {
		return this.areaAtuacaoNumeros;
	}

	public void setAreaAtuacaoNumeros(Set<MamAreaAtuacaoNumero> areaAtuacaoNumeros) {
		this.areaAtuacaoNumeros = areaAtuacaoNumeros;
	}
	
	public enum Fields {
		SEQ("seq"), CODIGO_LOGRADOURO("logradouro.codigo"), NOME_LOGRADOURO(
				"logradouro.nome"), SITUACAO("situacao"), OD_MUNICIPAL_LOGRADOURO(
				"codigoMunicipalLogradouro"), DESCRICAO_LOGRADOURO(
				"descricaoLogradouro")
				;

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((seq == null) ? 0 : seq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		MamAreaAtuacao other = (MamAreaAtuacao) obj;
		if (seq == null) {
			if (other.seq != null) {
				return false;
			}
		} else if (!seq.equals(other.seq)) {
			return false;
		}
		return true;
	}
	
}
