package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MamConcatenacaoId generated by hbm2java
 */
@Embeddable
public class MamConcatenacaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4293053936902867244L;
	private Integer qusQutSeq;
	private Short qusSeqp;
	private Integer qusQutSeqConcatenado;
	private Short qusSeqpConcatenado;

	public MamConcatenacaoId() {
	}

	public MamConcatenacaoId(Integer qusQutSeq, Short qusSeqp, Integer qusQutSeqConcatenado, Short qusSeqpConcatenado) {
		this.qusQutSeq = qusQutSeq;
		this.qusSeqp = qusSeqp;
		this.qusQutSeqConcatenado = qusQutSeqConcatenado;
		this.qusSeqpConcatenado = qusSeqpConcatenado;
	}

	@Column(name = "QUS_QUT_SEQ", nullable = false)
	public Integer getQusQutSeq() {
		return this.qusQutSeq;
	}

	public void setQusQutSeq(Integer qusQutSeq) {
		this.qusQutSeq = qusQutSeq;
	}

	@Column(name = "QUS_SEQP", nullable = false)
	public Short getQusSeqp() {
		return this.qusSeqp;
	}

	public void setQusSeqp(Short qusSeqp) {
		this.qusSeqp = qusSeqp;
	}

	@Column(name = "QUS_QUT_SEQ_CONCATENADO", nullable = false)
	public Integer getQusQutSeqConcatenado() {
		return this.qusQutSeqConcatenado;
	}

	public void setQusQutSeqConcatenado(Integer qusQutSeqConcatenado) {
		this.qusQutSeqConcatenado = qusQutSeqConcatenado;
	}

	@Column(name = "QUS_SEQP_CONCATENADO", nullable = false)
	public Short getQusSeqpConcatenado() {
		return this.qusSeqpConcatenado;
	}

	public void setQusSeqpConcatenado(Short qusSeqpConcatenado) {
		this.qusSeqpConcatenado = qusSeqpConcatenado;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getQusQutSeq());
		umHashCodeBuilder.append(this.getQusSeqp());
		umHashCodeBuilder.append(this.getQusQutSeqConcatenado());
		umHashCodeBuilder.append(this.getQusSeqpConcatenado());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamConcatenacaoId)) {
			return false;
		}
		MamConcatenacaoId other = (MamConcatenacaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getQusQutSeq(), other.getQusQutSeq());
		umEqualsBuilder.append(this.getQusSeqp(), other.getQusSeqp());
		umEqualsBuilder.append(this.getQusQutSeqConcatenado(), other.getQusQutSeqConcatenado());
		umEqualsBuilder.append(this.getQusSeqpConcatenado(), other.getQusSeqpConcatenado());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
