package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MamEmgGrpPlanoXPerfilId generated by hbm2java
 */
@Embeddable
public class MamEmgGrpPlanoXPerfilId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1802685196539149618L;
	private Short egpSeq;
	private Short seqp;

	public MamEmgGrpPlanoXPerfilId() {
	}

	public MamEmgGrpPlanoXPerfilId(Short egpSeq, Short seqp) {
		this.egpSeq = egpSeq;
		this.seqp = seqp;
	}

	@Column(name = "EGP_SEQ", nullable = false)
	public Short getEgpSeq() {
		return this.egpSeq;
	}

	public void setEgpSeq(Short egpSeq) {
		this.egpSeq = egpSeq;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getEgpSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamEmgGrpPlanoXPerfilId)) {
			return false;
		}
		MamEmgGrpPlanoXPerfilId other = (MamEmgGrpPlanoXPerfilId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getEgpSeq(), other.getEgpSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
