package br.gov.mec.aghu.model;

// Generated 05/04/2011 11:18:40 by Hibernate Tools 3.2.5.Beta

import java.io.Serializable;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MamExtratoControles generated by hbm2java
 */
@Entity

@Table(name = "MAM_EXTRATO_CONTROLES", schema = "AGH")
public class MamExtratoControles extends BaseEntityId<MamExtratoControlesId> implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1651551422557308318L;
	private MamExtratoControlesId id;
	private Date dthrMovimento;
	private String micNome;
	private MamSituacaoAtendimentos situacaoAtendimento;
	private Date criadoEm;
	private RapServidores servidor;
	private MamControles controle;

	public MamExtratoControles() {
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "ctlSeq", column = @Column(name = "CTL_SEQ", nullable = false, precision = 14, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 3, scale = 0)) })
	public MamExtratoControlesId getId() {
		return this.id;
	}

	public void setId(MamExtratoControlesId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_MOVIMENTO", nullable = false, length = 7)
	public Date getDthrMovimento() {
		return this.dthrMovimento;
	}

	public void setDthrMovimento(Date dthrMovimento) {
		this.dthrMovimento = dthrMovimento;
	}

	@Column(name = "MIC_NOME", length = 50)
	public String getMicNome() {
		return this.micNome;
	}

	public void setMicNome(String micNome) {
		this.micNome = micNome;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAT_SEQ")	
	public MamSituacaoAtendimentos getSituacaoAtendimento() {
		return this.situacaoAtendimento;
	}

	public void setSituacaoAtendimento(MamSituacaoAtendimentos situacaoAtendimento) {
		this.situacaoAtendimento = situacaoAtendimento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@ManyToOne
	@JoinColumn(name="CTL_SEQ", insertable=false, updatable=false)
	public MamControles getControle() {
		return controle;
	}

	public void setControle(MamControles controle) {
		this.controle = controle;
	}
	
	public enum Fields {
		
		CONTROLE("controle"), 
		CTL_SEQ("id.ctlSeq"), 
		SEQP("id.seqp"), 
		SITUACAO_ATENDIMENTO("situacaoAtendimento"),
		SITUACAO_ATENDIMENTO_SEQ("situacaoAtendimento.seq"),		
		SERVIDOR("servidor"),
		SERVIDOR_MATRICULA("servidor.id.matricula"),
		SERVIDOR_VIN_CODIGO("servidor.id.vinCodigo"),
		DTHR_MOVIMENTO("dthrMovimento");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamExtratoControles)) {
			return false;
		}
		MamExtratoControles other = (MamExtratoControles) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
