package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MamEmgDestino generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mamEdeSq1", sequenceName="AGH.MAM_EDE_SQ1", allocationSize = 1)
@Table(name = "MAM_EMG_DESTINOS", schema = "AGH")
public class MamEmgDestino extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2276216775467123932L;
	private Short seq;
	private Integer version;
	private MamSituacaoEmergencia mamSituacaoEmergencia;
	private MamEmgLocais mamEmgLocaisByEloSeq;
	private RapServidores rapServidores;
	private MamEmgLocais mamEmgLocaisByEloSeqFisico;
	private String descricao;
	private Date criadoEm;
	private String indSituacao;
	private String indMudaSituacao;
	private String indGeraAtend;
	private String indGeraAvisoAdmin;
	private String indDeterminacaoAlta;
	private String indPedePatologia;
	private String indPedeEspecialidade;
	private String indPacVoltaTriagem;
	private String indUsoConsult;
	private String indUsoForaConsult;
	private Short ordem;
	private String indExigeAih;
	private String envProntUnidInt;
	private String indPedeEstadoPac;
	private Set<MamEmgDestXPerfil> mamEmgDestXPerfiles = new HashSet<MamEmgDestXPerfil>(0);
	private Set<MamEmgDestXGrpPatol> mamEmgDestXGrpPatoles = new HashSet<MamEmgDestXGrpPatol>(0);
	private Set<MamEmgDestXLocal> mamEmgDestXLocales = new HashSet<MamEmgDestXLocal>(0);

	// FIXME Implementar este relacionamento
//	private Set<MamDestinos> mamDestinoses = new HashSet<MamDestinos>(0);

	public MamEmgDestino() {
	}

	public MamEmgDestino(Short seq, RapServidores rapServidores, String descricao, Date criadoEm, String indSituacao,
			String indPedeEspecialidade, String indPacVoltaTriagem, String indUsoConsult, String indUsoForaConsult, Short ordem) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.descricao = descricao;
		this.criadoEm = criadoEm;
		this.indSituacao = indSituacao;
		this.indPedeEspecialidade = indPedeEspecialidade;
		this.indPacVoltaTriagem = indPacVoltaTriagem;
		this.indUsoConsult = indUsoConsult;
		this.indUsoForaConsult = indUsoForaConsult;
		this.ordem = ordem;
	}

	public MamEmgDestino(Short seq, MamSituacaoEmergencia mamSituacaoEmergencia, MamEmgLocais mamEmgLocaisByEloSeq,
			RapServidores rapServidores, MamEmgLocais mamEmgLocaisByEloSeqFisico, String descricao, Date criadoEm, String indSituacao,
			String indMudaSituacao, String indGeraAtend, String indGeraAvisoAdmin, String indDeterminacaoAlta,
			String indPedePatologia, String indPedeEspecialidade, String indPacVoltaTriagem, String indUsoConsult,
			String indUsoForaConsult, Short ordem, String indExigeAih, String envProntUnidInt, String indPedeEstadoPac,
			Set<MamEmgDestXPerfil> mamEmgDestXPerfiles, Set<MamEmgDestXGrpPatol> mamEmgDestXGrpPatoles,
//			Set<MamDestinos> mamDestinoses,
			Set<MamEmgDestXLocal> mamEmgDestXLocales) {
		this.seq = seq;
		this.mamSituacaoEmergencia = mamSituacaoEmergencia;
		this.mamEmgLocaisByEloSeq = mamEmgLocaisByEloSeq;
		this.rapServidores = rapServidores;
		this.mamEmgLocaisByEloSeqFisico = mamEmgLocaisByEloSeqFisico;
		this.descricao = descricao;
		this.criadoEm = criadoEm;
		this.indSituacao = indSituacao;
		this.indMudaSituacao = indMudaSituacao;
		this.indGeraAtend = indGeraAtend;
		this.indGeraAvisoAdmin = indGeraAvisoAdmin;
		this.indDeterminacaoAlta = indDeterminacaoAlta;
		this.indPedePatologia = indPedePatologia;
		this.indPedeEspecialidade = indPedeEspecialidade;
		this.indPacVoltaTriagem = indPacVoltaTriagem;
		this.indUsoConsult = indUsoConsult;
		this.indUsoForaConsult = indUsoForaConsult;
		this.ordem = ordem;
		this.indExigeAih = indExigeAih;
		this.envProntUnidInt = envProntUnidInt;
		this.indPedeEstadoPac = indPedeEstadoPac;
		this.mamEmgDestXPerfiles = mamEmgDestXPerfiles;
		this.mamEmgDestXGrpPatoles = mamEmgDestXGrpPatoles;
//		this.mamDestinoses = mamDestinoses;
		this.mamEmgDestXLocales = mamEmgDestXLocales;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mamEdeSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEG_SEQ")
	public MamSituacaoEmergencia getMamSituacaoEmergencia() {
		return this.mamSituacaoEmergencia;
	}

	public void setMamSituacaoEmergencia(MamSituacaoEmergencia mamSituacaoEmergencia) {
		this.mamSituacaoEmergencia = mamSituacaoEmergencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELO_SEQ")
	public MamEmgLocais getMamEmgLocaisByEloSeq() {
		return this.mamEmgLocaisByEloSeq;
	}

	public void setMamEmgLocaisByEloSeq(MamEmgLocais mamEmgLocaisByEloSeq) {
		this.mamEmgLocaisByEloSeq = mamEmgLocaisByEloSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELO_SEQ_FISICO")
	public MamEmgLocais getMamEmgLocaisByEloSeqFisico() {
		return this.mamEmgLocaisByEloSeqFisico;
	}

	public void setMamEmgLocaisByEloSeqFisico(MamEmgLocais mamEmgLocaisByEloSeqFisico) {
		this.mamEmgLocaisByEloSeqFisico = mamEmgLocaisByEloSeqFisico;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 120)
	@NotNull
	@Length(max = 120)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	@NotNull
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(String indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "IND_MUDA_SITUACAO", length = 1)
	@Length(max = 1)
	public String getIndMudaSituacao() {
		return this.indMudaSituacao;
	}

	public void setIndMudaSituacao(String indMudaSituacao) {
		this.indMudaSituacao = indMudaSituacao;
	}

	@Column(name = "IND_GERA_ATEND", length = 1)
	@Length(max = 1)
	public String getIndGeraAtend() {
		return this.indGeraAtend;
	}

	public void setIndGeraAtend(String indGeraAtend) {
		this.indGeraAtend = indGeraAtend;
	}

	@Column(name = "IND_GERA_AVISO_ADMIN", length = 1)
	@Length(max = 1)
	public String getIndGeraAvisoAdmin() {
		return this.indGeraAvisoAdmin;
	}

	public void setIndGeraAvisoAdmin(String indGeraAvisoAdmin) {
		this.indGeraAvisoAdmin = indGeraAvisoAdmin;
	}

	@Column(name = "IND_DETERMINACAO_ALTA", length = 1)
	@Length(max = 1)
	public String getIndDeterminacaoAlta() {
		return this.indDeterminacaoAlta;
	}

	public void setIndDeterminacaoAlta(String indDeterminacaoAlta) {
		this.indDeterminacaoAlta = indDeterminacaoAlta;
	}

	@Column(name = "IND_PEDE_PATOLOGIA", length = 1)
	@Length(max = 1)
	public String getIndPedePatologia() {
		return this.indPedePatologia;
	}

	public void setIndPedePatologia(String indPedePatologia) {
		this.indPedePatologia = indPedePatologia;
	}

	@Column(name = "IND_PEDE_ESPECIALIDADE", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getIndPedeEspecialidade() {
		return this.indPedeEspecialidade;
	}

	public void setIndPedeEspecialidade(String indPedeEspecialidade) {
		this.indPedeEspecialidade = indPedeEspecialidade;
	}

	@Column(name = "IND_PAC_VOLTA_TRIAGEM", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getIndPacVoltaTriagem() {
		return this.indPacVoltaTriagem;
	}

	public void setIndPacVoltaTriagem(String indPacVoltaTriagem) {
		this.indPacVoltaTriagem = indPacVoltaTriagem;
	}

	@Column(name = "IND_USO_CONSULT", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getIndUsoConsult() {
		return this.indUsoConsult;
	}

	public void setIndUsoConsult(String indUsoConsult) {
		this.indUsoConsult = indUsoConsult;
	}

	@Column(name = "IND_USO_FORA_CONSULT", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getIndUsoForaConsult() {
		return this.indUsoForaConsult;
	}

	public void setIndUsoForaConsult(String indUsoForaConsult) {
		this.indUsoForaConsult = indUsoForaConsult;
	}

	@Column(name = "ORDEM", nullable = false)
	public Short getOrdem() {
		return this.ordem;
	}

	public void setOrdem(Short ordem) {
		this.ordem = ordem;
	}

	@Column(name = "IND_EXIGE_AIH", length = 1)
	@Length(max = 1)
	public String getIndExigeAih() {
		return this.indExigeAih;
	}

	public void setIndExigeAih(String indExigeAih) {
		this.indExigeAih = indExigeAih;
	}

	@Column(name = "ENV_PRONT_UNID_INT", length = 1)
	@Length(max = 1)
	public String getEnvProntUnidInt() {
		return this.envProntUnidInt;
	}

	public void setEnvProntUnidInt(String envProntUnidInt) {
		this.envProntUnidInt = envProntUnidInt;
	}

	@Column(name = "IND_PEDE_ESTADO_PAC", length = 1)
	@Length(max = 1)
	public String getIndPedeEstadoPac() {
		return this.indPedeEstadoPac;
	}

	public void setIndPedeEstadoPac(String indPedeEstadoPac) {
		this.indPedeEstadoPac = indPedeEstadoPac;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamEmgDestino")
	public Set<MamEmgDestXPerfil> getMamEmgDestXPerfiles() {
		return this.mamEmgDestXPerfiles;
	}

	public void setMamEmgDestXPerfiles(Set<MamEmgDestXPerfil> mamEmgDestXPerfiles) {
		this.mamEmgDestXPerfiles = mamEmgDestXPerfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamEmgDestino")
	public Set<MamEmgDestXGrpPatol> getMamEmgDestXGrpPatoles() {
		return this.mamEmgDestXGrpPatoles;
	}

	public void setMamEmgDestXGrpPatoles(Set<MamEmgDestXGrpPatol> mamEmgDestXGrpPatoles) {
		this.mamEmgDestXGrpPatoles = mamEmgDestXGrpPatoles;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamEmgDestino")
//	public Set<MamDestinos> getMamDestinoses() {
//		return this.mamDestinoses;
//	}
//
//	public void setMamDestinoses(Set<MamDestinos> mamDestinoses) {
//		this.mamDestinoses = mamDestinoses;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamEmgDestino")
	public Set<MamEmgDestXLocal> getMamEmgDestXLocales() {
		return this.mamEmgDestXLocales;
	}

	public void setMamEmgDestXLocales(Set<MamEmgDestXLocal> mamEmgDestXLocales) {
		this.mamEmgDestXLocales = mamEmgDestXLocales;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		MAM_SITUACAO_EMERGENCIAS("mamSituacaoEmergencia"),
		MAM_EMG_LOCAIS_BY_ELO_SEQ("mamEmgLocaisByEloSeq"),
		RAP_SERVIDORES("rapServidores"),
		MAM_EMG_LOCAIS_BY_ELO_SEQ_FISICO("mamEmgLocaisByEloSeqFisico"),
		DESCRICAO("descricao"),
		CRIADO_EM("criadoEm"),
		IND_SITUACAO("indSituacao"),
		IND_MUDA_SITUACAO("indMudaSituacao"),
		IND_GERA_ATEND("indGeraAtend"),
		IND_GERA_AVISO_ADMIN("indGeraAvisoAdmin"),
		IND_DETERMINACAO_ALTA("indDeterminacaoAlta"),
		IND_PEDE_PATOLOGIA("indPedePatologia"),
		IND_PEDE_ESPECIALIDADE("indPedeEspecialidade"),
		IND_PAC_VOLTA_TRIAGEM("indPacVoltaTriagem"),
		IND_USO_CONSULT("indUsoConsult"),
		IND_USO_FORA_CONSULT("indUsoForaConsult"),
		ORDEM("ordem"),
		IND_EXIGE_AIH("indExigeAih"),
		ENV_PRONT_UNID_INT("envProntUnidInt"),
		IND_PEDE_ESTADO_PAC("indPedeEstadoPac"),
		MAM_EMG_DEST_X_PERFILES("mamEmgDestXPerfiles"),
		MAM_EMG_DEST_X_GRP_PATOLES("mamEmgDestXGrpPatoles"),
//		MAM_DESTINOSES("mamDestinoses"),
		MAM_EMG_DEST_X_LOCALES("mamEmgDestXLocales");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamEmgDestino)) {
			return false;
		}
		MamEmgDestino other = (MamEmgDestino) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
