package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MamFuncaoCalculoAtendemId generated by hbm2java
 */
@Embeddable
public class MamFuncaoCalculoAtendemId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4627077814585773898L;
	private Integer fclSeq;
	private Short seqp;

	public MamFuncaoCalculoAtendemId() {
	}

	public MamFuncaoCalculoAtendemId(Integer fclSeq, Short seqp) {
		this.fclSeq = fclSeq;
		this.seqp = seqp;
	}

	@Column(name = "FCL_SEQ", nullable = false)
	public Integer getFclSeq() {
		return this.fclSeq;
	}

	public void setFclSeq(Integer fclSeq) {
		this.fclSeq = fclSeq;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getFclSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamFuncaoCalculoAtendemId)) {
			return false;
		}
		MamFuncaoCalculoAtendemId other = (MamFuncaoCalculoAtendemId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getFclSeq(), other.getFclSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
