package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MamFuncaoCalculoAtendem generated by hbm2java
 */
@Entity
@Table(name = "MAM_FUNCAO_CALCULO_ATENDEM", schema = "AGH")
public class MamFuncaoCalculoAtendem extends BaseEntityId<MamFuncaoCalculoAtendemId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5172082860895435281L;
	private MamFuncaoCalculoAtendemId id;
	private Integer version;
	private MamQuestao mamQuestao;
	private RapServidores rapServidores;
	private MamQuestionario mamQuestionario;
	private MamFuncaoCalculo mamFuncaoCalculo;
	private Date criadoEm;
	private String indSituacao;

	public MamFuncaoCalculoAtendem() {
	}

	public MamFuncaoCalculoAtendem(MamFuncaoCalculoAtendemId id, RapServidores rapServidores, MamFuncaoCalculo mamFuncaoCalculo,
			Date criadoEm, String indSituacao) {
		this.id = id;
		this.rapServidores = rapServidores;
		this.mamFuncaoCalculo = mamFuncaoCalculo;
		this.criadoEm = criadoEm;
		this.indSituacao = indSituacao;
	}

	public MamFuncaoCalculoAtendem(MamFuncaoCalculoAtendemId id, MamQuestao mamQuestao, RapServidores rapServidores,
			MamQuestionario mamQuestionario, MamFuncaoCalculo mamFuncaoCalculo, Date criadoEm, String indSituacao) {
		this.id = id;
		this.mamQuestao = mamQuestao;
		this.rapServidores = rapServidores;
		this.mamQuestionario = mamQuestionario;
		this.mamFuncaoCalculo = mamFuncaoCalculo;
		this.criadoEm = criadoEm;
		this.indSituacao = indSituacao;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "fclSeq", column = @Column(name = "FCL_SEQ", nullable = false)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false)) })
	public MamFuncaoCalculoAtendemId getId() {
		return this.id;
	}

	public void setId(MamFuncaoCalculoAtendemId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "QUS_QUT_SEQ", referencedColumnName = "QUT_SEQ"),
			@JoinColumn(name = "QUS_SEQP", referencedColumnName = "SEQP") })
	public MamQuestao getMamQuestao() {
		return this.mamQuestao;
	}

	public void setMamQuestao(MamQuestao mamQuestao) {
		this.mamQuestao = mamQuestao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUT_SEQ")
	public MamQuestionario getMamQuestionario() {
		return this.mamQuestionario;
	}

	public void setMamQuestionario(MamQuestionario mamQuestionario) {
		this.mamQuestionario = mamQuestionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCL_SEQ", nullable = false, insertable = false, updatable = false)
	public MamFuncaoCalculo getMamFuncaoCalculo() {
		return this.mamFuncaoCalculo;
	}

	public void setMamFuncaoCalculo(MamFuncaoCalculo mamFuncaoCalculo) {
		this.mamFuncaoCalculo = mamFuncaoCalculo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(String indSituacao) {
		this.indSituacao = indSituacao;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		MAM_QUESTOES("mamQuestao"),
		RAP_SERVIDORES("rapServidores"),
		MAM_QUESTIONARIOS("mamQuestionario"),
		MAM_FUNCAO_CALCULOS("mamFuncaoCalculo"),
		CRIADO_EM("criadoEm"),
		IND_SITUACAO("indSituacao");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamFuncaoCalculoAtendem)) {
			return false;
		}
		MamFuncaoCalculoAtendem other = (MamFuncaoCalculoAtendem) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
