package br.gov.mec.aghu.model;

// Generated 13/06/2011 10:22:04 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MamItemEvolucoesId generated by hbm2java
 */
@Embeddable
public class MamItemEvolucoesId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5956229530605876378L;
	private Long evoSeq;
	private Integer tieSeq;

	public MamItemEvolucoesId() {
	}

	public MamItemEvolucoesId(Long evoSeq, Integer tieSeq) {
		this.evoSeq = evoSeq;
		this.tieSeq = tieSeq;
	}

	@Column(name = "EVO_SEQ", nullable = false, precision = 14, scale = 0)
	public Long getEvoSeq() {
		return this.evoSeq;
	}

	public void setEvoSeq(Long evoSeq) {
		this.evoSeq = evoSeq;
	}

	@Column(name = "TIE_SEQ", nullable = false, precision = 5, scale = 0)
	public Integer getTieSeq() {
		return this.tieSeq;
	}

	public void setTieSeq(Integer tieSeq) {
		this.tieSeq = tieSeq;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((evoSeq == null) ? 0 : evoSeq.hashCode());
		result = prime * result + ((tieSeq == null) ? 0 : tieSeq.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
		if (obj == null){
			return false;
		}
		if (getClass() != obj.getClass()){
			return false;
		}
		MamItemEvolucoesId other = (MamItemEvolucoesId) obj;
		if (evoSeq == null) {
			if (other.evoSeq != null){
				return false;
			}
		} else if (!evoSeq.equals(other.evoSeq)){
			return false;
		}
		if (tieSeq == null) {
			if (other.tieSeq != null){
				return false;
			}
		} else if (!tieSeq.equals(other.tieSeq)){
			return false;
		}
		return true;
	}
}
