package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MamPcControle generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mamPleSq1", sequenceName="AGH.MAM_PLE_SQ1", allocationSize = 1)
@Table(name = "MAM_PC_CONTROLES", schema = "AGH")
public class MamPcControle extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5868147350574160046L;
	private Integer seq;
	private Integer version;
	private RapServidores rapServidores;
	private Date criadoEm;
	private Date dtReferencia;
	private Date dthrInicio;
	private Date dthrFim;
	private Set<MamPcPaciente> mamPcPacientees = new HashSet<MamPcPaciente>(0);

	public MamPcControle() {
	}

	public MamPcControle(Integer seq, RapServidores rapServidores, Date criadoEm, Date dtReferencia) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.criadoEm = criadoEm;
		this.dtReferencia = dtReferencia;
	}

	public MamPcControle(Integer seq, RapServidores rapServidores, Date criadoEm, Date dtReferencia, Date dthrInicio, Date dthrFim,
			Set<MamPcPaciente> mamPcPacientees) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.criadoEm = criadoEm;
		this.dtReferencia = dtReferencia;
		this.dthrInicio = dthrInicio;
		this.dthrFim = dthrFim;
		this.mamPcPacientees = mamPcPacientees;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mamPleSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_REFERENCIA", nullable = false, length = 29)
	public Date getDtReferencia() {
		return this.dtReferencia;
	}

	public void setDtReferencia(Date dtReferencia) {
		this.dtReferencia = dtReferencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_INICIO", length = 29)
	public Date getDthrInicio() {
		return this.dthrInicio;
	}

	public void setDthrInicio(Date dthrInicio) {
		this.dthrInicio = dthrInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FIM", length = 29)
	public Date getDthrFim() {
		return this.dthrFim;
	}

	public void setDthrFim(Date dthrFim) {
		this.dthrFim = dthrFim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcControle")
	public Set<MamPcPaciente> getMamPcPacientees() {
		return this.mamPcPacientees;
	}

	public void setMamPcPacientees(Set<MamPcPaciente> mamPcPacientees) {
		this.mamPcPacientees = mamPcPacientees;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		CRIADO_EM("criadoEm"),
		DT_REFERENCIA("dtReferencia"),
		DTHR_INICIO("dthrInicio"),
		DTHR_FIM("dthrFim"),
		MAM_PC_PACIENTEES("mamPcPacientees");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamPcControle)) {
			return false;
		}
		MamPcControle other = (MamPcControle) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
