package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MamPcSumLegenda generated by hbm2java
 */
@Entity
@Table(name = "MAM_PC_SUM_LEGENDA", schema = "AGH")
public class MamPcSumLegenda extends BaseEntityId<MamPcSumLegendaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3599304160684629447L;
	private MamPcSumLegendaId id;
	private MamPcIntParada mamPcIntParada;

	public MamPcSumLegenda() {
	}

	public MamPcSumLegenda(MamPcSumLegendaId id) {
		this.id = id;
	}

	public MamPcSumLegenda(MamPcSumLegendaId id, MamPcIntParada mamPcIntParada) {
		this.id = id;
		this.mamPcIntParada = mamPcIntParada;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "prontuario", column = @Column(name = "PRONTUARIO")),
			@AttributeOverride(name = "recemNascido", column = @Column(name = "RECEM_NASCIDO", length = 1)),
			@AttributeOverride(name = "pertenceSumario", column = @Column(name = "PERTENCE_SUMARIO", nullable = false, length = 1)),
			@AttributeOverride(name = "dthrEvento", column = @Column(name = "DTHR_EVENTO", nullable = false, length = 29)),
			@AttributeOverride(name = "numeroLegenda", column = @Column(name = "NUMERO_LEGENDA", nullable = false)),
			@AttributeOverride(name = "descricao", column = @Column(name = "DESCRICAO", nullable = false, length = 120)),
			@AttributeOverride(name = "grupoLegenda", column = @Column(name = "GRUPO_LEGENDA", nullable = false)),
			@AttributeOverride(name = "pacCodigo", column = @Column(name = "PAC_CODIGO", nullable = false)),
			@AttributeOverride(name = "serVinCodigoConsultado", column = @Column(name = "SER_VIN_CODIGO_CONSULTADO")),
			@AttributeOverride(name = "serMatriculaConsultado", column = @Column(name = "SER_MATRICULA_CONSULTADO")),
			@AttributeOverride(name = "ltoLtoId", column = @Column(name = "LTO_LTO_ID", length = 5)),
			@AttributeOverride(name = "dthrFim", column = @Column(name = "DTHR_FIM", length = 29)),
			@AttributeOverride(name = "ppePleSeq", column = @Column(name = "PPE_PLE_SEQ")),
			@AttributeOverride(name = "ppeSeqp", column = @Column(name = "PPE_SEQP")),
			@AttributeOverride(name = "pirDthrCriacao", column = @Column(name = "PIR_DTHR_CRIACAO", length = 29)),
			@AttributeOverride(name = "pirAtdSeq", column = @Column(name = "PIR_ATD_SEQ")),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false)) })
	public MamPcSumLegendaId getId() {
		return this.id;
	}

	public void setId(MamPcSumLegendaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "PIR_ATD_SEQ", referencedColumnName = "ATD_SEQ", insertable = false, updatable = false),
			@JoinColumn(name = "PIR_DTHR_CRIACAO", referencedColumnName = "DTHR_CRIACAO", insertable = false, updatable = false) })
	public MamPcIntParada getMamPcIntParada() {
		return this.mamPcIntParada;
	}

	public void setMamPcIntParada(MamPcIntParada mamPcIntParada) {
		this.mamPcIntParada = mamPcIntParada;
	}

	public enum Fields {

		ID("id"),
		MAM_PC_INT_PARADAS("mamPcIntParada");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamPcSumLegenda)) {
			return false;
		}
		MamPcSumLegenda other = (MamPcSumLegenda) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
