package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MamPistaNotifInfeccao generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mamPnnSq1", sequenceName="AGH.MAM_PNN_SQ1", allocationSize = 1)
@Table(name = "MAM_PISTA_NOTIF_INFECCOES", schema = "AGH")
public class MamPistaNotifInfeccao extends BaseEntitySeq<Long> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8276625046689220145L;
	private Long seq;
	private Integer version;
	private String indTipoPista;
	private String contaminacao;
	private Date dthrEvento;
	private Date dtInicPergunta;
	private Date dtFimPerguntaRotina;
	private Date dtFimPergunta;
	private Date criadoEm;
	private Integer pacCodigo;
	private Integer crgSeq;
	private Integer atdSeq;
	private Integer serMatricula;
	private Short serVinCodigo;
	private AacConsultas consulta;
	private Set<MamRespostaNotifInfeccao> mamRespostaNotifInfeccaoes = new HashSet<MamRespostaNotifInfeccao>(0);

	public MamPistaNotifInfeccao() {
	}

	public MamPistaNotifInfeccao(Long seq, String indTipoPista, Date dthrEvento, Date dtInicPergunta, Date dtFimPerguntaRotina,
			Date dtFimPergunta, Date criadoEm, Integer pacCodigo, Integer serMatricula, Short serVinCodigo) {
		this.seq = seq;
		this.indTipoPista = indTipoPista;
		this.dthrEvento = dthrEvento;
		this.dtInicPergunta = dtInicPergunta;
		this.dtFimPerguntaRotina = dtFimPerguntaRotina;
		this.dtFimPergunta = dtFimPergunta;
		this.criadoEm = criadoEm;
		this.pacCodigo = pacCodigo;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mamPnnSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Long getSeq() {
		return this.seq;
	}

	public void setSeq(Long seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "IND_TIPO_PISTA", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndTipoPista() {
		return this.indTipoPista;
	}

	public void setIndTipoPista(String indTipoPista) {
		this.indTipoPista = indTipoPista;
	}

	@Column(name = "CONTAMINACAO", length = 1)
	@Length(max = 1)
	public String getContaminacao() {
		return this.contaminacao;
	}

	public void setContaminacao(String contaminacao) {
		this.contaminacao = contaminacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_EVENTO", nullable = false, length = 29)
	public Date getDthrEvento() {
		return this.dthrEvento;
	}

	public void setDthrEvento(Date dthrEvento) {
		this.dthrEvento = dthrEvento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INIC_PERGUNTA", nullable = false, length = 29)
	public Date getDtInicPergunta() {
		return this.dtInicPergunta;
	}

	public void setDtInicPergunta(Date dtInicPergunta) {
		this.dtInicPergunta = dtInicPergunta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM_PERGUNTA_ROTINA", nullable = false, length = 29)
	public Date getDtFimPerguntaRotina() {
		return this.dtFimPerguntaRotina;
	}

	public void setDtFimPerguntaRotina(Date dtFimPerguntaRotina) {
		this.dtFimPerguntaRotina = dtFimPerguntaRotina;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM_PERGUNTA", nullable = false, length = 29)
	public Date getDtFimPergunta() {
		return this.dtFimPergunta;
	}

	public void setDtFimPergunta(Date dtFimPergunta) {
		this.dtFimPergunta = dtFimPergunta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "PAC_CODIGO", nullable = false)
	public Integer getPacCodigo() {
		return this.pacCodigo;
	}

	public void setPacCodigo(Integer pacCodigo) {
		this.pacCodigo = pacCodigo;
	}

	@Column(name = "CRG_SEQ")
	public Integer getCrgSeq() {
		return this.crgSeq;
	}

	public void setCrgSeq(Integer crgSeq) {
		this.crgSeq = crgSeq;
	}

	@Column(name = "ATD_SEQ")
	public Integer getAtdSeq() {
		return this.atdSeq;
	}

	public void setAtdSeq(Integer atdSeq) {
		this.atdSeq = atdSeq;
	}

	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_NUMERO")
	public AacConsultas getConsulta() {
		return consulta;
	}
	
	public void setConsulta(AacConsultas consulta) {
		this.consulta = consulta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPistaNotifInfeccao")
	public Set<MamRespostaNotifInfeccao> getMamRespostaNotifInfeccaoes() {
		return this.mamRespostaNotifInfeccaoes;
	}

	public void setMamRespostaNotifInfeccaoes(Set<MamRespostaNotifInfeccao> mamRespostaNotifInfeccaoes) {
		this.mamRespostaNotifInfeccaoes = mamRespostaNotifInfeccaoes;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		IND_TIPO_PISTA("indTipoPista"),
		CONTAMINACAO("contaminacao"),
		DTHR_EVENTO("dthrEvento"),
		DT_INIC_PERGUNTA("dtInicPergunta"),
		DT_FIM_PERGUNTA_ROTINA("dtFimPerguntaRotina"),
		DT_FIM_PERGUNTA("dtFimPergunta"),
		CRIADO_EM("criadoEm"),
		PAC_CODIGO("pacCodigo"),
		CRG_SEQ("crgSeq"),
		ATD_SEQ("atdSeq"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		CONSULTA("consulta"),
		MAM_RESPOSTA_NOTIF_INFECCAOES("mamRespostaNotifInfeccaoes"),
		CONSULTA_CON_NUMERO("consulta.numero");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamPistaNotifInfeccao)) {
			return false;
		}
		MamPistaNotifInfeccao other = (MamPistaNotifInfeccao) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
