package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSumarioExame;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MamPcSumExameTab generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mamSeaSq1", sequenceName="AGH.MAM_SEA_SQ1", allocationSize = 1)
@Table(name = "MAM_PC_SUM_EXAMES_TAB", schema = "AGH")
public class MamPcSumExameTab extends BaseEntitySeq<Long> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2843937744570596210L;
	private Long seq;
	private MamPcPaciente mamPcPaciente;
	private MamPcIntParada mamPcIntParada;
	private Integer prontuario;
	private String ltoLtoId;
	private Boolean recemNascido;
	private String ufeEmaExaSigla;
	private Integer ufeEmaManSeq;
	private Short ufeUnfSeq;
	private DominioSumarioExame pertenceSumario;
	private Integer iseSoeSeqDept;
	private Short iseSeqpDept;
	private Integer calSeq;
	private String calNome;
	private Double reeValor;
	private Integer iseSoeSeq;
	private Short iseSeqp;
	private Integer cacSeq;
	private Integer rcdGtcSeq;
	private Integer rcdSeqp;
	private String descricao;
	private Date dthrEventoAreaExec;
	private Short ordem;
	private String calNomeSumario;
	private Integer pacCodigo;
	private Short serVinCodigoConsultado;
	private Integer serMatriculaConsultado;
	private Boolean indImprime;
	private Date dthrFim;
	private Integer ppePleSeq;
	private Integer ppeSeqp;
	private Integer pirAtdSeq;
	private Date pirDthrCriacao;
	private Integer version;

	public MamPcSumExameTab() {
	}
	
	public MamPcSumExameTab(Boolean recemNascido, String ufeEmaExaSigla, Integer ufeEmaManSeq, Short ufeUnfSeq, DominioSumarioExame pertenceSumario,
			Integer calSeq, String calNome, Integer iseSoeSeq, Short iseSeqp, Date dthrEventoAreaExec, Integer pacCodigo, Integer version) {
		this.recemNascido = recemNascido;
		this.ufeEmaExaSigla = ufeEmaExaSigla;
		this.ufeEmaManSeq = ufeEmaManSeq;
		this.ufeUnfSeq = ufeUnfSeq;
		this.pertenceSumario = pertenceSumario;
		this.calSeq = calSeq;
		this.calNome = calNome;
		this.iseSoeSeq = iseSoeSeq;
		this.iseSeqp = iseSeqp;
		this.dthrEventoAreaExec = dthrEventoAreaExec;
		this.pacCodigo = pacCodigo;
		this.version = version;
	}

	@SuppressWarnings({"PMD.ExcessiveParameterList"})
	public MamPcSumExameTab(Integer prontuario, Integer pacCodigo, String ltoLtoId,  Boolean recemNascido, String ufeEmaExaSigla, Integer ufeEmaManSeq,
						    Short ufeUnfSeq, DominioSumarioExame pertenceSumario, Integer iseSoeSeqDept, Short iseSeqpDept, Integer calSeq, String calNome,
							Double reeValor, Integer iseSoeSeq, Short iseSeqp, Integer cacSeq, Integer rcdGtcSeq, Integer rcdSeqp, String descricao,
							Date dthrEventoAreaExec, Short ordem, String calNomeSumario, Boolean indImprime, Date dthrFim, Integer ppePleSeq, Integer ppeSeqp,
							Short serVinCodigoConsultado, Integer serMatriculaConsultado, Integer pirAtdSeq, Date pirDthrCriacao, Integer version) {
			
		this.prontuario = prontuario;
		this.ltoLtoId = ltoLtoId;
		this.recemNascido = recemNascido;
		this.ufeEmaExaSigla = ufeEmaExaSigla;
		this.ufeEmaManSeq = ufeEmaManSeq;
		this.ufeUnfSeq = ufeUnfSeq;
		this.pertenceSumario = pertenceSumario;
		this.iseSoeSeqDept = iseSoeSeqDept;
		this.iseSeqpDept = iseSeqpDept;
		this.calSeq = calSeq;
		this.calNome = calNome;
		this.reeValor = reeValor;
		this.iseSoeSeq = iseSoeSeq;
		this.iseSeqp = iseSeqp;
		this.cacSeq = cacSeq;
		this.rcdGtcSeq = rcdGtcSeq;
		this.rcdSeqp = rcdSeqp;
		this.descricao = descricao;
		this.dthrEventoAreaExec = dthrEventoAreaExec;
		this.ordem = ordem;
		this.calNomeSumario = calNomeSumario;
		this.pacCodigo = pacCodigo;
		this.serVinCodigoConsultado = serVinCodigoConsultado;
		this.serMatriculaConsultado = serMatriculaConsultado;
		this.indImprime = indImprime;
		this.dthrFim = dthrFim;
		this.ppePleSeq = ppePleSeq;
		this.ppeSeqp = ppeSeqp;
		this.pirAtdSeq = pirAtdSeq;
		this.pirDthrCriacao = pirDthrCriacao;
		this.version = version;
	}
	
	public MamPcSumExameTab(Integer prontuario, Boolean recemNascido, Integer pacCodigo, Integer pirAtdSeq) {
		this.prontuario = prontuario;
		this.recemNascido = recemNascido;
		this.pacCodigo = pacCodigo;
		this.pirAtdSeq = pirAtdSeq;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mamSeaSq1")
	@Column(name = "SEQ", nullable = false, precision = 19, scale = 0)
	public Long getSeq() {
		return seq;
	}
	
	public void setSeq(Long seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "PPE_PLE_SEQ", referencedColumnName = "PLE_SEQ", insertable = false, updatable = false),
			@JoinColumn(name = "PPE_SEQP", referencedColumnName = "SEQP", insertable = false, updatable = false) })
	public MamPcPaciente getMamPcPaciente() {
		return this.mamPcPaciente;
	}

	public void setMamPcPaciente(MamPcPaciente mamPcPaciente) {
		this.mamPcPaciente = mamPcPaciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "PIR_ATD_SEQ", referencedColumnName = "ATD_SEQ", insertable = false, updatable = false),
			@JoinColumn(name = "PIR_DTHR_CRIACAO", referencedColumnName = "DTHR_CRIACAO", insertable = false, updatable = false) })
	public MamPcIntParada getMamPcIntParada() {
		return this.mamPcIntParada;
	}

	public void setMamPcIntParada(MamPcIntParada mamPcIntParada) {
		this.mamPcIntParada = mamPcIntParada;
	}

	@Column(name = "PRONTUARIO")
	public Integer getProntuario() {
		return this.prontuario;
	}

	public void setProntuario(Integer prontuario) {
		this.prontuario = prontuario;
	}

	@Column(name = "LTO_LTO_ID", length = 5)
	@Length(max = 5)
	public String getLtoLtoId() {
		return this.ltoLtoId;
	}

	public void setLtoLtoId(String ltoLtoId) {
		this.ltoLtoId = ltoLtoId;
	}

	@Column(name = "RECEM_NASCIDO", nullable = false, length = 1)
	@Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getRecemNascido() {
		return this.recemNascido;
	}

	public void setRecemNascido(Boolean recemNascido) {
		this.recemNascido = recemNascido;
	}

	@Column(name = "UFE_EMA_EXA_SIGLA", nullable = false, length = 5)
	@Length(max = 5)
	public String getUfeEmaExaSigla() {
		return this.ufeEmaExaSigla;
	}

	public void setUfeEmaExaSigla(String ufeEmaExaSigla) {
		this.ufeEmaExaSigla = ufeEmaExaSigla;
	}

	@Column(name = "UFE_EMA_MAN_SEQ", nullable = false)
	public Integer getUfeEmaManSeq() {
		return this.ufeEmaManSeq;
	}

	public void setUfeEmaManSeq(Integer ufeEmaManSeq) {
		this.ufeEmaManSeq = ufeEmaManSeq;
	}

	@Column(name = "UFE_UNF_SEQ", nullable = false)
	public Short getUfeUnfSeq() {
		return this.ufeUnfSeq;
	}

	public void setUfeUnfSeq(Short ufeUnfSeq) {
		this.ufeUnfSeq = ufeUnfSeq;
	}

	@Column(name = "PERTENCE_SUMARIO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSumarioExame getPertenceSumario() {
		return this.pertenceSumario;
	}

	public void setPertenceSumario(DominioSumarioExame pertenceSumario) {
		this.pertenceSumario = pertenceSumario;
	}

	@Column(name = "ISE_SOE_SEQ_DEPT")
	public Integer getIseSoeSeqDept() {
		return this.iseSoeSeqDept;
	}

	public void setIseSoeSeqDept(Integer iseSoeSeqDept) {
		this.iseSoeSeqDept = iseSoeSeqDept;
	}

	@Column(name = "ISE_SEQP_DEPT")
	public Short getIseSeqpDept() {
		return this.iseSeqpDept;
	}

	public void setIseSeqpDept(Short iseSeqpDept) {
		this.iseSeqpDept = iseSeqpDept;
	}

	@Column(name = "CAL_SEQ", nullable = false)
	public Integer getCalSeq() {
		return this.calSeq;
	}

	public void setCalSeq(Integer calSeq) {
		this.calSeq = calSeq;
	}

	@Column(name = "CAL_NOME", nullable = false, length = 100)
	@Length(max = 100)
	public String getCalNome() {
		return this.calNome;
	}

	public void setCalNome(String calNome) {
		this.calNome = calNome;
	}

	@Column(name = "REE_VALOR", precision = 17, scale = 17)
	public Double getReeValor() {
		return this.reeValor;
	}
	
	public void setReeValor(Double reeValor) {
		this.reeValor = reeValor;
	}

	@Column(name = "ISE_SOE_SEQ", nullable = false)
	public Integer getIseSoeSeq() {
		return this.iseSoeSeq;
	}

	public void setIseSoeSeq(Integer iseSoeSeq) {
		this.iseSoeSeq = iseSoeSeq;
	}

	@Column(name = "ISE_SEQP", nullable = false)
	public Short getIseSeqp() {
		return this.iseSeqp;
	}

	public void setIseSeqp(Short iseSeqp) {
		this.iseSeqp = iseSeqp;
	}

	@Column(name = "CAC_SEQ")
	public Integer getCacSeq() {
		return this.cacSeq;
	}

	public void setCacSeq(Integer cacSeq) {
		this.cacSeq = cacSeq;
	}

	@Column(name = "RCD_GTC_SEQ")
	public Integer getRcdGtcSeq() {
		return this.rcdGtcSeq;
	}

	public void setRcdGtcSeq(Integer rcdGtcSeq) {
		this.rcdGtcSeq = rcdGtcSeq;
	}

	@Column(name = "RCD_SEQP")
	public Integer getRcdSeqp() {
		return this.rcdSeqp;
	}

	public void setRcdSeqp(Integer rcdSeqp) {
		this.rcdSeqp = rcdSeqp;
	}

	@Lob
	@Type(type="text")
	@Column(name = "DESCRICAO")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "DTHR_EVENTO_AREA_EXEC", nullable = false, length = 29)
	public Date getDthrEventoAreaExec() {
		return this.dthrEventoAreaExec;
	}

	public void setDthrEventoAreaExec(Date dthrEventoAreaExec) {
		this.dthrEventoAreaExec = dthrEventoAreaExec;
	}

	@Column(name = "ORDEM")
	public Short getOrdem() {
		return this.ordem;
	}

	public void setOrdem(Short ordem) {
		this.ordem = ordem;
	}

	@Column(name = "CAL_NOME_SUMARIO", length = 30)
	@Length(max = 30)
	public String getCalNomeSumario() {
		return this.calNomeSumario;
	}

	public void setCalNomeSumario(String calNomeSumario) {
		this.calNomeSumario = calNomeSumario;
	}

	@Column(name = "PAC_CODIGO", nullable = false)
	public Integer getPacCodigo() {
		return this.pacCodigo;
	}

	public void setPacCodigo(Integer pacCodigo) {
		this.pacCodigo = pacCodigo;
	}

	@Column(name = "SER_VIN_CODIGO_CONSULTADO")
	public Short getSerVinCodigoConsultado() {
		return this.serVinCodigoConsultado;
	}

	public void setSerVinCodigoConsultado(Short serVinCodigoConsultado) {
		this.serVinCodigoConsultado = serVinCodigoConsultado;
	}

	@Column(name = "SER_MATRICULA_CONSULTADO")
	public Integer getSerMatriculaConsultado() {
		return this.serMatriculaConsultado;
	}

	public void setSerMatriculaConsultado(Integer serMatriculaConsultado) {
		this.serMatriculaConsultado = serMatriculaConsultado;
	}

	@Column(name = "IND_IMPRIME", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndImprime() {
		return this.indImprime;
	}

	public void setIndImprime(Boolean indImprime) {
		this.indImprime = indImprime;
	}

	@Column(name = "DTHR_FIM", length = 29)
	public Date getDthrFim() {
		return this.dthrFim;
	}

	public void setDthrFim(Date dthrFim) {
		this.dthrFim = dthrFim;
	}

	@Column(name = "PPE_PLE_SEQ")
	public Integer getPpePleSeq() {
		return this.ppePleSeq;
	}

	public void setPpePleSeq(Integer ppePleSeq) {
		this.ppePleSeq = ppePleSeq;
	}

	@Column(name = "PPE_SEQP")
	public Integer getPpeSeqp() {
		return this.ppeSeqp;
	}

	public void setPpeSeqp(Integer ppeSeqp) {
		this.ppeSeqp = ppeSeqp;
	}

	@Column(name = "PIR_ATD_SEQ")
	public Integer getPirAtdSeq() {
		return this.pirAtdSeq;
	}

	public void setPirAtdSeq(Integer pirAtdSeq) {
		this.pirAtdSeq = pirAtdSeq;
	}

	@Column(name = "PIR_DTHR_CRIACAO", length = 29)
	public Date getPirDthrCriacao() {
		return this.pirDthrCriacao;
	}

	public void setPirDthrCriacao(Date pirDthrCriacao) {
		this.pirDthrCriacao = pirDthrCriacao;
	}

	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	
	public enum Fields {

		PAC_CODIGO("pacCodigo"),
		PIR_ATD_SEQ("pirAtdSeq"),
		PIR_DTHR_CRIACAO("pirDthrCriacao"),		
		MAM_PC_PACIENTES("mamPcPaciente"),
		MAM_PC_INT_PARADAS("mamPcIntParada"),
		RECEM_NASCIDO("recemNascido"),
		PRONTUARIO("prontuario"),
		DTHR_EVENTO_AREA_EXEC("dthrEventoAreaExec"),
		ORDEM("ordem"),
		PERTENCE_SUMARIO("pertenceSumario");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamPcSumExameTab)) {
			return false;
		}
		MamPcSumExameTab other = (MamPcSumExameTab) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
