package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MamPcIntParada generated by hbm2java
 */
@Entity
@Table(name = "MAM_PC_INT_PARADAS", schema = "AGH")
public class MamPcIntParada extends BaseEntityId<MamPcIntParadaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7163726910161829833L;
	private MamPcIntParadaId id;
	private Integer version;
	private AghAtendimentos aghAtendimentos;
	private String situacao;
	private Date dthrUltExecucao;
	private Date dthrGeracaoPdf;
	private String servidor;
	private Set<MamPcSumExameMasc> mamPcSumExameMascs = new HashSet<MamPcSumExameMasc>(0);
	private Set<MamPcSumLegenda> mamPcSumLegendas = new HashSet<MamPcSumLegenda>(0);
	private Set<MamPcHorarioCtrl> mamPcHorarioCtrles = new HashSet<MamPcHorarioCtrl>(0);
	private Set<MamPcIntItemParada> mamPcIntItemParadaes = new HashSet<MamPcIntItemParada>(0);
	private Set<MamPcSumExameTab> mamPcSumExameTabs = new HashSet<MamPcSumExameTab>(0);
	private Set<MamPcSumObservacao> mamPcSumObservacaos = new HashSet<MamPcSumObservacao>(0);
	private Set<MamPcSumMascCampoEdit> mamPcSumMascCampoEdits = new HashSet<MamPcSumMascCampoEdit>(0);
	private Set<MamPcSumMascLinha> mamPcSumMascLinhas = new HashSet<MamPcSumMascLinha>(0);
	private Set<MamPcControlePac> mamPcControlePaces = new HashSet<MamPcControlePac>(0);

	public MamPcIntParada() {
	}

	public MamPcIntParada(MamPcIntParadaId id, AghAtendimentos aghAtendimentos, String situacao) {
		this.id = id;
		this.aghAtendimentos = aghAtendimentos;
		this.situacao = situacao;
	}

	public MamPcIntParada(MamPcIntParadaId id, AghAtendimentos aghAtendimentos, String situacao, Date dthrUltExecucao,
			Date dthrGeracaoPdf, String servidor, Set<MamPcSumExameMasc> mamPcSumExameMascs, Set<MamPcSumLegenda> mamPcSumLegendas,
			Set<MamPcHorarioCtrl> mamPcHorarioCtrles, Set<MamPcIntItemParada> mamPcIntItemParadaes,
			Set<MamPcSumExameTab> mamPcSumExameTabs, Set<MamPcSumObservacao> mamPcSumObservacaos,
			Set<MamPcSumMascCampoEdit> mamPcSumMascCampoEdits, Set<MamPcSumMascLinha> mamPcSumMascLinhas,
			Set<MamPcControlePac> mamPcControlePaces) {
		this.id = id;
		this.aghAtendimentos = aghAtendimentos;
		this.situacao = situacao;
		this.dthrUltExecucao = dthrUltExecucao;
		this.dthrGeracaoPdf = dthrGeracaoPdf;
		this.servidor = servidor;
		this.mamPcSumExameMascs = mamPcSumExameMascs;
		this.mamPcSumLegendas = mamPcSumLegendas;
		this.mamPcHorarioCtrles = mamPcHorarioCtrles;
		this.mamPcIntItemParadaes = mamPcIntItemParadaes;
		this.mamPcSumExameTabs = mamPcSumExameTabs;
		this.mamPcSumObservacaos = mamPcSumObservacaos;
		this.mamPcSumMascCampoEdits = mamPcSumMascCampoEdits;
		this.mamPcSumMascLinhas = mamPcSumMascLinhas;
		this.mamPcControlePaces = mamPcControlePaces;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "atdSeq", column = @Column(name = "ATD_SEQ", nullable = false)),
			@AttributeOverride(name = "dthrCriacao", column = @Column(name = "DTHR_CRIACAO", nullable = false, length = 29)) })
	public MamPcIntParadaId getId() {
		return this.id;
	}

	public void setId(MamPcIntParadaId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATD_SEQ", nullable = false, insertable = false, updatable = false)
	public AghAtendimentos getAghAtendimentos() {
		return this.aghAtendimentos;
	}

	public void setAghAtendimentos(AghAtendimentos aghAtendimentos) {
		this.aghAtendimentos = aghAtendimentos;
	}

	@Column(name = "SITUACAO", nullable = false, length = 3)
	@Length(max = 3)
	public String getSituacao() {
		return this.situacao;
	}

	public void setSituacao(String situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_ULT_EXECUCAO", length = 29)
	public Date getDthrUltExecucao() {
		return this.dthrUltExecucao;
	}

	public void setDthrUltExecucao(Date dthrUltExecucao) {
		this.dthrUltExecucao = dthrUltExecucao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_GERACAO_PDF", length = 29)
	public Date getDthrGeracaoPdf() {
		return this.dthrGeracaoPdf;
	}

	public void setDthrGeracaoPdf(Date dthrGeracaoPdf) {
		this.dthrGeracaoPdf = dthrGeracaoPdf;
	}

	@Column(name = "SERVIDOR", length = 15)
	@Length(max = 15)
	public String getServidor() {
		return this.servidor;
	}

	public void setServidor(String servidor) {
		this.servidor = servidor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcSumExameMasc> getMamPcSumExameMascs() {
		return this.mamPcSumExameMascs;
	}

	public void setMamPcSumExameMascs(Set<MamPcSumExameMasc> mamPcSumExameMascs) {
		this.mamPcSumExameMascs = mamPcSumExameMascs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcSumLegenda> getMamPcSumLegendas() {
		return this.mamPcSumLegendas;
	}

	public void setMamPcSumLegendas(Set<MamPcSumLegenda> mamPcSumLegendas) {
		this.mamPcSumLegendas = mamPcSumLegendas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcHorarioCtrl> getMamPcHorarioCtrles() {
		return this.mamPcHorarioCtrles;
	}

	public void setMamPcHorarioCtrles(Set<MamPcHorarioCtrl> mamPcHorarioCtrles) {
		this.mamPcHorarioCtrles = mamPcHorarioCtrles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcIntItemParada> getMamPcIntItemParadaes() {
		return this.mamPcIntItemParadaes;
	}

	public void setMamPcIntItemParadaes(Set<MamPcIntItemParada> mamPcIntItemParadaes) {
		this.mamPcIntItemParadaes = mamPcIntItemParadaes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcSumExameTab> getMamPcSumExameTabs() {
		return this.mamPcSumExameTabs;
	}

	public void setMamPcSumExameTabs(Set<MamPcSumExameTab> mamPcSumExameTabs) {
		this.mamPcSumExameTabs = mamPcSumExameTabs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcSumObservacao> getMamPcSumObservacaos() {
		return this.mamPcSumObservacaos;
	}

	public void setMamPcSumObservacaos(Set<MamPcSumObservacao> mamPcSumObservacaos) {
		this.mamPcSumObservacaos = mamPcSumObservacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcSumMascCampoEdit> getMamPcSumMascCampoEdits() {
		return this.mamPcSumMascCampoEdits;
	}

	public void setMamPcSumMascCampoEdits(Set<MamPcSumMascCampoEdit> mamPcSumMascCampoEdits) {
		this.mamPcSumMascCampoEdits = mamPcSumMascCampoEdits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcSumMascLinha> getMamPcSumMascLinhas() {
		return this.mamPcSumMascLinhas;
	}

	public void setMamPcSumMascLinhas(Set<MamPcSumMascLinha> mamPcSumMascLinhas) {
		this.mamPcSumMascLinhas = mamPcSumMascLinhas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mamPcIntParada")
	public Set<MamPcControlePac> getMamPcControlePaces() {
		return this.mamPcControlePaces;
	}

	public void setMamPcControlePaces(Set<MamPcControlePac> mamPcControlePaces) {
		this.mamPcControlePaces = mamPcControlePaces;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		AGH_ATENDIMENTOS("aghAtendimentos"),
		SITUACAO("situacao"),
		DTHR_ULT_EXECUCAO("dthrUltExecucao"),
		DTHR_GERACAO_PDF("dthrGeracaoPdf"),
		SERVIDOR("servidor"),
		ATENDIMENTO_SEQ("aghAtendimentos.seq"),
		MAM_PC_SUM_EXAME_MASCS("mamPcSumExameMascs"),
		MAM_PC_SUM_LEGENDAS("mamPcSumLegendas"),
		MAM_PC_HORARIO_CTRLES("mamPcHorarioCtrles"),
		MAM_PC_INT_ITEM_PARADAES("mamPcIntItemParadaes"),
		MAM_PC_SUM_EXAME_TABS("mamPcSumExameTabs"),
		MAM_PC_SUM_OBSERVACAOS("mamPcSumObservacaos"),
		MAM_PC_SUM_MASC_CAMPO_EDITS("mamPcSumMascCampoEdits"),
		MAM_PC_SUM_MASC_LINHAS("mamPcSumMascLinhas"),
		MAM_PC_CONTROLE_PACES("mamPcControlePaces"),
		PIR_ATD_SEQ("id.atdSeq"),
		PIR_DTHR_CRIACAO("id.dthrCriacao");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamPcIntParada)) {
			return false;
		}
		MamPcIntParada other = (MamPcIntParada) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
