package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MamTmpEmgListaResumoId generated by hbm2java
 */
@Embeddable
public class MamTmpEmgListaResumoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9159631861581294320L;
	private Long tm1Seq;
	private Integer tm1Seqp;
	private Short seqp;

	public MamTmpEmgListaResumoId() {
	}

	public MamTmpEmgListaResumoId(Long tm1Seq, Integer tm1Seqp, Short seqp) {
		this.tm1Seq = tm1Seq;
		this.tm1Seqp = tm1Seqp;
		this.seqp = seqp;
	}

	@Column(name = "TM1_SEQ", nullable = false)
	public Long getTm1Seq() {
		return this.tm1Seq;
	}

	public void setTm1Seq(Long tm1Seq) {
		this.tm1Seq = tm1Seq;
	}

	@Column(name = "TM1_SEQP", nullable = false)
	public Integer getTm1Seqp() {
		return this.tm1Seqp;
	}

	public void setTm1Seqp(Integer tm1Seqp) {
		this.tm1Seqp = tm1Seqp;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}






	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getTm1Seq());
		umHashCodeBuilder.append(this.getTm1Seqp());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamTmpEmgListaResumoId)) {
			return false;
		}
		MamTmpEmgListaResumoId other = (MamTmpEmgListaResumoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getTm1Seq(), other.getTm1Seq());
		umEqualsBuilder.append(this.getTm1Seqp(), other.getTm1Seqp());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
