package br.gov.mec.aghu.model;

// Generated 11/10/2011 19:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MamTrgEncAmbulatoriais generated by hbm2java
 */

@Entity
@Table(name = "MAM_TRG_ENC_AMBULATORIAIS", schema = "AGH")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.TRANSACTIONAL)
public class MamTrgEncAmbulatoriais extends BaseEntityId<MamTrgEncAmbulatoriaisId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6707946722574882376L;
	private MamTrgEncAmbulatoriaisId id;
	private Integer version;
	private String observacao;
	private Short eqpSeq;
	private AghEspecialidades especialidade;
	private Date criadoEm;
	private String micNome;
	private String indImpresso;
	private RapServidores servidor;
	private Integer serMatriculaResponsavel;
	private Short serVinCodigoResponsavel;
	private Date dthrEstorno;
	private Integer serMatriculaEstornado;
	private Short serVinCodigoEstornado;

	public MamTrgEncAmbulatoriais() {
	}

	public MamTrgEncAmbulatoriais(MamTrgEncAmbulatoriaisId id,
			AghEspecialidades especialidade, Date criadoEm, String indImpresso) {
		super();
		this.id = id;
		this.especialidade = especialidade;
		this.criadoEm = criadoEm;
		this.indImpresso = indImpresso;
	}

	

	public MamTrgEncAmbulatoriais(MamTrgEncAmbulatoriaisId id, Integer version,
			String observacao, Short eqpSeq, AghEspecialidades especialidade,
			Date criadoEm, String micNome, String indImpresso,
			RapServidores servidor, Integer serMatriculaResponsavel,
			Short serVinCodigoResponsavel, Date dthrEstorno,
			Integer serMatriculaEstornado, Short serVinCodigoEstornado) {
		super();
		this.id = id;
		this.version = version;
		this.observacao = observacao;
		this.eqpSeq = eqpSeq;
		this.especialidade = especialidade;
		this.criadoEm = criadoEm;
		this.micNome = micNome;
		this.indImpresso = indImpresso;
		this.servidor = servidor;
		this.serMatriculaResponsavel = serMatriculaResponsavel;
		this.serVinCodigoResponsavel = serVinCodigoResponsavel;
		this.dthrEstorno = dthrEstorno;
		this.serMatriculaEstornado = serMatriculaEstornado;
		this.serVinCodigoEstornado = serVinCodigoEstornado;
	}


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "trgSeq", column = @Column(name = "TRG_SEQ", nullable = false)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false)) })
	public MamTrgEncAmbulatoriaisId getId() {
		return this.id;
	}

	public void setId(MamTrgEncAmbulatoriaisId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "OBSERVACAO", length = 2000)
	@Length(max = 2000)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "EQP_SEQ")
	public Short getEqpSeq() {
		return this.eqpSeq;
	}

	public void setEqpSeq(Short eqpSeq) {
		this.eqpSeq = eqpSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESP_SEQ")
	public AghEspecialidades getEspecialidade() {
		return especialidade;
	}

	public void setEspecialidade(AghEspecialidades especialidade) {
		this.especialidade = especialidade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "MIC_NOME", length = 50)
	@Length(max = 50)
	public String getMicNome() {
		return this.micNome;
	}

	public void setMicNome(String micNome) {
		this.micNome = micNome;
	}

	@Column(name = "IND_IMPRESSO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndImpresso() {
		return this.indImpresso;
	}

	public void setIndImpresso(String indImpresso) {
		this.indImpresso = indImpresso;
	}

	@Column(name = "SER_MATRICULA_RESPONSAVEL")
	public Integer getSerMatriculaResponsavel() {
		return this.serMatriculaResponsavel;
	}

	public void setSerMatriculaResponsavel(Integer serMatriculaResponsavel) {
		this.serMatriculaResponsavel = serMatriculaResponsavel;
	}

	@Column(name = "SER_VIN_CODIGO_RESPONSAVEL")
	public Short getSerVinCodigoResponsavel() {
		return this.serVinCodigoResponsavel;
	}

	public void setSerVinCodigoResponsavel(Short serVinCodigoResponsavel) {
		this.serVinCodigoResponsavel = serVinCodigoResponsavel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_ESTORNO", length = 29)
	public Date getDthrEstorno() {
		return this.dthrEstorno;
	}

	public void setDthrEstorno(Date dthrEstorno) {
		this.dthrEstorno = dthrEstorno;
	}

	@Column(name = "SER_MATRICULA_ESTORNADO")
	public Integer getSerMatriculaEstornado() {
		return this.serMatriculaEstornado;
	}

	public void setSerMatriculaEstornado(Integer serMatriculaEstornado) {
		this.serMatriculaEstornado = serMatriculaEstornado;
	}

	@Column(name = "SER_VIN_CODIGO_ESTORNADO")
	public Short getSerVinCodigoEstornado() {
		return this.serVinCodigoEstornado;
	}

	public void setSerVinCodigoEstornado(Short serVinCodigoEstornado) {
		this.serVinCodigoEstornado = serVinCodigoEstornado;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable=false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable=false) })
	public RapServidores getServidor() {
		return servidor;
	}
	
	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}
	
	public enum Fields {
		
		TRG_SEQ("id.trgSeq"),
		SEQP("id.seqp"),
		CRIADO_EM("criadoEm"),
		SER_MATRICULA("servidor.id.matricula"),
		SER_VIN_CODIGO("servidor.id.vinCodigo"),
		DTHR_ESTORNO("dthrEstorno"),
		SER_MATRICULA_ESTORNADO("serMatriculaEstornado"),
		SER_VIN_CODIGO_ESTORNADO("serVinCodigoEstornado"),
		ESPECIALIDADE("especialidade")
		;
		
		private String fields;
		
		private Fields(String fields) {
			this.fields = fields;
		}
		
		@Override
		public String toString() {
			return this.fields;
		}
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamTrgEncAmbulatoriais)) {
			return false;
		}
		MamTrgEncAmbulatoriais other = (MamTrgEncAmbulatoriais) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
