package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MamTmpImpTriagem generated by hbm2java
 */
@Entity
@Table(name = "MAM_TMP_IMP_TRIAGENS", schema = "AGH")
public class MamTmpImpTriagem extends BaseEntityId<MamTmpImpTriagemId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6694500656101960092L;
	private MamTmpImpTriagemId id;
	private Integer version;
	private MamEvolucoes mamEvolucoes;
	private MamAnamneses mamAnamneses;
	private MamRegistro mamRegistro;
	private Long trgSeq;
	private Integer pacCodigo;
	private Long eaaSeq;

	public MamTmpImpTriagem() {
	}

	public MamTmpImpTriagem(MamTmpImpTriagemId id, Integer pacCodigo) {
		this.id = id;
		this.pacCodigo = pacCodigo;
	}

	public MamTmpImpTriagem(MamTmpImpTriagemId id, MamEvolucoes mamEvolucoes, MamAnamneses mamAnamneses, MamRegistro mamRegistro,
			Long trgSeq, Integer pacCodigo, Long eaaSeq) {
		this.id = id;
		this.mamEvolucoes = mamEvolucoes;
		this.mamAnamneses = mamAnamneses;
		this.mamRegistro = mamRegistro;
		this.trgSeq = trgSeq;
		this.pacCodigo = pacCodigo;
		this.eaaSeq = eaaSeq;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "nroSessao", column = @Column(name = "NRO_SESSAO", nullable = false)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false)) })
	public MamTmpImpTriagemId getId() {
		return this.id;
	}

	public void setId(MamTmpImpTriagemId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVO_SEQ")
	public MamEvolucoes getMamEvolucoes() {
		return this.mamEvolucoes;
	}

	public void setMamEvolucoes(MamEvolucoes mamEvolucoes) {
		this.mamEvolucoes = mamEvolucoes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ANA_SEQ")
	public MamAnamneses getMamAnamneses() {
		return this.mamAnamneses;
	}

	public void setMamAnamneses(MamAnamneses mamAnamneses) {
		this.mamAnamneses = mamAnamneses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RGT_SEQ")
	public MamRegistro getMamRegistro() {
		return this.mamRegistro;
	}

	public void setMamRegistro(MamRegistro mamRegistro) {
		this.mamRegistro = mamRegistro;
	}

	@Column(name = "TRG_SEQ")
	public Long getTrgSeq() {
		return this.trgSeq;
	}

	public void setTrgSeq(Long trgSeq) {
		this.trgSeq = trgSeq;
	}

	@Column(name = "PAC_CODIGO", nullable = false)
	public Integer getPacCodigo() {
		return this.pacCodigo;
	}

	public void setPacCodigo(Integer pacCodigo) {
		this.pacCodigo = pacCodigo;
	}

	@Column(name = "EAA_SEQ")
	public Long getEaaSeq() {
		return this.eaaSeq;
	}

	public void setEaaSeq(Long eaaSeq) {
		this.eaaSeq = eaaSeq;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		MAM_EVOLUCOES("mamEvolucoes"),
		MAM_ANAMNESES("mamAnamneses"),
		MAM_REGISTRO("mamRegistro"),
		TRG_SEQ("trgSeq"),
		PAC_CODIGO("pacCodigo"),
		EAA_SEQ("eaaSeq");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamTmpImpTriagem)) {
			return false;
		}
		MamTmpImpTriagem other = (MamTmpImpTriagem) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
