package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MamUnidXMedicacaoId generated by hbm2java
 */
@Embeddable
public class MamUnidXMedicacaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4803399578676219802L;
	private Integer mdmSeq;
	private Short uanUnfSeq;

	public MamUnidXMedicacaoId() {
	}

	public MamUnidXMedicacaoId(Integer mdmSeq, Short uanUnfSeq) {
		this.mdmSeq = mdmSeq;
		this.uanUnfSeq = uanUnfSeq;
	}

	@Column(name = "MDM_SEQ", nullable = false)
	public Integer getMdmSeq() {
		return this.mdmSeq;
	}

	public void setMdmSeq(Integer mdmSeq) {
		this.mdmSeq = mdmSeq;
	}

	@Column(name = "UAN_UNF_SEQ", nullable = false)
	public Short getUanUnfSeq() {
		return this.uanUnfSeq;
	}

	public void setUanUnfSeq(Short uanUnfSeq) {
		this.uanUnfSeq = uanUnfSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getMdmSeq());
		umHashCodeBuilder.append(this.getUanUnfSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MamUnidXMedicacaoId)) {
			return false;
		}
		MamUnidXMedicacaoId other = (MamUnidXMedicacaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getMdmSeq(), other.getMdmSeq());
		umEqualsBuilder.append(this.getUanUnfSeq(), other.getUanUnfSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
