package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MbcAgendaDiagnosticoId generated by hbm2java
 */
@Embeddable
public class MbcAgendaDiagnosticoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5622076985533406410L;
	private Integer agdSeq;
	private Integer cidSeq;

	public MbcAgendaDiagnosticoId() {
	}

	public MbcAgendaDiagnosticoId(Integer agdSeq, Integer cidSeq) {
		this.agdSeq = agdSeq;
		this.cidSeq = cidSeq;
	}

	@Column(name = "AGD_SEQ", unique = true, nullable = false)
	public Integer getAgdSeq() {
		return this.agdSeq;
	}

	public void setAgdSeq(Integer agdSeq) {
		this.agdSeq = agdSeq;
	}

	@Column(name = "CID_SEQ", nullable = false)
	public Integer getCidSeq() {
		return this.cidSeq;
	}

	public void setCidSeq(Integer cidSeq) {
		this.cidSeq = cidSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getCidSeq());
		umHashCodeBuilder.append(this.getAgdSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcAgendaDiagnosticoId)) {
			return false;
		}
		MbcAgendaDiagnosticoId other = (MbcAgendaDiagnosticoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getCidSeq(), other.getCidSeq());
		umEqualsBuilder.append(this.getAgdSeq(), other.getAgdSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
