package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MbcEventoAdversoPorGrupoId generated by hbm2java
 */
@Embeddable
public class MbcEventoAdversoPorGrupoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1786519313882937998L;
	private Short eadSeq;
	private Short geaSeq;

	public MbcEventoAdversoPorGrupoId() {
	}

	public MbcEventoAdversoPorGrupoId(Short eadSeq, Short geaSeq) {
		this.eadSeq = eadSeq;
		this.geaSeq = geaSeq;
	}

	@Column(name = "EAD_SEQ", nullable = false)
	public Short getEadSeq() {
		return this.eadSeq;
	}

	public void setEadSeq(Short eadSeq) {
		this.eadSeq = eadSeq;
	}

	@Column(name = "GEA_SEQ", nullable = false)
	public Short getGeaSeq() {
		return this.geaSeq;
	}

	public void setGeaSeq(Short geaSeq) {
		this.geaSeq = geaSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getEadSeq());
		umHashCodeBuilder.append(this.getGeaSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcEventoAdversoPorGrupoId)) {
			return false;
		}
		MbcEventoAdversoPorGrupoId other = (MbcEventoAdversoPorGrupoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getEadSeq(), other.getEadSeq());
		umEqualsBuilder.append(this.getGeaSeq(), other.getGeaSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
