package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MbcEquipamentoNotaSala generated by hbm2java
 */
@Entity
@Table(name = "MBC_EQUIPAMENTO_NOTA_SALAS", schema = "AGH")
public class MbcEquipamentoNotaSala extends BaseEntityId<MbcEquipamentoNotaSalaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -441511718972152370L;
	private MbcEquipamentoNotaSalaId id;
	private Integer version;
	private MbcUnidadeNotaSala mbcUnidadeNotaSala;
	private RapServidores rapServidores;
	private MbcEquipamentoCirurgico mbcEquipamentoCirurgico;
	private Date criadoEm;
	private Short ordemImp;

	public MbcEquipamentoNotaSala() {
	}

	public MbcEquipamentoNotaSala(MbcEquipamentoNotaSalaId id, MbcUnidadeNotaSala mbcUnidadeNotaSala, RapServidores rapServidores,
			MbcEquipamentoCirurgico mbcEquipamentoCirurgico, Date criadoEm, Short ordemImp) {
		this.id = id;
		this.mbcUnidadeNotaSala = mbcUnidadeNotaSala;
		this.rapServidores = rapServidores;
		this.mbcEquipamentoCirurgico = mbcEquipamentoCirurgico;
		this.criadoEm = criadoEm;
		this.ordemImp = ordemImp;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "euuSeq", column = @Column(name = "EUU_SEQ", nullable = false)),
			@AttributeOverride(name = "noaUnfSeq", column = @Column(name = "NOA_UNF_SEQ", nullable = false)),
			@AttributeOverride(name = "noaSeqp", column = @Column(name = "NOA_SEQP", nullable = false)) })
	public MbcEquipamentoNotaSalaId getId() {
		return this.id;
	}

	public void setId(MbcEquipamentoNotaSalaId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "NOA_UNF_SEQ", referencedColumnName = "UNF_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NOA_SEQP", referencedColumnName = "SEQP", nullable = false, insertable = false, updatable = false) })
	public MbcUnidadeNotaSala getMbcUnidadeNotaSala() {
		return this.mbcUnidadeNotaSala;
	}

	public void setMbcUnidadeNotaSala(MbcUnidadeNotaSala mbcUnidadeNotaSala) {
		this.mbcUnidadeNotaSala = mbcUnidadeNotaSala;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EUU_SEQ", nullable = false, insertable = false, updatable = false)
	public MbcEquipamentoCirurgico getMbcEquipamentoCirurgico() {
		return this.mbcEquipamentoCirurgico;
	}

	public void setMbcEquipamentoCirurgico(MbcEquipamentoCirurgico mbcEquipamentoCirurgico) {
		this.mbcEquipamentoCirurgico = mbcEquipamentoCirurgico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "ORDEM_IMP", nullable = false)
	public Short getOrdemImp() {
		return this.ordemImp;
	}

	public void setOrdemImp(Short ordemImp) {
		this.ordemImp = ordemImp;
	}

	public enum Fields {

		ID("id"),
		UNF_SEQ("id.noaUnfSeq"),
		SEQP("id.noaSeqp"),		
		VERSION("version"),
		MBC_UNIDADE_NOTA_SALAS("mbcUnidadeNotaSala"),
		MBC_UNIDADE_NOTA_SALAS_SEQP("mbcUnidadeNotaSala.id.seqp"),
		RAP_SERVIDORES("rapServidores"),
		MBC_EQUIPAMENTO_CIRURGICO("mbcEquipamentoCirurgico"),
		CRIADO_EM("criadoEm"),
		ORDEM_IMP("ordemImp");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcEquipamentoNotaSala)) {
			return false;
		}
		MbcEquipamentoNotaSala other = (MbcEquipamentoNotaSala) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
