package br.gov.mec.aghu.model;

// Generated 28/03/2012 15:17:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;


import br.gov.mec.aghu.dominio.DominioOrigemFichaTecnicaEspecial;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MbcFichaTecnicaEspeciais generated by hbm2java
 */
@Entity
@Table(name = "MBC_FICHA_TECNICA_ESPECIAIS", schema = "AGH")
public class MbcFichaTecnicaEspecial extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7066602742971810548L;
	private Integer seq;
	private Integer version;
	private MbcTecnicaEspecial mbcTecnicaEspeciais;
	private MbcFichaAnestesias mbcFichaAnestesias;
	private DominioOrigemFichaTecnicaEspecial origem;
	private Short tempoAplicacao;
	/*private Integer serMatricula;
	private Short serVinCodigo;*/
	private RapServidores servidor;
	private Date criadoEm;

	public MbcFichaTecnicaEspecial() {
	}

	@Id
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TNP_SEQ", nullable = false)
	public MbcTecnicaEspecial getMbcTecnicaEspeciais() {
		return this.mbcTecnicaEspeciais;
	}

	public void setMbcTecnicaEspeciais(MbcTecnicaEspecial mbcTecnicaEspeciais) {
		this.mbcTecnicaEspeciais = mbcTecnicaEspeciais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIC_SEQ", nullable = false)
	public MbcFichaAnestesias getMbcFichaAnestesias() {
		return this.mbcFichaAnestesias;
	}

	public void setMbcFichaAnestesias(MbcFichaAnestesias mbcFichaAnestesias) {
		this.mbcFichaAnestesias = mbcFichaAnestesias;
	}

	@Column(name = "ORIGEM", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioOrigemFichaTecnicaEspecial getOrigem() {
		return this.origem;
	}

	public void setOrigem(DominioOrigemFichaTecnicaEspecial origem) {
		this.origem = origem;
	}

	@Column(name = "TEMPO_APLICACAO")
	public Short getTempoAplicacao() {
		return this.tempoAplicacao;
	}

	public void setTempoAplicacao(Short tempoAplicacao) {
		this.tempoAplicacao = tempoAplicacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA"),
		@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO")})
	public RapServidores getServidor() {
		return servidor;
	}
	
	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	public MbcFichaTecnicaEspecial(Integer seq, Integer version,
			MbcTecnicaEspecial mbcTecnicaEspeciais,
			MbcFichaAnestesias mbcFichaAnestesias,
			DominioOrigemFichaTecnicaEspecial origem, Short tempoAplicacao,
			RapServidores servidor, Date criadoEm) {
		super();
		this.seq = seq;
		this.version = version;
		this.mbcTecnicaEspeciais = mbcTecnicaEspeciais;
		this.mbcFichaAnestesias = mbcFichaAnestesias;
		this.origem = origem;
		this.tempoAplicacao = tempoAplicacao;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}
	
	public enum Fields {
		SEQ("seq"),
		TECNOCA_ESPECIAL("mbcTecnicaEspeciais"),
		FICHA_ANESTESIA("mbcFichaAnestesias"),
		ORIGEM("origem"),
		TEMPO_APLICACAO("tempoAplicacao"),
		SERVIDOR("servidor"),
		CRIADO_EM("criadoEm");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}
	
	@Transient
	public String getTempoAplicacaoEmHorasEMinutos(){
		StringBuffer ret = new StringBuffer();
		if(tempoAplicacao != null){
			ret.append(" (");
			ret.append((tempoAplicacao /60) %24);
			ret.append("00");
			ret.append(':');
			ret.append(tempoAplicacao /60);
			ret.append("00");
			ret.append(')');
		}
		
		return ret.toString();
	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcFichaTecnicaEspecial)) {
			return false;
		}
		MbcFichaTecnicaEspecial other = (MbcFichaTecnicaEspecial) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
