package br.gov.mec.aghu.model;

// Generated 28/03/2012 15:17:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MbcFichaBloqNervoPlexos generated by hbm2java
 */
@Entity
@Table(name = "MBC_FICHA_BLOQ_NERVO_PLEXOS", schema = "AGH")
public class MbcFichaBloqNervoPlexos extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6446673429916241131L;
	private Integer seq;
	private Integer version;
	private MbcFichaAnestesias mbcFichaAnestesias;
	private MbcTecnBloqNervoPlexos mbcTecnBloqNervoPlexos;
	private MbcNervoPlexos mbcNervoPlexos;
	private String outroNervo;
	private String outraTecnica;
	private Boolean neuroestimulacao;
	private Boolean parestesias;
	private Boolean ultraSom;
	private Date criadoEm;
	private RapServidores rapServidores;

	public MbcFichaBloqNervoPlexos() {
	}

	public MbcFichaBloqNervoPlexos(Integer seq,
			MbcFichaAnestesias mbcFichaAnestesias, Boolean neuroestimulacao,
			Boolean parestesias, Boolean ultraSom, Date criadoEm,
			RapServidores rapServidores) {
		this.seq = seq;
		this.mbcFichaAnestesias = mbcFichaAnestesias;
		this.neuroestimulacao = neuroestimulacao;
		this.parestesias = parestesias;
		this.ultraSom = ultraSom;
		this.criadoEm = criadoEm;
		this.rapServidores = rapServidores;
	}

	public MbcFichaBloqNervoPlexos(Integer seq,
			MbcFichaAnestesias mbcFichaAnestesias,
			MbcTecnBloqNervoPlexos mbcTecnBloqNervoPlexos,
			MbcNervoPlexos mbcNervoPlexos, String outroNervo,
			String outraTecnica, Boolean neuroestimulacao, Boolean parestesias,
			Boolean ultraSom, Date criadoEm, RapServidores rapServidores) {
		this.seq = seq;
		this.mbcFichaAnestesias = mbcFichaAnestesias;
		this.mbcTecnBloqNervoPlexos = mbcTecnBloqNervoPlexos;
		this.mbcNervoPlexos = mbcNervoPlexos;
		this.outroNervo = outroNervo;
		this.outraTecnica = outraTecnica;
		this.neuroestimulacao = neuroestimulacao;
		this.parestesias = parestesias;
		this.ultraSom = ultraSom;
		this.criadoEm = criadoEm;
		this.rapServidores = rapServidores;
	}

	@Id
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIC_SEQ", nullable = false)
	public MbcFichaAnestesias getMbcFichaAnestesias() {
		return this.mbcFichaAnestesias;
	}

	public void setMbcFichaAnestesias(MbcFichaAnestesias mbcFichaAnestesias) {
		this.mbcFichaAnestesias = mbcFichaAnestesias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TBN_SEQ")
	public MbcTecnBloqNervoPlexos getMbcTecnBloqNervoPlexos() {
		return this.mbcTecnBloqNervoPlexos;
	}

	public void setMbcTecnBloqNervoPlexos(
			MbcTecnBloqNervoPlexos mbcTecnBloqNervoPlexos) {
		this.mbcTecnBloqNervoPlexos = mbcTecnBloqNervoPlexos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NPX_SEQ")
	public MbcNervoPlexos getMbcNervoPlexos() {
		return this.mbcNervoPlexos;
	}

	public void setMbcNervoPlexos(MbcNervoPlexos mbcNervoPlexos) {
		this.mbcNervoPlexos = mbcNervoPlexos;
	}

	@Column(name = "OUTRO_NERVO", length = 60)
	@Length(max = 60)
	public String getOutroNervo() {
		return this.outroNervo;
	}

	public void setOutroNervo(String outroNervo) {
		this.outroNervo = outroNervo;
	}

	@Column(name = "OUTRA_TECNICA", length = 60)
	@Length(max = 60)
	public String getOutraTecnica() {
		return this.outraTecnica;
	}

	public void setOutraTecnica(String outraTecnica) {
		this.outraTecnica = outraTecnica;
	}

	@Column(name = "NEUROESTIMULACAO", nullable = false, length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getNeuroestimulacao() {
		return this.neuroestimulacao;
	}

	public void setNeuroestimulacao(Boolean neuroestimulacao) {
		this.neuroestimulacao = neuroestimulacao;
	}

	@Column(name = "PARESTESIAS", nullable = false, length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getParestesias() {
		return this.parestesias;
	}

	public void setParestesias(Boolean parestesias) {
		this.parestesias = parestesias;
	}

	@Column(name = "ULTRA_SOM", nullable = false, length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getUltraSom() {
		return this.ultraSom;
	}

	public void setUltraSom(Boolean ultraSom) {
		this.ultraSom = ultraSom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	public enum Fields {

		SEQ("seq"),
		MBC_FICHA_ANESTESIAS("mbcFichaAnestesias"),
		MBC_TECN_BLOQ_NERVO_PLEXOS("mbcTecnBloqNervoPlexos"),
		MBC_NERVO_PLEXOS("mbcNervoPlexos"),
		OUTRO_NERVO("outroNervo"),
		OUTRA_TECNICA("outraTecnica"),
		NEUROESTIMULACAO("neuroestimulacao"),
		PARESTESIAS("parestesias"),
		ULTRA_SOM("ultraSom"),
		CRIADO_EM("criadoEm"),
		RAP_SERVIDORES("rapServidores");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcFichaBloqNervoPlexos)) {
			return false;
		}
		MbcFichaBloqNervoPlexos other = (MbcFichaBloqNervoPlexos) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
