package br.gov.mec.aghu.model;

// Generated 28/03/2012 15:17:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioOrigemFichaTecnicaEspecial;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MbcFichaPosicionamentos generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mbcPonSq1", sequenceName="AGH.MBC_PON_SQ1", allocationSize = 1)
@Table(name = "MBC_FICHA_POSICIONAMENTOS", schema = "AGH")
public class MbcFichaPosicionamento extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8945987758680146592L;
	private Integer seq;
	private Integer version;
	private MbcFichaAnestesias mbcFichaAnestesias;
	private MbcPosicionamento mbcPosicionamentos;
	private Boolean selecionado;
	private Boolean posicaoBloqueioNeuroeixo;
	private DominioOrigemFichaTecnicaEspecial origem;
	private Date criadoEm;
	private RapServidores servidor;

	public MbcFichaPosicionamento() {
	}

	public MbcFichaPosicionamento(Integer seq, Integer version,
			MbcFichaAnestesias mbcFichaAnestesias,
			MbcPosicionamento mbcPosicionamentos, Boolean selecionado,
			Boolean posicaoBloqueioNeuroeixo,
			DominioOrigemFichaTecnicaEspecial origem, Date criadoEm,
			RapServidores servidor) {
		super();
		this.seq = seq;
		this.version = version;
		this.mbcFichaAnestesias = mbcFichaAnestesias;
		this.mbcPosicionamentos = mbcPosicionamentos;
		this.selecionado = selecionado;
		this.posicaoBloqueioNeuroeixo = posicaoBloqueioNeuroeixo;
		this.origem = origem;
		this.criadoEm = criadoEm;
		this.servidor = servidor;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mbcPonSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIC_SEQ", nullable = false)
	public MbcFichaAnestesias getMbcFichaAnestesias() {
		return this.mbcFichaAnestesias;
	}

	public void setMbcFichaAnestesias(MbcFichaAnestesias mbcFichaAnestesias) {
		this.mbcFichaAnestesias = mbcFichaAnestesias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POI_SEQ", nullable = false)
	public MbcPosicionamento getMbcPosicionamentos() {
		return this.mbcPosicionamentos;
	}

	public void setMbcPosicionamentos(MbcPosicionamento mbcPosicionamentos) {
		this.mbcPosicionamentos = mbcPosicionamentos;
	}

	@Column(name = "SELECIONADO", nullable = false, length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getSelecionado() {
		return this.selecionado;
	}

	public void setSelecionado(Boolean selecionado) {
		this.selecionado = selecionado;
	}

	@Column(name = "POSICAO_BLOQUEIO_NEUROEIXO", length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getPosicaoBloqueioNeuroeixo() {
		return this.posicaoBloqueioNeuroeixo;
	}

	public void setPosicaoBloqueioNeuroeixo(Boolean posicaoBloqueioNeuroeixo) {
		this.posicaoBloqueioNeuroeixo = posicaoBloqueioNeuroeixo;
	}

	@Column(name = "ORIGEM", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioOrigemFichaTecnicaEspecial getOrigem() {
		return this.origem;
	}

	public void setOrigem(DominioOrigemFichaTecnicaEspecial origem) {
		this.origem = origem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA"),
		@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO")})
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	public enum Fields {

		SEQ("seq"),
		MBC_FICHA_ANESTESIAS("mbcFichaAnestesias"),
		MBC_POSICIONAMENTOS("mbcPosicionamentos"),
		SELECIONADO("selecionado"),
		POSICAO_BLOQUEIO_NEUROEIXO("posicaoBloqueioNeuroeixo"),
		ORIGEM("origem"),
		CRIADO_EM("criadoEm");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcFichaPosicionamento)) {
			return false;
		}
		MbcFichaPosicionamento other = (MbcFichaPosicionamento) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
