package br.gov.mec.aghu.model;

// Generated 28/03/2012 15:17:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioPorteFichaFinal;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MbcFichaFinais generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mbcFflSq1", sequenceName="AGH.MBC_FFL_SQ1", allocationSize = 1)
@Table(name = "MBC_FICHA_FINAIS", schema = "AGH", uniqueConstraints = @UniqueConstraint(columnNames = "fic_seq"))
public class MbcFichaFinal extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3356591398641381048L;
	private Integer seq;
	private Integer version;
	private MbcFichaAnestesias mbcFichaAnestesias;
	private MbcCondPsicoSensorial mbcCondPsicoSensoriais;
	private MbcViaAerea mbcViaAereas;
	private DominioPorteFichaFinal porte;
	private Short o2;
	private String regime;
	private String recuperacao;
	private String numLinhasVenosas;
	private Boolean nenhumFluidoAdministrado;
	private Boolean nenhumEventoAdverso;
	//private Short dpaSeq;
	private MbcDestinoPaciente destinoPaciente;
	private RapServidores servidor;
	private Date criadoEm;
	private Boolean provaCruzadaEmSala;

	public MbcFichaFinal() {
	}

	public MbcFichaFinal(Integer seq, Integer version,
			MbcFichaAnestesias mbcFichaAnestesias,
			MbcCondPsicoSensorial mbcCondPsicoSensoriais,
			MbcViaAerea mbcViaAereas, DominioPorteFichaFinal porte, Short o2,
			String regime, String recuperacao, String numLinhasVenosas,
			Boolean nenhumFluidoAdministrado, Boolean nenhumEventoAdverso,
			MbcDestinoPaciente destinoPaciente, RapServidores servidor, Date criadoEm,
			Boolean provaCruzadaEmSala) {
		super();
		this.seq = seq;
		this.version = version;
		this.mbcFichaAnestesias = mbcFichaAnestesias;
		this.mbcCondPsicoSensoriais = mbcCondPsicoSensoriais;
		this.mbcViaAereas = mbcViaAereas;
		this.porte = porte;
		this.o2 = o2;
		this.regime = regime;
		this.recuperacao = recuperacao;
		this.numLinhasVenosas = numLinhasVenosas;
		this.nenhumFluidoAdministrado = nenhumFluidoAdministrado;
		this.nenhumEventoAdverso = nenhumEventoAdverso;
		this.destinoPaciente = destinoPaciente;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
		this.provaCruzadaEmSala = provaCruzadaEmSala;
	}



	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mbcFflSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIC_SEQ", unique = true, nullable = false)
	public MbcFichaAnestesias getMbcFichaAnestesias() {
		return this.mbcFichaAnestesias;
	}

	public void setMbcFichaAnestesias(MbcFichaAnestesias mbcFichaAnestesias) {
		this.mbcFichaAnestesias = mbcFichaAnestesias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CPS_SEQ", nullable = false)
	public MbcCondPsicoSensorial getMbcCondPsicoSensoriais() {
		return this.mbcCondPsicoSensoriais;
	}

	public void setMbcCondPsicoSensoriais(
			MbcCondPsicoSensorial mbcCondPsicoSensoriais) {
		this.mbcCondPsicoSensoriais = mbcCondPsicoSensoriais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VIA_SEQ", nullable = false)
	public MbcViaAerea getMbcViaAereas() {
		return this.mbcViaAereas;
	}

	public void setMbcViaAereas(MbcViaAerea mbcViaAereas) {
		this.mbcViaAereas = mbcViaAereas;
	}

	@Column(name = "PORTE", length = 2)
	@Enumerated(EnumType.STRING)
	public DominioPorteFichaFinal getPorte() {
		return this.porte;
	}

	public void setPorte(DominioPorteFichaFinal porte) {
		this.porte = porte;
	}

	@Column(name = "O2")
	public Short getO2() {
		return this.o2;
	}

	public void setO2(Short o2) {
		this.o2 = o2;
	}

	@Column(name = "REGIME", length = 45)
	@Length(max = 45)
	public String getRegime() {
		return this.regime;
	}

	public void setRegime(String regime) {
		this.regime = regime;
	}

	@Column(name = "RECUPERACAO", length = 45)
	@Length(max = 45)
	public String getRecuperacao() {
		return this.recuperacao;
	}

	public void setRecuperacao(String recuperacao) {
		this.recuperacao = recuperacao;
	}

	@Column(name = "NUM_LINHAS_VENOSAS", length = 3)
	@Length(max = 3)
	public String getNumLinhasVenosas() {
		return this.numLinhasVenosas;
	}

	public void setNumLinhasVenosas(String numLinhasVenosas) {
		this.numLinhasVenosas = numLinhasVenosas;
	}

	@Column(name = "NENHUM_FLUIDO_ADMINISTRADO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getNenhumFluidoAdministrado() {
		return this.nenhumFluidoAdministrado;
	}

	public void setNenhumFluidoAdministrado(Boolean nenhumFluidoAdministrado) {
		this.nenhumFluidoAdministrado = nenhumFluidoAdministrado;
	}

	@Column(name = "NENHUM_EVENTO_ADVERSO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getNenhumEventoAdverso() {
		return this.nenhumEventoAdverso;
	}

	public void setNenhumEventoAdverso(Boolean nenhumEventoAdverso) {
		this.nenhumEventoAdverso = nenhumEventoAdverso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "PROVA_CRUZADA_EM_SALA", length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getProvaCruzadaEmSala() {
		return this.provaCruzadaEmSala;
	}

	public void setProvaCruzadaEmSala(Boolean provaCruzadaEmSala) {
		this.provaCruzadaEmSala = provaCruzadaEmSala;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA"),
		@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO")})
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPA_SEQ", nullable = false)
	public MbcDestinoPaciente getDestinoPaciente() {
		return destinoPaciente;
	}

	public void setDestinoPaciente(MbcDestinoPaciente destinoPaciente) {
		this.destinoPaciente = destinoPaciente;
	}

	public enum Fields {

		SEQ("seq"),
		MBC_COND_PSICO_SENSORIAIS("mbcCondPsicoSensoriais"),
		MBC_VIA_AEREAS("mbcViaAereas"),
		PORTE("porte"),
		O2("o2"),
		REGIME("regime"),
		RECUPERACAO("recuperacao"),
		NUM_LINHAS_VENOSAS("numLinhasVenosas"),
		NENHUM_FLUIDO_ADMINISTRADO("nenhumFluidoAdministrado"),
		NENHUM_EVENTO_ADVERSO("nenhumEventoAdverso"),
		CRIADO_EM("criadoEm"),
		PROVA_CRUZADA_EM_SALA("provaCruzadaEmSala"),
		FICHA_ANESTESIA("mbcFichaAnestesias"),
		FICHA_ANESTESIA_SEQ("mbcFichaAnestesias.seq");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcFichaFinal)) {
			return false;
		}
		MbcFichaFinal other = (MbcFichaFinal) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
