package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MbcFiguraProcEspId generated by hbm2java
 */
@Embeddable
public class MbcFiguraProcEspId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1904247445459540636L;
	private Integer pciSeq;
	private Integer fiuSeq;
	private Short espSeq;

	public MbcFiguraProcEspId() {
	}

	public MbcFiguraProcEspId(Integer pciSeq, Integer fiuSeq, Short espSeq) {
		this.pciSeq = pciSeq;
		this.fiuSeq = fiuSeq;
		this.espSeq = espSeq;
	}

	@Column(name = "PCI_SEQ", nullable = false)
	public Integer getPciSeq() {
		return this.pciSeq;
	}

	public void setPciSeq(Integer pciSeq) {
		this.pciSeq = pciSeq;
	}

	@Column(name = "FIU_SEQ", nullable = false)
	public Integer getFiuSeq() {
		return this.fiuSeq;
	}

	public void setFiuSeq(Integer fiuSeq) {
		this.fiuSeq = fiuSeq;
	}

	@Column(name = "ESP_SEQ", nullable = false)
	public Short getEspSeq() {
		return this.espSeq;
	}

	public void setEspSeq(Short espSeq) {
		this.espSeq = espSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getEspSeq());
		umHashCodeBuilder.append(this.getPciSeq());
		umHashCodeBuilder.append(this.getFiuSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcFiguraProcEspId)) {
			return false;
		}
		MbcFiguraProcEspId other = (MbcFiguraProcEspId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getEspSeq(), other.getEspSeq());
		umEqualsBuilder.append(this.getPciSeq(), other.getPciSeq());
		umEqualsBuilder.append(this.getFiuSeq(), other.getFiuSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
