package br.gov.mec.aghu.model;

// Generated 28/03/2012 15:17:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioCardEspessura;
import br.gov.mec.aghu.dominio.DominioCardFluxo;
import br.gov.mec.aghu.dominio.DominioCardMomento;
import br.gov.mec.aghu.dominio.DominioCardTemperatura;
import br.gov.mec.aghu.dominio.DominioCecCanulArterial;
import br.gov.mec.aghu.dominio.DominioCecCanulAtrial;
import br.gov.mec.aghu.dominio.DominioCecFluxo;
import br.gov.mec.aghu.dominio.DominioCecOxigenador;
import br.gov.mec.aghu.dominio.DominioChild;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MbcFichaGrandePortes generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mbcFgpSq1", sequenceName="AGH.MBC_FGP_SQ1", allocationSize = 1)
@Table(name = "MBC_FICHA_GRANDE_PORTES", schema = "AGH")
public class MbcFichaGrandePorte extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6165139168442210967L;
	private Integer seq;
	private Integer version;
	private MbcFichaAnestesias mbcFichaAnestesias;
	private DominioCecCanulArterial cecCanulArterial;
	private DominioCecCanulAtrial cecCanulAtrial;
	private DominioCecOxigenador cecOxigenador;
	private DominioCecFluxo cecFluxo;
	private DominioCardEspessura cardEspessura;
	private DominioCardTemperatura cardTemperatura;
	private DominioCardMomento cardMomento;
	private DominioCardFluxo cardFluxo;
	private Boolean retransplante;
	private Boolean intervivos;
	private DominioChild child;
	private Short meldPeld;
	private RapServidores servidor;
	private Date criadoEm;

	public MbcFichaGrandePorte() {
	}


	public MbcFichaGrandePorte(Integer seq, Integer version,
			MbcFichaAnestesias mbcFichaAnestesias,
			DominioCecCanulArterial cecCanulArterial,
			DominioCecCanulAtrial cecCanulAtrial,
			DominioCecOxigenador cecOxigenador, DominioCecFluxo cecFluxo,
			DominioCardEspessura cardEspessura,
			DominioCardTemperatura cardTemperatura,
			DominioCardMomento cardMomento, DominioCardFluxo cardFluxo,
			Boolean retransplante, Boolean intervivos, DominioChild child,
			Short meldPeld, RapServidores servidor, Date criadoEm) {
		super();
		this.seq = seq;
		this.version = version;
		this.mbcFichaAnestesias = mbcFichaAnestesias;
		this.cecCanulArterial = cecCanulArterial;
		this.cecCanulAtrial = cecCanulAtrial;
		this.cecOxigenador = cecOxigenador;
		this.cecFluxo = cecFluxo;
		this.cardEspessura = cardEspessura;
		this.cardTemperatura = cardTemperatura;
		this.cardMomento = cardMomento;
		this.cardFluxo = cardFluxo;
		this.retransplante = retransplante;
		this.intervivos = intervivos;
		this.child = child;
		this.meldPeld = meldPeld;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mbcFgpSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIC_SEQ", nullable = false)
	public MbcFichaAnestesias getMbcFichaAnestesias() {
		return this.mbcFichaAnestesias;
	}

	public void setMbcFichaAnestesias(MbcFichaAnestesias mbcFichaAnestesias) {
		this.mbcFichaAnestesias = mbcFichaAnestesias;
	}

	@Column(name = "CEC_CANUL_ARTERIAL", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioCecCanulArterial getCecCanulArterial() {
		return this.cecCanulArterial;
	}

	public void setCecCanulArterial(DominioCecCanulArterial cecCanulArterial) {
		this.cecCanulArterial = cecCanulArterial;
	}

	@Column(name = "CEC_CANUL_ATRIAL", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioCecCanulAtrial getCecCanulAtrial() {
		return this.cecCanulAtrial;
	}

	public void setCecCanulAtrial(DominioCecCanulAtrial cecCanulAtrial) {
		this.cecCanulAtrial = cecCanulAtrial;
	}

	@Column(name = "CEC_OXIGENADOR", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioCecOxigenador getCecOxigenador() {
		return this.cecOxigenador;
	}

	public void setCecOxigenador(DominioCecOxigenador cecOxigenador) {
		this.cecOxigenador = cecOxigenador;
	}

	@Column(name = "CEC_FLUXO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioCecFluxo getCecFluxo() {
		return this.cecFluxo;
	}

	public void setCecFluxo(DominioCecFluxo cecFluxo) {
		this.cecFluxo = cecFluxo;
	}

	@Column(name = "CARD_ESPESSURA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioCardEspessura getCardEspessura() {
		return this.cardEspessura;
	}

	public void setCardEspessura(DominioCardEspessura cardEspessura) {
		this.cardEspessura = cardEspessura;
	}

	@Column(name = "CARD_TEMPERATURA", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioCardTemperatura getCardTemperatura() {
		return this.cardTemperatura;
	}

	public void setCardTemperatura(DominioCardTemperatura cardTemperatura) {
		this.cardTemperatura = cardTemperatura;
	}

	@Column(name = "CARD_MOMENTO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioCardMomento getCardMomento() {
		return this.cardMomento;
	}

	public void setCardMomento(DominioCardMomento cardMomento) {
		this.cardMomento = cardMomento;
	}

	@Column(name = "CARD_FLUXO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioCardFluxo getCardFluxo() {
		return this.cardFluxo;
	}

	public void setCardFluxo(DominioCardFluxo cardFluxo) {
		this.cardFluxo = cardFluxo;
	}

	@Column(name = "RETRANSPLANTE", nullable = false, length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getRetransplante() {
		return this.retransplante;
	}

	public void setRetransplante(Boolean retransplante) {
		this.retransplante = retransplante;
	}

	@Column(name = "INTERVIVOS", nullable = false, length = 1)
	@Length(max = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIntervivos() {
		return this.intervivos;
	}

	public void setIntervivos(Boolean intervivos) {
		this.intervivos = intervivos;
	}

	@Column(name = "CHILD", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioChild getChild() {
		return this.child;
	}

	public void setChild(DominioChild child) {
		this.child = child;
	}

	@Column(name = "MELD_PELD")
	public Short getMeldPeld() {
		return this.meldPeld;
	}

	public void setMeldPeld(Short meldPeld) {
		this.meldPeld = meldPeld;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}
	
	public enum Fields {

		SEQ("seq"),
		CEC_CANUL_ARTERIAL("cecCanulArterial"),
		CEC_CANUL_ATRIAL("cecCanulAtrial"),
		CEC_OXIGENADOR("cecOxigenador"),
		CEC_FLUXO("cecFluxo"),
		CARD_ESPESSURA("cardEspessura"),
		CARD_TEMPERATURA("cardTemperatura"),
		CARD_MOMENTO("cardMomento"),
		CARD_FLUXO("cardFluxo"),
		RETRANSPLANTE("retransplante"),
		INTERVIVOS("intervivos"),
		CHILD("child"),
		MELD_PELD("meldPeld"),
		CRIADO_EM("criadoEm"),
		FICHA_ANESTESIA("mbcFichaAnestesias"),
		FICHA_ANESTESIA_SEQ("mbcFichaAnestesias.seq");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcFichaGrandePorte)) {
			return false;
		}
		MbcFichaGrandePorte other = (MbcFichaGrandePorte) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
