package br.gov.mec.aghu.model;

// Generated 08/02/2010 17:25:25 by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioIndPendenteAmbulatorio;
import br.gov.mec.aghu.dominio.DominioNaturezaFichaAnestesia;
import br.gov.mec.aghu.dominio.DominioOrigemMbcFichaAnestesia;
import br.gov.mec.aghu.dominio.DominioSimNao;
import br.gov.mec.aghu.dominio.DominioTipoParto;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MbcFichaAnestesias generated by hbm2java
 */
@SuppressWarnings({"PMD.AghuUsoIndevidoDaEnumDominioSimNaoEntity"})
@Entity
@SequenceGenerator(name="mbcFicSq1", sequenceName="AGH.MBC_FIC_SQ1", allocationSize = 1)
@Table(name = "MBC_FICHA_ANESTESIAS", schema = "AGH")
public class MbcFichaAnestesias extends BaseEntitySeq<Long> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3435851699674858681L;
	private Long seq;
	private MbcFichaAnestesias mbcFichaAnestesias;
	private AipPacientes paciente; 
	private DominioOrigemMbcFichaAnestesia origem;
	private DominioIndPendenteAmbulatorio pendente;
	private Boolean transplante;
	private DominioTipoParto tipoParto;
	private Date data;
	private Date dthrCriacao;
	private Date dthrValida;
	private Date dthrMvto;
	private Date dthrValidaMvto;
	
	private Integer gsoPacCodigo;
	
	private Short gsoSeqp;
	
	private MbcCirurgias cirurgia;	
	
	private McoGestacoes gestacao;
	
	private AelItemSolicitacaoExames itemSolicitacaoExame;
	
	private AinInternacao internacao;
	
	private AacConsultas consulta;
		
	private AghUnidadesFuncionais unidadeFuncional;
	
	private RapServidores servidor;
	private RapServidores servidorValida;
	private RapServidores servidorMvto;
	private RapServidores servidorValidaMvto;
	
	
	private String especificaPosicionamento;
	private DominioNaturezaFichaAnestesia natureza;
	private Short sala;
	private String especificaVentilacaoSistema;
	private DominioSimNao nenhumaMedicacaoPreAnest;
	private String observacao;
	private String leito;
	
	private AghAtendimentos atendimento;
	
	private String microcomputador;
	private Set<MbcFichaAnestesias> mbcFichaAnestesiases = new HashSet<MbcFichaAnestesias>(
			0);
	
	private Set<MbcFichaProcedimento> mbcFichaProcedimentos = new HashSet<MbcFichaProcedimento>(0);
	private Set<MbcFichaEquipeAnestesia> mbcFichaEquipeAnestesia = new HashSet<MbcFichaEquipeAnestesia>(0);
	

	//private Set<McoNascIndicacoes> nascIndicacoes;
	//private McoRecemNascidos recemNascido;*/
	
	public MbcFichaAnestesias() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mbcFicSq1")
	@Column(name = "SEQ", nullable = false, precision = 10, scale = 0)
	public Long getSeq() {
		return this.seq;
	}

	public void setSeq(Long seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIC_SEQ")
	public MbcFichaAnestesias getMbcFichaAnestesias() {
		return this.mbcFichaAnestesias;
	}

	public void setMbcFichaAnestesias(MbcFichaAnestesias mbcFichaAnestesias) {
		this.mbcFichaAnestesias = mbcFichaAnestesias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAC_CODIGO")
	public AipPacientes getPaciente() {
		return paciente;
	}

	public void setPaciente(AipPacientes paciente) {
		this.paciente = paciente;
	}

	@Column(name = "ORIGEM", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioOrigemMbcFichaAnestesia getOrigem() {
		return this.origem;
	}

	public void setOrigem(DominioOrigemMbcFichaAnestesia origem) {
		this.origem = origem;
	}

	@Column(name = "PENDENTE", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioIndPendenteAmbulatorio getPendente() {
		return this.pendente;
	}

	public void setPendente(DominioIndPendenteAmbulatorio pendente) {
		this.pendente = pendente;
	}

	@Column(name = "TRANSPLANTE", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getTransplante() {
		return this.transplante;
	}

	public void setTransplante(Boolean transplante) {
		this.transplante = transplante;
	}

	@Column(name = "TIPO_PARTO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioTipoParto getTipoParto() {
		return this.tipoParto;
	}

	public void setTipoParto(DominioTipoParto tipoParto) {
		this.tipoParto = tipoParto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA", nullable = false, length = 7)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_CRIACAO", nullable = false, length = 7)
	public Date getDthrCriacao() {
		return this.dthrCriacao;
	}

	public void setDthrCriacao(Date dthrCriacao) {
		this.dthrCriacao = dthrCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_VALIDA", length = 7)
	public Date getDthrValida() {
		return this.dthrValida;
	}

	public void setDthrValida(Date dthrValida) {
		this.dthrValida = dthrValida;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_MVTO", length = 7)
	public Date getDthrMvto() {
		return this.dthrMvto;
	}

	public void setDthrMvto(Date dthrMvto) {
		this.dthrMvto = dthrMvto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_VALIDA_MVTO", length = 7)
	public Date getDthrValidaMvto() {
		return this.dthrValidaMvto;
	}

	public void setDthrValidaMvto(Date dthrValidaMvto) {
		this.dthrValidaMvto = dthrValidaMvto;
	}	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRG_SEQ")
	public MbcCirurgias getCirurgia() {
		return cirurgia;
	}

	public void setCirurgia(MbcCirurgias cirurgia) {
		this.cirurgia = cirurgia;
	}	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "GSO_PAC_CODIGO", referencedColumnName = "PAC_CODIGO"),
			@JoinColumn(name = "GSO_SEQP", referencedColumnName = "SEQP") })
	public McoGestacoes getGestacao() {
		return gestacao;
	}

	public void setGestacao(McoGestacoes gestacao) {
		this.gestacao = gestacao;
	}
	
	@Column(name = "GSO_PAC_CODIGO", precision = 8, scale = 0, insertable = false, updatable = false)
	public Integer getGsoPacCodigo() {
		return this.gsoPacCodigo;
	}

	public void setGsoPacCodigo(Integer gsoPacCodigo) {
		this.gsoPacCodigo = gsoPacCodigo;
	}

	@Column(name = "GSO_SEQP", precision = 3, scale = 0, insertable = false, updatable = false)
	public Short getGsoSeqp() {
		return this.gsoSeqp;
	}

	public void setGsoSeqp(Short gsoSeqp) {
		this.gsoSeqp = gsoSeqp;
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "ISE_SOE_SEQ", referencedColumnName = "SOE_SEQ"),
			@JoinColumn(name = "ISE_SEQP", referencedColumnName = "SEQP") })
	
	public AelItemSolicitacaoExames getItemSolicitacaoExame() {
		return itemSolicitacaoExame;
	}

	public void setItemSolicitacaoExame(
			AelItemSolicitacaoExames itemSolicitacaoExame) {
		this.itemSolicitacaoExame = itemSolicitacaoExame;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INT_SEQ")
	public AinInternacao getInternacao() {
		return internacao;
	}

	public void setInternacao(AinInternacao internacao) {
		this.internacao = internacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_NUMERO")
	public AacConsultas getConsulta() {
		return consulta;
	}

	public void setConsulta(AacConsultas consulta) {
		this.consulta = consulta;
	}	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNF_SEQ")
	public AghUnidadesFuncionais getUnidadeFuncional() {
		return unidadeFuncional;
	}

	public void setUnidadeFuncional(AghUnidadesFuncionais unidadeFuncional) {
		this.unidadeFuncional = unidadeFuncional;
	}	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_VALIDA", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_VALIDA", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorValida() {
		return this.servidorValida;
	}
	
	public void setServidorValida(RapServidores servidorValida) {
		this.servidorValida = servidorValida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_MVTO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_MVTO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorMvto() {
		return this.servidorMvto;
	}
	
	public void setServidorMvto(RapServidores servidorMvto) {
		this.servidorMvto = servidorMvto;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_VALIDA_MVTO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_VALIDA_MVTO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorValidaMvto() {
		return this.servidorValidaMvto;
	}
	
	public void setServidorValidaMvto(RapServidores servidorValidaMvto) {
		this.servidorValidaMvto = servidorValidaMvto;
	}
	
	@Column(name = "ESPECIFICA_POSICIONAMENTO", length = 60)
	@Length(max = 60)
	public String getEspecificaPosicionamento() {
		return this.especificaPosicionamento;
	}

	public void setEspecificaPosicionamento(String especificaPosicionamento) {
		this.especificaPosicionamento = especificaPosicionamento;
	}

	@Column(name = "NATUREZA", length = 3)
	@Enumerated(EnumType.STRING)
	public DominioNaturezaFichaAnestesia getNatureza() {
		return this.natureza;
	}

	public void setNatureza(DominioNaturezaFichaAnestesia natureza) {
		this.natureza = natureza;
	}

	@Column(name = "SALA", precision = 3, scale = 0)
	public Short getSala() {
		return this.sala;
	}

	public void setSala(Short sala) {
		this.sala = sala;
	}

	@Column(name = "ESPECIFICA_VENTILACAO_SISTEMA", length = 60)
	@Length(max = 60)
	public String getEspecificaVentilacaoSistema() {
		return this.especificaVentilacaoSistema;
	}

	public void setEspecificaVentilacaoSistema(
			String especificaVentilacaoSistema) {
		this.especificaVentilacaoSistema = especificaVentilacaoSistema;
	}

	@Column(name = "NENHUMA_MEDICACAO_PRE_ANEST", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSimNao getNenhumaMedicacaoPreAnest() {
		return this.nenhumaMedicacaoPreAnest;
	}

	public void setNenhumaMedicacaoPreAnest(DominioSimNao nenhumaMedicacaoPreAnest) {
		this.nenhumaMedicacaoPreAnest = nenhumaMedicacaoPreAnest;
	}

	@Column(name = "OBSERVACAO", length = 1000)
	@Length(max = 1000)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "LEITO", length = 16)
	@Length(max = 16)
	public String getLeito() {
		return this.leito;
	}

	public void setLeito(String leito) {
		this.leito = leito;
	}


	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATD_SEQ")
	public AghAtendimentos getAtendimento() {
		return atendimento;
	}

	public void setAtendimento(AghAtendimentos atendimento) {
		this.atendimento = atendimento;
	}

	@Column(name = "MICROCOMPUTADOR", length = 50)
	@Length(max = 50)
	public String getMicrocomputador() {
		return this.microcomputador;
	}

	public void setMicrocomputador(String microcomputador) {
		this.microcomputador = microcomputador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbcFichaAnestesias")
	public Set<MbcFichaAnestesias> getMbcFichaAnestesiases() {
		return this.mbcFichaAnestesiases;
	}

	public void setMbcFichaAnestesiases(
			Set<MbcFichaAnestesias> mbcFichaAnestesiases) {
		this.mbcFichaAnestesiases = mbcFichaAnestesiases;
	}

	public enum Fields {
		PAC_CODIGO("paciente.codigo"), 
		GSO_PAC_CODIGO("gestacao.id.pacCodigo"),
		GSO_SEQUENCE("gestacao.id.seqp"), 
		PACIENTE("paciente"),
		SEQ("seq"),
		NENHUMA_MEDICACAO_PRE_ANEST("nenhumaMedicacaoPreAnest"),
		CRG_SEQ("cirurgia.seq"),
		DTHR_MVTO("dthrMvto"),
		PENDENTE("pendente"),
		NUMERO_CONSULTA("consulta.numero"),
		ATD_SEQ("atendimento.seq"),
		GESTACAO("gestacao"),
		ISE_SOE_SEQ("itemSolicitacaoExame.id.soeSeq"), 
		ISE_SEQP("itemSolicitacaoExame.id.seqp"),
		UNF_SEQ("unidadeFuncional.seq"),
		DATA("data"),
		FICHA_PROCEDIMENTOS("mbcFichaProcedimentos"),
		FICHA_EQUIPE_ANESTESIA("mbcFichaEquipeAnestesia");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcFichaAnestesias)) {
			return false;
		}
		MbcFichaAnestesias other = (MbcFichaAnestesias) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbcFichaAnestesias")
	public Set<MbcFichaProcedimento> getMbcFichaProcedimentos() {
		return mbcFichaProcedimentos;
	}

	public void setMbcFichaProcedimentos(Set<MbcFichaProcedimento> mbcFichaProcedimentos) {
		this.mbcFichaProcedimentos = mbcFichaProcedimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbcFichaAnestesias")
	public Set<MbcFichaEquipeAnestesia> getMbcFichaEquipeAnestesia() {
		return mbcFichaEquipeAnestesia;
	}

	public void setMbcFichaEquipeAnestesia(Set<MbcFichaEquipeAnestesia> mbcFichaEquipeAnestesia) {
		this.mbcFichaEquipeAnestesia = mbcFichaEquipeAnestesia;
	}

/*	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "MCO_GESTACOES", schema = "AGH"
		, joinColumns = {
			@JoinColumn(name = "csr_nas_gso_pac_codigo", updatable = false, referencedColumnName="gso_pac_codigo"),
			@JoinColumn(name = "CSR_NAS_GSO_SEQP", updatable = false, referencedColumnName="gso_seqp") }
		,inverseJoinColumns = {
			@JoinColumn(name = "PAC_CODIGO", nullable = false, updatable = false, referencedColumnName="csr_nas_gso_pac_codigo"),
			@JoinColumn(name = "SEQP", nullable = false, updatable = false, referencedColumnName="CSR_NAS_GSO_SEQP")})
	public Set<McoNascIndicacoes> getNascIndicacoes() {
		return nascIndicacoes;
	}

	public void setNascIndicacoes(Set<McoNascIndicacoes> nascIndicacoes) {
		this.nascIndicacoes = nascIndicacoes;
	}*/
	// ##### GeradorEqualsHashCodeMain #####

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "GSO_PAC_CODIGO", referencedColumnName = "	", insertable=false, updatable=false),
			@JoinColumn(name = "GSO_SEQP", referencedColumnName = "GSO_SEQP", insertable=false, updatable=false) })
	public McoRecemNascidos getRecemNascido() {
		return recemNascido;
	}

	public void setRecemNascido(McoRecemNascidos recemNascido) {
		this.recemNascido = recemNascido;
	}*/

}
