package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import br.gov.mec.aghu.dominio.DominioOcorrenciaFichaEvento;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MbcOcorrenciaFichaAcao generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mbcOfoSq1", sequenceName="AGH.MBC_OFO_SQ1", allocationSize = 1)
@Table(name = "MBC_OCORRENCIA_FICHA_ACOES", schema = "AGH")
public class MbcOcorrenciaFichaAcao extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6567044985302589220L;
	private Integer seq;
	private Integer version;
	private RapServidores rapServidores;
	private MbcFichaAcao mbcFichaAcao;
	private DominioOcorrenciaFichaEvento tipoOcorrencia;
	private Date dthrOcorrencia;
	private Date criadoEm;
	private Short lote;

	public MbcOcorrenciaFichaAcao() {
	}

	public MbcOcorrenciaFichaAcao(Integer seq, RapServidores rapServidores, MbcFichaAcao mbcFichaAcao, DominioOcorrenciaFichaEvento tipoOcorrencia,
			Date dthrOcorrencia, Date criadoEm, Short lote) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.mbcFichaAcao = mbcFichaAcao;
		this.tipoOcorrencia = tipoOcorrencia;
		this.dthrOcorrencia = dthrOcorrencia;
		this.criadoEm = criadoEm;
		this.lote = lote;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mbcOfoSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCH_SEQ", nullable = false)
	public MbcFichaAcao getMbcFichaAcao() {
		return this.mbcFichaAcao;
	}

	public void setMbcFichaAcao(MbcFichaAcao mbcFichaAcao) {
		this.mbcFichaAcao = mbcFichaAcao;
	}

	@Column(name = "TIPO_OCORRENCIA", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioOcorrenciaFichaEvento getTipoOcorrencia() {
		return this.tipoOcorrencia;
	}

	public void setTipoOcorrencia(DominioOcorrenciaFichaEvento tipoOcorrencia) {
		this.tipoOcorrencia = tipoOcorrencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_OCORRENCIA", nullable = false, length = 29)
	public Date getDthrOcorrencia() {
		return this.dthrOcorrencia;
	}

	public void setDthrOcorrencia(Date dthrOcorrencia) {
		this.dthrOcorrencia = dthrOcorrencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "LOTE", nullable = false)
	public Short getLote() {
		return this.lote;
	}

	public void setLote(Short lote) {
		this.lote = lote;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		MBC_FICHA_ACOES("mbcFichaAcao"),
		TIPO_OCORRENCIA("tipoOcorrencia"),
		DTHR_OCORRENCIA("dthrOcorrencia"),
		CRIADO_EM("criadoEm"),
		LOTE("lote");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcOcorrenciaFichaAcao)) {
			return false;
		}
		MbcOcorrenciaFichaAcao other = (MbcOcorrenciaFichaAcao) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
