package br.gov.mec.aghu.model;

// Generated 28/03/2012 15:17:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import br.gov.mec.aghu.dominio.DominioGravidadeFichaEvento;
import br.gov.mec.aghu.dominio.DominioOcorrenciaFichaEvento;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MbcOcorrenciaFichaEventos generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mbcOfeSq1", sequenceName="AGH.MBC_OFE_SQ1", allocationSize = 1)
@Table(name = "MBC_OCORRENCIA_FICHA_EVENTOS", schema = "AGH")
public class MbcOcorrenciaFichaEvento extends BaseEntitySeq<Integer> implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1370671850666609568L;
	
	private Integer seq;
	private Integer version;
	private MbcFichaEvento mbcFichaEventos;
	private Date dthrOcorrencia;
	private Date criadoEm;
	private DominioOcorrenciaFichaEvento tipoOcorrencia;
	private RapServidores servidor;
	private DominioGravidadeFichaEvento gravidade;
	private Date dthrResolucao;

	public MbcOcorrenciaFichaEvento() {
	}

	public MbcOcorrenciaFichaEvento(Integer seq, MbcFichaEvento mbcFichaEventos,
			Date dthrOcorrencia, Date criadoEm, DominioOcorrenciaFichaEvento tipoOcorrencia,
			RapServidores servidor) {
		this.seq = seq;
		this.mbcFichaEventos = mbcFichaEventos;
		this.dthrOcorrencia = dthrOcorrencia;
		this.criadoEm = criadoEm;
		this.tipoOcorrencia = tipoOcorrencia;
		this.setServidor(servidor);
	}

	public MbcOcorrenciaFichaEvento(Integer seq, MbcFichaEvento mbcFichaEventos,
			Date dthrOcorrencia, Date criadoEm, DominioOcorrenciaFichaEvento tipoOcorrencia,
			RapServidores servidor, DominioGravidadeFichaEvento gravidade,
			Date dthrResolucao) {
		this.seq = seq;
		this.mbcFichaEventos = mbcFichaEventos;
		this.dthrOcorrencia = dthrOcorrencia;
		this.criadoEm = criadoEm;
		this.tipoOcorrencia = tipoOcorrencia;
		this.setServidor(servidor);
		this.gravidade = gravidade;
		this.dthrResolucao = dthrResolucao;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mbcOfeSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FET_SEQ", nullable = false)
	public MbcFichaEvento getMbcFichaEventos() {
		return this.mbcFichaEventos;
	}

	public void setMbcFichaEventos(MbcFichaEvento mbcFichaEventos) {
		this.mbcFichaEventos = mbcFichaEventos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_OCORRENCIA", nullable = false, length = 29)
	public Date getDthrOcorrencia() {
		return this.dthrOcorrencia;
	}

	public void setDthrOcorrencia(Date dthrOcorrencia) {
		this.dthrOcorrencia = dthrOcorrencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "TIPO_OCORRENCIA", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioOcorrenciaFichaEvento getTipoOcorrencia() {
		return this.tipoOcorrencia;
	}

	public void setTipoOcorrencia(DominioOcorrenciaFichaEvento tipoOcorrencia) {
		this.tipoOcorrencia = tipoOcorrencia;
	}

	@Column(name = "GRAVIDADE", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioGravidadeFichaEvento getGravidade() {
		return this.gravidade;
	}

	public void setGravidade(DominioGravidadeFichaEvento gravidade) {
		this.gravidade = gravidade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_RESOLUCAO", length = 29)
	public Date getDthrResolucao() {
		return this.dthrResolucao;
	}

	public void setDthrResolucao(Date dthrResolucao) {
		this.dthrResolucao = dthrResolucao;
	}
	
	public enum Fields {
		SEQ("seq"),
		FICHA_EVENTO("mbcFichaEventos"),
		DTHT_OCORRENCIA("dthrOcorrencia"),
		CRIADO_EM("criadoEm"),
		TIPO_OCORRENCIA("tipoOcorrencia"),
		SER_MATRICULA("servidor.id.matricula"),
		SER_VIN_CODIGO("servidor.id.vinCodigo"),
		GRAVIDADE("gravidade"),
		DTHR_RESOLUCAO("dthrResolucao");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcOcorrenciaFichaEvento)) {
			return false;
		}
		MbcOcorrenciaFichaEvento other = (MbcOcorrenciaFichaEvento) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return servidor;
	}

}
