package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MbcTipoAnestesiaCombinada generated by hbm2java
 */
@Entity
@Table(name = "MBC_TIPO_ANESTESIA_COMBINADAS", schema = "AGH")
public class MbcTipoAnestesiaCombinada extends BaseEntityId<MbcTipoAnestesiaCombinadaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4500450209504292606L;
	private MbcTipoAnestesiaCombinadaId id;
	private Integer version;
	private RapServidores rapServidores;
	private MbcTipoAnestesias mbcTipoAnestesiasByTanSeq;
	private MbcTipoAnestesias mbcTipoAnestesiasByTanSeqCombina;
	private DominioSituacao situacao;
	private Date criadoEm;

	public MbcTipoAnestesiaCombinada() {
	}

	public MbcTipoAnestesiaCombinada(MbcTipoAnestesiaCombinadaId id, RapServidores rapServidores,
			MbcTipoAnestesias mbcTipoAnestesiasByTanSeq, MbcTipoAnestesias mbcTipoAnestesiasByTanSeqCombina, DominioSituacao situacao,
			Date criadoEm) {
		this.id = id;
		this.rapServidores = rapServidores;
		this.mbcTipoAnestesiasByTanSeq = mbcTipoAnestesiasByTanSeq;
		this.mbcTipoAnestesiasByTanSeqCombina = mbcTipoAnestesiasByTanSeqCombina;
		this.situacao = situacao;
		this.criadoEm = criadoEm;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "tanSeq", column = @Column(name = "TAN_SEQ", nullable = false)),
			@AttributeOverride(name = "tanSeqCombina", column = @Column(name = "TAN_SEQ_COMBINA", nullable = false)) })
	public MbcTipoAnestesiaCombinadaId getId() {
		return this.id;
	}

	public void setId(MbcTipoAnestesiaCombinadaId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TAN_SEQ", nullable = false, insertable = false, updatable = false)
	public MbcTipoAnestesias getMbcTipoAnestesiasByTanSeq() {
		return this.mbcTipoAnestesiasByTanSeq;
	}

	public void setMbcTipoAnestesiasByTanSeq(MbcTipoAnestesias mbcTipoAnestesiasByTanSeq) {
		this.mbcTipoAnestesiasByTanSeq = mbcTipoAnestesiasByTanSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TAN_SEQ_COMBINA", nullable = false, insertable = false, updatable = false)
	public MbcTipoAnestesias getMbcTipoAnestesiasByTanSeqCombina() {
		return this.mbcTipoAnestesiasByTanSeqCombina;
	}

	public void setMbcTipoAnestesiasByTanSeqCombina(MbcTipoAnestesias mbcTipoAnestesiasByTanSeqCombina) {
		this.mbcTipoAnestesiasByTanSeqCombina = mbcTipoAnestesiasByTanSeqCombina;
	}

	@Column(name = "SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getSituacao() {
		return this.situacao;
	}

	public void setSituacao(DominioSituacao situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		MBC_TIPO_ANESTESIAS_BY_TAN_SEQ("mbcTipoAnestesiasByTanSeq"),
		MBC_TIPO_ANESTESIAS_BY_TAN_SEQ_COMBINA("mbcTipoAnestesiasByTanSeqCombina"),
		SITUACAO("situacao"),
		CRIADO_EM("criadoEm");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcTipoAnestesiaCombinada)) {
			return false;
		}
		MbcTipoAnestesiaCombinada other = (MbcTipoAnestesiaCombinada) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
