package br.gov.mec.aghu.model;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntity;

/**
 * MbcAdministraFichaFluidos generated by hbm2java
 */
@Entity
@Table(name = "MBC_TURNOS", schema = "AGH")
public class MbcTurnos implements BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5928965949443682979L;
	private String turno;
	private String descricao;
	private Short ordem;
	private DominioSituacao situacao;
	private Date criadoEm;
	private RapServidores servidor;
	private Integer version;
	private Set<MbcHorarioTurnoCirg> mbcHorarioTurnoCirg = new HashSet<MbcHorarioTurnoCirg>(0);

	@Id
	@Column(name = "TURNO", unique = true, nullable = false)
	public String getTurno() {
		return turno;
	}

	public void setTurno(String turno) {
		this.turno = turno;
	}

	@Column(name = "DESCRICAO", length = 10, nullable = false)
	@Length(max = 10)
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "ORDEM", nullable = false, precision = 3, scale = 0)
	public Short getOrdem() {
		return ordem;
	}

	public void setOrdem(Short ordem) {
		this.ordem = ordem;
	}


	@Column(name = "SITUACAO", length = 1, nullable = false)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getSituacao() {
		return situacao;
	}

	public void setSituacao(DominioSituacao situacao) {
		this.situacao = situacao;
	}

	
	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
		@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false)})
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}
	
	/**
	 * Campo sintético criado para mapear diretamente este dominio booleano em
	 * um componente selectOneCheckBox
	 * 
	 * @author jvaranda
	 * @return
	 */
	@Transient
	public boolean isAtivo() {
		if (situacao != null && situacao.isAtivo()) {
			return Boolean.TRUE;
		} else {
			return Boolean.FALSE;
		}
	}

	@Transient
	public void setAtivo(boolean ativo) {
		if (ativo) {
			this.situacao = DominioSituacao.A;
		} else {
			this.situacao = DominioSituacao.I;
		}
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mbcTurnos")
	public Set<MbcHorarioTurnoCirg> getMbcHorarioTurnoCirg() {
		return mbcHorarioTurnoCirg;
	}
	
	public void setMbcHorarioTurnoCirg(Set<MbcHorarioTurnoCirg> mbcHorarioTurnoCirg) {
		this.mbcHorarioTurnoCirg = mbcHorarioTurnoCirg;
	}	
	
	public enum Fields {
		TURNO("turno"),
		DESCRICAO("descricao"),
		ORDEM("ordem"),
		SITUACAO("situacao"),
		CRIADO_EM("criadoEm"),
		SERVIDOR("servidor"),
		HORARIO_TURNO_CIRG("mbcHorarioTurnoCirg");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getTurno() == null) ? 0 : getTurno().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MbcTurnos)) {
			return false;
		}
		MbcTurnos other = (MbcTurnos) obj;
		if (getTurno() == null) {
			if (other.getTurno() != null) {
				return false;
			}
		} else if (!getTurno().equals(other.getTurno())) {
			return false;
		}
		return true;
	}

}
