package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MciColunaLinhaExportacaoId generated by hbm2java
 */
@Embeddable
public class MciColunaLinhaExportacaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1832423964044997954L;
	private Short ncrSeq;
	private Short ledSeq;

	public MciColunaLinhaExportacaoId() {
	}

	public MciColunaLinhaExportacaoId(Short ncrSeq, Short ledSeq) {
		this.ncrSeq = ncrSeq;
		this.ledSeq = ledSeq;
	}

	@Column(name = "NCR_SEQ", nullable = false)
	public Short getNcrSeq() {
		return this.ncrSeq;
	}

	public void setNcrSeq(Short ncrSeq) {
		this.ncrSeq = ncrSeq;
	}

	@Column(name = "LED_SEQ", nullable = false)
	public Short getLedSeq() {
		return this.ledSeq;
	}

	public void setLedSeq(Short ledSeq) {
		this.ledSeq = ledSeq;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getLedSeq());
		umHashCodeBuilder.append(this.getNcrSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MciColunaLinhaExportacaoId)) {
			return false;
		}
		MciColunaLinhaExportacaoId other = (MciColunaLinhaExportacaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getLedSeq(), other.getLedSeq());
		umEqualsBuilder.append(this.getNcrSeq(), other.getNcrSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
