package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MciMicroorganismoPatologia generated by hbm2java
 */
@Entity
@Table(name = "MCI_MICROORGANISMO_PATOLOGIAS", schema = "AGH")
public class MciMicroorganismoPatologia extends BaseEntityId<MciMicroorganismoPatologiaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2941662274338213952L;
	private MciMicroorganismoPatologiaId id;
	private Integer version;
	private RapServidores rapServidores;
	private MciPatologiaInfeccao mciPatologiaInfeccao;
	private String descricao;
	private DominioSituacao indSituacao;
	private Date criadoEm;
	private Set<MciMicroorgPatologiaExame> mciMicroorgPatologiaExamees = new HashSet<MciMicroorgPatologiaExame>(0);
	
	private RapServidores rapServidoresMov;
	private Date alteradoEm;

	public MciMicroorganismoPatologia() {
	}

	public MciMicroorganismoPatologia(MciMicroorganismoPatologiaId id, RapServidores rapServidores,
			MciPatologiaInfeccao mciPatologiaInfeccao, String descricao, DominioSituacao indSituacao, Date criadoEm) {
		this.id = id;
		this.rapServidores = rapServidores;
		this.mciPatologiaInfeccao = mciPatologiaInfeccao;
		this.descricao = descricao;
		this.indSituacao = indSituacao;
		this.criadoEm = criadoEm;
	}

	public MciMicroorganismoPatologia(MciMicroorganismoPatologiaId id, RapServidores rapServidores,
			MciPatologiaInfeccao mciPatologiaInfeccao, String descricao, DominioSituacao indSituacao, Date criadoEm,
			Set<MciMicroorgPatologiaExame> mciMicroorgPatologiaExamees) {
		this.id = id;
		this.rapServidores = rapServidores;
		this.mciPatologiaInfeccao = mciPatologiaInfeccao;
		this.descricao = descricao;
		this.indSituacao = indSituacao;
		this.criadoEm = criadoEm;
		this.mciMicroorgPatologiaExamees = mciMicroorgPatologiaExamees;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "paiSeq", column = @Column(name = "PAI_SEQ", nullable = false)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false)) })
	public MciMicroorganismoPatologiaId getId() {
		return this.id;
	}

	public void setId(MciMicroorganismoPatologiaId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAI_SEQ", nullable = false, insertable = false, updatable = false)
	public MciPatologiaInfeccao getMciPatologiaInfeccao() {
		return this.mciPatologiaInfeccao;
	}

	public void setMciPatologiaInfeccao(MciPatologiaInfeccao mciPatologiaInfeccao) {
		this.mciPatologiaInfeccao = mciPatologiaInfeccao;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mciMicroorganismoPatologia")
	public Set<MciMicroorgPatologiaExame> getMciMicroorgPatologiaExamees() {
		return this.mciMicroorgPatologiaExamees;
	}

	public void setMciMicroorgPatologiaExamees(Set<MciMicroorgPatologiaExame> mciMicroorgPatologiaExamees) {
		this.mciMicroorgPatologiaExamees = mciMicroorgPatologiaExamees;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA_MOVIMENTADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_MOVIMENTADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getRapServidoresMov() {
		return rapServidoresMov;
	}

	public void setRapServidoresMov(RapServidores rapServidoresMov) {
		this.rapServidoresMov = rapServidoresMov;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 29)
	public Date getAlteradoEm() {
		return alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}
	
	

	public enum Fields {

		ID("id"),
		ID_PAI_SEQ("id.paiSeq"),
		ID_SEQP("id.seqp"),		
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		MCI_PATOLOGIA_INFECCAO("mciPatologiaInfeccao"),
		DESCRICAO("descricao"),
		IND_SITUACAO("indSituacao"),
		CRIADO_EM("criadoEm"),
		MCI_MICROORG_PATOLOGIA_EXAMEES("mciMicroorgPatologiaExamees"),
		ALTERADO_EM("alteradoEm"),
		RAP_SERVIDORES_MOV("rapServidoresMov")
		;

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MciMicroorganismoPatologia)) {
			return false;
		}
		MciMicroorganismoPatologia other = (MciMicroorganismoPatologia) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
