package br.gov.mec.aghu.model;

// Generated 08/02/2010 17:25:25 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.annotations.Parameter;

import br.gov.mec.aghu.dominio.DominioConfirmacaoCCI;
import br.gov.mec.aghu.dominio.DominioMotivoEncerramentoNotificacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MciMvtoMedidaPreventivas generated by hbm2java
 */
@Entity
@SequenceGenerator(name="mciMmpSq1", sequenceName="AGH.MCI_MMP_SQ1", allocationSize = 1)
@Table(name = "MCI_MVTO_MEDIDA_PREVENTIVAS", schema = "AGH")

public class MciMvtoMedidaPreventivas extends BaseEntitySeq<Integer> implements java.io.Serializable {

	private static final long serialVersionUID = -6015769107048997516L;
	
	private Integer seq;
	private RapServidores servidor;
	private MciMvtoInfeccaoTopografias mciMvtoInfeccaoTopografias;
	private AghUnidadesFuncionais unidadeFuncional;
	private AghUnidadesFuncionais unidadeFuncionalNotificada;
	private AipPacientes paciente;
	private DominioConfirmacaoCCI confirmacaoCci;
	private Date dataInicio;
	private Date criadoEm;
	private MciEtiologiaInfeccao mciEtiologiaInfeccao;
	private MciPatologiaInfeccao patologiaInfeccao;
	private RapServidores servidorConfirmado;
	private AghAtendimentos atendimento;
	private AghInstituicoesHospitalares ihoSeq;
	private AinQuartos quarto;
	private AinQuartos quartoNotificado;
	private AinLeitos leito;
	private AinLeitos leitoNotificado;
	private RapServidores servidorEncerrado;
	private Date dataFim;
	private DominioMotivoEncerramentoNotificacao motivoEncerramento;
	private Boolean impressao;
	private Integer cifSeq;
	private Boolean gmr;
	private Boolean isolamento;
	private Integer version; 

	public MciMvtoMedidaPreventivas() {
	}

	public MciMvtoMedidaPreventivas(Integer seq, RapServidores servidor,
			AghUnidadesFuncionais unidadeFuncional,
			AghUnidadesFuncionais unidadeFuncionalNotificada,
			AipPacientes paciente, DominioConfirmacaoCCI confirmacaoCci,
			Date dataInicio, Date criadoEm, Boolean impressao) {
		this.seq = seq;
		this.servidor = servidor;
		this.unidadeFuncional = unidadeFuncional;
		this.unidadeFuncionalNotificada = unidadeFuncionalNotificada;
		this.paciente = paciente;
		this.confirmacaoCci = confirmacaoCci;
		this.dataInicio = dataInicio;
		this.criadoEm = criadoEm;
		this.impressao = impressao;
	}

	public MciMvtoMedidaPreventivas(Integer seq,
			MciMvtoInfeccaoTopografias mciMvtoInfeccaoTopografias,
			RapServidores servidor, AghUnidadesFuncionais unidadeFuncional,
			AghUnidadesFuncionais unidadeFuncionalNotificada,
			AipPacientes paciente, DominioConfirmacaoCCI confirmacaoCci,
			Date dataInicio, Date criadoEm, MciPatologiaInfeccao patologiaInfeccao,
			RapServidores servidorConfirmado, AghAtendimentos atendimento,
			AghInstituicoesHospitalares ihoSeq, AinQuartos quarto, AinQuartos quartoNotificado,
			AinLeitos leito, AinLeitos leitoNotificado,
			RapServidores servidorEncerrado, Date dataFim,
			DominioMotivoEncerramentoNotificacao motivoEncerramento, Boolean impressao, Integer cifSeq,
			Boolean gmr, Boolean isolamento) {
		this.seq = seq;
		this.mciMvtoInfeccaoTopografias = mciMvtoInfeccaoTopografias;
		this.servidor = servidor;
		this.unidadeFuncional = unidadeFuncional;
		this.unidadeFuncionalNotificada = unidadeFuncionalNotificada;
		this.paciente = paciente;
		this.confirmacaoCci = confirmacaoCci;
		this.dataInicio = dataInicio;
		this.criadoEm = criadoEm;
		this.patologiaInfeccao = patologiaInfeccao;
		this.servidorConfirmado = servidorConfirmado;
		this.atendimento = atendimento;
		this.ihoSeq = ihoSeq;
		this.quarto = quarto;
		this.quartoNotificado = quartoNotificado;
		this.leito = leito;
		this.leitoNotificado = leitoNotificado;
		this.servidorEncerrado = servidorEncerrado;
		this.dataFim = dataFim;
		this.motivoEncerramento = motivoEncerramento;
		this.impressao = impressao;
		this.cifSeq = cifSeq;
		this.gmr = gmr;
		this.isolamento = isolamento;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "mciMmpSq1")
	@Column(name = "SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MIT_SEQ")
	public MciMvtoInfeccaoTopografias getMciMvtoInfeccaoTopografias() {
		return this.mciMvtoInfeccaoTopografias;
	}

	public void setMciMvtoInfeccaoTopografias(
			MciMvtoInfeccaoTopografias mciMvtoInfeccaoTopografias) {
		this.mciMvtoInfeccaoTopografias = mciMvtoInfeccaoTopografias;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNF_SEQ", nullable = false)
	public AghUnidadesFuncionais getUnidadeFuncional() {
		return this.unidadeFuncional;
	}

	public void setUnidadeFuncional(AghUnidadesFuncionais unidadeFuncional) {
		this.unidadeFuncional = unidadeFuncional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNF_SEQ_NOTIFICADO", nullable = false)
	public AghUnidadesFuncionais getUnidadeFuncionalNotificada() {
		return this.unidadeFuncionalNotificada;
	}

	public void setUnidadeFuncionalNotificada(
			AghUnidadesFuncionais unidadeFuncionalNotificada) {
		this.unidadeFuncionalNotificada = unidadeFuncionalNotificada;
	}

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "PAC_CODIGO", nullable = false, referencedColumnName = "CODIGO")
	public AipPacientes getPaciente() {
		return paciente;
	}

	public void setPaciente(AipPacientes paciente) {
		this.paciente = paciente;
	}

	@Column(name = "IND_CONFIRMACAO_CCI", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioConfirmacaoCCI getConfirmacaoCci() {
		return this.confirmacaoCci;
	}

	public void setConfirmacaoCci(DominioConfirmacaoCCI confirmacaoCci) {
		this.confirmacaoCci = confirmacaoCci;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO", nullable = false)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EIN_TIPO")
	public MciEtiologiaInfeccao getMciEtiologiaInfeccao() {
		return this.mciEtiologiaInfeccao;
	}

	public void setMciEtiologiaInfeccao(MciEtiologiaInfeccao mciEtiologiaInfeccao) {
		this.mciEtiologiaInfeccao = mciEtiologiaInfeccao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAI_SEQ")
	public MciPatologiaInfeccao getPatologiaInfeccao() {
		return this.patologiaInfeccao;
	}

	public void setPatologiaInfeccao(MciPatologiaInfeccao patologiaInfeccao) {
		this.patologiaInfeccao = patologiaInfeccao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_CONFIRMADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_CONFIRMADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorConfirmado() {
		return this.servidorConfirmado;
	}

	public void setServidorConfirmado(RapServidores servidorConfirmado) {
		this.servidorConfirmado = servidorConfirmado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATD_SEQ")
	public AghAtendimentos getAtendimento() {
		return this.atendimento;
	}

	public void setAtendimento(AghAtendimentos atendimento) {
		this.atendimento = atendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IHO_SEQ")
	public AghInstituicoesHospitalares getIhoSeq() {
		return this.ihoSeq;
	}

	public void setIhoSeq(AghInstituicoesHospitalares ihoSeq) {
		this.ihoSeq = ihoSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QRT_NUMERO")
	public AinQuartos getQuarto() {
		return this.quarto;
	}

	public void setQuarto(AinQuartos quarto) {
		this.quarto = quarto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QRT_NUMERO_NOTIFICADO")
	public AinQuartos getQuartoNotificado() {
		return this.quartoNotificado;
	}

	public void setQuartoNotificado(AinQuartos quartoNotificado) {
		this.quartoNotificado = quartoNotificado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LTO_LTO_ID")
	public AinLeitos getLeito() {
		return this.leito;
	}

	public void setLeito(AinLeitos leito) {
		this.leito = leito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LTO_LTO_ID_NOTIFICADO")
	public AinLeitos getLeitoNotificado() {
		return this.leitoNotificado;
	}

	public void setLeitoNotificado(AinLeitos leitoNotificado) {
		this.leitoNotificado = leitoNotificado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_ENCERRADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_ENCERRADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorEncerrado() {
		return this.servidorEncerrado;
	}

	public void setServidorEncerrado(RapServidores servidorEncerrado) {
		this.servidorEncerrado = servidorEncerrado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM")
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}


	@Column(name = "MOTIVO_ENCERRAMENTO")
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioMotivoEncerramentoNotificacao") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioMotivoEncerramentoNotificacao getMotivoEncerramento() {
		return this.motivoEncerramento;
	}

	public void setMotivoEncerramento(DominioMotivoEncerramentoNotificacao motivoEncerramento) {
		this.motivoEncerramento = motivoEncerramento;
	}

	@Column(name = "IND_IMPRESSAO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getImpressao() {
		return this.impressao;
	}

	public void setimpressao(Boolean impressao) {
		this.impressao = impressao;
	}

	@Column(name = "CIF_SEQ", precision = 5, scale = 0)
	public Integer getCifSeq() {
		return this.cifSeq;
	}

	public void setCifSeq(Integer cifSeq) {
		this.cifSeq = cifSeq;
	}

	@Column(name = "IND_GMR", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getGmr() {
		return this.gmr;
	}

	public void setGmr(Boolean gmr) {
		this.gmr = gmr;
	}

	@Column(name = "IND_ISOLAMENTO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIsolamento() {
		return this.isolamento;
	}

	public void setIsolamento(Boolean isolamento) {
		this.isolamento = isolamento;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	

	public enum Fields {
		SEQ("seq"),
		UNF_SEQ("unidadeFuncional.seq"),
		UNF_SEQ_NOTIFICADO("unidadeFuncionalNotificada.seq"),
		MVTO_INFECCAO_TOPOGRAFIAS("mciMvtoInfeccaoTopografias"),
		MVTO_INFECCAO_TOPOGRAFIAS_SEQ("mciMvtoInfeccaoTopografias.seq"),
		EIN_TIPO("mciEtiologiaInfeccao.codigo"),
		MCI_ETIOLOGIA_INFECCAO("mciEtiologiaInfeccao"),
		PACIENTE("paciente"),
		COD_PACIENTE("paciente.codigo"),
		DATA_FIM("dataFim"),
		PATOLOGIA_QUARTO_PRIVATIVO("patologiaInfeccao.usoQuartoPrivativo"),
		PATOLOGIA_INFECCAO("patologiaInfeccao"),
		PATOLOGIA_INFECCAO_SEQ("patologiaInfeccao.seq"),
		ISOLAMENTO("isolamento"),
		ATENDIMENTO("atendimento"),
		ATENDIMENTO_SEQ("atendimento.seq"),
		IHO_SEQ("ihoSeq"),
		MIT_SEQ("mciMvtoInfeccaoTopografias"),
		SER_MATRICULA("servidor.id.matricula"),
		SER_VIN_CODIGO("servidor.id.vinCodigo"),
		SER_MATRICULA_ENCERRADO("servidorEncerrado.id.matricula"),
		SER_VIN_CODIGO_ENCERRADO("servidorEncerrado.id.vinCodigo"),
		SER_MATRICULA_CONFIRMADO("servidorConfirmado.id.matricula"),
		SER_VIN_CODIGO_CONFIRMADO("servidorConfirmado.id.vinCodigo"),
		IND_CONFIRMACAO_CCI("confirmacaoCci"),
		DT_INICIO("dataInicio"),
		CRIADO_EM("criadoEm"),
		QRT_NUMERO("quarto.numero"),
		QRT_NUMERO_NOTIFICADO("quartoNotificado.numero"),
		LTO_LTO_ID("leito.leitoID"),
		LTO_LTO_ID_NOTIFICADO("leitoNotificado.leitoID"),
		MOTIVO_ENCERRAMENTO("motivoEncerramento"),
		IND_IMPRESSAO("impressao"),
		CIF_SEQ("cifSeq"),
		IND_GMR("gmr"),
		IND_ISOLAMENTO("isolamento"),
		ATENDIMENTO_DESCRICAO_LOCAL("atendimento.descricaoLocalizacao"),
		INSTITUICAO_HOSPITALAR_SEQ("ihoSeq.seq");
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MciMvtoMedidaPreventivas)) {
			return false;
		}
		MciMvtoMedidaPreventivas other = (MciMvtoMedidaPreventivas) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
