package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MciTmpCargaBi generated by hbm2java
 */
@Entity
@Table(name = "MCI_TMP_CARGA_BIS", schema = "AGH")
public class MciTmpCargaBi extends BaseEntityId<MciTmpCargaBiId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6880990552397350687L;
	private MciTmpCargaBiId id;

	public MciTmpCargaBi() {
	}

	public MciTmpCargaBi(MciTmpCargaBiId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "data", column = @Column(name = "DATA", nullable = false, length = 29)),
			@AttributeOverride(name = "numeroTabelaFato", column = @Column(name = "NUMERO_TABELA_FATO", nullable = false)),
			@AttributeOverride(name = "qtdInfeccoes", column = @Column(name = "QTD_INFECCOES", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdHorasHosp", column = @Column(name = "QTD_HORAS_HOSP", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdSaidas", column = @Column(name = "QTD_SAIDAS", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCirurgiaLimpa", column = @Column(name = "QTD_CIRURGIA_LIMPA", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCirurgiaLimpaNotif", column = @Column(name = "QTD_CIRURGIA_LIMPA_NOTIF", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdPartoNormal", column = @Column(name = "QTD_PARTO_NORMAL", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdPartoNormalInf", column = @Column(name = "QTD_PARTO_NORMAL_INF", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCesariana", column = @Column(name = "QTD_CESARIANA", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCesarianaInf", column = @Column(name = "QTD_CESARIANA_INF", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdInfecPneumo", column = @Column(name = "QTD_INFEC_PNEUMO", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdUsoPneumo", column = @Column(name = "QTD_USO_PNEUMO", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdInfecVesic", column = @Column(name = "QTD_INFEC_VESIC", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdUsoVesic", column = @Column(name = "QTD_USO_VESIC", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdInfecUrin", column = @Column(name = "QTD_INFEC_URIN", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdUsoUrin", column = @Column(name = "QTD_USO_URIN", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdInfecVasc", column = @Column(name = "QTD_INFEC_VASC", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdUsoVasc", column = @Column(name = "QTD_USO_VASC", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdInfecSipageh", column = @Column(name = "QTD_INFEC_SIPAGEH", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdUsoSipageh", column = @Column(name = "QTD_USO_SIPAGEH", precision = 17, scale = 17)),
			@AttributeOverride(name = "unfSeq", column = @Column(name = "UNF_SEQ")),
			@AttributeOverride(name = "fpdSeq", column = @Column(name = "FPD_SEQ")),
			@AttributeOverride(name = "qtdCirurgiaLimpaCca", column = @Column(name = "QTD_CIRURGIA_LIMPA_CCA", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCirurgiaLimpaNotifCca", column = @Column(name = "QTD_CIRURGIA_LIMPA_NOTIF_CCA", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCirurgiaInfectada", column = @Column(name = "QTD_CIRURGIA_INFECTADA", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCirurgiaInfectadaNotif", column = @Column(name = "QTD_CIRURGIA_INFECTADA_NOTIF", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCirurgiaContaminada", column = @Column(name = "QTD_CIRURGIA_CONTAMINADA", precision = 17, scale = 17)),
			@AttributeOverride(name = "qtdCirurgiaContaminadaNotif", column = @Column(name = "QTD_CIRURGIA_CONTAMINADA_NOTIF", precision = 17, scale = 17)),
			@AttributeOverride(name = "prontuario", column = @Column(name = "PRONTUARIO")),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false)) })
	public MciTmpCargaBiId getId() {
		return this.id;
	}

	public void setId(MciTmpCargaBiId id) {
		this.id = id;
	}

	public enum Fields {

		ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
