package br.gov.mec.aghu.model;

// Generated 26/02/2010 17:37:25 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * McoApgarsId generated by hbm2java
 */
@Embeddable
public class McoApgarsId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6175695692396966776L;
	private Integer rnaGsoPacCodigo;
	private Short rnaGsoSeqp;
	private Byte rnaSeqp;
	private Integer serMatricula;
	private Short serVinCodigo;

	public McoApgarsId() {
	}

	public McoApgarsId(Integer rnaGsoPacCodigo, Short rnaGsoSeqp, Byte rnaSeqp,
			Integer serMatricula, Short serVinCodigo) {
		this.rnaGsoPacCodigo = rnaGsoPacCodigo;
		this.rnaGsoSeqp = rnaGsoSeqp;
		this.rnaSeqp = rnaSeqp;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "RNA_GSO_PAC_CODIGO", nullable = false, precision = 8, scale = 0)
	@NotNull
	public Integer getRnaGsoPacCodigo() {
		return this.rnaGsoPacCodigo;
	}

	public void setRnaGsoPacCodigo(Integer rnaGsoPacCodigo) {
		this.rnaGsoPacCodigo = rnaGsoPacCodigo;
	}

	@Column(name = "RNA_GSO_SEQP", nullable = false, precision = 3, scale = 0)
	@NotNull
	public Short getRnaGsoSeqp() {
		return this.rnaGsoSeqp;
	}

	public void setRnaGsoSeqp(Short rnaGsoSeqp) {
		this.rnaGsoSeqp = rnaGsoSeqp;
	}

	@Column(name = "RNA_SEQP", nullable = false, precision = 2, scale = 0)
	@NotNull
	public Byte getRnaSeqp() {
		return this.rnaSeqp;
	}

	public void setRnaSeqp(Byte rnaSeqp) {
		this.rnaSeqp = rnaSeqp;
	}

	@Column(name = "SER_MATRICULA", nullable = false, precision = 7, scale = 0)
	@NotNull
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false, precision = 3, scale = 0)
	@NotNull
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSerMatricula());
		umHashCodeBuilder.append(this.getSerVinCodigo());
		umHashCodeBuilder.append(this.getRnaGsoPacCodigo());
		umHashCodeBuilder.append(this.getRnaGsoSeqp());
		umHashCodeBuilder.append(this.getRnaSeqp());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof McoApgarsId)) {
			return false;
		}
		McoApgarsId other = (McoApgarsId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSerMatricula(), other.getSerMatricula());
		umEqualsBuilder.append(this.getSerVinCodigo(), other.getSerVinCodigo());
		umEqualsBuilder.append(this.getRnaGsoPacCodigo(), other.getRnaGsoPacCodigo());
		umEqualsBuilder.append(this.getRnaGsoSeqp(), other.getRnaGsoSeqp());
		umEqualsBuilder.append(this.getRnaSeqp(), other.getRnaSeqp());
		return umEqualsBuilder.isEquals();
	}
}
