package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * McoExameFisicoRnJn generated by hbm2java
 */
@Entity
@Table(name = "MCO_EXAME_FISICO_RNS_JN", schema = "AGH")
@Immutable
public class McoExameFisicoRnJn extends BaseJournal {

/**
	 * 
	 */
	private static final long serialVersionUID = 2996421767278344203L;
	/* ATUALIZADOR JOURNALS - PROPERTIES	private Long seqJn;
	private String jnUser;
	private Date jnDateTime;
	private String jnOperation;*/
	private Integer rnaGsoPacCodigo;
	private Short rnaGsoSeqp;
	private Short rnaSeqp;
	private Float perCefalico;
	private Float perToracico;
	private Short freqCardiaca;
	private Short freqRespiratoria;
	private Float cirAbdominal;
	private Short igFinal;
	private String adequacaoPeso;
	private String aspectoGeral;
	private String indSemParticularidades;
	private String moro;
	private String fugaAAsfixia;
	private String reptacao;
	private String marcha;
	private String succao;
	private String observacao;
	private Date criadoEm;
	private Integer sdmSeq;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Float temperatura;
	private String indCrede;
	private Short tempoRetornoMae;
	private Short tempoRetornoMin;
	private String reflexoVermelho;

	public McoExameFisicoRnJn() {
	}

	public McoExameFisicoRnJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer rnaGsoPacCodigo, Short rnaGsoSeqp,
			Short rnaSeqp) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.rnaGsoPacCodigo = rnaGsoPacCodigo;
		this.rnaGsoSeqp = rnaGsoSeqp;
		this.rnaSeqp = rnaSeqp;
	}

	@SuppressWarnings({"PMD.ExcessiveParameterList"})
	public McoExameFisicoRnJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer rnaGsoPacCodigo, Short rnaGsoSeqp,
			Short rnaSeqp, Float perCefalico, Float perToracico, Short freqCardiaca, Short freqRespiratoria, Float cirAbdominal,
			Short igFinal, String adequacaoPeso, String aspectoGeral, String indSemParticularidades, String moro, String fugaAAsfixia,
			String reptacao, String marcha, String succao, String observacao, Date criadoEm, Integer sdmSeq, Integer serMatricula,
			Short serVinCodigo, Float temperatura, String indCrede, Short tempoRetornoMae, Short tempoRetornoMin,
			String reflexoVermelho) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.rnaGsoPacCodigo = rnaGsoPacCodigo;
		this.rnaGsoSeqp = rnaGsoSeqp;
		this.rnaSeqp = rnaSeqp;
		this.perCefalico = perCefalico;
		this.perToracico = perToracico;
		this.freqCardiaca = freqCardiaca;
		this.freqRespiratoria = freqRespiratoria;
		this.cirAbdominal = cirAbdominal;
		this.igFinal = igFinal;
		this.adequacaoPeso = adequacaoPeso;
		this.aspectoGeral = aspectoGeral;
		this.indSemParticularidades = indSemParticularidades;
		this.moro = moro;
		this.fugaAAsfixia = fugaAAsfixia;
		this.reptacao = reptacao;
		this.marcha = marcha;
		this.succao = succao;
		this.observacao = observacao;
		this.criadoEm = criadoEm;
		this.sdmSeq = sdmSeq;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.temperatura = temperatura;
		this.indCrede = indCrede;
		this.tempoRetornoMae = tempoRetornoMae;
		this.tempoRetornoMin = tempoRetornoMin;
		this.reflexoVermelho = reflexoVermelho;
	}

	// ATUALIZADOR JOURNALS - ID
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	//@GeneratedValue(strategy = GenerationType.AUTO, generator = "")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	// ATUALIZADOR JOURNALS - ID
	
/* ATUALIZADOR JOURNALS - Get / Set	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	public Long getSeqJn() {
		return this.seqJn;
	}

	public void setSeqJn(Long seqJn) {
		this.seqJn = seqJn;
	}

	@Column(name = "JN_USER", nullable = false, length = 30)
	@Length(max = 30)
	public String getJnUser() {
		return this.jnUser;
	}

	public void setJnUser(String jnUser) {
		this.jnUser = jnUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JN_DATE_TIME", nullable = false, length = 29)
	public Date getJnDateTime() {
		return this.jnDateTime;
	}

	public void setJnDateTime(Date jnDateTime) {
		this.jnDateTime = jnDateTime;
	}

	@Column(name = "JN_OPERATION", nullable = false, length = 3)
	@Length(max = 3)
	public String getJnOperation() {
		return this.jnOperation;
	}

	public void setJnOperation(String jnOperation) {
		this.jnOperation = jnOperation;
	}*/

	@Column(name = "RNA_GSO_PAC_CODIGO", nullable = false)
	public Integer getRnaGsoPacCodigo() {
		return this.rnaGsoPacCodigo;
	}

	public void setRnaGsoPacCodigo(Integer rnaGsoPacCodigo) {
		this.rnaGsoPacCodigo = rnaGsoPacCodigo;
	}

	@Column(name = "RNA_GSO_SEQP", nullable = false)
	public Short getRnaGsoSeqp() {
		return this.rnaGsoSeqp;
	}

	public void setRnaGsoSeqp(Short rnaGsoSeqp) {
		this.rnaGsoSeqp = rnaGsoSeqp;
	}

	@Column(name = "RNA_SEQP", nullable = false)
	public Short getRnaSeqp() {
		return this.rnaSeqp;
	}

	public void setRnaSeqp(Short rnaSeqp) {
		this.rnaSeqp = rnaSeqp;
	}

	@Column(name = "PER_CEFALICO", precision = 8, scale = 8)
	public Float getPerCefalico() {
		return this.perCefalico;
	}

	public void setPerCefalico(Float perCefalico) {
		this.perCefalico = perCefalico;
	}

	@Column(name = "PER_TORACICO", precision = 8, scale = 8)
	public Float getPerToracico() {
		return this.perToracico;
	}

	public void setPerToracico(Float perToracico) {
		this.perToracico = perToracico;
	}

	@Column(name = "FREQ_CARDIACA")
	public Short getFreqCardiaca() {
		return this.freqCardiaca;
	}

	public void setFreqCardiaca(Short freqCardiaca) {
		this.freqCardiaca = freqCardiaca;
	}

	@Column(name = "FREQ_RESPIRATORIA")
	public Short getFreqRespiratoria() {
		return this.freqRespiratoria;
	}

	public void setFreqRespiratoria(Short freqRespiratoria) {
		this.freqRespiratoria = freqRespiratoria;
	}

	@Column(name = "CIR_ABDOMINAL", precision = 8, scale = 8)
	public Float getCirAbdominal() {
		return this.cirAbdominal;
	}

	public void setCirAbdominal(Float cirAbdominal) {
		this.cirAbdominal = cirAbdominal;
	}

	@Column(name = "IG_FINAL")
	public Short getIgFinal() {
		return this.igFinal;
	}

	public void setIgFinal(Short igFinal) {
		this.igFinal = igFinal;
	}

	@Column(name = "ADEQUACAO_PESO", length = 3)
	@Length(max = 3)
	public String getAdequacaoPeso() {
		return this.adequacaoPeso;
	}

	public void setAdequacaoPeso(String adequacaoPeso) {
		this.adequacaoPeso = adequacaoPeso;
	}

	@Column(name = "ASPECTO_GERAL", length = 4)
	@Length(max = 4)
	public String getAspectoGeral() {
		return this.aspectoGeral;
	}

	public void setAspectoGeral(String aspectoGeral) {
		this.aspectoGeral = aspectoGeral;
	}

	@Column(name = "IND_SEM_PARTICULARIDADES", length = 1)
	@Length(max = 1)
	public String getIndSemParticularidades() {
		return this.indSemParticularidades;
	}

	public void setIndSemParticularidades(String indSemParticularidades) {
		this.indSemParticularidades = indSemParticularidades;
	}

	@Column(name = "MORO", length = 3)
	@Length(max = 3)
	public String getMoro() {
		return this.moro;
	}

	public void setMoro(String moro) {
		this.moro = moro;
	}

	@Column(name = "FUGA_A_ASFIXIA", length = 3)
	@Length(max = 3)
	public String getFugaAAsfixia() {
		return this.fugaAAsfixia;
	}

	public void setFugaAAsfixia(String fugaAAsfixia) {
		this.fugaAAsfixia = fugaAAsfixia;
	}

	@Column(name = "REPTACAO", length = 3)
	@Length(max = 3)
	public String getReptacao() {
		return this.reptacao;
	}

	public void setReptacao(String reptacao) {
		this.reptacao = reptacao;
	}

	@Column(name = "MARCHA", length = 3)
	@Length(max = 3)
	public String getMarcha() {
		return this.marcha;
	}

	public void setMarcha(String marcha) {
		this.marcha = marcha;
	}

	@Column(name = "SUCCAO", length = 3)
	@Length(max = 3)
	public String getSuccao() {
		return this.succao;
	}

	public void setSuccao(String succao) {
		this.succao = succao;
	}

	@Column(name = "OBSERVACAO", length = 500)
	@Length(max = 500)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "SDM_SEQ")
	public Integer getSdmSeq() {
		return this.sdmSeq;
	}

	public void setSdmSeq(Integer sdmSeq) {
		this.sdmSeq = sdmSeq;
	}

	@Column(name = "SER_MATRICULA")
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO")
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "TEMPERATURA", precision = 8, scale = 8)
	public Float getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(Float temperatura) {
		this.temperatura = temperatura;
	}

	@Column(name = "IND_CREDE", length = 1)
	@Length(max = 1)
	public String getIndCrede() {
		return this.indCrede;
	}

	public void setIndCrede(String indCrede) {
		this.indCrede = indCrede;
	}

	@Column(name = "TEMPO_RETORNO_MAE")
	public Short getTempoRetornoMae() {
		return this.tempoRetornoMae;
	}

	public void setTempoRetornoMae(Short tempoRetornoMae) {
		this.tempoRetornoMae = tempoRetornoMae;
	}

	@Column(name = "TEMPO_RETORNO_MIN")
	public Short getTempoRetornoMin() {
		return this.tempoRetornoMin;
	}

	public void setTempoRetornoMin(Short tempoRetornoMin) {
		this.tempoRetornoMin = tempoRetornoMin;
	}

	@Column(name = "REFLEXO_VERMELHO", length = 1)
	@Length(max = 1)
	public String getReflexoVermelho() {
		return this.reflexoVermelho;
	}

	public void setReflexoVermelho(String reflexoVermelho) {
		this.reflexoVermelho = reflexoVermelho;
	}

	public enum Fields {

	/* ATUALIZADOR JOURNALS - Fields	SEQ_JN("seqJn"),
		JN_USER("jnUser"),
		JN_DATE_TIME("jnDateTime"),
		JN_OPERATION("jnOperation"),*/
		RNA_GSO_PAC_CODIGO("rnaGsoPacCodigo"),
		RNA_GSO_SEQP("rnaGsoSeqp"),
		RNA_SEQP("rnaSeqp"),
		PER_CEFALICO("perCefalico"),
		PER_TORACICO("perToracico"),
		FREQ_CARDIACA("freqCardiaca"),
		FREQ_RESPIRATORIA("freqRespiratoria"),
		CIR_ABDOMINAL("cirAbdominal"),
		IG_FINAL("igFinal"),
		ADEQUACAO_PESO("adequacaoPeso"),
		ASPECTO_GERAL("aspectoGeral"),
		IND_SEM_PARTICULARIDADES("indSemParticularidades"),
		MORO("moro"),
		FUGA_A_ASFIXIA("fugaAAsfixia"),
		REPTACAO("reptacao"),
		MARCHA("marcha"),
		SUCCAO("succao"),
		OBSERVACAO("observacao"),
		CRIADO_EM("criadoEm"),
		SDM_SEQ("sdmSeq"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		TEMPERATURA("temperatura"),
		IND_CREDE("indCrede"),
		TEMPO_RETORNO_MAE("tempoRetornoMae"),
		TEMPO_RETORNO_MIN("tempoRetornoMin"),
		REFLEXO_VERMELHO("reflexoVermelho");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
