package br.gov.mec.aghu.model;

// Generated 26/02/2010 17:37:25 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * McoIntercorrenciaGestacoes generated by hbm2java
 */
@Entity
@Table(name = "MCO_INTERCORRENCIA_GESTACOES", schema = "AGH")
public class McoIntercorrenciaGestacoes extends BaseEntityId<McoIntercorrenciaGestacoesId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7744929680476624249L;
	private McoIntercorrenciaGestacoesId id;
	private McoGestacoes mcoGestacoes;
	private String ocorrencia;
	private String complemento;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Date criadoEm;

	public McoIntercorrenciaGestacoes() {
	}

	public McoIntercorrenciaGestacoes(McoIntercorrenciaGestacoesId id,
			McoGestacoes mcoGestacoes, String ocorrencia, Integer serMatricula,
			Short serVinCodigo, Date criadoEm) {
		this.id = id;
		this.mcoGestacoes = mcoGestacoes;
		this.ocorrencia = ocorrencia;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.criadoEm = criadoEm;
	}

	public McoIntercorrenciaGestacoes(McoIntercorrenciaGestacoesId id,
			McoGestacoes mcoGestacoes, String ocorrencia, String complemento,
			Integer serMatricula, Short serVinCodigo, Date criadoEm) {
		this.id = id;
		this.mcoGestacoes = mcoGestacoes;
		this.ocorrencia = ocorrencia;
		this.complemento = complemento;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.criadoEm = criadoEm;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "gsoPacCodigo", column = @Column(name = "GSO_PAC_CODIGO", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "gsoSeqp", column = @Column(name = "GSO_SEQP", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "opaSeq", column = @Column(name = "OPA_SEQ", nullable = false, precision = 22, scale = 0)) })
	public McoIntercorrenciaGestacoesId getId() {
		return this.id;
	}

	public void setId(McoIntercorrenciaGestacoesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "GSO_PAC_CODIGO", referencedColumnName = "PAC_CODIGO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GSO_SEQP", referencedColumnName = "SEQP", nullable = false, insertable = false, updatable = false) })
	public McoGestacoes getMcoGestacoes() {
		return this.mcoGestacoes;
	}

	public void setMcoGestacoes(McoGestacoes mcoGestacoes) {
		this.mcoGestacoes = mcoGestacoes;
	}

	@Column(name = "OCORRENCIA", nullable = false, length = 1)
	@Length(max = 1)
	public String getOcorrencia() {
		return this.ocorrencia;
	}

	public void setOcorrencia(String ocorrencia) {
		this.ocorrencia = ocorrencia;
	}

	@Column(name = "COMPLEMENTO", length = 2000)
	@Length(max = 2000)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "SER_MATRICULA", nullable = false, precision = 7, scale = 0)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false, precision = 3, scale = 0)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}
	
	public enum Fields {
		CODIGO_PACIENTE("id.gsoPacCodigo"), 
		SEQUENCE("id.gsoSeqp"),
		OCORRENCIA("ocorrencia");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}		


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof McoIntercorrenciaGestacoes)) {
			return false;
		}
		McoIntercorrenciaGestacoes other = (McoIntercorrenciaGestacoes) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
