package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Parameter;

import br.gov.mec.aghu.dominio.DominioFormaOrelha;
import br.gov.mec.aghu.dominio.DominioFormacaoMamilo;
import br.gov.mec.aghu.dominio.DominioGlandulaMamaria;
import br.gov.mec.aghu.dominio.DominioPregasPlantares;
import br.gov.mec.aghu.dominio.DominioTexturaPele;
import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * McoIddGestCapurroJn generated by hbm2java
 */
@Entity
@SequenceGenerator(name="aghMcoIdcJnSeq", sequenceName="AGH.MCO_IDC_JN_SEQ", allocationSize = 1)
@Table(name = "MCO_IDD_GEST_CAPURROS_JN", schema = "AGH")
@Immutable
public class McoIddGestCapurrosJn extends BaseJournal {

	private static final long serialVersionUID = -4860137740242486340L;
	
	private DominioTexturaPele texturaPele;
	private DominioPregasPlantares pregasPlantares;
	private DominioFormacaoMamilo formacaoMamilo;
	private DominioFormaOrelha formaOrelha;
	private DominioGlandulaMamaria glandulaMamaria;
	private Date criadoEm;
	private Date alteradoEm;
	private Byte igSemanas;
	private Byte igDias;
	private Integer pacCodigo;
	private Integer serMatricula;
	private Short serVinCodigo;

	public McoIddGestCapurrosJn() {
	}

	public McoIddGestCapurrosJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer pacCodigo, Integer serMatricula,
			Short serVinCodigo) {
		this.pacCodigo = pacCodigo;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
	}

	public McoIddGestCapurrosJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, DominioTexturaPele texturaPele,
			DominioPregasPlantares pregasPlantares, DominioFormacaoMamilo formacaoMamilo, DominioFormaOrelha formaOrelha,
			DominioGlandulaMamaria glandulaMamaria, Date criadoEm, Date alteradoEm,
			Byte igSemanas, Byte igDias, Integer pacCodigo, Integer serMatricula, Short serVinCodigo) {
		this.texturaPele = texturaPele;
		this.pregasPlantares = pregasPlantares;
		this.formacaoMamilo = formacaoMamilo;
		this.formaOrelha = formaOrelha;
		this.glandulaMamaria = glandulaMamaria;
		this.criadoEm = criadoEm;
		this.alteradoEm = alteradoEm;
		this.igSemanas = igSemanas;
		this.igDias = igDias;
		this.pacCodigo = pacCodigo;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
	}

	// ATUALIZADOR JOURNALS - ID
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "aghMcoIdcJnSeq")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	// ATUALIZADOR JOURNALS - ID
	
	@Column(name = "TEXTURA_PELE", nullable = false, length = 2)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioTexturaPele") },
		type = "br.gov.mec.aghu.core.model.jpa.DominioStringUserType")
	public DominioTexturaPele getTexturaPele() {
		return this.texturaPele;
	}

	public void setTexturaPele(DominioTexturaPele texturaPele) {
		this.texturaPele = texturaPele;
	}

	@Column(name = "PREGAS_PLANTARES", nullable = false, length = 2)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPregasPlantares") },
		type = "br.gov.mec.aghu.core.model.jpa.DominioStringUserType")
	public DominioPregasPlantares getPregasPlantares() {
		return this.pregasPlantares;
	}

	public void setPregasPlantares(DominioPregasPlantares pregasPlantares) {
		this.pregasPlantares = pregasPlantares;
	}

	@Column(name = "FORMACAO_MAMILO", nullable = false, length = 2)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioFormacaoMamilo") },
		type = "br.gov.mec.aghu.core.model.jpa.DominioStringUserType")
	public DominioFormacaoMamilo getFormacaoMamilo() {
		return this.formacaoMamilo;
	}

	public void setFormacaoMamilo(DominioFormacaoMamilo formacaoMamilo) {
		this.formacaoMamilo = formacaoMamilo;
	}

	@Column(name = "FORMA_ORELHA", nullable = false, length = 2)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioFormaOrelha") },
		type = "br.gov.mec.aghu.core.model.jpa.DominioStringUserType")
	public DominioFormaOrelha getFormaOrelha() {
		return this.formaOrelha;
	}

	public void setFormaOrelha(DominioFormaOrelha formaOrelha) {
		this.formaOrelha = formaOrelha;
	}

	@Column(name = "GLANDULA_MAMARIA", nullable = false, length = 2)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioGlandulaMamaria") },
		type = "br.gov.mec.aghu.core.model.jpa.DominioStringUserType")
	public DominioGlandulaMamaria getGlandulaMamaria() {
		return this.glandulaMamaria;
	}

	public void setGlandulaMamaria(DominioGlandulaMamaria glandulaMamaria) {
		this.glandulaMamaria = glandulaMamaria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 29)
	public Date getAlteradoEm() {
		return alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@Column(name = "IG_SEMANAS", nullable = false, precision = 2, scale = 0)
	@NotNull
	public Byte getIgSemanas() {
		return this.igSemanas;
	}

	public void setIgSemanas(Byte igSemanas) {
		this.igSemanas = igSemanas;
	}

	@Column(name = "IG_DIAS", precision = 2, scale = 0)
	public Byte getIgDias() {
		return this.igDias;
	}

	public void setIgDias(Byte igDias) {
		this.igDias = igDias;
	}

	@Column(name = "PAC_CODIGO", nullable = false)
	public Integer getPacCodigo() {
		return this.pacCodigo;
	}

	public void setPacCodigo(Integer pacCodigo) {
		this.pacCodigo = pacCodigo;
	}

	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	public enum Fields {

		TEXTURA_PELE("texturaPele"),
		PREGAS_PLANTARES("pregasPlantares"),
		FORMACAO_MAMILO("formacaoMamilo"),
		FORMA_ORELHA("formaOrelha"),
		GLANDULA_MAMARIA("glandulaMamaria"),
		CRIADO_EM("criadoEm"),
		IG_SEMANAS("igSemanas"),
		IG_DIAS("igDias"),
		PAC_CODIGO("pacCodigo"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
