package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * McoRefCodeId generated by hbm2java
 */
@Embeddable
public class McoRefCodeId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6612772931208397410L;
	private String rvDomain;
	private String rvLowValue;
	private String rvHighValue;
	private String rvAbbreviation;
	private String rvMeaning;
	private Integer version;

	public McoRefCodeId() {
	}

	public McoRefCodeId(String rvDomain, String rvLowValue, Integer version) {
		this.rvDomain = rvDomain;
		this.rvLowValue = rvLowValue;
		this.version = version;
	}

	public McoRefCodeId(String rvDomain, String rvLowValue, String rvHighValue, String rvAbbreviation, String rvMeaning, Integer version) {
		this.rvDomain = rvDomain;
		this.rvLowValue = rvLowValue;
		this.rvHighValue = rvHighValue;
		this.rvAbbreviation = rvAbbreviation;
		this.rvMeaning = rvMeaning;
		this.version = version;
	}

	@Column(name = "RV_DOMAIN", nullable = false, length = 100)
	@Length(max = 100)
	public String getRvDomain() {
		return this.rvDomain;
	}

	public void setRvDomain(String rvDomain) {
		this.rvDomain = rvDomain;
	}

	@Column(name = "RV_LOW_VALUE", nullable = false, length = 240)
	@Length(max = 240)
	public String getRvLowValue() {
		return this.rvLowValue;
	}

	public void setRvLowValue(String rvLowValue) {
		this.rvLowValue = rvLowValue;
	}

	@Column(name = "RV_HIGH_VALUE", length = 240)
	@Length(max = 240)
	public String getRvHighValue() {
		return this.rvHighValue;
	}

	public void setRvHighValue(String rvHighValue) {
		this.rvHighValue = rvHighValue;
	}

	@Column(name = "RV_ABBREVIATION", length = 240)
	@Length(max = 240)
	public String getRvAbbreviation() {
		return this.rvAbbreviation;
	}

	public void setRvAbbreviation(String rvAbbreviation) {
		this.rvAbbreviation = rvAbbreviation;
	}

	@Column(name = "RV_MEANING", length = 240)
	@Length(max = 240)
	public String getRvMeaning() {
		return this.rvMeaning;
	}

	public void setRvMeaning(String rvMeaning) {
		this.rvMeaning = rvMeaning;
	}

	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getVersion());
		umHashCodeBuilder.append(this.getRvLowValue());
		umHashCodeBuilder.append(this.getRvHighValue());
		umHashCodeBuilder.append(this.getRvAbbreviation());
		umHashCodeBuilder.append(this.getRvDomain());
		umHashCodeBuilder.append(this.getRvMeaning());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof McoRefCodeId)) {
			return false;
		}
		McoRefCodeId other = (McoRefCodeId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getVersion(), other.getVersion());
		umEqualsBuilder.append(this.getRvLowValue(), other.getRvLowValue());
		umEqualsBuilder.append(this.getRvHighValue(), other.getRvHighValue());
		umEqualsBuilder.append(this.getRvAbbreviation(), other.getRvAbbreviation());
		umEqualsBuilder.append(this.getRvDomain(), other.getRvDomain());
		umEqualsBuilder.append(this.getRvMeaning(), other.getRvMeaning());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
