package br.gov.mec.aghu.model;

// Generated 10/03/2011 17:20:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MpaCadOrdItemExames generated by hbm2java
 */

@Entity
@Table(name = "MPA_CAD_ORD_ITEM_EXAMES", schema = "AGH")
public class MpaCadOrdItemExame extends BaseEntityId<MpaCadOrdItemExameId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7151815999020121929L;
	private MpaCadOrdItemExameId id;
	private Byte nroAmostras;
	private Byte intervaloDias;
	private Date intervaloHoras;
	private Date criadoEm;
	private String ufeEmaExaSigla;
	private Integer ufeEmaManSeq;
	private Short ufeUnfSeq;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Short icoSeq;


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "coxSeq", column = @Column(name = "COX_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 8, scale = 0)) })
	public MpaCadOrdItemExameId getId() {
		return this.id;
	}

	public void setId(MpaCadOrdItemExameId id) {
		this.id = id;
	}

	@Column(name = "NRO_AMOSTRAS", precision = 2, scale = 0)
	public Byte getNroAmostras() {
		return this.nroAmostras;
	}

	public void setNroAmostras(Byte nroAmostras) {
		this.nroAmostras = nroAmostras;
	}

	@Column(name = "INTERVALO_DIAS", precision = 2, scale = 0)
	public Byte getIntervaloDias() {
		return this.intervaloDias;
	}

	public void setIntervaloDias(Byte intervaloDias) {
		this.intervaloDias = intervaloDias;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INTERVALO_HORAS", length = 7)
	public Date getIntervaloHoras() {
		return this.intervaloHoras;
	}

	public void setIntervaloHoras(Date intervaloHoras) {
		this.intervaloHoras = intervaloHoras;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "UFE_EMA_EXA_SIGLA", nullable = false, length = 5)
	@Length(max = 5)
	public String getUfeEmaExaSigla() {
		return this.ufeEmaExaSigla;
	}

	public void setUfeEmaExaSigla(String ufeEmaExaSigla) {
		this.ufeEmaExaSigla = ufeEmaExaSigla;
	}

	@Column(name = "UFE_EMA_MAN_SEQ", nullable = false, precision = 5, scale = 0)
	public Integer getUfeEmaManSeq() {
		return this.ufeEmaManSeq;
	}

	public void setUfeEmaManSeq(Integer ufeEmaManSeq) {
		this.ufeEmaManSeq = ufeEmaManSeq;
	}

	@Column(name = "UFE_UNF_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getUfeUnfSeq() {
		return this.ufeUnfSeq;
	}

	public void setUfeUnfSeq(Short ufeUnfSeq) {
		this.ufeUnfSeq = ufeUnfSeq;
	}

	@Column(name = "SER_MATRICULA", nullable = false, precision = 7, scale = 0)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false, precision = 3, scale = 0)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "ICO_SEQ", precision = 4, scale = 0)
	public Short getIcoSeq() {
		return this.icoSeq;
	}

	public void setIcoSeq(Short icoSeq) {
		this.icoSeq = icoSeq;
	}
	
	public enum Fields {
		ID("id"),
		NRO_AMOSTRAS("nroAmostras"),
		INTERVALO_DIAS("intervaloDias"),
		INTERVALO_HORAS("intervaloHoras"),
		CRIADO_EM("criadoEm"),
		UFE_EMA_EXA_SIGLA("ufeEmaExaSigla"),
		UFE_EMA_MAN_SEQ("ufeEmaManSeq"),
		UFE_UNF_SEQ("ufeUnfSeq"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		ICO_SEQ("icoSeq");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MpaCadOrdItemExame)) {
			return false;
		}
		MpaCadOrdItemExame other = (MpaCadOrdItemExame) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
