package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MpaConsGrupoAvaliadorId generated by hbm2java
 */
@Embeddable
public class MpaConsGrupoAvaliadorId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1220379382736885219L;
	private Short gapSeq;
	private Short cprCodigo;
	private Double seqp;

	public MpaConsGrupoAvaliadorId() {
	}

	public MpaConsGrupoAvaliadorId(Short gapSeq, Short cprCodigo, Double seqp) {
		this.gapSeq = gapSeq;
		this.cprCodigo = cprCodigo;
		this.seqp = seqp;
	}

	@Column(name = "GAP_SEQ", nullable = false)
	public Short getGapSeq() {
		return this.gapSeq;
	}

	public void setGapSeq(Short gapSeq) {
		this.gapSeq = gapSeq;
	}

	@Column(name = "CPR_CODIGO", nullable = false)
	public Short getCprCodigo() {
		return this.cprCodigo;
	}

	public void setCprCodigo(Short cprCodigo) {
		this.cprCodigo = cprCodigo;
	}

	@Column(name = "SEQP", nullable = false, precision = 17, scale = 17)
	public Double getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Double seqp) {
		this.seqp = seqp;
	}

	




	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getGapSeq());
		umHashCodeBuilder.append(this.getCprCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MpaConsGrupoAvaliadorId)) {
			return false;
		}
		MpaConsGrupoAvaliadorId other = (MpaConsGrupoAvaliadorId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getGapSeq(), other.getGapSeq());
		umEqualsBuilder.append(this.getCprCodigo(), other.getCprCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
