package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityCodigo;

/**
 * MpaTipoItemProtocolo generated by hbm2java
 */
@Entity
@Table(name = "MPA_TIPO_ITEM_PROTOCOLOS", schema = "AGH")
public class MpaTipoItemProtocolo extends BaseEntityCodigo<String> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -23628345890034886L;
	private String codigo;
	private Integer version;
	private String descricao;
	private Date criadoEm;
	private Double ordemImpressao;

	public MpaTipoItemProtocolo() {
	}

	public MpaTipoItemProtocolo(String codigo, String descricao, Date criadoEm) {
		this.codigo = codigo;
		this.descricao = descricao;
		this.criadoEm = criadoEm;
	}

	public MpaTipoItemProtocolo(String codigo, String descricao, Date criadoEm, Double ordemImpressao) {
		this.codigo = codigo;
		this.descricao = descricao;
		this.criadoEm = criadoEm;
		this.ordemImpressao = ordemImpressao;
	}

	@Id
	@Column(name = "CODIGO", unique = true, nullable = false, length = 2)
	@Length(max = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 30)
	@Length(max = 30)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "ORDEM_IMPRESSAO", precision = 17, scale = 17)
	public Double getOrdemImpressao() {
		return this.ordemImpressao;
	}

	public void setOrdemImpressao(Double ordemImpressao) {
		this.ordemImpressao = ordemImpressao;
	}

	public enum Fields {

		CODIGO("codigo"),
		VERSION("version"),
		DESCRICAO("descricao"),
		CRIADO_EM("criadoEm"),
		ORDEM_IMPRESSAO("ordemImpressao");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getCodigo() == null) ? 0 : getCodigo().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MpaTipoItemProtocolo)) {
			return false;
		}
		MpaTipoItemProtocolo other = (MpaTipoItemProtocolo) obj;
		if (getCodigo() == null) {
			if (other.getCodigo() != null) {
				return false;
			}
		} else if (!getCodigo().equals(other.getCodigo())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
