package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MpaUsoExameDiagnostico generated by hbm2java
 */
@Entity
@Table(name = "MPA_USO_EXAME_DIAGNOSTICOS", schema = "AGH")
public class MpaUsoExameDiagnostico extends BaseEntityId<MpaUsoExameDiagnosticoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -784995758071860165L;
	private MpaUsoExameDiagnosticoId id;
	private Integer version;
	private MpaUsoProtocolo mpaUsoProtocolo;
	private RapServidores rapServidores;
	private MpaCadExameDiagnostico mpaCadExameDiagnostico;
	private Date criadoEm;
	private String indMarcada;
	private Set<MpaUsoOrdExame> mpaUsoOrdExamees = new HashSet<MpaUsoOrdExame>(0);

	public MpaUsoExameDiagnostico() {
	}

	public MpaUsoExameDiagnostico(MpaUsoExameDiagnosticoId id, MpaUsoProtocolo mpaUsoProtocolo, RapServidores rapServidores,
			MpaCadExameDiagnostico mpaCadExameDiagnostico, Date criadoEm, String indMarcada) {
		this.id = id;
		this.mpaUsoProtocolo = mpaUsoProtocolo;
		this.rapServidores = rapServidores;
		this.mpaCadExameDiagnostico = mpaCadExameDiagnostico;
		this.criadoEm = criadoEm;
		this.indMarcada = indMarcada;
	}

	public MpaUsoExameDiagnostico(MpaUsoExameDiagnosticoId id, MpaUsoProtocolo mpaUsoProtocolo, RapServidores rapServidores,
			MpaCadExameDiagnostico mpaCadExameDiagnostico, Date criadoEm, String indMarcada, Set<MpaUsoOrdExame> mpaUsoOrdExamees) {
		this.id = id;
		this.mpaUsoProtocolo = mpaUsoProtocolo;
		this.rapServidores = rapServidores;
		this.mpaCadExameDiagnostico = mpaCadExameDiagnostico;
		this.criadoEm = criadoEm;
		this.indMarcada = indMarcada;
		this.mpaUsoOrdExamees = mpaUsoOrdExamees;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "uspApaAtdSeq", column = @Column(name = "USP_APA_ATD_SEQ", nullable = false)),
			@AttributeOverride(name = "uspApaSeq", column = @Column(name = "USP_APA_SEQ", nullable = false)),
			@AttributeOverride(name = "uspVpaPtaSeq", column = @Column(name = "USP_VPA_PTA_SEQ", nullable = false)),
			@AttributeOverride(name = "uspVpaSeqp", column = @Column(name = "USP_VPA_SEQP", nullable = false)),
			@AttributeOverride(name = "uspSeq", column = @Column(name = "USP_SEQ", nullable = false)),
			@AttributeOverride(name = "cedCitVpaPtaSeq", column = @Column(name = "CED_CIT_VPA_PTA_SEQ", nullable = false)),
			@AttributeOverride(name = "cedCitVpaSeqp", column = @Column(name = "CED_CIT_VPA_SEQP", nullable = false)),
			@AttributeOverride(name = "cedCitSeqp", column = @Column(name = "CED_CIT_SEQP", nullable = false)),
			@AttributeOverride(name = "cedSeqp", column = @Column(name = "CED_SEQP", nullable = false)) })
	public MpaUsoExameDiagnosticoId getId() {
		return this.id;
	}

	public void setId(MpaUsoExameDiagnosticoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "USP_APA_ATD_SEQ", referencedColumnName = "APA_ATD_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "USP_APA_SEQ", referencedColumnName = "APA_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "USP_VPA_PTA_SEQ", referencedColumnName = "VPA_PTA_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "USP_VPA_SEQP", referencedColumnName = "VPA_SEQP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "USP_SEQ", referencedColumnName = "SEQ", nullable = false, insertable = false, updatable = false) })
	public MpaUsoProtocolo getMpaUsoProtocolo() {
		return this.mpaUsoProtocolo;
	}

	public void setMpaUsoProtocolo(MpaUsoProtocolo mpaUsoProtocolo) {
		this.mpaUsoProtocolo = mpaUsoProtocolo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CED_CIT_VPA_PTA_SEQ", referencedColumnName = "CIT_VPA_PTA_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CED_CIT_VPA_SEQP", referencedColumnName = "CIT_VPA_SEQP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CED_CIT_SEQP", referencedColumnName = "CIT_SEQP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CED_SEQP", referencedColumnName = "SEQP", nullable = false, insertable = false, updatable = false) })
	public MpaCadExameDiagnostico getMpaCadExameDiagnostico() {
		return this.mpaCadExameDiagnostico;
	}

	public void setMpaCadExameDiagnostico(MpaCadExameDiagnostico mpaCadExameDiagnostico) {
		this.mpaCadExameDiagnostico = mpaCadExameDiagnostico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "IND_MARCADA", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndMarcada() {
		return this.indMarcada;
	}

	public void setIndMarcada(String indMarcada) {
		this.indMarcada = indMarcada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mpaUsoExameDiagnostico")
	public Set<MpaUsoOrdExame> getMpaUsoOrdExamees() {
		return this.mpaUsoOrdExamees;
	}

	public void setMpaUsoOrdExamees(Set<MpaUsoOrdExame> mpaUsoOrdExamees) {
		this.mpaUsoOrdExamees = mpaUsoOrdExamees;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		MPA_USO_PROTOCOLOS("mpaUsoProtocolo"),
		RAP_SERVIDORES("rapServidores"),
		MPA_CAD_EXAME_DIAGNOSTICOS("mpaCadExameDiagnostico"),
		CRIADO_EM("criadoEm"),
		IND_MARCADA("indMarcada"),
		MPA_USO_ORD_EXAMEES("mpaUsoOrdExamees");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MpaUsoExameDiagnostico)) {
			return false;
		}
		MpaUsoExameDiagnostico other = (MpaUsoExameDiagnostico) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
