package br.gov.mec.aghu.model;

// Generated 29/10/2010 11:32:32 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MpaUsoOrdModoProceds generated by hbm2java
 */
@Entity
@Table(name = "MPA_USO_ORD_MODO_PROCEDS", schema = "AGH")
public class MpaUsoOrdModoProced extends BaseEntityId<MpaUsoOrdModoProcedId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1052672371565957228L;
	private MpaUsoOrdModoProcedId id;
	private MpaUsoOrdProcedimento usoOrdProcedimento; 
	private Integer cmpCopSeq;
	private Short cmpSeqp;
	private MpmTipoModoUsoProcedimento tipoModoUsoProcedimento;
	private RapServidores servidor;
	private Date criadoEm;
	private Short quantidade;
	private MpmModoUsoPrescProced modoUsoPrescProced;

	public MpaUsoOrdModoProced() {
	}

	public MpaUsoOrdModoProced(MpaUsoOrdModoProcedId id, MpmTipoModoUsoProcedimento tipoModoUsoProcedimento, RapServidores servidor,
			Date criadoEm) {
		this.id = id;
		this.tipoModoUsoProcedimento = tipoModoUsoProcedimento;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
	}

	public MpaUsoOrdModoProced(MpaUsoOrdModoProcedId id, Integer cmpCopSeq, Short cmpSeqp, MpmTipoModoUsoProcedimento tipoModoUsoProcedimento,
			RapServidores servidor, Date criadoEm, Short quantidade, MpmModoUsoPrescProced modoUsoPrescProced) {
		this.id = id;
		this.cmpCopSeq = cmpCopSeq;
		this.cmpSeqp = cmpSeqp;
		this.tipoModoUsoProcedimento = tipoModoUsoProcedimento;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
		this.quantidade = quantidade;
		this.modoUsoPrescProced = modoUsoPrescProced;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "uopSeq", column = @Column(name = "UOP_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 4, scale = 0)) })
	public MpaUsoOrdModoProcedId getId() {
		return this.id;
	}

	public void setId(MpaUsoOrdModoProcedId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name = "UOP_SEQ", nullable = false, insertable = false, updatable = false)
	public MpaUsoOrdProcedimento getUsoOrdProcedimento() {
		return this.usoOrdProcedimento;
	}

	public void setUsoOrdProcedimento(MpaUsoOrdProcedimento usoOrdProcedimento) {
		this.usoOrdProcedimento = usoOrdProcedimento;
	}

	@Column(name = "CMP_COP_SEQ", precision = 8, scale = 0)
	public Integer getCmpCopSeq() {
		return this.cmpCopSeq;
	}

	public void setCmpCopSeq(Integer cmpCopSeq) {
		this.cmpCopSeq = cmpCopSeq;
	}

	@Column(name = "CMP_SEQP", precision = 4, scale = 0)
	public Short getCmpSeqp() {
		return this.cmpSeqp;
	}

	public void setCmpSeqp(Short cmpSeqp) {
		this.cmpSeqp = cmpSeqp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "TUP_SEQP", referencedColumnName = "SEQP", nullable = false),
			@JoinColumn(name = "TUP_PED_SEQ", referencedColumnName = "PED_SEQ", nullable = false) })
	public MpmTipoModoUsoProcedimento getTipoModoUsoProcedimento() {
		return this.tipoModoUsoProcedimento;
	}

	public void setTipoModoUsoProcedimento(MpmTipoModoUsoProcedimento tipoModoUsoProcedimento) {
		this.tipoModoUsoProcedimento = tipoModoUsoProcedimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "QUANTIDADE", precision = 3, scale = 0)
	public Short getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Short quantidade) {
		this.quantidade = quantidade;
	}

	@JoinColumns({ @JoinColumn(name = "MUP_PPR_ATD_SEQ", referencedColumnName = "PPR_ATD_SEQ"),
			@JoinColumn(name = "MUP_PPR_SEQ", referencedColumnName = "PPR_SEQ"),
			@JoinColumn(name = "MUP_SEQP", referencedColumnName = "SEQP") })
	public MpmModoUsoPrescProced getModoUsoPrescProced() {
		return this.modoUsoPrescProced;
	}

	public void setModoUsoPrescProced(MpmModoUsoPrescProced modoUsoPrescProced) {
		this.modoUsoPrescProced = modoUsoPrescProced;
	}
	
	public enum Fields {
		ID("id"),USO_ORD_PROCEDIMENTO("usoOrdProcedimento");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}

	@Override
	public int hashCode() {
		return this.getId() == null ? 0 : this.getId().hashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		
		MpaUsoOrdModoProced other = (MpaUsoOrdModoProced) obj;
		return this.getId() != null && this.getId().equals(other.getId());
	}

}