package br.gov.mec.aghu.model;

// Generated 04/02/2011 16:54:07 by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MpaUsoOrdItemNutricoes generated by hbm2java
 */

@Entity
@Table(name = "MPA_USO_ORD_ITEM_NUTRICOES", schema = "AGH")
public class MpaUsoOrdItemNutricoes extends BaseEntityId<MpaUsoOrdItemNutricoesId> implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5558581231677717823L;
	private MpaUsoOrdItemNutricoesId id;
	private MpaCadOrdItemNutricoes cadOrdItemNutricoes; 
	private AnuTipoItemDieta tipoItemDieta; 
	private RapServidores servidor; 
	private MpmItemPrescricaoDieta itemPrescricaoDieta;
	private MpmTipoFrequenciaAprazamento tipoFrequenciaAprazamento;
	private Integer frequencia;
	private BigDecimal quantidade;
	private Date criadoEm;
	private Byte numVezes;

	public MpaUsoOrdItemNutricoes() {
	}

	public MpaUsoOrdItemNutricoes(MpaUsoOrdItemNutricoesId id, AnuTipoItemDieta tipoItemDieta,
			RapServidores servidor, Date criadoEm) {
		this.id = id;
		this.tipoItemDieta = tipoItemDieta;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
	}

	public MpaUsoOrdItemNutricoes(MpaUsoOrdItemNutricoesId id,
			MpaCadOrdItemNutricoes cadOrdItemNutricoes, AnuTipoItemDieta tipoItemDieta,
			RapServidores servidor, MpmItemPrescricaoDieta itemPrescricaoDieta, MpmTipoFrequenciaAprazamento tipoFrequenciaAprazamento,
			Integer frequencia, BigDecimal quantidade, Date criadoEm,
			Byte numVezes) {
		this.id = id;
		this.cadOrdItemNutricoes = cadOrdItemNutricoes;
		this.tipoItemDieta = tipoItemDieta;
		this.servidor = servidor;
		this.itemPrescricaoDieta = itemPrescricaoDieta;
		this.tipoFrequenciaAprazamento = tipoFrequenciaAprazamento;
		this.frequencia = frequencia;
		this.quantidade = quantidade;
		this.criadoEm = criadoEm;
		this.numVezes = numVezes;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "uonSeq", column = @Column(name = "UON_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 4, scale = 0)) })
	public MpaUsoOrdItemNutricoesId getId() {
		return this.id;
	}

	public void setId(MpaUsoOrdItemNutricoesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "CRN_COR_SEQ", referencedColumnName = "COR_SEQ"),
			@JoinColumn(name = "CRN_SEQP", referencedColumnName = "SEQP") })
	public MpaCadOrdItemNutricoes getCadOrdItemNutricoes() {
		return this.cadOrdItemNutricoes;
	}

	public void setCadOrdItemNutricoes(
			MpaCadOrdItemNutricoes cadOrdItemNutricoes) {
		this.cadOrdItemNutricoes = cadOrdItemNutricoes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TID_SEQ", referencedColumnName = "SEQ", nullable = false, insertable = false, updatable = false)
	public AnuTipoItemDieta getTipoItemDieta() {
		return tipoItemDieta;
	}

	public void setTipoItemDieta(AnuTipoItemDieta tipoItemDieta) {
		this.tipoItemDieta = tipoItemDieta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "IPD_PDT_ATD_SEQ", referencedColumnName = "PDT_ATD_SEQ", nullable = false),
			@JoinColumn(name = "IPD_PDT_SEQ", referencedColumnName = "PDT_SEQ", nullable = false),
			@JoinColumn(name = "IPD_TID_SEQ", referencedColumnName = "TID_SEQ", nullable = false) })
	public MpmItemPrescricaoDieta getItemPrescricaoDieta() {
		return itemPrescricaoDieta;
	}
	
	public void setItemPrescricaoDieta(
			MpmItemPrescricaoDieta itemPrescricaoDieta) {
		this.itemPrescricaoDieta = itemPrescricaoDieta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TFQ_SEQ")
	public MpmTipoFrequenciaAprazamento getTipoFrequenciaAprazamento() {
		return tipoFrequenciaAprazamento;
	}

	public void setTipoFrequenciaAprazamento(MpmTipoFrequenciaAprazamento tipoFrequenciaAprazamento) {
		this.tipoFrequenciaAprazamento = tipoFrequenciaAprazamento;
	}

	@Column(name = "FREQUENCIA", precision = 5, scale = 0)
	public Integer getFrequencia() {
		return this.frequencia;
	}

	public void setFrequencia(Integer frequencia) {
		this.frequencia = frequencia;
	}

	@Column(name = "QUANTIDADE", precision = 7)
	public BigDecimal getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(BigDecimal quantidade) {
		this.quantidade = quantidade;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "NUM_VEZES", precision = 2, scale = 0)
	public Byte getNumVezes() {
		return this.numVezes;
	}

	public void setNumVezes(Byte numVezes) {
		this.numVezes = numVezes;
	}
	
	public enum Fields {
		ID("id"),CAD_ORD_ITEM_NUTRICAO("cadOrdItemNutricoes"),TIPO_ITEM_DIETA("tipoItemDieta"),
		SERVIDOR("servidor"),ITEM_PRESCRICAO_DIETA("itemPrescricaoDieta"),TIPO_FREQ_APRAZAMENTO("tipoFrequenciaAprazamento"),
		FREQUENCIA("frequencia"),QUANTIDADE("quantidade"),CRIADO_EM("criadoEm"),NUM_VEZES("numVezes");	

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MpaUsoOrdItemNutricoes)) {
			return false;
		}
		MpaUsoOrdItemNutricoes other = (MpaUsoOrdItemNutricoes) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
