package br.gov.mec.aghu.model;

// Generated 14/09/2010 17:49:55 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;


import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MpmAprazamentoFrequenciaId generated by hbm2java
 */

@Embeddable
public class MpmAprazamentoFrequenciaId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3210037225181577101L;
	private Short tfqSeq;
	private Short seqp;

	public MpmAprazamentoFrequenciaId() {
	}

	public MpmAprazamentoFrequenciaId(Short tfqSeq, Short seqp) {
		this.tfqSeq = tfqSeq;
		this.seqp = seqp;
	}

	@Column(name = "TFQ_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getTfqSeq() {
		return this.tfqSeq;
	}

	public void setTfqSeq(Short tfqSeq) {
		this.tfqSeq = tfqSeq;
	}

	@Column(name = "SEQP", nullable = false, precision = 4, scale = 0)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof MpmAprazamentoFrequenciaId)) {
			return false;
		}
		MpmAprazamentoFrequenciaId castOther = (MpmAprazamentoFrequenciaId) other;

		return (this.getTfqSeq() == castOther.getTfqSeq())
				&& (this.getSeqp() == castOther.getSeqp());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTfqSeq();
		result = 37 * result + this.getSeqp();
		return result;
	}

}
