package br.gov.mec.aghu.model;

// Generated 14/09/2010 17:49:55 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MpmAltaRespostaConsultoriasId generated by hbm2java
 */
@Embeddable
public class MpmAltaRespostaConsultoriaId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8557755311636485853L;
	private Integer acnAsuApaAtdSeq;
	private Integer acnAsuApaSeq;
	private Short acnAsuSeqp;
	private Short acnSeqp;
	private Short seqp;

	public MpmAltaRespostaConsultoriaId() {
	}

	public MpmAltaRespostaConsultoriaId(Integer acnAsuApaAtdSeq, Integer acnAsuApaSeq,
			Short acnAsuSeqp, Short acnSeqp, Short seqp) {
		this.acnAsuApaAtdSeq = acnAsuApaAtdSeq;
		this.acnAsuApaSeq = acnAsuApaSeq;
		this.acnAsuSeqp = acnAsuSeqp;
		this.acnSeqp = acnSeqp;
		this.seqp = seqp;
	}

	@Column(name = "ACN_ASU_APA_ATD_SEQ", nullable = false, precision = 7, scale = 0)
	public Integer getAcnAsuApaAtdSeq() {
		return this.acnAsuApaAtdSeq;
	}

	public void setAcnAsuApaAtdSeq(Integer acnAsuApaAtdSeq) {
		this.acnAsuApaAtdSeq = acnAsuApaAtdSeq;
	}

	@Column(name = "ACN_ASU_APA_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getAcnAsuApaSeq() {
		return this.acnAsuApaSeq;
	}

	public void setAcnAsuApaSeq(Integer acnAsuApaSeq) {
		this.acnAsuApaSeq = acnAsuApaSeq;
	}

	@Column(name = "ACN_ASU_SEQP", nullable = false, precision = 3, scale = 0)
	public Short getAcnAsuSeqp() {
		return this.acnAsuSeqp;
	}

	public void setAcnAsuSeqp(Short acnAsuSeqp) {
		this.acnAsuSeqp = acnAsuSeqp;
	}

	@Column(name = "ACN_SEQP", nullable = false, precision = 3, scale = 0)
	public Short getAcnSeqp() {
		return this.acnSeqp;
	}

	public void setAcnSeqp(Short acnSeqp) {
		this.acnSeqp = acnSeqp;
	}

	@Column(name = "SEQP", nullable = false, precision = 4, scale = 0)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getAcnAsuApaAtdSeq());
		umHashCodeBuilder.append(this.getAcnAsuApaSeq());
		umHashCodeBuilder.append(this.getAcnAsuSeqp());
		umHashCodeBuilder.append(this.getAcnSeqp());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MpmAltaRespostaConsultoriaId)) {
			return false;
		}
		MpmAltaRespostaConsultoriaId other = (MpmAltaRespostaConsultoriaId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getAcnAsuApaAtdSeq(), other.getAcnAsuApaAtdSeq());
		umEqualsBuilder.append(this.getAcnAsuApaSeq(), other.getAcnAsuApaSeq());
		umEqualsBuilder.append(this.getAcnAsuSeqp(), other.getAcnAsuSeqp());
		umEqualsBuilder.append(this.getAcnSeqp(), other.getAcnSeqp());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
