package br.gov.mec.aghu.model;

// Generated 14/09/2010 17:49:55 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;


import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MpmComposicaoPrescricaoNptId generated by hbm2java
 */
@Embeddable
public class MpmComposicaoPrescricaoNptId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7161377167379034196L;
	private Integer pnpAtdSeq;
	private Integer pnpSeq;
	private Short seqp;

	public MpmComposicaoPrescricaoNptId() {
	}

	public MpmComposicaoPrescricaoNptId(Integer pnpAtdSeq, Integer pnpSeq, Short seqp) {
		this.pnpAtdSeq = pnpAtdSeq;
		this.pnpSeq = pnpSeq;
		this.seqp = seqp;
	}

	@Column(name = "PNP_ATD_SEQ", nullable = false, precision = 7, scale = 0)
	public Integer getPnpAtdSeq() {
		return this.pnpAtdSeq;
	}

	public void setPnpAtdSeq(Integer pnpAtdSeq) {
		this.pnpAtdSeq = pnpAtdSeq;
	}
	
	@Column(name = "PNP_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getPnpSeq() {
		return this.pnpSeq;
	}

	public void setPnpSeq(Integer pnpSeq) {
		this.pnpSeq = pnpSeq;
	}

	@Column(name = "SEQP", nullable = false, precision = 3, scale = 0)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof MpmComposicaoPrescricaoNptId)) {
			return false;
		}
		MpmComposicaoPrescricaoNptId castOther = (MpmComposicaoPrescricaoNptId) other;

		return (this.getPnpAtdSeq() != null && this.getPnpAtdSeq().equals(castOther.getPnpAtdSeq()))
				&& (this.getPnpSeq() != null && this.getPnpSeq().equals(castOther.getPnpSeq()))
				&& (this.getSeqp() != null && this.getSeqp().equals(castOther.getSeqp()));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (this.getPnpAtdSeq() == null ? 0 : this.getPnpAtdSeq().hashCode());
		result = 37 * result + (this.getPnpSeq() == null ? 0 : this.getPnpSeq().hashCode());
		result = 37 * result + (this.getSeqp() == null ? 0 : this.getSeqp().hashCode());
		
		return result;
	}

}
