package br.gov.mec.aghu.model;

// Generated 10/08/2010 18:17:45 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Parameter;

import br.gov.mec.aghu.dominio.DominioPontuacaoApacheCreatinaSerica;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheFio2Maior5;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheFio2Menor5;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheFrequenciaCardiaca;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheFrequenciaRespiratoria;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheHematocrito;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheIdade;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheLeucocitometria;
import br.gov.mec.aghu.dominio.DominioPontuacaoApachePHArterial;
import br.gov.mec.aghu.dominio.DominioPontuacaoApachePotassioPlasmatico;
import br.gov.mec.aghu.dominio.DominioPontuacaoApachePressaoArterialMedia;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheSodioPlasmatico;
import br.gov.mec.aghu.dominio.DominioPontuacaoApacheTemperatura;
import br.gov.mec.aghu.dominio.DominioSituacaoApache;
import br.gov.mec.aghu.dominio.DominioSituacaoEnvioAvisoPrescricao;
import br.gov.mec.aghu.core.exception.BaseRuntimeException;
import br.gov.mec.aghu.core.exception.BusinessExceptionCode;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MpmFichaApache generated by hbm2java
 */
@Entity
@Table(name = "MPM_FICHAS_APACHE", schema = "AGH")

public class MpmFichaApache extends BaseEntityId<MpmFichaApacheId> implements java.io.Serializable {

	// TODO Implementar coluna version quando utilizar essa entidade para
	// persistencia

	/**
	 * 
	 */
	private static final long serialVersionUID = -941179225277089574L;
	private MpmFichaApacheId id;
	private RapServidores servidor;
	private MpmEscalaGlasgow escalaGlasgow;
	private AghUnidadesFuncionais unidadeFuncional;
	private AghAtendimentos atendimento;
	private Date criadoEm;
	private DominioPontuacaoApacheTemperatura pontuacaoApacheTemperatura;
	private DominioPontuacaoApachePressaoArterialMedia pontuacaoApachePressaoArterialMedia;
	private DominioPontuacaoApacheFrequenciaCardiaca pontuacaoApacheFrequenciaCardiaca;
	private DominioPontuacaoApacheFrequenciaRespiratoria pontuacaoApacheFrequenciaRespiratoria;
	private DominioPontuacaoApachePHArterial pontuacaoApachePHArterial;
	private DominioPontuacaoApacheSodioPlasmatico pontuacaoApacheSodioPlasmatico;
	private DominioPontuacaoApachePotassioPlasmatico pontuacaoApachePotassioPlasmatico;
	private DominioPontuacaoApacheCreatinaSerica pontuacaoApacheCreatininaSerica;
	private Boolean creatinaSericaAguda;
	private DominioPontuacaoApacheHematocrito pontuacaoApacheHematocrito;
	private DominioPontuacaoApacheLeucocitometria pontuacaoApacheLeucocitometria;
	private DominioPontuacaoApacheIdade pontuacaoApacheIdade;
	private Boolean clinicoPosOperacaoUrgencia;
	private Boolean cirurgiaProgramada;
	private DominioPontuacaoApacheFio2Maior5 pontuacaoApacheO2Fio2Maior05;
	private DominioPontuacaoApacheFio2Menor5 pontuacaoApacheO2Fio2Menor05;
	private Date dthrRealizacao;
	private DominioSituacaoEnvioAvisoPrescricao envioAviso;
	private DominioSituacaoApache situacaoApache;
	private Date dthrIngressoUnidade;
	private Boolean pacienteCirurgico;
	private Boolean cirurgiaExtracorporea;
	private Boolean sindromeCoronariana;
	private Boolean choqueCardiogenico;
	private Boolean doencaFigado;
	private Boolean doencaCoracao;
	private Boolean doencaPulmao;
	private Boolean doencaRenal;
	private Boolean doencaImunologica;
	private Boolean posOperatorioUrgencia;

	
	private enum FichasApacheExceptionCode implements BusinessExceptionCode {
		MPM_FIA_CK18
	}
	
	public MpmFichaApache() {
	}

	public MpmFichaApache(MpmFichaApacheId id,
			AghUnidadesFuncionais unidadeFuncional,
			AghAtendimentos atendimento, Date criadoEm, Date dthrRealizacao,
			DominioSituacaoApache situacaoApache, Date dthrIngressoUnidade) {
		this.id = id;
		this.unidadeFuncional = unidadeFuncional;
		this.atendimento = atendimento;
		this.criadoEm = criadoEm;
		this.dthrRealizacao = dthrRealizacao;
		this.situacaoApache = situacaoApache;
		this.dthrIngressoUnidade = dthrIngressoUnidade;
	}

	@SuppressWarnings({"PMD.ExcessiveParameterList"})
	public MpmFichaApache(
			MpmFichaApacheId id,
			RapServidores servidor,
			MpmEscalaGlasgow escalaGlasgow,
			AghUnidadesFuncionais unidadeFuncional,
			AghAtendimentos atendimento,
			Date criadoEm,
			DominioPontuacaoApacheTemperatura pontuacaoApacheTemperatura,
			DominioPontuacaoApachePressaoArterialMedia pontuacaoApachePressaoArterialMedia,
			DominioPontuacaoApacheFrequenciaCardiaca pontuacaoApacheFrequenciaCardiaca,
			DominioPontuacaoApacheFrequenciaRespiratoria pontuacaoApacheFrequenciaRespiratoria,
			DominioPontuacaoApachePHArterial pontuacaoApachePHArterial,
			DominioPontuacaoApacheSodioPlasmatico pontuacaoApacheSodioPlasmatico,
			DominioPontuacaoApachePotassioPlasmatico pontuacaoApachePotassioPlasmatico,
			DominioPontuacaoApacheCreatinaSerica pontuacaoApacheCreatininaSerica,
			Boolean creatinaSericaAguda,
			DominioPontuacaoApacheHematocrito pontuacaoApacheHematocrito,
			DominioPontuacaoApacheLeucocitometria pontuacaoApacheLeucocitometria,
			DominioPontuacaoApacheIdade pontuacaoApacheIdade,
			Boolean clinicoPosOperacaoUrgencia, Boolean cirurgiaProgramada,
			DominioPontuacaoApacheFio2Maior5 pontuacaoApacheO2Fio2Maior05,
			DominioPontuacaoApacheFio2Menor5 pontuacaoApacheO2Fio2Menor05,
			Date dthrRealizacao,
			DominioSituacaoEnvioAvisoPrescricao envioAviso,
			DominioSituacaoApache situacaoApache, Date dthrIngressoUnidade,
			Boolean pacienteCirurgico, Boolean cirurgiaExtracorporea,
			Boolean sindromeCoronariana, Boolean choqueCardiogenico,
			Boolean doencaFigado, Boolean doencaCoracao, Boolean doencaPulmao,
			Boolean doencaRenal, Boolean doencaImunologica,
			Boolean posOperatorioUrgencia) {
		this.id = id;
		this.servidor = servidor;
		this.escalaGlasgow = escalaGlasgow;
		this.unidadeFuncional = unidadeFuncional;
		this.atendimento = atendimento;
		this.criadoEm = criadoEm;
		this.pontuacaoApacheTemperatura = pontuacaoApacheTemperatura;
		this.pontuacaoApachePressaoArterialMedia = pontuacaoApachePressaoArterialMedia;
		this.pontuacaoApacheFrequenciaCardiaca = pontuacaoApacheFrequenciaCardiaca;
		this.pontuacaoApacheFrequenciaRespiratoria = pontuacaoApacheFrequenciaRespiratoria;
		this.pontuacaoApachePHArterial = pontuacaoApachePHArterial;
		this.pontuacaoApacheSodioPlasmatico = pontuacaoApacheSodioPlasmatico;
		this.pontuacaoApachePotassioPlasmatico = pontuacaoApachePotassioPlasmatico;
		this.pontuacaoApacheCreatininaSerica = pontuacaoApacheCreatininaSerica;
		this.creatinaSericaAguda = creatinaSericaAguda;
		this.pontuacaoApacheHematocrito = pontuacaoApacheHematocrito;
		this.pontuacaoApacheLeucocitometria = pontuacaoApacheLeucocitometria;
		this.pontuacaoApacheIdade = pontuacaoApacheIdade;
		this.clinicoPosOperacaoUrgencia = clinicoPosOperacaoUrgencia;
		this.cirurgiaProgramada = cirurgiaProgramada;
		this.pontuacaoApacheO2Fio2Maior05 = pontuacaoApacheO2Fio2Maior05;
		this.pontuacaoApacheO2Fio2Menor05 = pontuacaoApacheO2Fio2Menor05;
		this.dthrRealizacao = dthrRealizacao;
		this.envioAviso = envioAviso;
		this.situacaoApache = situacaoApache;
		this.dthrIngressoUnidade = dthrIngressoUnidade;
		this.pacienteCirurgico = pacienteCirurgico;
		this.cirurgiaExtracorporea = cirurgiaExtracorporea;
		this.sindromeCoronariana = sindromeCoronariana;
		this.choqueCardiogenico = choqueCardiogenico;
		this.doencaFigado = doencaFigado;
		this.doencaCoracao = doencaCoracao;
		this.doencaPulmao = doencaPulmao;
		this.doencaRenal = doencaRenal;
		this.doencaImunologica = doencaImunologica;
		this.posOperatorioUrgencia = posOperatorioUrgencia;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "atdSeq", column = @Column(name = "ATD_SEQ", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 3, scale = 0)) })
	public MpmFichaApacheId getId() {
		return this.id;
	}

	public void setId(MpmFichaApacheId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EGW_SEQ")
	public MpmEscalaGlasgow getEscalaGlasgow() {
		return this.escalaGlasgow;
	}

	public void setEscalaGlasgow(MpmEscalaGlasgow escalaGlasgow) {
		this.escalaGlasgow = escalaGlasgow;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNF_SEQ", nullable = false)
	public AghUnidadesFuncionais getUnidadeFuncional() {
		return this.unidadeFuncional;
	}

	public void setUnidadeFuncional(AghUnidadesFuncionais unidadeFuncional) {
		this.unidadeFuncional = unidadeFuncional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATD_SEQ", nullable = false, insertable = false, updatable = false)
	public AghAtendimentos getAtendimento() {
		return this.atendimento;
	}

	public void setAtendimento(AghAtendimentos atendimento) {
		this.atendimento = atendimento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "PONT_TEMPERATURA", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheTemperatura") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheTemperatura getPontuacaoApacheTemperatura() {
		return this.pontuacaoApacheTemperatura;
	}

	public void setPontuacaoApacheTemperatura(
			DominioPontuacaoApacheTemperatura pontuacaoApacheTemperatura) {
		this.pontuacaoApacheTemperatura = pontuacaoApacheTemperatura;
	}

	@Column(name = "PONT_PRES_ARTERIAL_MEDIA", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApachePressaoArterialMedia") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApachePressaoArterialMedia getPontuacaoApachePressaoArterialMedia() {
		return this.pontuacaoApachePressaoArterialMedia;
	}

	public void setPontuacaoApachePressaoArterialMedia(
			DominioPontuacaoApachePressaoArterialMedia pontuacaoApachePressaoArterialMedia) {
		this.pontuacaoApachePressaoArterialMedia = pontuacaoApachePressaoArterialMedia;
	}

	@Column(name = "PONT_FREQ_CARDIACA", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheFrequenciaCardiaca") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheFrequenciaCardiaca getPontuacaoApacheFrequenciaCardiaca() {
		return this.pontuacaoApacheFrequenciaCardiaca;
	}

	public void setPontuacaoApacheFrequenciaCardiaca(
			DominioPontuacaoApacheFrequenciaCardiaca pontuacaoApacheFrequenciaCardiaca) {
		this.pontuacaoApacheFrequenciaCardiaca = pontuacaoApacheFrequenciaCardiaca;
	}

	@Column(name = "PONT_FREQ_RESPIRATORIA", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheFrequenciaRespiratoria") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheFrequenciaRespiratoria getPontuacaoApacheFrequenciaRespiratoria() {
		return this.pontuacaoApacheFrequenciaRespiratoria;
	}

	public void setPontuacaoApacheFrequenciaRespiratoria(
			DominioPontuacaoApacheFrequenciaRespiratoria pontuacaoApacheFrequenciaRespiratoria) {
		this.pontuacaoApacheFrequenciaRespiratoria = pontuacaoApacheFrequenciaRespiratoria;
	}

	@Column(name = "PONT_PH_ARTERIAL", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApachePHArterial") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApachePHArterial getPontuacaoApachePHArterial() {
		return this.pontuacaoApachePHArterial;
	}

	public void setPontuacaoApachePHArterial(
			DominioPontuacaoApachePHArterial pontuacaoApachePHArterial) {
		this.pontuacaoApachePHArterial = pontuacaoApachePHArterial;
	}

	@Column(name = "PONT_SODIO_PLASMATICO", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheSodioPlasmatico") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheSodioPlasmatico getPontuacaoApacheSodioPlasmatico() {
		return this.pontuacaoApacheSodioPlasmatico;
	}

	public void setPontuacaoApacheSodioPlasmatico(
			DominioPontuacaoApacheSodioPlasmatico pontuacaoApacheSodioPlasmatico) {
		this.pontuacaoApacheSodioPlasmatico = pontuacaoApacheSodioPlasmatico;
	}

	@Column(name = "PONT_POTASSIO_PLASMATICO", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApachePotassioPlasmatico") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApachePotassioPlasmatico getPontuacaoApachePotassioPlasmatico() {
		return this.pontuacaoApachePotassioPlasmatico;
	}

	public void setPontuacaoApachePotassioPlasmatico(
			DominioPontuacaoApachePotassioPlasmatico pontuacaoApachePotassioPlasmatico) {
		this.pontuacaoApachePotassioPlasmatico = pontuacaoApachePotassioPlasmatico;
	}

	@Column(name = "PONT_CREATININA_SERICA", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheCreatinaSerica") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheCreatinaSerica getPontuacaoApacheCreatininaSerica() {
		return this.pontuacaoApacheCreatininaSerica;
	}

	public void setPontuacaoApacheCreatininaSerica(
			DominioPontuacaoApacheCreatinaSerica pontuacaoApacheCreatininaSerica) {
		this.pontuacaoApacheCreatininaSerica = pontuacaoApacheCreatininaSerica;
	}

	@Column(name = "IND_CREAT_SERICA_AGUDA", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getCreatinaSericaAguda() {
		return this.creatinaSericaAguda;
	}

	public void setCreatinaSericaAguda(Boolean creatinaSericaAguda) {
		this.creatinaSericaAguda = creatinaSericaAguda;
	}

	@Column(name = "PONT_HEMATOCRITO", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheHematocrito") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheHematocrito getPontuacaoApacheHematocrito() {
		return this.pontuacaoApacheHematocrito;
	}

	public void setPontuacaoApacheHematocrito(
			DominioPontuacaoApacheHematocrito pontuacaoApacheHematocrito) {
		this.pontuacaoApacheHematocrito = pontuacaoApacheHematocrito;
	}

	@Column(name = "PONT_LEUCOCITOMETRIA", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheLeucocitometria") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheLeucocitometria getPontuacaoApacheLeucocitometria() {
		return this.pontuacaoApacheLeucocitometria;
	}

	public void setPontuacaoApacheLeucocitometria(
			DominioPontuacaoApacheLeucocitometria pontuacaoApacheLeucocitometria) {
		this.pontuacaoApacheLeucocitometria = pontuacaoApacheLeucocitometria;
	}

	@Column(name = "PONT_IDADE", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheIdade") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheIdade getPontuacaoApacheIdade() {
		return this.pontuacaoApacheIdade;
	}

	public void setPontuacaoApacheIdade(
			DominioPontuacaoApacheIdade pontuacaoApacheIdade) {
		this.pontuacaoApacheIdade = pontuacaoApacheIdade;
	}

	@Column(name = "IND_CLIN_POS_OPER_URG", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getClinicoPosOperacaoUrgencia() {
		return this.clinicoPosOperacaoUrgencia;
	}

	public void setClinicoPosOperacaoUrgencia(Boolean clinicoPosOperacaoUrgencia) {
		this.clinicoPosOperacaoUrgencia = clinicoPosOperacaoUrgencia;
	}

	@Column(name = "IND_CIRURG_PROGRAMADA", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getCirurgiaProgramada() {
		return this.cirurgiaProgramada;
	}

	public void setCirurgiaProgramada(Boolean cirurgiaProgramada) {
		this.cirurgiaProgramada = cirurgiaProgramada;
	}

	@Column(name = "PONT_O2_FIO2_MAIOR_05", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheFio2Maior5") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheFio2Maior5 getPontuacaoApacheO2Fio2Maior05() {
		return this.pontuacaoApacheO2Fio2Maior05;
	}

	public void setPontuacaoApacheO2Fio2Maior05(
			DominioPontuacaoApacheFio2Maior5 pontuacaoApacheO2Fio2Maior05) {
		this.pontuacaoApacheO2Fio2Maior05 = pontuacaoApacheO2Fio2Maior05;
	}

	@Column(name = "PONT_O2_FIO2_MENOR_05", precision = 1, scale = 0)
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioPontuacaoApacheFio2Menor5") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioPontuacaoApacheFio2Menor5 getPontuacaoApacheO2Fio2Menor05() {
		return this.pontuacaoApacheO2Fio2Menor05;
	}

	public void setPontuacaoApacheO2Fio2Menor05(
			DominioPontuacaoApacheFio2Menor5 pontuacaoApacheO2Fio2Menor05) {
		this.pontuacaoApacheO2Fio2Menor05 = pontuacaoApacheO2Fio2Menor05;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_REALIZACAO", nullable = false, length = 7)
	public Date getDthrRealizacao() {
		return this.dthrRealizacao;
	}

	public void setDthrRealizacao(Date dthrRealizacao) {
		this.dthrRealizacao = dthrRealizacao;
	}

	@Column(name = "SIT_ENVIO_AVISO", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacaoEnvioAvisoPrescricao getEnvioAviso() {
		return this.envioAviso;
	}

	public void setEnvioAviso(DominioSituacaoEnvioAvisoPrescricao envioAviso) {
		this.envioAviso = envioAviso;
	}

	@Column(name = "SIT_APACHE", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacaoApache getSituacaoApache() {
		return this.situacaoApache;
	}

	public void setSituacaoApache(DominioSituacaoApache situacaoApache) {
		this.situacaoApache = situacaoApache;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_INGRESSO_UNIDADE", nullable = false, length = 7)
	public Date getDthrIngressoUnidade() {
		return this.dthrIngressoUnidade;
	}

	public void setDthrIngressoUnidade(Date dthrIngressoUnidade) {
		this.dthrIngressoUnidade = dthrIngressoUnidade;
	}

	@Column(name = "IND_PAC_CIRURGICO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getPacienteCirurgico() {
		return this.pacienteCirurgico;
	}

	public void setPacienteCirurgico(Boolean pacienteCirurgico) {
		this.pacienteCirurgico = pacienteCirurgico;
	}

	@Column(name = "IND_CIRG_EXTRACORPOREA", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getCirurgiaExtracorporea() {
		return this.cirurgiaExtracorporea;
	}

	public void setCirurgiaExtracorporea(Boolean cirurgiaExtracorporea) {
		this.cirurgiaExtracorporea = cirurgiaExtracorporea;
	}

	@Column(name = "IND_SINDROME_CORONARIANA", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getSindromeCoronariana() {
		return this.sindromeCoronariana;
	}

	public void setSindromeCoronariana(Boolean sindromeCoronariana) {
		this.sindromeCoronariana = sindromeCoronariana;
	}

	@Column(name = "IND_CHOQUE_CARDIOGENICO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getChoqueCardiogenico() {
		return this.choqueCardiogenico;
	}

	public void setChoqueCardiogenico(Boolean choqueCardiogenico) {
		this.choqueCardiogenico = choqueCardiogenico;
	}

	@Column(name = "IND_DOENCA_FIGADO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getDoencaFigado() {
		return this.doencaFigado;
	}

	public void setDoencaFigado(Boolean doencaFigado) {
		this.doencaFigado = doencaFigado;
	}

	@Column(name = "IND_DOENCA_CORACAO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getDoencaCoracao() {
		return this.doencaCoracao;
	}

	public void setDoencaCoracao(Boolean doencaCoracao) {
		this.doencaCoracao = doencaCoracao;
	}

	@Column(name = "IND_DOENCA_PULMAO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getDoencaPulmao() {
		return this.doencaPulmao;
	}

	public void setDoencaPulmao(Boolean doencaPulmao) {
		this.doencaPulmao = doencaPulmao;
	}

	@Column(name = "IND_DOENCA_RENAL", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getDoencaRenal() {
		return this.doencaRenal;
	}

	public void setDoencaRenal(Boolean doencaRenal) {
		this.doencaRenal = doencaRenal;
	}

	@Column(name = "IND_DOENCA_IMUNOLOGICA", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getDoencaImunologica() {
		return this.doencaImunologica;
	}

	public void setDoencaImunologica(Boolean doencaImunologica) {
		this.doencaImunologica = doencaImunologica;
	}

	@Column(name = "IND_POS_OPER_URG", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getPosOperatorioUrgencia() {
		return this.posOperatorioUrgencia;
	}

	public void setPosOperatorioUrgencia(Boolean posOperatorioUrgencia) {
		this.posOperatorioUrgencia = posOperatorioUrgencia;
	}

	public enum Fields {
		ID("id"),
		SEQP("id.seqp"),
		SERVIDOR("servidor"),
		ESCALA_GLASGOW("escalaGlasgow"),
		UNIDADE_FUNCIONAL("unidadeFuncional"),
		ATD_SEQ("atendimento.seq"),
		ATENDIMENTO("atendimento"),
		CRIADO_EM("criadoEm"),
		PONTUACAO_APACHE_TEMPERATURA("pontuacaoApacheTemperatura"),
		PONTUACAO_APACHE_PRESSAO_ARTERIAL_MEDIA("pontuacaoApachePressaoArterialMedia"),
		PONTUACAO_APACHE_FREQUENCIA_CARDIACA("pontuacaoApacheFrequenciaCardiaca"),
		PONTUACAO_APACHE_FREQUENCIA_RESPIRATORIA("pontuacaoApacheFrequenciaRespiratoria"),
		PONTUACAO_APACHE_PH_ARTERIAL("pontuacaoApachePHArterial"),
		PONTUACAO_APACHE_SODIO_PLASMATICO("pontuacaoApacheSodioPlasmatico"),
		PONTUACAO_APACHE_POTASSIO_PLASMATICO("pontuacaoApachePotassioPlasmatico"),
		PONTUACAO_APACHE_CREATININA_SERICA("pontuacaoApacheCreatininaSerica"),
		CREATINA_SERICA_AGUDA("creatinaSericaAguda"),
		PONTUACAO_APACHE_HEMATOCRITO("pontuacaoApacheHematocrito"),
		PONTUACAO_APACHE_LEUCOCITOMETRIA("pontuacaoApacheLeucocitometria"),
		PONTUACAO_APACHE_IDADE("pontuacaoApacheIdade"),
		CLINICO_POS_OPERACAO_URGENCIA("clinicoPosOperacaoUrgencia"),
		CIRURGIA_PROGRAMADA("cirurgiaProgramada"),
		PONTUACAO_APACHE_O2_FIO_2_MAIOR_05("pontuacaoApacheO2Fio2Maior05"),
		PONTUACAO_APACHE_O2_FIO_2_MENOR_05("pontuacaoApacheO2Fio2Menor05"),
		DTHR_REALIZACAO("dthrRealizacao"),
		ENVIO_AVISO("envioAviso"),
		SITUACAO_APACHE("situacaoApache"),
		DTHR_INGRESSO_UNIDADE("dthrIngressoUnidade"),
		PACIENTE_CIRURGICO("pacienteCirurgico"),
		CIRURGIA_EXTRA_CORPOREA("cirurgiaExtracorporea"),
		SINDROME_CORONARIANA("sindromeCoronariana"),
		CHOQUE_CARDIOGENICO("choqueCardiogenico"),
		DOENCA_FIGADO("doencaFigado"),
		DOENCA_CORACAO("doencaCoracao"),
		DOENCA_PULMAO("doencaPulmao"),
		DOENCA_RENAL("doencaRenal"),
		DOENCA_IMUNOLOGICA("doencaImunologica"),
		POS_OPERATORIO_URGENCIA("posOperatorioUrgencia");

		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		MpmFichaApache other = (MpmFichaApache) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

	@PrePersist
	@PreUpdate
	@SuppressWarnings("unused")
	private void validarDados(){
		if(!((this.clinicoPosOperacaoUrgencia == null && this.cirurgiaProgramada == null)
			||(this.clinicoPosOperacaoUrgencia == false && this.cirurgiaProgramada == false)
			||(this.clinicoPosOperacaoUrgencia == true && this.cirurgiaProgramada == false)
			||(this.clinicoPosOperacaoUrgencia == false && this.cirurgiaProgramada == true)
		)){
			throw new BaseRuntimeException(FichasApacheExceptionCode.MPM_FIA_CK18);
		}
		
	}
}
