package br.gov.mec.aghu.model;

// Generated 14/09/2010 17:49:55 by Hibernate Tools 3.2.5.Beta

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MpmItemProcedimentoSumarios generated by hbm2java
 */
@Entity
@Table(name = "MPM_ITEM_PROCEDIMENTO_SUMARIOS", schema = "AGH")
public class MpmItemProcedimentoSumario extends BaseEntityId<MpmItemProcedimentoSumarioId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 512781943684018217L;
	private MpmItemProcedimentoSumarioId id;
	private MpmTipoModoUsoProcedimento mpmTipoModUsoProcedimentos;
	private MpmProcedEspecialDiversos mpmProcedEspecialDiversos;
	private MpmItemPrescricaoSumario mpmItemPrescricaoSumarios;
	private ScoMaterial material;
	private MbcProcedimentoCirurgicos procedimentoCirurgico;
	private Short quantidade;
	private Short quantidadeModoUso;
	private String infComplementares;

	public MpmItemProcedimentoSumario() {
	}

	public MpmItemProcedimentoSumario(MpmItemProcedimentoSumarioId id,
			MpmItemPrescricaoSumario mpmItemPrescricaoSumarios) {
		this.id = id;
		this.mpmItemPrescricaoSumarios = mpmItemPrescricaoSumarios;
	}

	public MpmItemProcedimentoSumario(MpmItemProcedimentoSumarioId id,
			MpmTipoModoUsoProcedimento mpmTipoModUsoProcedimentos,
			MpmProcedEspecialDiversos mpmProcedEspecialDiversos,
			MpmItemPrescricaoSumario mpmItemPrescricaoSumarios,
			ScoMaterial material, MbcProcedimentoCirurgicos procedimentoCirurgico, Short quantidade,
			Short quantidadeModoUso, String infComplementares) {
		this.id = id;
		this.mpmTipoModUsoProcedimentos = mpmTipoModUsoProcedimentos;
		this.mpmProcedEspecialDiversos = mpmProcedEspecialDiversos;
		this.mpmItemPrescricaoSumarios = mpmItemPrescricaoSumarios;
		this.material = material;
		this.procedimentoCirurgico = procedimentoCirurgico;
		this.quantidade = quantidade;
		this.quantidadeModoUso = quantidadeModoUso;
		this.infComplementares = infComplementares;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "ituSeq", column = @Column(name = "ITU_SEQ", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 5, scale = 0)) })
	public MpmItemProcedimentoSumarioId getId() {
		return this.id;
	}

	public void setId(MpmItemProcedimentoSumarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "TUP_PED_SEQ", referencedColumnName = "PED_SEQ"),
			@JoinColumn(name = "TUP_SEQP", referencedColumnName = "SEQP") })
	public MpmTipoModoUsoProcedimento getMpmTipoModUsoProcedimentos() {
		return this.mpmTipoModUsoProcedimentos;
	}

	public void setMpmTipoModUsoProcedimentos(
			MpmTipoModoUsoProcedimento mpmTipoModUsoProcedimentos) {
		this.mpmTipoModUsoProcedimentos = mpmTipoModUsoProcedimentos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PED_SEQ")
	public MpmProcedEspecialDiversos getMpmProcedEspecialDiversos() {
		return this.mpmProcedEspecialDiversos;
	}

	public void setMpmProcedEspecialDiversos(
			MpmProcedEspecialDiversos mpmProcedEspecialDiversos) {
		this.mpmProcedEspecialDiversos = mpmProcedEspecialDiversos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITU_SEQ", nullable = false, insertable = false, updatable = false)
	public MpmItemPrescricaoSumario getMpmItemPrescricaoSumarios() {
		return this.mpmItemPrescricaoSumarios;
	}

	public void setMpmItemPrescricaoSumarios(
			MpmItemPrescricaoSumario mpmItemPrescricaoSumarios) {
		this.mpmItemPrescricaoSumarios = mpmItemPrescricaoSumarios;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAT_CODIGO")
	public ScoMaterial getMaterial() {
		return this.material;
	}

	public void setMaterial(ScoMaterial material) {
		this.material = material;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="PCI_SEQ")
	public MbcProcedimentoCirurgicos getProcedimentoCirurgico() {
		return this.procedimentoCirurgico;
	}


	public void setProcedimentoCirurgico(MbcProcedimentoCirurgicos procedimentoCirurgico) {
		this.procedimentoCirurgico = procedimentoCirurgico;
	}
	
	
	@Column(name = "QUANTIDADE", precision = 4, scale = 0)
	public Short getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Short quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "QUANTIDADE_MODO_USO", precision = 3, scale = 0)
	public Short getQuantidadeModoUso() {
		return this.quantidadeModoUso;
	}

	public void setQuantidadeModoUso(Short quantidadeModoUso) {
		this.quantidadeModoUso = quantidadeModoUso;
	}

	@Column(name = "INF_COMPLEMENTARES", length = 240)
	@Length(max = 240)
	public String getInfComplementares() {
		return this.infComplementares;
	}

	public void setInfComplementares(String infComplementares) {
		this.infComplementares = infComplementares;
	}

	public enum Fields {

		ID("id"),
		MPM_TIPO_MOD_USO_PROCEDIMENTOS("mpmTipoModUsoProcedimentos"),
		MPM_PROCED_ESPECIAL_DIVERSOS("mpmProcedEspecialDiversos"),
		MPM_ITEM_PRESCRICAO_SUMARIOS("mpmItemPrescricaoSumarios"),
		MATERIAL("material"),
		PROCEDIMENTO_CIRURGICO("procedimentoCirurgico"),
		QUANTIDADE("quantidade"),
		QUANTIDADE_MODO_USO("quantidadeModoUso"),
		INF_COMPLEMENTARES("infComplementares");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MpmItemProcedimentoSumario)) {
			return false;
		}
		MpmItemProcedimentoSumario other = (MpmItemProcedimentoSumario) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
