package br.gov.mec.aghu.model;

// Generated 14/05/2010 11:16:01 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * MpmSumarioAlta generated by hbm2java
 */
@Entity
@Table(name = "MPM_SUMARIO_ALTAS", schema = "AGH")

public class MpmSumarioAlta extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5128970978917547395L;
	private Integer atdSeq;
	private AghAtendimentos aghAtendimento;
	private RapServidores servidor;
	private Short plaSeq;
	private MpmMotivoAltaMedica motivoAltaMedica;
	private Date criadoEm;
	private Date alteradoEm;
	private Date dthrAlta;
	private String indNecropsia;
	private String outrosProcedTerapeuticos;
	private String outrosFarmacosPrincipais;
	private String complPlanoPosAlta;
	private String complMotivoAlta;
	private String complAltaHospitalar;
	private String estadoPacienteAlta;
	private RapServidores servidorValido;
	private Date dthrSumarioPosAlta;
	private RapServidores servidorPosAlta;
	private Date dthrElaboracaoAlta;

	public MpmSumarioAlta() {
	}

	public MpmSumarioAlta(Integer atdSeq, RapServidores servidor,
			Date criadoEm, Date alteradoEm) {
		this.atdSeq = atdSeq;
		this.servidor = servidor;
		this.criadoEm = criadoEm;
		this.alteradoEm = alteradoEm;
	}

	public MpmSumarioAlta(Integer atdSeq, RapServidores servidor,
			Short plaSeq, MpmMotivoAltaMedica motivoAltaMedica, Date criadoEm, Date alteradoEm,
			Date dthrAlta, String indNecropsia,
			String outrosProcedTerapeuticos, String outrosFarmacosPrincipais,
			String complPlanoPosAlta, String complMotivoAlta,
			String complAltaHospitalar, String estadoPacienteAlta,
			RapServidores servidorValido,
			Date dthrSumarioPosAlta, RapServidores servidorPosAlta, Date dthrElaboracaoAlta) {
		this.atdSeq = atdSeq;
		this.servidor = servidor;
		this.plaSeq = plaSeq;
		this.motivoAltaMedica = motivoAltaMedica;
		this.criadoEm = criadoEm;
		this.alteradoEm = alteradoEm;
		this.dthrAlta = dthrAlta;
		this.indNecropsia = indNecropsia;
		this.outrosProcedTerapeuticos = outrosProcedTerapeuticos;
		this.outrosFarmacosPrincipais = outrosFarmacosPrincipais;
		this.complPlanoPosAlta = complPlanoPosAlta;
		this.complMotivoAlta = complMotivoAlta;
		this.complAltaHospitalar = complAltaHospitalar;
		this.estadoPacienteAlta = estadoPacienteAlta;
		this.servidorValido = servidorValido;
		this.dthrSumarioPosAlta = dthrSumarioPosAlta;
		this.servidorPosAlta = servidorPosAlta;
		this.dthrElaboracaoAlta = dthrElaboracaoAlta;
	}

	@Id
	@Column(name = "ATD_SEQ", nullable = false, precision = 7, scale = 0)
	public Integer getAtdSeq() {
		return this.atdSeq;
	}

	public void setAtdSeq(Integer atdSeq) {
		this.atdSeq = atdSeq;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATD_SEQ", nullable = false, insertable = false, updatable = false)
	public AghAtendimentos getAghAtendimento() {
		return this.aghAtendimento;
	}
	
	public void setAghAtendimento(AghAtendimentos aghAtendimento) {
		this.aghAtendimento = aghAtendimento;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidor() {
		return this.servidor;
	}

	public void setServidor(RapServidores servidor) {
		this.servidor = servidor;
	}
	
	
	@Column(name = "PLA_SEQ", precision = 4, scale = 0)
	public Short getPlaSeq() {
		return this.plaSeq;
	}

	public void setPlaSeq(Short plaSeq) {
		this.plaSeq = plaSeq;
	}

	
	@ManyToOne(fetch = FetchType.LAZY )
	@JoinColumn(name = "MAM_SEQ")
	public MpmMotivoAltaMedica getMotivoAltaMedica() {
		return this.motivoAltaMedica;
	}
	public void setMotivoAltaMedica(MpmMotivoAltaMedica motivoAltaMedica) {
		this.motivoAltaMedica = motivoAltaMedica;
	}
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 7)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", nullable = false, length = 7)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_ALTA", length = 7)
	public Date getDthrAlta() {
		return this.dthrAlta;
	}

	public void setDthrAlta(Date dthrAlta) {
		this.dthrAlta = dthrAlta;
	}

	@Column(name = "IND_NECROPSIA", length = 1)
	@Length(max = 1)
	public String getIndNecropsia() {
		return this.indNecropsia;
	}

	public void setIndNecropsia(String indNecropsia) {
		this.indNecropsia = indNecropsia;
	}

	@Column(name = "OUTROS_PROCED_TERAPEUTICOS", length = 240)
	@Length(max = 240)
	public String getOutrosProcedTerapeuticos() {
		return this.outrosProcedTerapeuticos;
	}

	public void setOutrosProcedTerapeuticos(String outrosProcedTerapeuticos) {
		this.outrosProcedTerapeuticos = outrosProcedTerapeuticos;
	}

	@Column(name = "OUTROS_FARMACOS_PRINCIPAIS", length = 120)
	@Length(max = 120)
	public String getOutrosFarmacosPrincipais() {
		return this.outrosFarmacosPrincipais;
	}

	public void setOutrosFarmacosPrincipais(String outrosFarmacosPrincipais) {
		this.outrosFarmacosPrincipais = outrosFarmacosPrincipais;
	}

	@Column(name = "COMPL_PLANO_POS_ALTA", length = 120)
	@Length(max = 120)
	public String getComplPlanoPosAlta() {
		return this.complPlanoPosAlta;
	}

	public void setComplPlanoPosAlta(String complPlanoPosAlta) {
		this.complPlanoPosAlta = complPlanoPosAlta;
	}

	@Column(name = "COMPL_MOTIVO_ALTA", length = 120)
	@Length(max = 120)
	public String getComplMotivoAlta() {
		return this.complMotivoAlta;
	}

	public void setComplMotivoAlta(String complMotivoAlta) {
		this.complMotivoAlta = complMotivoAlta;
	}

	@Column(name = "COMPL_ALTA_HOSPITALAR", length = 240)
	@Length(max = 240)
	public String getComplAltaHospitalar() {
		return this.complAltaHospitalar;
	}

	public void setComplAltaHospitalar(String complAltaHospitalar) {
		this.complAltaHospitalar = complAltaHospitalar;
	}

	@Column(name = "ESTADO_PACIENTE_ALTA", length = 1)
	@Length(max = 1)
	public String getEstadoPacienteAlta() {
		return this.estadoPacienteAlta;
	}

	public void setEstadoPacienteAlta(String estadoPacienteAlta) {
		this.estadoPacienteAlta = estadoPacienteAlta;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_VALIDA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO_VALIDA", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidorValido() {
		return this.servidorValido;
	}

	public void setServidorValido(RapServidores servidorValido) {
		this.servidorValido = servidorValido;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_SUMARIO_POS_ALTA", length = 7)
	public Date getDthrSumarioPosAlta() {
		return this.dthrSumarioPosAlta;
	}

	public void setDthrSumarioPosAlta(Date dthrSumarioPosAlta) {
		this.dthrSumarioPosAlta = dthrSumarioPosAlta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "SER_MATRICULA_POS_ALTA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO_POS_ALTA", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getServidorPosAlta() {
		return this.servidorPosAlta;
	}

	public void setServidorPosAlta(RapServidores servidorPosAlta) {
		this.servidorPosAlta = servidorPosAlta;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_ELABORACAO_ALTA", length = 7)
	public Date getDthrElaboracaoAlta() {
		return this.dthrElaboracaoAlta;
	}

	public void setDthrElaboracaoAlta(Date dthrElaboracaoAlta) {
		this.dthrElaboracaoAlta = dthrElaboracaoAlta;
	}

	
	public enum Fields {
		
		SEQ("atdSeq"), 
		PLA_SEQ("plaSeq"),
		ATENDIMENTO("aghAtendimento"),
		DATA_ALTA("dthrAlta"),
		DATA_ELB_ALTA("dthrElaboracaoAlta"),
		IND_NECROPSIA("indNecropsia"),
		MOTIVO_ALTA_MEDICA("motivoAltaMedica"),
		MOTIVO_ALTA_MEDICA_SEQ("motivoAltaMedica.seq"),
		MATRICULA_SERVIDOR_VLD("servidorValido.id.matricula"),
		CODIGO_SERVIDOR_VLD("servidorValido.id.vinCodigo"),
		MAM_SEQ("motivoAltaMedica"),
		COMPL_PLN_POS_ALTA("complPlanoPosAlta"),
		ESTD_PAC_ALTA("estadoPacienteAlta"),
		COMPL_MTV_ALTA("complMotivoAlta");


		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getAtdSeq() == null) ? 0 : getAtdSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MpmSumarioAlta)) {
			return false;
		}
		MpmSumarioAlta other = (MpmSumarioAlta) obj;
		if (getAtdSeq() == null) {
			if (other.getAtdSeq() != null) {
				return false;
			}
		} else if (!getAtdSeq().equals(other.getAtdSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####
 
 @Transient public Integer getSeq(){ return this.getAtdSeq();} 
 public void setSeq(Integer seq){ this.setAtdSeq(seq);}
}
