package br.gov.mec.aghu.model;

// Generated 14/09/2010 17:49:55 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MpmServRecomendacaoAltaId generated by hbm2java
 */

@Embeddable
public class MpmServRecomendacaoAltaId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4180250050160653501L;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Integer seqp;

	public MpmServRecomendacaoAltaId() {
	}

	public MpmServRecomendacaoAltaId(Integer serMatricula, Short serVinCodigo, Integer seqp) {
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.seqp = seqp;
	}

	@Column(name = "SEQP", nullable = false, precision = 5, scale = 0)
	public Integer getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Integer seqp) {
		this.seqp = seqp;
	}
	
	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}
	
	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSerMatricula());
		umHashCodeBuilder.append(this.getSerVinCodigo());
		umHashCodeBuilder.append(this.getSeqp());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AacConsCargaBullId)) {
			return false;
		}
		MpmServRecomendacaoAltaId other = (MpmServRecomendacaoAltaId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSerMatricula(), other.getSerMatricula());
		umEqualsBuilder.append(this.getSerVinCodigo(), other.getSerVinCodigo());
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		return umEqualsBuilder.isEquals();
	}

	@Override
	public String toString() {
		return new ToStringBuilder(this).append("vinCodigo",
				this.getSerVinCodigo()).append("matricula", this.getSerMatricula()).append("Seqp", this.getSeqp())
				.toString();		
	}

}
