package br.gov.mec.aghu.model;

// Generated 27/12/2010 20:08:36 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MptAgendaPrescricoesId generated by hbm2java
 */
@Embeddable

public class MptAgendaPrescricaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6277731883178826906L;
	private Integer pteAtdSeq;
	private Integer pteSeq;
	private Short seqp;

	public MptAgendaPrescricaoId() {
	}

	public MptAgendaPrescricaoId(Integer pteAtdSeq, Integer pteSeq, Short seqp) {
		this.pteAtdSeq = pteAtdSeq;
		this.pteSeq = pteSeq;
		this.seqp = seqp;
	}

	@Column(name = "PTE_ATD_SEQ", nullable = false, precision = 7, scale = 0)
	public Integer getPteAtdSeq() {
		return this.pteAtdSeq;
	}

	public void setPteAtdSeq(Integer pteAtdSeq) {
		this.pteAtdSeq = pteAtdSeq;
	}

	@Column(name = "PTE_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getPteSeq() {
		return this.pteSeq;
	}

	public void setPteSeq(Integer pteSeq) {
		this.pteSeq = pteSeq;
	}

	@Column(name = "SEQP", nullable = false, precision = 4, scale = 0)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof MptAgendaPrescricaoId)) {
			return false;
		}
		MptAgendaPrescricaoId castOther = (MptAgendaPrescricaoId) other;

		return (this.getPteAtdSeq() == castOther.getPteAtdSeq())
				&& (this.getPteSeq() == castOther.getPteSeq())
				&& (this.getSeqp() == castOther.getSeqp());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPteAtdSeq();
		result = 37 * result + this.getPteSeq();
		result = 37 * result + this.getSeqp();
		return result;
	}

}
