package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MptControleFreqSessaoId generated by hbm2java
 */
@Embeddable
public class MptControleFreqSessaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1496137854336800795L;
	private Integer ageSeq;
	private Date data;

	public MptControleFreqSessaoId() {
	}

	public MptControleFreqSessaoId(Integer ageSeq, Date data) {
		this.ageSeq = ageSeq;
		this.data = data;
	}

	@Column(name = "AGE_SEQ", nullable = false)
	public Integer getAgeSeq() {
		return this.ageSeq;
	}

	public void setAgeSeq(Integer ageSeq) {
		this.ageSeq = ageSeq;
	}

	@Column(name = "DATA", nullable = false, length = 29)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getData());
		umHashCodeBuilder.append(this.getAgeSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MptControleFreqSessaoId)) {
			return false;
		}
		MptControleFreqSessaoId other = (MptControleFreqSessaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getData(), other.getData());
		umEqualsBuilder.append(this.getAgeSeq(), other.getAgeSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
