package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MptMotivoJustifPrescricaoId generated by hbm2java
 */
@Embeddable
public class MptMotivoJustifPrescricaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2665867015233749647L;
	private Integer jupAtdSeq;
	private Integer jupSeq;
	private Short seqp;

	public MptMotivoJustifPrescricaoId() {
	}

	public MptMotivoJustifPrescricaoId(Integer jupAtdSeq, Integer jupSeq, Short seqp) {
		this.jupAtdSeq = jupAtdSeq;
		this.jupSeq = jupSeq;
		this.seqp = seqp;
	}

	@Column(name = "JUP_ATD_SEQ", nullable = false)
	public Integer getJupAtdSeq() {
		return this.jupAtdSeq;
	}

	public void setJupAtdSeq(Integer jupAtdSeq) {
		this.jupAtdSeq = jupAtdSeq;
	}

	@Column(name = "JUP_SEQ", nullable = false)
	public Integer getJupSeq() {
		return this.jupSeq;
	}

	public void setJupSeq(Integer jupSeq) {
		this.jupSeq = jupSeq;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getJupAtdSeq());
		umHashCodeBuilder.append(this.getJupSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MptMotivoJustifPrescricaoId)) {
			return false;
		}
		MptMotivoJustifPrescricaoId other = (MptMotivoJustifPrescricaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getJupAtdSeq(), other.getJupAtdSeq());
		umEqualsBuilder.append(this.getJupSeq(), other.getJupSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
