package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * MptTratamentoTerapeuticoJn generated by hbm2java
 */
@Entity
@Table(name = "MPT_TRATAMENTO_TERAPEUTICOS_JN", schema = "AGH")
@Immutable
public class MptTratamentoTerapeuticoJn extends BaseJournal {

/**
	 * 
	 */
	private static final long serialVersionUID = 7890370629125180422L;
	/* ATUALIZADOR JOURNALS - PROPERTIES	private Long seqJn;
	private String jnUser;
	private Date jnDateTime;
	private String jnOperation;*/
	private Integer seq;
	private Date dthrInicio;
	private Date dthrFim;
	private String observacao;
	private Date criadoEm;
	private Integer atdSeq;
	private Short unfSeq;
	private Integer pacCodigo;
	private Short espSeq;
	private Integer tptSeq;
	private Short cspCnvCodigo;
	private Short cspSeq;
	private Integer serMatriculaResponsavel;
	private Short serVinCodigoResponsavel;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Date dtInicioAgendaSessao;
	private Short nroDiasAgendaSessao;
	private Integer serMatriculaAutorizado;
	private Short serVinCodigoAutorizado;

	public MptTratamentoTerapeuticoJn() {
	}

	public MptTratamentoTerapeuticoJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer seq) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.seq = seq;
	}

	public MptTratamentoTerapeuticoJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer seq, Date dthrInicio,
			Date dthrFim, String observacao, Date criadoEm, Integer atdSeq, Short unfSeq, Integer pacCodigo, Short espSeq,
			Integer tptSeq, Short cspCnvCodigo, Short cspSeq, Integer serMatriculaResponsavel, Short serVinCodigoResponsavel,
			Integer serMatricula, Short serVinCodigo, Date dtInicioAgendaSessao, Short nroDiasAgendaSessao,
			Integer serMatriculaAutorizado, Short serVinCodigoAutorizado) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.seq = seq;
		this.dthrInicio = dthrInicio;
		this.dthrFim = dthrFim;
		this.observacao = observacao;
		this.criadoEm = criadoEm;
		this.atdSeq = atdSeq;
		this.unfSeq = unfSeq;
		this.pacCodigo = pacCodigo;
		this.espSeq = espSeq;
		this.tptSeq = tptSeq;
		this.cspCnvCodigo = cspCnvCodigo;
		this.cspSeq = cspSeq;
		this.serMatriculaResponsavel = serMatriculaResponsavel;
		this.serVinCodigoResponsavel = serVinCodigoResponsavel;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.dtInicioAgendaSessao = dtInicioAgendaSessao;
		this.nroDiasAgendaSessao = nroDiasAgendaSessao;
		this.serMatriculaAutorizado = serMatriculaAutorizado;
		this.serVinCodigoAutorizado = serVinCodigoAutorizado;
	}

	// ATUALIZADOR JOURNALS - ID
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	//@GeneratedValue(strategy = GenerationType.AUTO, generator = "")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	// ATUALIZADOR JOURNALS - ID
	
/* ATUALIZADOR JOURNALS - Get / Set	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	public Long getSeqJn() {
		return this.seqJn;
	}

	public void setSeqJn(Long seqJn) {
		this.seqJn = seqJn;
	}

	@Column(name = "JN_USER", nullable = false, length = 30)
	@Length(max = 30)
	public String getJnUser() {
		return this.jnUser;
	}

	public void setJnUser(String jnUser) {
		this.jnUser = jnUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JN_DATE_TIME", nullable = false, length = 29)
	public Date getJnDateTime() {
		return this.jnDateTime;
	}

	public void setJnDateTime(Date jnDateTime) {
		this.jnDateTime = jnDateTime;
	}

	@Column(name = "JN_OPERATION", nullable = false, length = 3)
	@Length(max = 3)
	public String getJnOperation() {
		return this.jnOperation;
	}

	public void setJnOperation(String jnOperation) {
		this.jnOperation = jnOperation;
	}*/

	@Column(name = "SEQ", nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_INICIO", length = 29)
	public Date getDthrInicio() {
		return this.dthrInicio;
	}

	public void setDthrInicio(Date dthrInicio) {
		this.dthrInicio = dthrInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FIM", length = 29)
	public Date getDthrFim() {
		return this.dthrFim;
	}

	public void setDthrFim(Date dthrFim) {
		this.dthrFim = dthrFim;
	}

	@Column(name = "OBSERVACAO", length = 2000)
	@Length(max = 2000)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "ATD_SEQ")
	public Integer getAtdSeq() {
		return this.atdSeq;
	}

	public void setAtdSeq(Integer atdSeq) {
		this.atdSeq = atdSeq;
	}

	@Column(name = "UNF_SEQ")
	public Short getUnfSeq() {
		return this.unfSeq;
	}

	public void setUnfSeq(Short unfSeq) {
		this.unfSeq = unfSeq;
	}

	@Column(name = "PAC_CODIGO")
	public Integer getPacCodigo() {
		return this.pacCodigo;
	}

	public void setPacCodigo(Integer pacCodigo) {
		this.pacCodigo = pacCodigo;
	}

	@Column(name = "ESP_SEQ")
	public Short getEspSeq() {
		return this.espSeq;
	}

	public void setEspSeq(Short espSeq) {
		this.espSeq = espSeq;
	}

	@Column(name = "TPT_SEQ")
	public Integer getTptSeq() {
		return this.tptSeq;
	}

	public void setTptSeq(Integer tptSeq) {
		this.tptSeq = tptSeq;
	}

	@Column(name = "CSP_CNV_CODIGO")
	public Short getCspCnvCodigo() {
		return this.cspCnvCodigo;
	}

	public void setCspCnvCodigo(Short cspCnvCodigo) {
		this.cspCnvCodigo = cspCnvCodigo;
	}

	@Column(name = "CSP_SEQ")
	public Short getCspSeq() {
		return this.cspSeq;
	}

	public void setCspSeq(Short cspSeq) {
		this.cspSeq = cspSeq;
	}

	@Column(name = "SER_MATRICULA_RESPONSAVEL")
	public Integer getSerMatriculaResponsavel() {
		return this.serMatriculaResponsavel;
	}

	public void setSerMatriculaResponsavel(Integer serMatriculaResponsavel) {
		this.serMatriculaResponsavel = serMatriculaResponsavel;
	}

	@Column(name = "SER_VIN_CODIGO_RESPONSAVEL")
	public Short getSerVinCodigoResponsavel() {
		return this.serVinCodigoResponsavel;
	}

	public void setSerVinCodigoResponsavel(Short serVinCodigoResponsavel) {
		this.serVinCodigoResponsavel = serVinCodigoResponsavel;
	}

	@Column(name = "SER_MATRICULA")
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO")
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO_AGENDA_SESSAO", length = 29)
	public Date getDtInicioAgendaSessao() {
		return this.dtInicioAgendaSessao;
	}

	public void setDtInicioAgendaSessao(Date dtInicioAgendaSessao) {
		this.dtInicioAgendaSessao = dtInicioAgendaSessao;
	}

	@Column(name = "NRO_DIAS_AGENDA_SESSAO")
	public Short getNroDiasAgendaSessao() {
		return this.nroDiasAgendaSessao;
	}

	public void setNroDiasAgendaSessao(Short nroDiasAgendaSessao) {
		this.nroDiasAgendaSessao = nroDiasAgendaSessao;
	}

	@Column(name = "SER_MATRICULA_AUTORIZADO")
	public Integer getSerMatriculaAutorizado() {
		return this.serMatriculaAutorizado;
	}

	public void setSerMatriculaAutorizado(Integer serMatriculaAutorizado) {
		this.serMatriculaAutorizado = serMatriculaAutorizado;
	}

	@Column(name = "SER_VIN_CODIGO_AUTORIZADO")
	public Short getSerVinCodigoAutorizado() {
		return this.serVinCodigoAutorizado;
	}

	public void setSerVinCodigoAutorizado(Short serVinCodigoAutorizado) {
		this.serVinCodigoAutorizado = serVinCodigoAutorizado;
	}

	public enum Fields {

	/* ATUALIZADOR JOURNALS - Fields	SEQ_JN("seqJn"),
		JN_USER("jnUser"),
		JN_DATE_TIME("jnDateTime"),
		JN_OPERATION("jnOperation"),*/
		SEQ("seq"),
		DTHR_INICIO("dthrInicio"),
		DTHR_FIM("dthrFim"),
		OBSERVACAO("observacao"),
		CRIADO_EM("criadoEm"),
		ATD_SEQ("atdSeq"),
		UNF_SEQ("unfSeq"),
		PAC_CODIGO("pacCodigo"),
		ESP_SEQ("espSeq"),
		TPT_SEQ("tptSeq"),
		CSP_CNV_CODIGO("cspCnvCodigo"),
		CSP_SEQ("cspSeq"),
		SER_MATRICULA_RESPONSAVEL("serMatriculaResponsavel"),
		SER_VIN_CODIGO_RESPONSAVEL("serVinCodigoResponsavel"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		DT_INICIO_AGENDA_SESSAO("dtInicioAgendaSessao"),
		NRO_DIAS_AGENDA_SESSAO("nroDiasAgendaSessao"),
		SER_MATRICULA_AUTORIZADO("serMatriculaAutorizado"),
		SER_VIN_CODIGO_AUTORIZADO("serVinCodigoAutorizado");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
