package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MvaipEnderPacCompletoId generated by hbm2java
 */
@Embeddable
public class MvaipEnderPacCompletoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5907048362876659044L;
	private Integer pacCodigo;
	private String logradouro;
	private Integer nroLogradouro;
	private String complLogradouro;
	private String bairro;
	private String cidade;
	private Double cep;
	private String uf;
	private Double codIbge;
	private Integer cddCodigo;
	private Double tipCodigo;

	public MvaipEnderPacCompletoId() {
	}

	public MvaipEnderPacCompletoId(Integer pacCodigo, String logradouro, Integer nroLogradouro, String complLogradouro, String bairro,
			String cidade, Double cep, String uf, Double codIbge, Integer cddCodigo, Double tipCodigo) {
		this.pacCodigo = pacCodigo;
		this.logradouro = logradouro;
		this.nroLogradouro = nroLogradouro;
		this.complLogradouro = complLogradouro;
		this.bairro = bairro;
		this.cidade = cidade;
		this.cep = cep;
		this.uf = uf;
		this.codIbge = codIbge;
		this.cddCodigo = cddCodigo;
		this.tipCodigo = tipCodigo;
	}

	@Column(name = "PAC_CODIGO")
	public Integer getPacCodigo() {
		return this.pacCodigo;
	}

	public void setPacCodigo(Integer pacCodigo) {
		this.pacCodigo = pacCodigo;
	}

	@Column(name = "LOGRADOURO", length = 132)
	@Length(max = 132)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "NRO_LOGRADOURO")
	public Integer getNroLogradouro() {
		return this.nroLogradouro;
	}

	public void setNroLogradouro(Integer nroLogradouro) {
		this.nroLogradouro = nroLogradouro;
	}

	@Column(name = "COMPL_LOGRADOURO", length = 20)
	@Length(max = 20)
	public String getComplLogradouro() {
		return this.complLogradouro;
	}

	public void setComplLogradouro(String complLogradouro) {
		this.complLogradouro = complLogradouro;
	}

	@Column(name = "BAIRRO", length = 60)
	@Length(max = 60)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "CIDADE", length = 40)
	@Length(max = 40)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "CEP", precision = 17, scale = 17)
	public Double getCep() {
		return this.cep;
	}

	public void setCep(Double cep) {
		this.cep = cep;
	}

	@Column(name = "UF", length = 2)
	@Length(max = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "COD_IBGE", precision = 17, scale = 17)
	public Double getCodIbge() {
		return this.codIbge;
	}

	public void setCodIbge(Double codIbge) {
		this.codIbge = codIbge;
	}

	@Column(name = "CDD_CODIGO")
	public Integer getCddCodigo() {
		return this.cddCodigo;
	}

	public void setCddCodigo(Integer cddCodigo) {
		this.cddCodigo = cddCodigo;
	}

	@Column(name = "TIP_CODIGO", precision = 17, scale = 17)
	public Double getTipCodigo() {
		return this.tipCodigo;
	}

	public void setTipCodigo(Double tipCodigo) {
		this.tipCodigo = tipCodigo;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getPacCodigo());
		umHashCodeBuilder.append(this.getLogradouro());
		umHashCodeBuilder.append(this.getNroLogradouro());
		umHashCodeBuilder.append(this.getComplLogradouro());
		umHashCodeBuilder.append(this.getCep());
		umHashCodeBuilder.append(this.getBairro());
		umHashCodeBuilder.append(this.getCidade());
		umHashCodeBuilder.append(this.getCddCodigo());
		umHashCodeBuilder.append(this.getCodIbge());
		umHashCodeBuilder.append(this.getUf());
		umHashCodeBuilder.append(this.getTipCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MvaipEnderPacCompletoId)) {
			return false;
		}
		MvaipEnderPacCompletoId other = (MvaipEnderPacCompletoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getPacCodigo(), other.getPacCodigo());
		umEqualsBuilder.append(this.getLogradouro(), other.getLogradouro());
		umEqualsBuilder.append(this.getNroLogradouro(), other.getNroLogradouro());
		umEqualsBuilder.append(this.getComplLogradouro(), other.getComplLogradouro());
		umEqualsBuilder.append(this.getCep(), other.getCep());
		umEqualsBuilder.append(this.getBairro(), other.getBairro());
		umEqualsBuilder.append(this.getCidade(), other.getCidade());
		umEqualsBuilder.append(this.getCddCodigo(), other.getCddCodigo());
		umEqualsBuilder.append(this.getCodIbge(), other.getCodIbge());
		umEqualsBuilder.append(this.getUf(), other.getUf());
		umEqualsBuilder.append(this.getTipCodigo(), other.getTipCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
