package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * MvaipEnderPacCompleto generated by hbm2java
 */
@Entity
@Table(name = "MVAIP_ENDER_PAC_COMPLETO", schema = "AGH")
public class MvaipEnderPacCompleto extends BaseEntityId<MvaipEnderPacCompletoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5330591730499760976L;
	private MvaipEnderPacCompletoId id;

	public MvaipEnderPacCompleto() {
	}

	public MvaipEnderPacCompleto(MvaipEnderPacCompletoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "pacCodigo", column = @Column(name = "PAC_CODIGO")),
			@AttributeOverride(name = "logradouro", column = @Column(name = "LOGRADOURO", length = 132)),
			@AttributeOverride(name = "nroLogradouro", column = @Column(name = "NRO_LOGRADOURO")),
			@AttributeOverride(name = "complLogradouro", column = @Column(name = "COMPL_LOGRADOURO", length = 20)),
			@AttributeOverride(name = "bairro", column = @Column(name = "BAIRRO", length = 60)),
			@AttributeOverride(name = "cidade", column = @Column(name = "CIDADE", length = 40)),
			@AttributeOverride(name = "cep", column = @Column(name = "CEP", precision = 17, scale = 17)),
			@AttributeOverride(name = "uf", column = @Column(name = "UF", length = 2)),
			@AttributeOverride(name = "codIbge", column = @Column(name = "COD_IBGE", precision = 17, scale = 17)),
			@AttributeOverride(name = "cddCodigo", column = @Column(name = "CDD_CODIGO")),
			@AttributeOverride(name = "tipCodigo", column = @Column(name = "TIP_CODIGO", precision = 17, scale = 17)) })
	public MvaipEnderPacCompletoId getId() {
		return this.id;
	}

	public void setId(MvaipEnderPacCompletoId id) {
		this.id = id;
	}

	public enum Fields {

		ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
