package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * MvaipBairroCepLogradouroId generated by hbm2java
 */
@Embeddable
public class MvaipBairroCepLogradouroId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1581380564061094669L;
	private Integer cloLgrCodigo;
	private Integer cloCep;
	private Integer baiCodigo;

	public MvaipBairroCepLogradouroId() {
	}

	public MvaipBairroCepLogradouroId(Integer cloLgrCodigo, Integer cloCep, Integer baiCodigo) {
		this.cloLgrCodigo = cloLgrCodigo;
		this.cloCep = cloCep;
		this.baiCodigo = baiCodigo;
	}

	@Column(name = "CLO_LGR_CODIGO", nullable = false)
	public Integer getCloLgrCodigo() {
		return this.cloLgrCodigo;
	}

	public void setCloLgrCodigo(Integer cloLgrCodigo) {
		this.cloLgrCodigo = cloLgrCodigo;
	}

	@Column(name = "CLO_CEP", nullable = false)
	public Integer getCloCep() {
		return this.cloCep;
	}

	public void setCloCep(Integer cloCep) {
		this.cloCep = cloCep;
	}

	@Column(name = "BAI_CODIGO", nullable = false)
	public Integer getBaiCodigo() {
		return this.baiCodigo;
	}

	public void setBaiCodigo(Integer baiCodigo) {
		this.baiCodigo = baiCodigo;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getCloCep());
		umHashCodeBuilder.append(this.getCloLgrCodigo());
		umHashCodeBuilder.append(this.getBaiCodigo());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof MvaipBairroCepLogradouroId)) {
			return false;
		}
		MvaipBairroCepLogradouroId other = (MvaipBairroCepLogradouroId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getCloCep(), other.getCloCep());
		umEqualsBuilder.append(this.getCloLgrCodigo(), other.getCloLgrCodigo());
		umEqualsBuilder.append(this.getBaiCodigo(), other.getBaiCodigo());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
