package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioAsa;
import br.gov.mec.aghu.dominio.DominioCaraterCirurgia;
import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * PdtDadoDescJn generated by hbm2java
 */
@Entity
@Table(name = "PDT_DADOS_DESCS_JN", schema = "AGH")
@SequenceGenerator(name = "pdtPddJnSeq", sequenceName = "AGH.PDT_PDD_JN_SEQ", allocationSize = 1)
@Immutable
public class PdtDadoDescJn extends BaseJournal {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8025585457876460335L;
	
	private Integer ddtSeq;
	private Boolean sedacao;
	private Integer nroFilme;
	private Date dthrInicio;
	private Date dthrFim;
	private DominioCaraterCirurgia carater;
	private String observacoesProc;
	private Short tanSeq;
	private Short deqSeq;
	private Integer dteSeq;
	private String criadoEm;
	private Integer serMatricula;
	private Short serVinCodigo;
	private DominioAsa asa;
	private Short tempoJejum;
	private Boolean intercorrencia;	
	private Boolean indUsoO2;

	public PdtDadoDescJn() {
	}

	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "pdtPddJnSeq")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	
	@Column(name = "DDT_SEQ", nullable = false)
	public Integer getDdtSeq() {
		return this.ddtSeq;
	}

	public void setDdtSeq(Integer ddtSeq) {
		this.ddtSeq = ddtSeq;
	}

	@Column(name = "SEDACAO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getSedacao() {
		return this.sedacao;
	}

	public void setSedacao(Boolean sedacao) {
		this.sedacao = sedacao;
	}

	@Column(name = "NRO_FILME")
	public Integer getNroFilme() {
		return this.nroFilme;
	}

	public void setNroFilme(Integer nroFilme) {
		this.nroFilme = nroFilme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_INICIO", length = 29)
	public Date getDthrInicio() {
		return this.dthrInicio;
	}

	public void setDthrInicio(Date dthrInicio) {
		this.dthrInicio = dthrInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_FIM", length = 29)
	public Date getDthrFim() {
		return this.dthrFim;
	}

	public void setDthrFim(Date dthrFim) {
		this.dthrFim = dthrFim;
	}

	@Column(name = "CARATER", length = 3)
	@Enumerated(EnumType.STRING)
	public DominioCaraterCirurgia getCarater() {
		return this.carater;
	}

	public void setCarater(DominioCaraterCirurgia  carater) {
		this.carater = carater;
	}

	@Column(name = "OBSERVACOES_PROC", length = 500)
	@Length(max = 500)
	public String getObservacoesProc() {
		return this.observacoesProc;
	}

	public void setObservacoesProc(String observacoesProc) {
		this.observacoesProc = observacoesProc;
	}

	@Column(name = "TAN_SEQ")
	public Short getTanSeq() {
		return this.tanSeq;
	}

	public void setTanSeq(Short tanSeq) {
		this.tanSeq = tanSeq;
	}

	@Column(name = "DEQ_SEQ")
	public Short getDeqSeq() {
		return this.deqSeq;
	}

	public void setDeqSeq(Short deqSeq) {
		this.deqSeq = deqSeq;
	}

	@Column(name = "DTE_SEQ")
	public Integer getDteSeq() {
		return this.dteSeq;
	}

	public void setDteSeq(Integer dteSeq) {
		this.dteSeq = dteSeq;
	}

	@Column(name = "CRIADO_EM", length = 240)
	@Length(max = 240)
	public String getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(String criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "SER_MATRICULA")
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO")
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}
	
	@Column(name = "ASA")
	@org.hibernate.annotations.Type(parameters = { @Parameter(name = "enumClassName", value = "br.gov.mec.aghu.dominio.DominioAsa") }, type = "br.gov.mec.aghu.core.model.jpa.DominioUserType")
	public DominioAsa getAsa() {
		return this.asa;
	}

	public void setAsa(DominioAsa asa) {
		this.asa = asa;
	}	
	
	@Column(name = "TEMPO_JEJUM", length = 1)
	public Short getTempoJejum() {
		return tempoJejum;
	}

	public void setTempoJejum(Short tempoJejum) {
		this.tempoJejum = tempoJejum;
	}

	@Column(name = "IND_INTERCORRENCIA", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIntercorrencia() {
		return intercorrencia;
	}

	public void setIntercorrencia(Boolean intercorrencia) {
		this.intercorrencia = intercorrencia;
	}	

	@Column(name = "IND_USO_O2", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndUsoO2() {
		return indUsoO2;
	}

	public void setIndUsoO2(Boolean indUsoO2) {
		this.indUsoO2 = indUsoO2;
	}

	
	
	
	public enum Fields {
		
		DDT_SEQ("ddtSeq"),
		SEDACAO("sedacao"),
		NRO_FILME("nroFilme"),
		DTHR_INICIO("dthrInicio"),
		DTHR_FIM("dthrFim"),
		CARATER("carater"),
		OBSERVACOES_PROC("observacoesProc"),
		TAN_SEQ("tanSeq"),
		DEQ_SEQ("deqSeq"),
		DTE_SEQ("dteSeq"),
		CRIADO_EM("criadoEm"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
