package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * PdtEquipamento generated by hbm2java
 */
@Entity
@SequenceGenerator(name="pdtDeqSq1", sequenceName="AGH.PDT_DEQ_SQ1", allocationSize = 1)
@Table(name = "PDT_EQUIPAMENTOS", schema = "AGH")
public class PdtEquipamento extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3573050622914429126L;
	private Short seq;
	private Integer version;
	private RapServidores rapServidores;
	private String descricao;
	private String motivoInat;
	private DominioSituacao indSituacao;
	private Date criadoEm;
	private String patchImagens;
	private Set<PdtDadoDesc> pdtDadoDesces = new HashSet<PdtDadoDesc>(0);
	private Set<PdtInstrPorEquip> pdtInstrPorEquipes = new HashSet<PdtInstrPorEquip>(0);
	private Set<PdtEquipPorProc> pdtEquipPorProces = new HashSet<PdtEquipPorProc>(0);

	public PdtEquipamento() {
	}

	public PdtEquipamento(Short seq, RapServidores rapServidores, String descricao, DominioSituacao indSituacao, Date criadoEm) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.descricao = descricao;
		this.indSituacao = indSituacao;
		this.criadoEm = criadoEm;
	}

	public PdtEquipamento(Short seq, RapServidores rapServidores, String descricao, String motivoInat, DominioSituacao indSituacao,
			Date criadoEm, String patchImagens, Set<PdtDadoDesc> pdtDadoDesces, Set<PdtInstrPorEquip> pdtInstrPorEquipes,
			Set<PdtEquipPorProc> pdtEquipPorProces) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.descricao = descricao;
		this.motivoInat = motivoInat;
		this.indSituacao = indSituacao;
		this.criadoEm = criadoEm;
		this.patchImagens = patchImagens;
		this.pdtDadoDesces = pdtDadoDesces;
		this.pdtInstrPorEquipes = pdtInstrPorEquipes;
		this.pdtEquipPorProces = pdtEquipPorProces;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "pdtDeqSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 100)
	@Length(max = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "MOTIVO_INAT", length = 120)
	@Length(max = 120)
	public String getMotivoInat() {
		return this.motivoInat;
	}

	public void setMotivoInat(String motivoInat) {
		this.motivoInat = motivoInat;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Column(name = "PATCH_IMAGENS", length = 120)
	@Length(max = 120)
	public String getPatchImagens() {
		return this.patchImagens;
	}

	public void setPatchImagens(String patchImagens) {
		this.patchImagens = patchImagens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtEquipamento")
	public Set<PdtDadoDesc> getPdtDadoDesces() {
		return this.pdtDadoDesces;
	}

	public void setPdtDadoDesces(Set<PdtDadoDesc> pdtDadoDesces) {
		this.pdtDadoDesces = pdtDadoDesces;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtEquipamento")
	public Set<PdtInstrPorEquip> getPdtInstrPorEquipes() {
		return this.pdtInstrPorEquipes;
	}

	public void setPdtInstrPorEquipes(Set<PdtInstrPorEquip> pdtInstrPorEquipes) {
		this.pdtInstrPorEquipes = pdtInstrPorEquipes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pdtEquipamento")
	public Set<PdtEquipPorProc> getPdtEquipPorProces() {
		return this.pdtEquipPorProces;
	}

	public void setPdtEquipPorProces(Set<PdtEquipPorProc> pdtEquipPorProces) {
		this.pdtEquipPorProces = pdtEquipPorProces;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		DESCRICAO("descricao"),
		MOTIVO_INAT("motivoInat"),
		IND_SITUACAO("indSituacao"),
		CRIADO_EM("criadoEm"),
		PATCH_IMAGENS("patchImagens"),
		PDT_DADO_DESCES("pdtDadoDesces"),
		PDT_INSTR_POR_EQUIPES("pdtInstrPorEquipes"),
		PDT_EQUIP_POR_PROCES("pdtEquipPorProces");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PdtEquipamento)) {
			return false;
		}
		PdtEquipamento other = (PdtEquipamento) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
