package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * RapDependenteUnimedJn generated by hbm2java
 */
@Entity
@Table(name = "RAP_DEPENDENTES_UNIMED_JN", schema = "AGH")
@Immutable
public class RapDependenteUnimedJn extends BaseJournal {

/**
	 * 
	 */
	private static final long serialVersionUID = 5794891201373276737L;
	/* ATUALIZADOR JOURNALS - PROPERTIES	private Long seqJn;
	private String jnUser;
	private Date jnDateTime;
	private String jnOperation;*/
	private Integer serMatricula;
	private Short serVinCodigo;
	private Integer codigo;
	private Short grauParentesco;
	private String indUnimed;
	private String indSos;
	private String indOdonto;
	private Date dtOdonto;
	private Date dtInicio;
	private Date dtFim;
	private String indSubsidio;
	private String nroCarteira;

	public RapDependenteUnimedJn() {
	}

	public RapDependenteUnimedJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer serMatricula,
			Short serVinCodigo, Integer codigo) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.codigo = codigo;
	}

	public RapDependenteUnimedJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Integer serMatricula,
			Short serVinCodigo, Integer codigo, Short grauParentesco, String indUnimed, String indSos, String indOdonto, Date dtOdonto,
			Date dtInicio, Date dtFim, String indSubsidio, String nroCarteira) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.codigo = codigo;
		this.grauParentesco = grauParentesco;
		this.indUnimed = indUnimed;
		this.indSos = indSos;
		this.indOdonto = indOdonto;
		this.dtOdonto = dtOdonto;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
		this.indSubsidio = indSubsidio;
		this.nroCarteira = nroCarteira;
	}

	// ATUALIZADOR JOURNALS - ID
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	//@GeneratedValue(strategy = GenerationType.AUTO, generator = "")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	// ATUALIZADOR JOURNALS - ID
	
/* ATUALIZADOR JOURNALS - Get / Set	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	public Long getSeqJn() {
		return this.seqJn;
	}

	public void setSeqJn(Long seqJn) {
		this.seqJn = seqJn;
	}

	@Column(name = "JN_USER", nullable = false, length = 30)
	@Length(max = 30)
	public String getJnUser() {
		return this.jnUser;
	}

	public void setJnUser(String jnUser) {
		this.jnUser = jnUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JN_DATE_TIME", nullable = false, length = 29)
	public Date getJnDateTime() {
		return this.jnDateTime;
	}

	public void setJnDateTime(Date jnDateTime) {
		this.jnDateTime = jnDateTime;
	}

	@Column(name = "JN_OPERATION", nullable = false, length = 3)
	@Length(max = 3)
	public String getJnOperation() {
		return this.jnOperation;
	}

	public void setJnOperation(String jnOperation) {
		this.jnOperation = jnOperation;
	}*/

	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "CODIGO", nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "GRAU_PARENTESCO")
	public Short getGrauParentesco() {
		return this.grauParentesco;
	}

	public void setGrauParentesco(Short grauParentesco) {
		this.grauParentesco = grauParentesco;
	}

	@Column(name = "IND_UNIMED", length = 1)
	@Length(max = 1)
	public String getIndUnimed() {
		return this.indUnimed;
	}

	public void setIndUnimed(String indUnimed) {
		this.indUnimed = indUnimed;
	}

	@Column(name = "IND_SOS", length = 1)
	@Length(max = 1)
	public String getIndSos() {
		return this.indSos;
	}

	public void setIndSos(String indSos) {
		this.indSos = indSos;
	}

	@Column(name = "IND_ODONTO", length = 1)
	@Length(max = 1)
	public String getIndOdonto() {
		return this.indOdonto;
	}

	public void setIndOdonto(String indOdonto) {
		this.indOdonto = indOdonto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_ODONTO", length = 29)
	public Date getDtOdonto() {
		return this.dtOdonto;
	}

	public void setDtOdonto(Date dtOdonto) {
		this.dtOdonto = dtOdonto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO", length = 29)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM", length = 29)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Column(name = "IND_SUBSIDIO", length = 1)
	@Length(max = 1)
	public String getIndSubsidio() {
		return this.indSubsidio;
	}

	public void setIndSubsidio(String indSubsidio) {
		this.indSubsidio = indSubsidio;
	}

	@Column(name = "NRO_CARTEIRA", length = 20)
	@Length(max = 20)
	public String getNroCarteira() {
		return this.nroCarteira;
	}

	public void setNroCarteira(String nroCarteira) {
		this.nroCarteira = nroCarteira;
	}

	public enum Fields {

	/* ATUALIZADOR JOURNALS - Fields	SEQ_JN("seqJn"),
		JN_USER("jnUser"),
		JN_DATE_TIME("jnDateTime"),
		JN_OPERATION("jnOperation"),*/
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		CODIGO("codigo"),
		GRAU_PARENTESCO("grauParentesco"),
		IND_UNIMED("indUnimed"),
		IND_SOS("indSos"),
		IND_ODONTO("indOdonto"),
		DT_ODONTO("dtOdonto"),
		DT_INICIO("dtInicio"),
		DT_FIM("dtFim"),
		IND_SUBSIDIO("indSubsidio"),
		NRO_CARTEIRA("nroCarteira");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
