package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * RapForma generated by hbm2java
 */
@Entity
@SequenceGenerator(name="rapFrmSq1", sequenceName="AGH.RAP_FRM_SQ1", allocationSize = 1)
@Table(name = "RAP_FORMAS", schema = "AGH")
public class RapForma extends BaseEntitySeq<Short> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3316686703280883150L;
	private Short seq;
	private Integer version;
	private String descricao;
	private Set<RapMedidaExtrato> rapMedidaExtratos = new HashSet<RapMedidaExtrato>(0);
	private Set<RapMedidaPlanejada> rapMedidaPlanejadaes = new HashSet<RapMedidaPlanejada>(0);

	public RapForma() {
	}

	public RapForma(Short seq, String descricao) {
		this.seq = seq;
		this.descricao = descricao;
	}

	public RapForma(Short seq, String descricao, Set<RapMedidaExtrato> rapMedidaExtratos,
			Set<RapMedidaPlanejada> rapMedidaPlanejadaes) {
		this.seq = seq;
		this.descricao = descricao;
		this.rapMedidaExtratos = rapMedidaExtratos;
		this.rapMedidaPlanejadaes = rapMedidaPlanejadaes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "rapFrmSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Short getSeq() {
		return this.seq;
	}

	public void setSeq(Short seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rapForma")
	public Set<RapMedidaExtrato> getRapMedidaExtratos() {
		return this.rapMedidaExtratos;
	}

	public void setRapMedidaExtratos(Set<RapMedidaExtrato> rapMedidaExtratos) {
		this.rapMedidaExtratos = rapMedidaExtratos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rapForma")
	public Set<RapMedidaPlanejada> getRapMedidaPlanejadaes() {
		return this.rapMedidaPlanejadaes;
	}

	public void setRapMedidaPlanejadaes(Set<RapMedidaPlanejada> rapMedidaPlanejadaes) {
		this.rapMedidaPlanejadaes = rapMedidaPlanejadaes;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		DESCRICAO("descricao"),
		RAP_MEDIDA_EXTRATOS("rapMedidaExtratos"),
		RAP_MEDIDA_PLANEJADAES("rapMedidaPlanejadaes");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RapForma)) {
			return false;
		}
		RapForma other = (RapForma) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
