package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * RapTmpLote generated by hbm2java
 */
@Entity
@Table(name = "RAP_TMP_LOTES", schema = "AGH")
public class RapTmpLote extends BaseEntityId<RapTmpLoteId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5070244903289622800L;
	private RapTmpLoteId id;
	private RapServidores rapServidores;

	public RapTmpLote() {
	}

	public RapTmpLote(RapTmpLoteId id) {
		this.id = id;
	}

	public RapTmpLote(RapTmpLoteId id, RapServidores rapServidores) {
		this.id = id;
		this.rapServidores = rapServidores;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "seq", column = @Column(name = "SEQ")),
			@AttributeOverride(name = "serMatricula", column = @Column(name = "SER_MATRICULA")),
			@AttributeOverride(name = "serVinCodigo", column = @Column(name = "SER_VIN_CODIGO")),
			@AttributeOverride(name = "dthr", column = @Column(name = "DTHR", length = 29)),
			@AttributeOverride(name = "tipoLote", column = @Column(name = "TIPO_LOTE", length = 2)),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false)) })
	public RapTmpLoteId getId() {
		return this.id;
	}

	public void setId(RapTmpLoteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", insertable = false, updatable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", insertable = false, updatable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	public enum Fields {

		ID("id"),
		RAP_SERVIDORES("rapServidores");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RapTmpLote)) {
			return false;
		}
		RapTmpLote other = (RapTmpLote) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
