package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * RapTmpFeriasFolhaAmigaId generated by hbm2java
 */
@Embeddable
public class RapTmpFeriasFolhaAmigaId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4466380177570035108L;
	private Integer matricula;
	private Short filial;
	private String centroCusto;
	private String dtInicio;
	private String dtFim;
	private String dtInicioPa;
	private String dtFimPa;
	private String dtInicioReal;
	private String dtFimReal;
	private String progFerias;
	private Integer version;

	public RapTmpFeriasFolhaAmigaId() {
	}

	public RapTmpFeriasFolhaAmigaId(Integer version) {
		this.version = version;
	}

	public RapTmpFeriasFolhaAmigaId(Integer matricula, Short filial, String centroCusto, String dtInicio, String dtFim,
			String dtInicioPa, String dtFimPa, String dtInicioReal, String dtFimReal, String progFerias, Integer version) {
		this.matricula = matricula;
		this.filial = filial;
		this.centroCusto = centroCusto;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
		this.dtInicioPa = dtInicioPa;
		this.dtFimPa = dtFimPa;
		this.dtInicioReal = dtInicioReal;
		this.dtFimReal = dtFimReal;
		this.progFerias = progFerias;
		this.version = version;
	}

	@Column(name = "MATRICULA")
	public Integer getMatricula() {
		return this.matricula;
	}

	public void setMatricula(Integer matricula) {
		this.matricula = matricula;
	}

	@Column(name = "FILIAL")
	public Short getFilial() {
		return this.filial;
	}

	public void setFilial(Short filial) {
		this.filial = filial;
	}

	@Column(name = "CENTRO_CUSTO", length = 12)
	@Length(max = 12)
	public String getCentroCusto() {
		return this.centroCusto;
	}

	public void setCentroCusto(String centroCusto) {
		this.centroCusto = centroCusto;
	}

	@Column(name = "DT_INICIO", length = 8)
	@Length(max = 8)
	public String getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(String dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Column(name = "DT_FIM", length = 8)
	@Length(max = 8)
	public String getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(String dtFim) {
		this.dtFim = dtFim;
	}

	@Column(name = "DT_INICIO_PA", length = 8)
	@Length(max = 8)
	public String getDtInicioPa() {
		return this.dtInicioPa;
	}

	public void setDtInicioPa(String dtInicioPa) {
		this.dtInicioPa = dtInicioPa;
	}

	@Column(name = "DT_FIM_PA", length = 8)
	@Length(max = 8)
	public String getDtFimPa() {
		return this.dtFimPa;
	}

	public void setDtFimPa(String dtFimPa) {
		this.dtFimPa = dtFimPa;
	}

	@Column(name = "DT_INICIO_REAL", length = 8)
	@Length(max = 8)
	public String getDtInicioReal() {
		return this.dtInicioReal;
	}

	public void setDtInicioReal(String dtInicioReal) {
		this.dtInicioReal = dtInicioReal;
	}

	@Column(name = "DT_FIM_REAL", length = 8)
	@Length(max = 8)
	public String getDtFimReal() {
		return this.dtFimReal;
	}

	public void setDtFimReal(String dtFimReal) {
		this.dtFimReal = dtFimReal;
	}

	@Column(name = "PROG_FERIAS", length = 1)
	@Length(max = 1)
	public String getProgFerias() {
		return this.progFerias;
	}

	public void setProgFerias(String progFerias) {
		this.progFerias = progFerias;
	}

	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getVersion());
		umHashCodeBuilder.append(this.getMatricula());
		umHashCodeBuilder.append(this.getDtInicio());
		umHashCodeBuilder.append(this.getDtFim());
		umHashCodeBuilder.append(this.getCentroCusto());
		umHashCodeBuilder.append(this.getFilial());
		umHashCodeBuilder.append(this.getDtInicioPa());
		umHashCodeBuilder.append(this.getDtFimPa());
		umHashCodeBuilder.append(this.getDtInicioReal());
		umHashCodeBuilder.append(this.getDtFimReal());
		umHashCodeBuilder.append(this.getProgFerias());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RapTmpFeriasFolhaAmigaId)) {
			return false;
		}
		RapTmpFeriasFolhaAmigaId other = (RapTmpFeriasFolhaAmigaId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getVersion(), other.getVersion());
		umEqualsBuilder.append(this.getMatricula(), other.getMatricula());
		umEqualsBuilder.append(this.getDtInicio(), other.getDtInicio());
		umEqualsBuilder.append(this.getDtFim(), other.getDtFim());
		umEqualsBuilder.append(this.getCentroCusto(), other.getCentroCusto());
		umEqualsBuilder.append(this.getFilial(), other.getFilial());
		umEqualsBuilder.append(this.getDtInicioPa(), other.getDtInicioPa());
		umEqualsBuilder.append(this.getDtFimPa(), other.getDtFimPa());
		umEqualsBuilder.append(this.getDtInicioReal(), other.getDtInicioReal());
		umEqualsBuilder.append(this.getDtFimReal(), other.getDtFimReal());
		umEqualsBuilder.append(this.getProgFerias(), other.getProgFerias());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
