package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * RapTmpAfastamento generated by hbm2java
 */
@Entity
@Table(name = "RAP_TMP_AFASTAMENTOS", schema = "AGH")
public class RapTmpAfastamento extends BaseEntityId<RapTmpAfastamentoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1790279571257960874L;
	private RapTmpAfastamentoId id;
	private Integer version;
	private String lotSeq;
	private Integer serMatricula;
	private Short serVinCodigo;
	private String oldTafCodigo;
	private Date oldDtInicio;
	private Date oldDtFim;
	private String newTafCodigo;
	private Date newDtInicio;
	private Date newDtFim;
	private Integer serMatriculaCriado;
	private Short serVinCodigoCriado;

	public RapTmpAfastamento() {
	}

	public RapTmpAfastamento(RapTmpAfastamentoId id) {
		this.id = id;
	}

	public RapTmpAfastamento(RapTmpAfastamentoId id, String lotSeq, Integer serMatricula, Short serVinCodigo, String oldTafCodigo,
			Date oldDtInicio, Date oldDtFim, String newTafCodigo, Date newDtInicio, Date newDtFim, Integer serMatriculaCriado,
			Short serVinCodigoCriado) {
		this.id = id;
		this.lotSeq = lotSeq;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.oldTafCodigo = oldTafCodigo;
		this.oldDtInicio = oldDtInicio;
		this.oldDtFim = oldDtFim;
		this.newTafCodigo = newTafCodigo;
		this.newDtInicio = newDtInicio;
		this.newDtFim = newDtFim;
		this.serMatriculaCriado = serMatriculaCriado;
		this.serVinCodigoCriado = serVinCodigoCriado;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "sequencia", column = @Column(name = "SEQUENCIA", nullable = false)),
			@AttributeOverride(name = "operacao", column = @Column(name = "OPERACAO", nullable = false, length = 3)),
			@AttributeOverride(name = "dthrOperacao", column = @Column(name = "DTHR_OPERACAO", nullable = false, length = 29)) })
	public RapTmpAfastamentoId getId() {
		return this.id;
	}

	public void setId(RapTmpAfastamentoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "LOT_SEQ", length = 10)
	@Length(max = 10)
	public String getLotSeq() {
		return this.lotSeq;
	}

	public void setLotSeq(String lotSeq) {
		this.lotSeq = lotSeq;
	}

	@Column(name = "SER_MATRICULA")
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO")
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "OLD_TAF_CODIGO", length = 2)
	@Length(max = 2)
	public String getOldTafCodigo() {
		return this.oldTafCodigo;
	}

	public void setOldTafCodigo(String oldTafCodigo) {
		this.oldTafCodigo = oldTafCodigo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OLD_DT_INICIO", length = 29)
	public Date getOldDtInicio() {
		return this.oldDtInicio;
	}

	public void setOldDtInicio(Date oldDtInicio) {
		this.oldDtInicio = oldDtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OLD_DT_FIM", length = 29)
	public Date getOldDtFim() {
		return this.oldDtFim;
	}

	public void setOldDtFim(Date oldDtFim) {
		this.oldDtFim = oldDtFim;
	}

	@Column(name = "NEW_TAF_CODIGO", length = 2)
	@Length(max = 2)
	public String getNewTafCodigo() {
		return this.newTafCodigo;
	}

	public void setNewTafCodigo(String newTafCodigo) {
		this.newTafCodigo = newTafCodigo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEW_DT_INICIO", length = 29)
	public Date getNewDtInicio() {
		return this.newDtInicio;
	}

	public void setNewDtInicio(Date newDtInicio) {
		this.newDtInicio = newDtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEW_DT_FIM", length = 29)
	public Date getNewDtFim() {
		return this.newDtFim;
	}

	public void setNewDtFim(Date newDtFim) {
		this.newDtFim = newDtFim;
	}

	@Column(name = "SER_MATRICULA_CRIADO")
	public Integer getSerMatriculaCriado() {
		return this.serMatriculaCriado;
	}

	public void setSerMatriculaCriado(Integer serMatriculaCriado) {
		this.serMatriculaCriado = serMatriculaCriado;
	}

	@Column(name = "SER_VIN_CODIGO_CRIADO")
	public Short getSerVinCodigoCriado() {
		return this.serVinCodigoCriado;
	}

	public void setSerVinCodigoCriado(Short serVinCodigoCriado) {
		this.serVinCodigoCriado = serVinCodigoCriado;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		LOT_SEQ("lotSeq"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		OLD_TAF_CODIGO("oldTafCodigo"),
		OLD_DT_INICIO("oldDtInicio"),
		OLD_DT_FIM("oldDtFim"),
		NEW_TAF_CODIGO("newTafCodigo"),
		NEW_DT_INICIO("newDtInicio"),
		NEW_DT_FIM("newDtFim"),
		SER_MATRICULA_CRIADO("serMatriculaCriado"),
		SER_VIN_CODIGO_CRIADO("serVinCodigoCriado");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RapTmpAfastamento)) {
			return false;
		}
		RapTmpAfastamento other = (RapTmpAfastamento) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
