package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.model.BaseJournal;

/**
 * RapUniConsultaJn generated by hbm2java
 */
@Entity
@Table(name = "RAP_UNI_CONSULTAS_JN", schema = "AGH")
@Immutable
public class RapUniConsultaJn extends BaseJournal {

/**
	 * 
	 */
	private static final long serialVersionUID = -4283184478740271108L;
	/* ATUALIZADOR JOURNALS - PROPERTIES	private Long seqJn;
	private String jnUser;
	private Date jnDateTime;
	private String jnOperation;*/
	private Date cunDtInicio;
	private Integer sadSerMatricula;
	private Short sadSerVinCodigo;
	private Short sadSeqp;
	private Short seqp;
	private Date data;
	private Double valor;
	private String nomeBeneficiario;
	private String nomeProfissional;
	private String observacao;

	public RapUniConsultaJn() {
	}

	public RapUniConsultaJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Date cunDtInicio, Integer sadSerMatricula,
			Short sadSerVinCodigo, Short sadSeqp, Short seqp, Date data, Double valor) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.cunDtInicio = cunDtInicio;
		this.sadSerMatricula = sadSerMatricula;
		this.sadSerVinCodigo = sadSerVinCodigo;
		this.sadSeqp = sadSeqp;
		this.seqp = seqp;
		this.data = data;
		this.valor = valor;
	}

	public RapUniConsultaJn(Long seqJn, String jnUser, Date jnDateTime, String jnOperation, Date cunDtInicio, Integer sadSerMatricula,
			Short sadSerVinCodigo, Short sadSeqp, Short seqp, Date data, Double valor, String nomeBeneficiario,
			String nomeProfissional, String observacao) {
	/* ATUALIZADOR JOURNALS - contrutor	this.seqJn = seqJn;
		this.jnUser = jnUser;
		this.jnDateTime = jnDateTime;
		this.jnOperation = jnOperation;*/
		this.cunDtInicio = cunDtInicio;
		this.sadSerMatricula = sadSerMatricula;
		this.sadSerVinCodigo = sadSerVinCodigo;
		this.sadSeqp = sadSeqp;
		this.seqp = seqp;
		this.data = data;
		this.valor = valor;
		this.nomeBeneficiario = nomeBeneficiario;
		this.nomeProfissional = nomeProfissional;
		this.observacao = observacao;
	}

	// ATUALIZADOR JOURNALS - ID
	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	//@GeneratedValue(strategy = GenerationType.AUTO, generator = "")
	@Override
	public Integer getSeqJn() {
		return super.getSeqJn();
	}
	// ATUALIZADOR JOURNALS - ID
	
/* ATUALIZADOR JOURNALS - Get / Set	@Id
	@Column(name = "SEQ_JN", unique = true, nullable = false)
	public Long getSeqJn() {
		return this.seqJn;
	}

	public void setSeqJn(Long seqJn) {
		this.seqJn = seqJn;
	}

	@Column(name = "JN_USER", nullable = false, length = 30)
	@Length(max = 30)
	public String getJnUser() {
		return this.jnUser;
	}

	public void setJnUser(String jnUser) {
		this.jnUser = jnUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JN_DATE_TIME", nullable = false, length = 29)
	public Date getJnDateTime() {
		return this.jnDateTime;
	}

	public void setJnDateTime(Date jnDateTime) {
		this.jnDateTime = jnDateTime;
	}

	@Column(name = "JN_OPERATION", nullable = false, length = 3)
	@Length(max = 3)
	public String getJnOperation() {
		return this.jnOperation;
	}

	public void setJnOperation(String jnOperation) {
		this.jnOperation = jnOperation;
	}*/

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CUN_DT_INICIO", nullable = false, length = 29)
	public Date getCunDtInicio() {
		return this.cunDtInicio;
	}

	public void setCunDtInicio(Date cunDtInicio) {
		this.cunDtInicio = cunDtInicio;
	}

	@Column(name = "SAD_SER_MATRICULA", nullable = false)
	public Integer getSadSerMatricula() {
		return this.sadSerMatricula;
	}

	public void setSadSerMatricula(Integer sadSerMatricula) {
		this.sadSerMatricula = sadSerMatricula;
	}

	@Column(name = "SAD_SER_VIN_CODIGO", nullable = false)
	public Short getSadSerVinCodigo() {
		return this.sadSerVinCodigo;
	}

	public void setSadSerVinCodigo(Short sadSerVinCodigo) {
		this.sadSerVinCodigo = sadSerVinCodigo;
	}

	@Column(name = "SAD_SEQP", nullable = false)
	public Short getSadSeqp() {
		return this.sadSeqp;
	}

	public void setSadSeqp(Short sadSeqp) {
		this.sadSeqp = sadSeqp;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA", nullable = false, length = 29)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "VALOR", nullable = false, precision = 17, scale = 17)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	@Column(name = "NOME_BENEFICIARIO", length = 25)
	@Length(max = 25)
	public String getNomeBeneficiario() {
		return this.nomeBeneficiario;
	}

	public void setNomeBeneficiario(String nomeBeneficiario) {
		this.nomeBeneficiario = nomeBeneficiario;
	}

	@Column(name = "NOME_PROFISSIONAL", length = 32)
	@Length(max = 32)
	public String getNomeProfissional() {
		return this.nomeProfissional;
	}

	public void setNomeProfissional(String nomeProfissional) {
		this.nomeProfissional = nomeProfissional;
	}

	@Column(name = "OBSERVACAO", length = 240)
	@Length(max = 240)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	public enum Fields {

	/* ATUALIZADOR JOURNALS - Fields	SEQ_JN("seqJn"),
		JN_USER("jnUser"),
		JN_DATE_TIME("jnDateTime"),
		JN_OPERATION("jnOperation"),*/
		CUN_DT_INICIO("cunDtInicio"),
		SAD_SER_MATRICULA("sadSerMatricula"),
		SAD_SER_VIN_CODIGO("sadSerVinCodigo"),
		SAD_SEQP("sadSeqp"),
		SEQP("seqp"),
		DATA("data"),
		VALOR("valor"),
		NOME_BENEFICIARIO("nomeBeneficiario"),
		NOME_PROFISSIONAL("nomeProfissional"),
		OBSERVACAO("observacao");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
