package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * RapUniDepSubsidio generated by hbm2java
 */
@Entity
@Table(name = "RAP_UNI_DEP_SUBSIDIOS", schema = "AGH")
public class RapUniDepSubsidio extends BaseEntityId<RapUniDepSubsidioId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2163460502602429704L;
	private RapUniDepSubsidioId id;
	private Integer version;
	private RapServidores rapServidoresByRapDsuSerFk2;
	private RapServidores rapServidoresByRapDsuSerFk1;
	private RapUniServDependente rapUniServDependente;
	private Date dtFim;
	private Date criadoEm;
	private Date alteradoEm;

	public RapUniDepSubsidio() {
	}

	public RapUniDepSubsidio(RapUniDepSubsidioId id, RapServidores rapServidoresByRapDsuSerFk1,
			RapUniServDependente rapUniServDependente, Date criadoEm) {
		this.id = id;
		this.rapServidoresByRapDsuSerFk1 = rapServidoresByRapDsuSerFk1;
		this.rapUniServDependente = rapUniServDependente;
		this.criadoEm = criadoEm;
	}

	public RapUniDepSubsidio(RapUniDepSubsidioId id, RapServidores rapServidoresByRapDsuSerFk2,
			RapServidores rapServidoresByRapDsuSerFk1, RapUniServDependente rapUniServDependente, Date dtFim, Date criadoEm,
			Date alteradoEm) {
		this.id = id;
		this.rapServidoresByRapDsuSerFk2 = rapServidoresByRapDsuSerFk2;
		this.rapServidoresByRapDsuSerFk1 = rapServidoresByRapDsuSerFk1;
		this.rapUniServDependente = rapUniServDependente;
		this.dtFim = dtFim;
		this.criadoEm = criadoEm;
		this.alteradoEm = alteradoEm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sdeSadSerMatricula", column = @Column(name = "SDE_SAD_SER_MATRICULA", nullable = false)),
			@AttributeOverride(name = "sdeSadSerVinCodigo", column = @Column(name = "SDE_SAD_SER_VIN_CODIGO", nullable = false)),
			@AttributeOverride(name = "sdeSadSeqp", column = @Column(name = "SDE_SAD_SEQP", nullable = false)),
			@AttributeOverride(name = "sdeDepPesCodigo", column = @Column(name = "SDE_DEP_PES_CODIGO", nullable = false)),
			@AttributeOverride(name = "sdeDepCodigo", column = @Column(name = "SDE_DEP_CODIGO", nullable = false)),
			@AttributeOverride(name = "sdeDtInicio", column = @Column(name = "SDE_DT_INICIO", nullable = false, length = 29)),
			@AttributeOverride(name = "dtInicio", column = @Column(name = "DT_INICIO", nullable = false, length = 29)) })
	public RapUniDepSubsidioId getId() {
		return this.id;
	}

	public void setId(RapUniDepSubsidioId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA_ALTERADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_ALTERADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getRapServidoresByRapDsuSerFk2() {
		return this.rapServidoresByRapDsuSerFk2;
	}

	public void setRapServidoresByRapDsuSerFk2(RapServidores rapServidoresByRapDsuSerFk2) {
		this.rapServidoresByRapDsuSerFk2 = rapServidoresByRapDsuSerFk2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA_CRIADO", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO_CRIADO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidoresByRapDsuSerFk1() {
		return this.rapServidoresByRapDsuSerFk1;
	}

	public void setRapServidoresByRapDsuSerFk1(RapServidores rapServidoresByRapDsuSerFk1) {
		this.rapServidoresByRapDsuSerFk1 = rapServidoresByRapDsuSerFk1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SDE_SAD_SER_MATRICULA", referencedColumnName = "SAD_SER_MATRICULA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SDE_SAD_SER_VIN_CODIGO", referencedColumnName = "SAD_SER_VIN_CODIGO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SDE_SAD_SEQP", referencedColumnName = "SAD_SEQP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SDE_DEP_PES_CODIGO", referencedColumnName = "DEP_PES_CODIGO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SDE_DEP_CODIGO", referencedColumnName = "DEP_CODIGO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SDE_DT_INICIO", referencedColumnName = "DT_INICIO", nullable = false, insertable = false, updatable = false) })
	public RapUniServDependente getRapUniServDependente() {
		return this.rapUniServDependente;
	}

	public void setRapUniServDependente(RapUniServDependente rapUniServDependente) {
		this.rapUniServDependente = rapUniServDependente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM", length = 29)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 29)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		RAP_SERVIDORES_BY_RAP_DSU_SER_FK2("rapServidoresByRapDsuSerFk2"),
		RAP_SERVIDORES_BY_RAP_DSU_SER_FK1("rapServidoresByRapDsuSerFk1"),
		RAP_UNI_SERV_DEPENDENTES("rapUniServDependente"),
		DT_FIM("dtFim"),
		CRIADO_EM("criadoEm"),
		ALTERADO_EM("alteradoEm");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RapUniDepSubsidio)) {
			return false;
		}
		RapUniDepSubsidio other = (RapUniDepSubsidio) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
