package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * RarItemAvaliacaoId generated by hbm2java
 */
@Embeddable
public class RarItemAvaliacaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2843430531728208789L;
	private Short avaSeq;
	private Short seqp;

	public RarItemAvaliacaoId() {
	}

	public RarItemAvaliacaoId(Short avaSeq, Short seqp) {
		this.avaSeq = avaSeq;
		this.seqp = seqp;
	}

	@Column(name = "AVA_SEQ", nullable = false)
	public Short getAvaSeq() {
		return this.avaSeq;
	}

	public void setAvaSeq(Short avaSeq) {
		this.avaSeq = avaSeq;
	}

	@Column(name = "SEQP", nullable = false)
	public Short getSeqp() {
		return this.seqp;
	}

	public void setSeqp(Short seqp) {
		this.seqp = seqp;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSeqp());
		umHashCodeBuilder.append(this.getAvaSeq());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RarItemAvaliacaoId)) {
			return false;
		}
		RarItemAvaliacaoId other = (RarItemAvaliacaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSeqp(), other.getSeqp());
		umEqualsBuilder.append(this.getAvaSeq(), other.getAvaSeq());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
