package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * RarPreceptorResidente generated by hbm2java
 */
@Entity
@SequenceGenerator(name="rarPrrSq1", sequenceName="AGH.RAR_PRR_SQ1", allocationSize = 1)
@Table(name = "RAR_PRECEPTOR_RESIDENTES", schema = "AGH", uniqueConstraints = @UniqueConstraint(columnNames = { "cpm_pga_seq",
		"cpm_cnd_seq", "ser_matricula", "ser_vin_codigo", "cro_seqp_residente", "cro_ava_seq_residente", "dt_inicio", "dt_fim" }))
public class RarPreceptorResidente extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5105325619900912988L;
	private Integer seq;
	private Integer version;
	private RapServidores rapServidoresByRarPrrSerFk3;
	private RapServidores rapServidoresByRarPrrSerFk1;
	private RarCandidatoPrograma rarCandidatoPrograma;
	private RapServidores rapServidoresByRarPrrSerFk2;
	private RarCronogramaAvaliacao rarCronogramaAvaliacoesByRarPrrCroFk1;
	private RarPrograma rarPrograma;
	private RarCronogramaAvaliacao rarCronogramaAvaliacoesByRarPrrCroFk2;
	private Date dtInicio;
	private Date dtFim;
	private Date criadoEm;
	private Date alteradoEm;
	private Short ano;
	private Set<RarNotaMedia> rarNotaMediaes = new HashSet<RarNotaMedia>(0);
	private Set<RarItemAvaliacaoProf> rarItemAvaliacaoProfs = new HashSet<RarItemAvaliacaoProf>(0);

	public RarPreceptorResidente() {
	}

	public RarPreceptorResidente(Integer seq, RapServidores rapServidoresByRarPrrSerFk1, RarCandidatoPrograma rarCandidatoPrograma,
			RarCronogramaAvaliacao rarCronogramaAvaliacoesByRarPrrCroFk1, RarPrograma rarPrograma,
			RarCronogramaAvaliacao rarCronogramaAvaliacoesByRarPrrCroFk2, Date criadoEm) {
		this.seq = seq;
		this.rapServidoresByRarPrrSerFk1 = rapServidoresByRarPrrSerFk1;
		this.rarCandidatoPrograma = rarCandidatoPrograma;
		this.rarCronogramaAvaliacoesByRarPrrCroFk1 = rarCronogramaAvaliacoesByRarPrrCroFk1;
		this.rarPrograma = rarPrograma;
		this.rarCronogramaAvaliacoesByRarPrrCroFk2 = rarCronogramaAvaliacoesByRarPrrCroFk2;
		this.criadoEm = criadoEm;
	}

	public RarPreceptorResidente(Integer seq, RapServidores rapServidoresByRarPrrSerFk3, RapServidores rapServidoresByRarPrrSerFk1,
			RarCandidatoPrograma rarCandidatoPrograma, RapServidores rapServidoresByRarPrrSerFk2,
			RarCronogramaAvaliacao rarCronogramaAvaliacoesByRarPrrCroFk1, RarPrograma rarPrograma,
			RarCronogramaAvaliacao rarCronogramaAvaliacoesByRarPrrCroFk2, Date dtInicio, Date dtFim, Date criadoEm, Date alteradoEm,
			Short ano, Set<RarNotaMedia> rarNotaMediaes, Set<RarItemAvaliacaoProf> rarItemAvaliacaoProfs) {
		this.seq = seq;
		this.rapServidoresByRarPrrSerFk3 = rapServidoresByRarPrrSerFk3;
		this.rapServidoresByRarPrrSerFk1 = rapServidoresByRarPrrSerFk1;
		this.rarCandidatoPrograma = rarCandidatoPrograma;
		this.rapServidoresByRarPrrSerFk2 = rapServidoresByRarPrrSerFk2;
		this.rarCronogramaAvaliacoesByRarPrrCroFk1 = rarCronogramaAvaliacoesByRarPrrCroFk1;
		this.rarPrograma = rarPrograma;
		this.rarCronogramaAvaliacoesByRarPrrCroFk2 = rarCronogramaAvaliacoesByRarPrrCroFk2;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
		this.criadoEm = criadoEm;
		this.alteradoEm = alteradoEm;
		this.ano = ano;
		this.rarNotaMediaes = rarNotaMediaes;
		this.rarItemAvaliacaoProfs = rarItemAvaliacaoProfs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "rarPrrSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA_ALTERADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_ALTERADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getRapServidoresByRarPrrSerFk3() {
		return this.rapServidoresByRarPrrSerFk3;
	}

	public void setRapServidoresByRarPrrSerFk3(RapServidores rapServidoresByRarPrrSerFk3) {
		this.rapServidoresByRarPrrSerFk3 = rapServidoresByRarPrrSerFk3;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidoresByRarPrrSerFk1() {
		return this.rapServidoresByRarPrrSerFk1;
	}

	public void setRapServidoresByRarPrrSerFk1(RapServidores rapServidoresByRarPrrSerFk1) {
		this.rapServidoresByRarPrrSerFk1 = rapServidoresByRarPrrSerFk1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "CPM_PGA_SEQ", referencedColumnName = "PGA_SEQ", nullable = false),
			@JoinColumn(name = "CPM_CND_SEQ", referencedColumnName = "CND_SEQ", nullable = false) })
	public RarCandidatoPrograma getRarCandidatoPrograma() {
		return this.rarCandidatoPrograma;
	}

	public void setRarCandidatoPrograma(RarCandidatoPrograma rarCandidatoPrograma) {
		this.rarCandidatoPrograma = rarCandidatoPrograma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA_CRIADO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_CRIADO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getRapServidoresByRarPrrSerFk2() {
		return this.rapServidoresByRarPrrSerFk2;
	}

	public void setRapServidoresByRarPrrSerFk2(RapServidores rapServidoresByRarPrrSerFk2) {
		this.rapServidoresByRarPrrSerFk2 = rapServidoresByRarPrrSerFk2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "CRO_AVA_SEQ_RESIDENTE", referencedColumnName = "AVA_SEQ", nullable = false),
			@JoinColumn(name = "CRO_SEQP_RESIDENTE", referencedColumnName = "SEQP", nullable = false) })
	public RarCronogramaAvaliacao getRarCronogramaAvaliacoesByRarPrrCroFk1() {
		return this.rarCronogramaAvaliacoesByRarPrrCroFk1;
	}

	public void setRarCronogramaAvaliacoesByRarPrrCroFk1(RarCronogramaAvaliacao rarCronogramaAvaliacoesByRarPrrCroFk1) {
		this.rarCronogramaAvaliacoesByRarPrrCroFk1 = rarCronogramaAvaliacoesByRarPrrCroFk1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CPM_PGA_SEQ", nullable = false, insertable = false, updatable = false)
	public RarPrograma getRarPrograma() {
		return this.rarPrograma;
	}

	public void setRarPrograma(RarPrograma rarPrograma) {
		this.rarPrograma = rarPrograma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "CRO_AVA_SEQ_PRECEPTOR", referencedColumnName = "AVA_SEQ", nullable = false),
			@JoinColumn(name = "CRO_SEQP_PRECEPTOR", referencedColumnName = "SEQP", nullable = false) })
	public RarCronogramaAvaliacao getRarCronogramaAvaliacoesByRarPrrCroFk2() {
		return this.rarCronogramaAvaliacoesByRarPrrCroFk2;
	}

	public void setRarCronogramaAvaliacoesByRarPrrCroFk2(RarCronogramaAvaliacao rarCronogramaAvaliacoesByRarPrrCroFk2) {
		this.rarCronogramaAvaliacoesByRarPrrCroFk2 = rarCronogramaAvaliacoesByRarPrrCroFk2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO", length = 29)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM", length = 29)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ALTERADO_EM", length = 29)
	public Date getAlteradoEm() {
		return this.alteradoEm;
	}

	public void setAlteradoEm(Date alteradoEm) {
		this.alteradoEm = alteradoEm;
	}

	@Column(name = "ANO")
	public Short getAno() {
		return this.ano;
	}

	public void setAno(Short ano) {
		this.ano = ano;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rarPreceptorResidente")
	public Set<RarNotaMedia> getRarNotaMediaes() {
		return this.rarNotaMediaes;
	}

	public void setRarNotaMediaes(Set<RarNotaMedia> rarNotaMediaes) {
		this.rarNotaMediaes = rarNotaMediaes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rarPreceptorResidente")
	public Set<RarItemAvaliacaoProf> getRarItemAvaliacaoProfs() {
		return this.rarItemAvaliacaoProfs;
	}

	public void setRarItemAvaliacaoProfs(Set<RarItemAvaliacaoProf> rarItemAvaliacaoProfs) {
		this.rarItemAvaliacaoProfs = rarItemAvaliacaoProfs;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		RAP_SERVIDORES_BY_RAR_PRR_SER_FK3("rapServidoresByRarPrrSerFk3"),
		RAP_SERVIDORES_BY_RAR_PRR_SER_FK1("rapServidoresByRarPrrSerFk1"),
		RAR_CANDIDATOS_PROGRAMA("rarCandidatoPrograma"),
		RAP_SERVIDORES_BY_RAR_PRR_SER_FK2("rapServidoresByRarPrrSerFk2"),
		RAR_CRONOGRAMA_AVALIACOES_BY_RAR_PRR_CRO_FK1("rarCronogramaAvaliacoesByRarPrrCroFk1"),
		RAR_PROGRAMAS("rarPrograma"),
		RAR_CRONOGRAMA_AVALIACOES_BY_RAR_PRR_CRO_FK2("rarCronogramaAvaliacoesByRarPrrCroFk2"),
		DT_INICIO("dtInicio"),
		DT_FIM("dtFim"),
		CRIADO_EM("criadoEm"),
		ALTERADO_EM("alteradoEm"),
		ANO("ano"),
		RAR_NOTA_MEDIAES("rarNotaMediaes"),
		RAR_ITEM_AVALIACAO_PROFS("rarItemAvaliacaoProfs");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RarPreceptorResidente)) {
			return false;
		}
		RarPreceptorResidente other = (RarPreceptorResidente) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
