package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * RarSubSecretariaId generated by hbm2java
 */
@Embeddable
public class RarSubSecretariaId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7319079027840852324L;
	private Integer chpPgaSeq;
	private Short chpSeqp;
	private Short serVinCodigo;
	private Integer serMatricula;

	public RarSubSecretariaId() {
	}

	public RarSubSecretariaId(Integer chpPgaSeq, Short chpSeqp, Short serVinCodigo, Integer serMatricula) {
		this.chpPgaSeq = chpPgaSeq;
		this.chpSeqp = chpSeqp;
		this.serVinCodigo = serVinCodigo;
		this.serMatricula = serMatricula;
	}

	@Column(name = "CHP_PGA_SEQ", nullable = false)
	public Integer getChpPgaSeq() {
		return this.chpPgaSeq;
	}

	public void setChpPgaSeq(Integer chpPgaSeq) {
		this.chpPgaSeq = chpPgaSeq;
	}

	@Column(name = "CHP_SEQP", nullable = false)
	public Short getChpSeqp() {
		return this.chpSeqp;
	}

	public void setChpSeqp(Short chpSeqp) {
		this.chpSeqp = chpSeqp;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getSerMatricula());
		umHashCodeBuilder.append(this.getSerVinCodigo());
		umHashCodeBuilder.append(this.getChpPgaSeq());
		umHashCodeBuilder.append(this.getChpSeqp());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RarSubSecretariaId)) {
			return false;
		}
		RarSubSecretariaId other = (RarSubSecretariaId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getSerMatricula(), other.getSerMatricula());
		umEqualsBuilder.append(this.getSerVinCodigo(), other.getSerVinCodigo());
		umEqualsBuilder.append(this.getChpPgaSeq(), other.getChpPgaSeq());
		umEqualsBuilder.append(this.getChpSeqp(), other.getChpSeqp());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
