package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * RarSubSecretaria generated by hbm2java
 */
@Entity
@Table(name = "RAR_SUBS_SECRETARIA", schema = "AGH")
public class RarSubSecretaria extends BaseEntityId<RarSubSecretariaId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7469032212849131743L;
	private RarSubSecretariaId id;
	private Integer version;
	private RarChefiaPrograma rarChefiaPrograma;
	private Date dtInicio;
	private Date dtFim;

	public RarSubSecretaria() {
	}

	public RarSubSecretaria(RarSubSecretariaId id, RarChefiaPrograma rarChefiaPrograma, Date dtInicio) {
		this.id = id;
		this.rarChefiaPrograma = rarChefiaPrograma;
		this.dtInicio = dtInicio;
	}

	public RarSubSecretaria(RarSubSecretariaId id, RarChefiaPrograma rarChefiaPrograma, Date dtInicio, Date dtFim) {
		this.id = id;
		this.rarChefiaPrograma = rarChefiaPrograma;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "chpPgaSeq", column = @Column(name = "CHP_PGA_SEQ", nullable = false)),
			@AttributeOverride(name = "chpSeqp", column = @Column(name = "CHP_SEQP", nullable = false)),
			@AttributeOverride(name = "serVinCodigo", column = @Column(name = "SER_VIN_CODIGO", nullable = false)),
			@AttributeOverride(name = "serMatricula", column = @Column(name = "SER_MATRICULA", nullable = false)) })
	public RarSubSecretariaId getId() {
		return this.id;
	}

	public void setId(RarSubSecretariaId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CHP_PGA_SEQ", referencedColumnName = "PGA_SEQ", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CHP_SEQP", referencedColumnName = "SEQP", nullable = false, insertable = false, updatable = false) })
	public RarChefiaPrograma getRarChefiaPrograma() {
		return this.rarChefiaPrograma;
	}

	public void setRarChefiaPrograma(RarChefiaPrograma rarChefiaPrograma) {
		this.rarChefiaPrograma = rarChefiaPrograma;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INICIO", nullable = false, length = 29)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_FIM", length = 29)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		RAR_CHEFIAS_PROGRAMA("rarChefiaPrograma"),
		DT_INICIO("dtInicio"),
		DT_FIM("dtFim");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RarSubSecretaria)) {
			return false;
		}
		RarSubSecretaria other = (RarSubSecretaria) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
