package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntitySeq;

/**
 * SceGrupoEnvioSiafi generated by hbm2java
 */
@Entity
@SequenceGenerator(name="sceGesiafiSq1", sequenceName="AGH.SCE_GESIAFI_SQ1", allocationSize = 1)
@Table(name = "SCE_GRUPO_ENVIO_SIAFI", schema = "AGH")
public class SceGrupoEnvioSiafi extends BaseEntitySeq<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9143430321550438864L;
	private Integer seq;
	private Integer version;
	private RapServidores rapServidores;
	private Date criadoEm;
	private Set<SceItemEnvioSiafi> sceItemEnvioSiafis = new HashSet<SceItemEnvioSiafi>(0);

	public SceGrupoEnvioSiafi() {
	}

	public SceGrupoEnvioSiafi(Integer seq, RapServidores rapServidores, Date criadoEm) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.criadoEm = criadoEm;
	}

	public SceGrupoEnvioSiafi(Integer seq, RapServidores rapServidores, Date criadoEm, Set<SceItemEnvioSiafi> sceItemEnvioSiafis) {
		this.seq = seq;
		this.rapServidores = rapServidores;
		this.criadoEm = criadoEm;
		this.sceItemEnvioSiafis = sceItemEnvioSiafis;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "sceGesiafiSq1")
	@Column(name = "SEQ", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "SER_MATRICULA", referencedColumnName = "MATRICULA", nullable = false),
			@JoinColumn(name = "SER_VIN_CODIGO", referencedColumnName = "VIN_CODIGO", nullable = false) })
	public RapServidores getRapServidores() {
		return this.rapServidores;
	}

	public void setRapServidores(RapServidores rapServidores) {
		this.rapServidores = rapServidores;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRIADO_EM", nullable = false, length = 29)
	public Date getCriadoEm() {
		return this.criadoEm;
	}

	public void setCriadoEm(Date criadoEm) {
		this.criadoEm = criadoEm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sceGrupoEnvioSiafi")
	public Set<SceItemEnvioSiafi> getSceItemEnvioSiafis() {
		return this.sceItemEnvioSiafis;
	}

	public void setSceItemEnvioSiafis(Set<SceItemEnvioSiafi> sceItemEnvioSiafis) {
		this.sceItemEnvioSiafis = sceItemEnvioSiafis;
	}

	public enum Fields {

		SEQ("seq"),
		VERSION("version"),
		RAP_SERVIDORES("rapServidores"),
		CRIADO_EM("criadoEm"),
		SCE_ITEM_ENVIO_SIAFIS("sceItemEnvioSiafis");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof SceGrupoEnvioSiafi)) {
			return false;
		}
		SceGrupoEnvioSiafi other = (SceGrupoEnvioSiafi) obj;
		if (getSeq() == null) {
			if (other.getSeq() != null) {
				return false;
			}
		} else if (!getSeq().equals(other.getSeq())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
