package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * SceMovimentoMaterialBull generated by hbm2java
 */
@Entity
@Table(name = "SCE_MOVIMENTO_MATERIAIS_BULL", schema = "AGH")
public class SceMovimentoMaterialBull extends BaseEntityId<SceMovimentoMaterialBullId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5507274922015256816L;
	private SceMovimentoMaterialBullId id;
	private Integer version;
	private Date dtGeracao;
	private Integer serMatricula;
	private Short serVinCodigo;
	private Short almSeq;
	private Integer matCodigo;
	private String umdCodigo;
	private Integer quantidade;
	private String indEstorno;
	private Short tmvSeq;
	private Short tmvComplemento;
	private Short tmvSeqDocumento;
	private Short tmvComplementoDocumento;
	private Integer nroDocGeracao;
	private Short itemDocGeracao;
	private Integer qtdeRequisitada;
	private String historico;
	private Integer frnNumero;
	private Integer cctCodigoRequisita;
	private Integer cctCodigo;
	private Short almSeqComplemento;
	private Integer qtdePosMovimento;
	private Double custoMedioPonderadoGer;
	private Double valor;
	private Double residuo;
	private Short mtvTmvSeq;
	private Short mtvTmvComplemento;
	private Short mtvNumero;
	private Integer nroDocRefere;
	private Integer frnNumeroRefereDoc;

	public SceMovimentoMaterialBull() {
	}

	public SceMovimentoMaterialBull(SceMovimentoMaterialBullId id, Date dtGeracao, Integer serMatricula, Short serVinCodigo,
			Short almSeq, Integer matCodigo, String umdCodigo, Integer quantidade, Short tmvSeq, Short tmvComplemento) {
		this.id = id;
		this.dtGeracao = dtGeracao;
		this.serMatricula = serMatricula;
		this.serVinCodigo = serVinCodigo;
		this.almSeq = almSeq;
		this.matCodigo = matCodigo;
		this.umdCodigo = umdCodigo;
		this.quantidade = quantidade;
		this.tmvSeq = tmvSeq;
		this.tmvComplemento = tmvComplemento;
	}
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false)),
			@AttributeOverride(name = "dtCompetencia", column = @Column(name = "DT_COMPETENCIA", nullable = false, length = 29)) })
	public SceMovimentoMaterialBullId getId() {
		return this.id;
	}

	public void setId(SceMovimentoMaterialBullId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_GERACAO", nullable = false, length = 29)
	public Date getDtGeracao() {
		return this.dtGeracao;
	}

	public void setDtGeracao(Date dtGeracao) {
		this.dtGeracao = dtGeracao;
	}

	@Column(name = "SER_MATRICULA", nullable = false)
	public Integer getSerMatricula() {
		return this.serMatricula;
	}

	public void setSerMatricula(Integer serMatricula) {
		this.serMatricula = serMatricula;
	}

	@Column(name = "SER_VIN_CODIGO", nullable = false)
	public Short getSerVinCodigo() {
		return this.serVinCodigo;
	}

	public void setSerVinCodigo(Short serVinCodigo) {
		this.serVinCodigo = serVinCodigo;
	}

	@Column(name = "ALM_SEQ", nullable = false)
	public Short getAlmSeq() {
		return this.almSeq;
	}

	public void setAlmSeq(Short almSeq) {
		this.almSeq = almSeq;
	}

	@Column(name = "MAT_CODIGO", nullable = false)
	public Integer getMatCodigo() {
		return this.matCodigo;
	}

	public void setMatCodigo(Integer matCodigo) {
		this.matCodigo = matCodigo;
	}

	@Column(name = "UMD_CODIGO", nullable = false, length = 3)
	@Length(max = 3)
	public String getUmdCodigo() {
		return this.umdCodigo;
	}

	public void setUmdCodigo(String umdCodigo) {
		this.umdCodigo = umdCodigo;
	}

	@Column(name = "QUANTIDADE", nullable = false)
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "IND_ESTORNO", length = 1)
	@Length(max = 1)
	public String getIndEstorno() {
		return this.indEstorno;
	}

	public void setIndEstorno(String indEstorno) {
		this.indEstorno = indEstorno;
	}

	@Column(name = "TMV_SEQ", nullable = false)
	public Short getTmvSeq() {
		return this.tmvSeq;
	}

	public void setTmvSeq(Short tmvSeq) {
		this.tmvSeq = tmvSeq;
	}

	@Column(name = "TMV_COMPLEMENTO", nullable = false)
	public Short getTmvComplemento() {
		return this.tmvComplemento;
	}

	public void setTmvComplemento(Short tmvComplemento) {
		this.tmvComplemento = tmvComplemento;
	}

	@Column(name = "TMV_SEQ_DOCUMENTO")
	public Short getTmvSeqDocumento() {
		return this.tmvSeqDocumento;
	}

	public void setTmvSeqDocumento(Short tmvSeqDocumento) {
		this.tmvSeqDocumento = tmvSeqDocumento;
	}

	@Column(name = "TMV_COMPLEMENTO_DOCUMENTO")
	public Short getTmvComplementoDocumento() {
		return this.tmvComplementoDocumento;
	}

	public void setTmvComplementoDocumento(Short tmvComplementoDocumento) {
		this.tmvComplementoDocumento = tmvComplementoDocumento;
	}

	@Column(name = "NRO_DOC_GERACAO")
	public Integer getNroDocGeracao() {
		return this.nroDocGeracao;
	}

	public void setNroDocGeracao(Integer nroDocGeracao) {
		this.nroDocGeracao = nroDocGeracao;
	}

	@Column(name = "ITEM_DOC_GERACAO")
	public Short getItemDocGeracao() {
		return this.itemDocGeracao;
	}

	public void setItemDocGeracao(Short itemDocGeracao) {
		this.itemDocGeracao = itemDocGeracao;
	}

	@Column(name = "QTDE_REQUISITADA")
	public Integer getQtdeRequisitada() {
		return this.qtdeRequisitada;
	}

	public void setQtdeRequisitada(Integer qtdeRequisitada) {
		this.qtdeRequisitada = qtdeRequisitada;
	}

	@Column(name = "HISTORICO", length = 240)
	@Length(max = 240)
	public String getHistorico() {
		return this.historico;
	}

	public void setHistorico(String historico) {
		this.historico = historico;
	}

	@Column(name = "FRN_NUMERO")
	public Integer getFrnNumero() {
		return this.frnNumero;
	}

	public void setFrnNumero(Integer frnNumero) {
		this.frnNumero = frnNumero;
	}

	@Column(name = "CCT_CODIGO_REQUISITA")
	public Integer getCctCodigoRequisita() {
		return this.cctCodigoRequisita;
	}

	public void setCctCodigoRequisita(Integer cctCodigoRequisita) {
		this.cctCodigoRequisita = cctCodigoRequisita;
	}

	@Column(name = "CCT_CODIGO")
	public Integer getCctCodigo() {
		return this.cctCodigo;
	}

	public void setCctCodigo(Integer cctCodigo) {
		this.cctCodigo = cctCodigo;
	}

	@Column(name = "ALM_SEQ_COMPLEMENTO")
	public Short getAlmSeqComplemento() {
		return this.almSeqComplemento;
	}

	public void setAlmSeqComplemento(Short almSeqComplemento) {
		this.almSeqComplemento = almSeqComplemento;
	}

	@Column(name = "QTDE_POS_MOVIMENTO")
	public Integer getQtdePosMovimento() {
		return this.qtdePosMovimento;
	}

	public void setQtdePosMovimento(Integer qtdePosMovimento) {
		this.qtdePosMovimento = qtdePosMovimento;
	}

	@Column(name = "CUSTO_MEDIO_PONDERADO_GER", precision = 17, scale = 17)
	public Double getCustoMedioPonderadoGer() {
		return this.custoMedioPonderadoGer;
	}

	public void setCustoMedioPonderadoGer(Double custoMedioPonderadoGer) {
		this.custoMedioPonderadoGer = custoMedioPonderadoGer;
	}

	@Column(name = "VALOR", precision = 17, scale = 17)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	@Column(name = "RESIDUO", precision = 17, scale = 17)
	public Double getResiduo() {
		return this.residuo;
	}

	public void setResiduo(Double residuo) {
		this.residuo = residuo;
	}

	@Column(name = "MTV_TMV_SEQ")
	public Short getMtvTmvSeq() {
		return this.mtvTmvSeq;
	}

	public void setMtvTmvSeq(Short mtvTmvSeq) {
		this.mtvTmvSeq = mtvTmvSeq;
	}

	@Column(name = "MTV_TMV_COMPLEMENTO")
	public Short getMtvTmvComplemento() {
		return this.mtvTmvComplemento;
	}

	public void setMtvTmvComplemento(Short mtvTmvComplemento) {
		this.mtvTmvComplemento = mtvTmvComplemento;
	}

	@Column(name = "MTV_NUMERO")
	public Short getMtvNumero() {
		return this.mtvNumero;
	}

	public void setMtvNumero(Short mtvNumero) {
		this.mtvNumero = mtvNumero;
	}

	@Column(name = "NRO_DOC_REFERE")
	public Integer getNroDocRefere() {
		return this.nroDocRefere;
	}

	public void setNroDocRefere(Integer nroDocRefere) {
		this.nroDocRefere = nroDocRefere;
	}

	@Column(name = "FRN_NUMERO_REFERE_DOC")
	public Integer getFrnNumeroRefereDoc() {
		return this.frnNumeroRefereDoc;
	}

	public void setFrnNumeroRefereDoc(Integer frnNumeroRefereDoc) {
		this.frnNumeroRefereDoc = frnNumeroRefereDoc;
	}

	public enum Fields {

		ID("id"),
		VERSION("version"),
		DT_GERACAO("dtGeracao"),
		SER_MATRICULA("serMatricula"),
		SER_VIN_CODIGO("serVinCodigo"),
		ALM_SEQ("almSeq"),
		MAT_CODIGO("matCodigo"),
		UMD_CODIGO("umdCodigo"),
		QUANTIDADE("quantidade"),
		IND_ESTORNO("indEstorno"),
		TMV_SEQ("tmvSeq"),
		TMV_COMPLEMENTO("tmvComplemento"),
		TMV_SEQ_DOCUMENTO("tmvSeqDocumento"),
		TMV_COMPLEMENTO_DOCUMENTO("tmvComplementoDocumento"),
		NRO_DOC_GERACAO("nroDocGeracao"),
		ITEM_DOC_GERACAO("itemDocGeracao"),
		QTDE_REQUISITADA("qtdeRequisitada"),
		HISTORICO("historico"),
		FRN_NUMERO("frnNumero"),
		CCT_CODIGO_REQUISITA("cctCodigoRequisita"),
		CCT_CODIGO("cctCodigo"),
		ALM_SEQ_COMPLEMENTO("almSeqComplemento"),
		QTDE_POS_MOVIMENTO("qtdePosMovimento"),
		CUSTO_MEDIO_PONDERADO_GER("custoMedioPonderadoGer"),
		VALOR("valor"),
		RESIDUO("residuo"),
		MTV_TMV_SEQ("mtvTmvSeq"),
		MTV_TMV_COMPLEMENTO("mtvTmvComplemento"),
		MTV_NUMERO("mtvNumero"),
		NRO_DOC_REFERE("nroDocRefere"),
		FRN_NUMERO_REFERE_DOC("frnNumeroRefereDoc");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof SceMovimentoMaterialBull)) {
			return false;
		}
		SceMovimentoMaterialBull other = (SceMovimentoMaterialBull) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
