package br.gov.mec.aghu.model;

// Generated 21/09/2011 17:21:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioIndMovimento;
import br.gov.mec.aghu.dominio.DominioIndOperacaoBasica;
import br.gov.mec.aghu.dominio.DominioIndUsoCm;
import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * SceTipoMovimentos generated by hbm2java
 */

@Entity
@Table(name = "SCE_TIPO_MOVIMENTOS", schema = "AGH")
public class SceTipoMovimento extends BaseEntityId<SceTipoMovimentoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 750366749611647267L;
	private SceTipoMovimentoId id;
	private SceTipoMovimento tipoMovimento;
	private SceTipoMovimento tipoMovimentoProximo;
	private String descricao;
	private DominioIndMovimento indMovimento;
	private DominioSituacao indSituacao;
	private Boolean indAlteraAf;
	private String indGeraTitulo;
	private Boolean indExigeMotivo;
	private DominioIndOperacaoBasica indQtdeDisponivel;
	private DominioIndOperacaoBasica indQtdeBloqueada;
	private DominioIndUsoCm indUsoCm;
	private Boolean indUsoResiduo;
	private Boolean indAltValrEstqAlmoxMvto;
	private Boolean indGuardaQtdePosMvto;
	private Boolean indCcustoRequisita;
	private Boolean indCcustoAplica;
	private Boolean indFornecedorProp;
	private Boolean indNroDocGeracao;
	private Boolean indAlmox;
	private String indGuardaValor;
	private String indGuardaCmGerado;
	private Boolean indAltValrEstqGeral;
	private Boolean indAlmoxComplemento;
	private DominioIndOperacaoBasica indQtdeBloqProblema;
	private Boolean indGuardaHistorico;
	private Boolean indDependeCaract;
	private DominioIndOperacaoBasica indOperacaoBasica;
	private String indGuardaResiduoUtlz;
	private String indGuardaResiduoGer;
	private DominioIndOperacaoBasica indQtdeEntradaValid;
	private DominioIndOperacaoBasica indQtdeConsumoValid;
	private DominioIndOperacaoBasica indQtdeDisponivelValid;
	private Boolean indDocumentoValidade;
	private Boolean movimentoConsumo;
	private Boolean indUsaQtdeDisponivel;
	private Boolean indAltQtdeEstqAlmoxMvto;
	private Boolean indGeraRegMovimento;
	private Boolean indTrataDevolucao;
	private String sigla;
	private String indBloqueioUso;
	private Byte ordem;
	private String indMovimentoEmpr;
	private Integer version;
	private Boolean indEsl; 


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "complemento", column = @Column(name = "COMPLEMENTO", nullable = false, precision = 2, scale = 0)) })
	public SceTipoMovimentoId getId() {
		return this.id;
	}

	public void setId(SceTipoMovimentoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "TMV_SEQ", referencedColumnName = "SEQ"),
			@JoinColumn(name = "TMV_COMPLEMENTO", referencedColumnName = "COMPLEMENTO") })
	public SceTipoMovimento getTipoMovimento() {
		return tipoMovimento;
	}

	public void setTipoMovimento(SceTipoMovimento tipoMovimento) {
		this.tipoMovimento = tipoMovimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "TMV_SEQ_PROXIMO", referencedColumnName = "SEQ"),
			@JoinColumn(name = "TMV_COMPLEMENTO_PROXIMO", referencedColumnName = "COMPLEMENTO") })
	public SceTipoMovimento getTipoMovimentoProximo() {
		return tipoMovimentoProximo;
	}

	public void setTipoMovimentoProximo(SceTipoMovimento tipoMovimentoProximo) {
		this.tipoMovimentoProximo = tipoMovimentoProximo;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_MOVIMENTO", nullable = false, length = 3)
	@Enumerated(EnumType.STRING)
	public DominioIndMovimento getIndMovimento() {
		return this.indMovimento;
	}

	public void setIndMovimento(DominioIndMovimento indMovimento) {
		this.indMovimento = indMovimento;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Transient
	public boolean isAtivo() {
		return this.indSituacao.isAtivo();
	}

	public void setAtivo(boolean ativo) {
		this.indSituacao = DominioSituacao.getInstance(ativo);
	}
	
	@Column(name = "IND_ALTERA_AF", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAlteraAf() {
		return this.indAlteraAf;
	}

	public void setIndAlteraAf(Boolean indAlteraAf) {
		this.indAlteraAf = indAlteraAf;
	}

	@Column(name = "IND_GERA_TITULO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndGeraTitulo() {
		return this.indGeraTitulo;
	}

	public void setIndGeraTitulo(String indGeraTitulo) {
		this.indGeraTitulo = indGeraTitulo;
	}

	@Column(name = "IND_EXIGE_MOTIVO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndExigeMotivo() {
		return this.indExigeMotivo;
	}

	public void setIndExigeMotivo(Boolean indExigeMotivo) {
		this.indExigeMotivo = indExigeMotivo;
	}

	@Column(name = "IND_QTDE_DISPONIVEL", nullable = false, length = 2)
	@Enumerated(EnumType.STRING)
	public DominioIndOperacaoBasica getIndQtdeDisponivel() {
		return this.indQtdeDisponivel;
	}

	public void setIndQtdeDisponivel(DominioIndOperacaoBasica indQtdeDisponivel) {
		this.indQtdeDisponivel = indQtdeDisponivel;
	}

	@Column(name = "IND_QTDE_BLOQUEADA", nullable = false, length = 2)
	@Enumerated(EnumType.STRING)
	public DominioIndOperacaoBasica getIndQtdeBloqueada() {
		return this.indQtdeBloqueada;
	}

	public void setIndQtdeBloqueada(DominioIndOperacaoBasica indQtdeBloqueada) {
		this.indQtdeBloqueada = indQtdeBloqueada;
	}

	@Column(name = "IND_USO_CM", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioIndUsoCm getIndUsoCm() {
		return this.indUsoCm;
	}

	public void setIndUsoCm(DominioIndUsoCm indUsoCm) {
		this.indUsoCm = indUsoCm;
	}

	@Column(name = "IND_USO_RESIDUO", nullable = false)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndUsoResiduo() {
		return this.indUsoResiduo;
	}

	public void setIndUsoResiduo(Boolean indUsoResiduo) {
		this.indUsoResiduo = indUsoResiduo;
	}

	@Column(name = "IND_ALT_VALR_ESTQ_ALMOX_MVTO", nullable = false)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAltValrEstqAlmoxMvto() {
		return this.indAltValrEstqAlmoxMvto;
	}

	public void setIndAltValrEstqAlmoxMvto(Boolean indAltValrEstqAlmoxMvto) {
		this.indAltValrEstqAlmoxMvto = indAltValrEstqAlmoxMvto;
	}

	@Column(name = "IND_GUARDA_QTDE_POS_MVTO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndGuardaQtdePosMvto() {
		return this.indGuardaQtdePosMvto;
	}

	public void setIndGuardaQtdePosMvto(Boolean indGuardaQtdePosMvto) {
		this.indGuardaQtdePosMvto = indGuardaQtdePosMvto;
	}

	@Column(name = "IND_CCUSTO_REQUISITA", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndCcustoRequisita() {
		return this.indCcustoRequisita;
	}

	public void setIndCcustoRequisita(Boolean indCcustoRequisita) {
		this.indCcustoRequisita = indCcustoRequisita;
	}

	@Column(name = "IND_CCUSTO_APLICA", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndCcustoAplica() {
		return this.indCcustoAplica;
	}

	public void setIndCcustoAplica(Boolean indCcustoAplica) {
		this.indCcustoAplica = indCcustoAplica;
	}

	@Column(name = "IND_FORNECEDOR_PROP", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndFornecedorProp() {
		return this.indFornecedorProp;
	}

	public void setIndFornecedorProp(Boolean indFornecedorProp) {
		this.indFornecedorProp = indFornecedorProp;
	}

	@Column(name = "IND_NRO_DOC_GERACAO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndNroDocGeracao() {
		return this.indNroDocGeracao;
	}

	public void setIndNroDocGeracao(Boolean indNroDocGeracao) {
		this.indNroDocGeracao = indNroDocGeracao;
	}

	@Column(name = "IND_ALMOX", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAlmox() {
		return this.indAlmox;
	}

	public void setIndAlmox(Boolean indAlmox) {
		this.indAlmox = indAlmox;
	}

	@Column(name = "IND_GUARDA_VALOR", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndGuardaValor() {
		return this.indGuardaValor;
	}

	public void setIndGuardaValor(String indGuardaValor) {
		this.indGuardaValor = indGuardaValor;
	}

	@Column(name = "IND_GUARDA_CM_GERADO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndGuardaCmGerado() {
		return this.indGuardaCmGerado;
	}

	public void setIndGuardaCmGerado(String indGuardaCmGerado) {
		this.indGuardaCmGerado = indGuardaCmGerado;
	}

	@Column(name = "IND_ALT_VALR_ESTQ_GERAL", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAltValrEstqGeral() {
		return this.indAltValrEstqGeral;
	}

	public void setIndAltValrEstqGeral(Boolean indAltValrEstqGeral) {
		this.indAltValrEstqGeral = indAltValrEstqGeral;
	}

	@Column(name = "IND_ALMOX_COMPLEMENTO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAlmoxComplemento() {
		return this.indAlmoxComplemento;
	}

	public void setIndAlmoxComplemento(Boolean indAlmoxComplemento) {
		this.indAlmoxComplemento = indAlmoxComplemento;
	}

	@Column(name = "IND_QTDE_BLOQ_PROBLEMA", nullable = false, length = 2)
	@Enumerated(EnumType.STRING)
	public DominioIndOperacaoBasica getIndQtdeBloqProblema() {
		return this.indQtdeBloqProblema;
	}

	public void setIndQtdeBloqProblema(DominioIndOperacaoBasica indQtdeBloqProblema) {
		this.indQtdeBloqProblema = indQtdeBloqProblema;
	}

	@Column(name = "IND_GUARDA_HISTORICO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndGuardaHistorico() {
		return this.indGuardaHistorico;
	}

	public void setIndGuardaHistorico(Boolean indGuardaHistorico) {
		this.indGuardaHistorico = indGuardaHistorico;
	}

	@Column(name = "IND_DEPENDE_CARACT", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndDependeCaract() {
		return this.indDependeCaract;
	}

	public void setIndDependeCaract(Boolean indDependeCaract) {
		this.indDependeCaract = indDependeCaract;
	}

	@Column(name = "IND_OPERACAO_BASICA", nullable = false, length = 2)
	@Enumerated(EnumType.STRING)
	public DominioIndOperacaoBasica getIndOperacaoBasica() {
		return this.indOperacaoBasica;
	}

	public void setIndOperacaoBasica(DominioIndOperacaoBasica indOperacaoBasica) {
		this.indOperacaoBasica = indOperacaoBasica;
	}

	@Column(name = "IND_GUARDA_RESIDUO_UTLZ", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndGuardaResiduoUtlz() {
		return this.indGuardaResiduoUtlz;
	}

	public void setIndGuardaResiduoUtlz(String indGuardaResiduoUtlz) {
		this.indGuardaResiduoUtlz = indGuardaResiduoUtlz;
	}

	@Column(name = "IND_GUARDA_RESIDUO_GER", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndGuardaResiduoGer() {
		return this.indGuardaResiduoGer;
	}

	public void setIndGuardaResiduoGer(String indGuardaResiduoGer) {
		this.indGuardaResiduoGer = indGuardaResiduoGer;
	}

	@Column(name = "IND_QTDE_ENTRADA_VALID", nullable = false, length = 2)
	@Enumerated(EnumType.STRING)
	public DominioIndOperacaoBasica getIndQtdeEntradaValid() {
		return this.indQtdeEntradaValid;
	}

	public void setIndQtdeEntradaValid(DominioIndOperacaoBasica indQtdeEntradaValid) {
		this.indQtdeEntradaValid = indQtdeEntradaValid;
	}

	@Column(name = "IND_QTDE_CONSUMO_VALID", nullable = false, length = 2)
	@Enumerated(EnumType.STRING)
	public DominioIndOperacaoBasica getIndQtdeConsumoValid() {
		return this.indQtdeConsumoValid;
	}

	public void setIndQtdeConsumoValid(DominioIndOperacaoBasica indQtdeConsumoValid) {
		this.indQtdeConsumoValid = indQtdeConsumoValid;
	}

	@Column(name = "IND_QTDE_DISPONIVEL_VALID", nullable = false, length = 2)
	@Enumerated(EnumType.STRING)
	public DominioIndOperacaoBasica getIndQtdeDisponivelValid() {
		return this.indQtdeDisponivelValid;
	}

	public void setIndQtdeDisponivelValid(DominioIndOperacaoBasica indQtdeDisponivelValid) {
		this.indQtdeDisponivelValid = indQtdeDisponivelValid;
	}

	@Column(name = "IND_DOCUMENTO_VALIDADE", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndDocumentoValidade() {
		return this.indDocumentoValidade;
	}

	public void setIndDocumentoValidade(Boolean indDocumentoValidade) {
		this.indDocumentoValidade = indDocumentoValidade;
	}

	@Column(name = "IND_MOVIMENTO_CONSUMO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getMovimentoConsumo() {
		return this.movimentoConsumo;
	}

	public void setMovimentoConsumo(Boolean indMovimentoConsumo) {
		this.movimentoConsumo = indMovimentoConsumo;
	}

	@Column(name = "IND_USA_QTDE_DISPONIVEL", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndUsaQtdeDisponivel() {
		return this.indUsaQtdeDisponivel;
	}

	public void setIndUsaQtdeDisponivel(Boolean indUsaQtdeDisponivel) {
		this.indUsaQtdeDisponivel = indUsaQtdeDisponivel;
	}

	@Column(name = "IND_ALT_QTDE_ESTQ_ALMOX_MVTO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndAltQtdeEstqAlmoxMvto() {
		return this.indAltQtdeEstqAlmoxMvto;
	}

	public void setIndAltQtdeEstqAlmoxMvto(Boolean indAltQtdeEstqAlmoxMvto) {
		this.indAltQtdeEstqAlmoxMvto = indAltQtdeEstqAlmoxMvto;
	}

	@Column(name = "IND_GERA_REG_MOVIMENTO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndGeraRegMovimento() {
		return this.indGeraRegMovimento;
	}

	public void setIndGeraRegMovimento(Boolean indGeraRegMovimento) {
		this.indGeraRegMovimento = indGeraRegMovimento;
	}

	@Column(name = "IND_TRATA_DEVOLUCAO", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndTrataDevolucao() {
		return this.indTrataDevolucao;
	}

	public void setIndTrataDevolucao(Boolean indTrataDevolucao) {
		this.indTrataDevolucao = indTrataDevolucao;
	}

	@Column(name = "SIGLA", nullable = false, length = 5)
	@Length(max = 5)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "IND_BLOQUEIO_USO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndBloqueioUso() {
		return this.indBloqueioUso;
	}

	public void setIndBloqueioUso(String indBloqueioUso) {
		this.indBloqueioUso = indBloqueioUso;
	}

	@Column(name = "ORDEM", precision = 2, scale = 0)
	public Byte getOrdem() {
		return this.ordem;
	}

	public void setOrdem(Byte ordem) {
		this.ordem = ordem;
	}

	@Column(name = "IND_MOVIMENTO_EMPR", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndMovimentoEmpr() {
		return this.indMovimentoEmpr;
	}

	public void setIndMovimentoEmpr(String indMovimentoEmpr) {
		this.indMovimentoEmpr = indMovimentoEmpr;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return version;
	}
	
	public void setVersion(Integer version) {
		this.version = version;
	}
	
	@Column(name = "IND_ESL", nullable = false, length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndEsl() {
		return indEsl;
	}

	public void setIndEsl(Boolean indEsl) {
		this.indEsl = indEsl;
	}

	@Override
	public boolean equals(Object other) {
		if (!(other instanceof SceTipoMovimento)){
			return false;
		}
		SceTipoMovimento castOther = (SceTipoMovimento) other;
		return new EqualsBuilder().append(this.getId().getSeq(), castOther.getId().getSeq())
				.isEquals() && new EqualsBuilder().append(this.getId().getComplemento(), castOther.getId().getComplemento())
				.isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.getId().getSeq()).append(this.getId().getComplemento()).toHashCode();
	}
	
	public enum Fields {
		ID("id"),
		SEQ("id.seq"),
		COMPLEMENTO("id.complemento"),
		DESCRICAO("descricao"),
		IND_SITUACAO("indSituacao"),
		IND_OPERACAO_BASICA("indOperacaoBasica"),
		IND_MOVIMENTO_CONSUMO("movimentoConsumo"),
		SIGLA("sigla"),
		SITUACAO("indSituacao"),
		IND_EXIGE_MOTIVO("indExigeMotivo"),
		ORDEM("ordem"),
		IND_MOVIMENTO("indMovimento"),
		IND_BLOQUEIO_USO("indBloqueioUso"),
		IND_TRATA_DEVOLUCAO("indTrataDevolucao"),
		TIPO_MOVIMENTO_SEQ("tipoMovimento.id.seq"),
		TIPO_MOVIMENTO_COMPLEMENTO("tipoMovimento.id.complemento"),
		TIPO_MOVIMENTO_SIGLA("tipoMovimento.sigla"),
		TIPO_MOVIMENTO_PROXIMO_SEQ("tipoMovimentoProximo.id.seq"),
		TIPO_MOVIMENTO_PROXIMO_COMPLEMENTO("tipoMovimentoProximo.id.complemento"),
		IND_ESL("indEsl");
		

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
		
	}

}
