package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * ScoExcMaterialTributacaoId generated by hbm2java
 */
@Embeddable
public class ScoExcMaterialTributacaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3461020753059921543L;
	private Integer matCodigo;
	private String classificacao;

	public ScoExcMaterialTributacaoId() {
	}

	public ScoExcMaterialTributacaoId(Integer matCodigo, String classificacao) {
		this.matCodigo = matCodigo;
		this.classificacao = classificacao;
	}

	@Column(name = "MAT_CODIGO", nullable = false)
	public Integer getMatCodigo() {
		return this.matCodigo;
	}

	public void setMatCodigo(Integer matCodigo) {
		this.matCodigo = matCodigo;
	}

	@Column(name = "CLASSIFICACAO", nullable = false, length = 1)
	@Length(max = 1)
	public String getClassificacao() {
		return this.classificacao;
	}

	public void setClassificacao(String classificacao) {
		this.classificacao = classificacao;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getMatCodigo());
		umHashCodeBuilder.append(this.getClassificacao());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ScoExcMaterialTributacaoId)) {
			return false;
		}
		ScoExcMaterialTributacaoId other = (ScoExcMaterialTributacaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getMatCodigo(), other.getMatCodigo());
		umEqualsBuilder.append(this.getClassificacao(), other.getClassificacao());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
