package br.gov.mec.aghu.model;

// Generated 04/01/2012 11:23:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioParecer;
import br.gov.mec.aghu.core.persistence.BaseEntityCodigo;


/**
 * ScoParecer Avaliacao  generated by hbm2java
 */
@Entity
@Table(name = "SCO_PARECER_AVALIACAO", schema = "AGH")
@SequenceGenerator(name="scoPavSq1", sequenceName="AGH.SCO_PAV_SQ1", allocationSize = 1)
public class ScoParecerAvaliacao extends BaseEntityCodigo<Integer> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2928349960562918139L;
		
		
	private Integer codigo;
	private ScoParecerMaterial parecerMaterial; 
	private String lote;
	private DominioParecer parecerGeral;
	private Date dtCriacao;
	private RapServidores servidorCriacao;
	private Date dtAlteracao;
	private RapServidores servidorAlteracao;	
	private Integer version;	
	private List<ScoParecerAvalTecnica> avaliacoesTecnicas;
	private List<ScoParecerAvalConsul> avaliacoesConsultoria;
	private List<ScoParecerAvalDesemp> avaliacoesDesempenho;
	
	public ScoParecerAvaliacao() {
	}

	@Id
	@Column(name = "CODIGO", nullable = false, precision = 6, scale = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "scoPavSq1")
	public Integer getCodigo() {
		return codigo;
	}
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PMT_CODIGO", referencedColumnName = "CODIGO")
	public ScoParecerMaterial getParecerMaterial() {
		return parecerMaterial;
	}

	public void setParecerMaterial(ScoParecerMaterial parecerMaterial) {
		this.parecerMaterial = parecerMaterial;
	}

	@Column(name = "LOTE", length = 20)
	@Length(max = 20)
	public String getLote() {
		return lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@Column(name = "PARECER_GERAL", length = 2, nullable = false)
	@Enumerated(EnumType.STRING)
	public DominioParecer getParecerGeral() {
		return parecerGeral;
	}

	public void setParecerGeral(DominioParecer parecerGeral) {
		this.parecerGeral = parecerGeral;
	}	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_CRIACAO", length = 7)
	public Date getDtCriacao() {
		return dtCriacao;
	}

	public void setDtCriacao(Date dtCriacao) {
		this.dtCriacao = dtCriacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SER_MATRICULA_CRIACAO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_CRIACAO", referencedColumnName = "VIN_CODIGO") })
	public RapServidores getServidorCriacao() {
		return servidorCriacao;
	}

	public void setServidorCriacao(RapServidores servidorCriacao) {
		this.servidorCriacao = servidorCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_ALTERACAO", length = 7)	
	public Date getDtAlteracao() {
		return dtAlteracao;
	}

	public void setDtAlteracao(Date dtAlteracao) {
		this.dtAlteracao = dtAlteracao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SER_MATRICULA_ALTERACAO", referencedColumnName = "MATRICULA"),
			@JoinColumn(name = "SER_VIN_CODIGO_ALTERACAO", referencedColumnName = "VIN_CODIGO") })	
	public RapServidores getServidorAlteracao() {
		return servidorAlteracao;
	}

	public void setServidorAlteracao(RapServidores servidorAlteracao) {
		this.servidorAlteracao = servidorAlteracao;
	}
	
	@Column(name = "VERSION", nullable = false)
	@Version
	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parecerAvaliacao")
	public List<ScoParecerAvalTecnica> getAvaliacoesTecnicas() {
		return avaliacoesTecnicas;
	}

	public void setAvaliacoesTecnicas(List<ScoParecerAvalTecnica> avaliacoesTecnicas) {
		this.avaliacoesTecnicas = avaliacoesTecnicas;
	}
    
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parecerAvaliacao")
	public List<ScoParecerAvalConsul> getAvaliacoesConsultoria() {
		return avaliacoesConsultoria;
	}

	public void setAvaliacoesConsultoria(
			List<ScoParecerAvalConsul> avaliacoesConsultoria) {
		this.avaliacoesConsultoria = avaliacoesConsultoria;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parecerAvaliacao")
	public List<ScoParecerAvalDesemp> getAvaliacoesDesempenho() {
		return avaliacoesDesempenho;
	}

	public void setAvaliacoesDesempenho(
			List<ScoParecerAvalDesemp> avaliacoesDesempenho) {
		this.avaliacoesDesempenho = avaliacoesDesempenho;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codigo == null) ? 0 : codigo.hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object other) {
		if (other instanceof ScoParecerAvaliacao){
			ScoParecerAvaliacao castOther = (ScoParecerAvaliacao) other;
			return new EqualsBuilder()
				.append(this.codigo, castOther.codigo)
			.isEquals();
		}
		else {
			return false;
		}	
	}
	
	public enum Fields {
		CODIGO("codigo"),
		PARECER_MATERIAL("parecerMaterial"),
		PARECER_MATERIAL_CODIGO("parecerMaterial.codigo"),
		LOTE("lote"),
		PARECER_GERAL("parecerGeral"),		
		DT_CRIACAO("dtCriacao"),
		SERVIDOR_CRIACAO("servidorCriacao"),
		MATRICULA_SERVIDOR_CRIACAO("servidorCriacao.id.matricula"),
		CODIGO_VINCULO_SERVIDOR_CRIACAO("servidorCriacao.id.vinCodigo"),
		DT_ALTERACAO("dtAlteracao"),
		SERVIDOR_ALTERACAO("servidorAlteracao"),
		MATRICULA_SERVIDOR_ALTERACAO("servidorAlteracao.id.matricula"),
		CODIGO_VINCULO_SERVIDOR_ALTERACAO("servidorAlteracao.id.vinCodigo"),
		AVALIACOES_TECNICAS("avaliacoesTecnicas"),
		AVALIACOES_CONSUL("avaliacoesConsultoria"),
		AVALIACOES_DESEMP("avaliacoesDesempenho");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}	

}
