package br.gov.mec.aghu.model;

// Generated 11/11/2011 09:11:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * ScoPrazoPagamentos generated by hbm2java
 */
@Entity
@Table(name = "SCO_PRAZO_PAGAMENTOS", schema = "AGH")
public class ScoPrazoPagamento extends BaseEntityId<ScoPrazoPagamentoId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8422115122104106031L;
	private ScoPrazoPagamentoId id;
	private Integer version;
	private Short parcela;

	public ScoPrazoPagamento() {
	}

	public ScoPrazoPagamento(ScoPrazoPagamentoId id, Short parcela) {
		this.id = id;
		this.parcela = parcela;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cdpNumero", column = @Column(name = "CDP_NUMERO", nullable = false)),
			@AttributeOverride(name = "numero", column = @Column(name = "NUMERO", nullable = false)) })
			
	public ScoPrazoPagamentoId getId() {
		return this.id;
	}

	public void setId(ScoPrazoPagamentoId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "PARCELA", nullable = false)
	public Short getParcela() {
		return this.parcela;
	}

	public void setParcela(Short parcela) {
		this.parcela = parcela;
	}

	public enum Fields {
		CDPNUMERO("id.cdpNumero"),
		NUMERO("id.numero"),
		PARCELA("parcela");
	    
	    private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
	}

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ScoPrazoPagamento)) {
			return false;
		}
		ScoPrazoPagamento other = (ScoPrazoPagamento) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
