package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * ScoSemMarcaId generated by hbm2java
 */
@Embeddable
public class ScoSemMarcaId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 255274582189861278L;
	private Integer licitacao;
	private Short item;
	private Integer fornecedor;
	private String marca;
	private Integer version;

	public ScoSemMarcaId() {
	}

	public ScoSemMarcaId(Integer licitacao, Short item, Integer fornecedor, Integer version) {
		this.licitacao = licitacao;
		this.item = item;
		this.fornecedor = fornecedor;
		this.version = version;
	}

	public ScoSemMarcaId(Integer licitacao, Short item, Integer fornecedor, String marca, Integer version) {
		this.licitacao = licitacao;
		this.item = item;
		this.fornecedor = fornecedor;
		this.marca = marca;
		this.version = version;
	}

	@Column(name = "LICITACAO", nullable = false)
	public Integer getLicitacao() {
		return this.licitacao;
	}

	public void setLicitacao(Integer licitacao) {
		this.licitacao = licitacao;
	}

	@Column(name = "ITEM", nullable = false)
	public Short getItem() {
		return this.item;
	}

	public void setItem(Short item) {
		this.item = item;
	}

	@Column(name = "FORNECEDOR", nullable = false)
	public Integer getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Integer fornecedor) {
		this.fornecedor = fornecedor;
	}

	@Column(name = "MARCA", length = 45)
	@Length(max = 45)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "VERSION", nullable = false)
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getVersion());
		umHashCodeBuilder.append(this.getLicitacao());
		umHashCodeBuilder.append(this.getFornecedor());
		umHashCodeBuilder.append(this.getItem());
		umHashCodeBuilder.append(this.getMarca());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ScoSemMarcaId)) {
			return false;
		}
		ScoSemMarcaId other = (ScoSemMarcaId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getVersion(), other.getVersion());
		umEqualsBuilder.append(this.getLicitacao(), other.getLicitacao());
		umEqualsBuilder.append(this.getFornecedor(), other.getFornecedor());
		umEqualsBuilder.append(this.getItem(), other.getItem());
		umEqualsBuilder.append(this.getMarca(), other.getMarca());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
