package br.gov.mec.aghu.model;

// Generated 09/04/2012 16:32:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * TblFatExmeAgh generated by hbm2java
 */
@Entity
@Table(name = "TBL_FAT_EXME_AGH", schema = "AGH")
public class TblFatExmeAgh extends BaseEntityId<TblFatExmeAghId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5315944752787214917L;
	private TblFatExmeAghId id;

	public TblFatExmeAgh() {
	}

	public TblFatExmeAgh(TblFatExmeAghId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "codUnidExec", column = @Column(name = "COD_UNID_EXEC")),
			@AttributeOverride(name = "dataLibLaud", column = @Column(name = "DATA_LIB_LAUD", length = 29)),
			@AttributeOverride(name = "indSitExmeSltc", column = @Column(name = "IND_SIT_EXME_SLTC")),
			@AttributeOverride(name = "indFat", column = @Column(name = "IND_FAT")),
			@AttributeOverride(name = "codExme", column = @Column(name = "COD_EXME")),
			@AttributeOverride(name = "dataHoraEntgMatLab", column = @Column(name = "DATA_HORA_ENTG_MAT_LAB", length = 29)),
			@AttributeOverride(name = "nroSltcExme", column = @Column(name = "NRO_SLTC_EXME")),
			@AttributeOverride(name = "nroSeqExmeSltc", column = @Column(name = "NRO_SEQ_EXME_SLTC")),
			@AttributeOverride(name = "codOrgmSltc", column = @Column(name = "COD_ORGM_SLTC")),
			@AttributeOverride(name = "dataHoraSltcExme", column = @Column(name = "DATA_HORA_SLTC_EXME", length = 29)),
			@AttributeOverride(name = "nroCons", column = @Column(name = "NRO_CONS")),
			@AttributeOverride(name = "codPrnt", column = @Column(name = "COD_PRNT")),
			@AttributeOverride(name = "codConv", column = @Column(name = "COD_CONV")),
			@AttributeOverride(name = "atendimento", column = @Column(name = "ATENDIMENTO")),
			@AttributeOverride(name = "nomePac", column = @Column(name = "NOME_PAC", length = 50)),
			@AttributeOverride(name = "version", column = @Column(name = "VERSION", nullable = false)) })
	public TblFatExmeAghId getId() {
		return this.id;
	}

	public void setId(TblFatExmeAghId id) {
		this.id = id;
	}

	public enum Fields {

		ID("id");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}

	}

}
