package br.gov.mec.aghu.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * VAelExamesSolicitacaoId generated by hbm2java.
 * 
 * Está VIEW só possui código ANSI SQL.
 * 
 * @author fwinck
 * 
 */
@Embeddable
public class VAelExamesSolicitacaoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1966328913112325231L;
	private String sigla;
	private Integer manSeq;
	private Integer unfSeq;
	private String descricaoUsualExame;

	public VAelExamesSolicitacaoId() {
	}
	
	public VAelExamesSolicitacaoId(String sigla, Integer manSeq, Integer unfSeq) {
		this.sigla = sigla;
		this.manSeq = manSeq;
		this.unfSeq = unfSeq;
	}
	
	public VAelExamesSolicitacaoId(String descricaoUsualExame) {
		this.descricaoUsualExame = descricaoUsualExame;
	}
	
	@Column(name = "SIGLA", length = 5)
	public String getSigla() {
		return sigla;
	}
	public void setSigla(String sigla) {
		this.sigla = sigla;
	}
	@Column(name = "MAN_SEQ", precision = 99, scale = 0)
	public Integer getManSeq() {
		return manSeq;
	}
	public void setManSeq(Integer manSeq) {
		this.manSeq = manSeq;
	}
	@Column(name = "UNF_SEQ", precision = 99, scale = 0)
	public Integer getUnfSeq() {
		return unfSeq;
	}

	public void setUnfSeq(Integer unfSeq) {
		this.unfSeq = unfSeq;
	}
	
	@Column(name = "DESCRICAO_USUAL_EXAME", length = 100)	
	public String getDescricaoUsualExame() {
		return descricaoUsualExame;
	}
	
	public void setDescricaoUsualExame(String descricaoUsualExame) {
		this.descricaoUsualExame = descricaoUsualExame;
	}

	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getUnfSeq());
		umHashCodeBuilder.append(this.getSigla());
		umHashCodeBuilder.append(this.getManSeq());
		umHashCodeBuilder.append(this.getDescricaoUsualExame());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof VAelExamesSolicitacaoId)) {
			return false;
		}
		VAelExamesSolicitacaoId other = (VAelExamesSolicitacaoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getUnfSeq(), other.getUnfSeq());
		umEqualsBuilder.append(this.getSigla(), other.getSigla());
		umEqualsBuilder.append(this.getManSeq(), other.getManSeq());
		umEqualsBuilder.append(this.getDescricaoUsualExame(), other.getDescricaoUsualExame());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
