package br.gov.mec.aghu.model;

// Generated 25/04/2012 11:01:27 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioDiaSemanaColetaExames;
import br.gov.mec.aghu.dominio.DominioSituacaoHorario;
import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * VAelHrGradeDispId generated by hbm2java
 */
@Embeddable
public class VAelHrGradeDispId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4106381678233038275L;
	private Date dthrAgenda;
	private String dtAgenda;
	private String hrAgenda;
	private DominioSituacaoHorario situacaoHorario;
	private Short tipo;
	private Boolean hrExtra;
	private Short grade;
	private Integer seqGrade;
	private Integer grupoExame;
	private String siglaExame;
	private Integer matExame;
	private Short unfExame;
	private Date tempoOcupSala;
	private Integer matriculaSer;
	private Short vinculoSer;
	private Short sala;
	private Short salaSeq;
	private String descrGrupoEx;
	private String indAgendaExMesmoHor;
	private String numSala;
	private String nomeFunc;
	private String indExclusivoExecutor;
	private DominioDiaSemanaColetaExames diaSemana;

	public VAelHrGradeDispId() {
	}

	public VAelHrGradeDispId(Date dthrAgenda, String dtAgenda, String hrAgenda,
			DominioSituacaoHorario situacaoHorario, Short tipo, Boolean hrExtra, Short grade,
			Integer seqGrade, Integer grupoExame, String siglaExame,
			Integer matExame, Short unfExame, Date tempoOcupSala,
			Integer matriculaSer, Short vinculoSer, Short sala, Short salaSeq,
			String descrGrupoEx, String indAgendaExMesmoHor, String numSala,
			String nomeFunc, String indExclusivoExecutor) {
		this.dthrAgenda = dthrAgenda;
		this.dtAgenda = dtAgenda;
		this.hrAgenda = hrAgenda;
		this.situacaoHorario = situacaoHorario;
		this.tipo = tipo;
		this.hrExtra = hrExtra;
		this.grade = grade;
		this.seqGrade = seqGrade;
		this.grupoExame = grupoExame;
		this.siglaExame = siglaExame;
		this.matExame = matExame;
		this.unfExame = unfExame;
		this.tempoOcupSala = tempoOcupSala;
		this.matriculaSer = matriculaSer;
		this.vinculoSer = vinculoSer;
		this.sala = sala;
		this.salaSeq = salaSeq;
		this.descrGrupoEx = descrGrupoEx;
		this.indAgendaExMesmoHor = indAgendaExMesmoHor;
		this.numSala = numSala;
		this.nomeFunc = nomeFunc;
		this.indExclusivoExecutor = indExclusivoExecutor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DTHR_AGENDA", length = 7)
	public Date getDthrAgenda() {
		return this.dthrAgenda;
	}

	public void setDthrAgenda(Date dthrAgenda) {
		this.dthrAgenda = dthrAgenda;
	}

	@Column(name = "DT_AGENDA", length = 7)
	public String getDtAgenda() {
		return this.dtAgenda;
	}

	public void setDtAgenda(String dtAgenda) {
		this.dtAgenda = dtAgenda;
	}

	@Column(name = "HR_AGENDA", length = 5)
	@Length(max = 5)
	public String getHrAgenda() {
		return this.hrAgenda;
	}

	public void setHrAgenda(String hrAgenda) {
		this.hrAgenda = hrAgenda;
	}

	@Column(name = "SIT", length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacaoHorario getSituacaoHorario() {
		return this.situacaoHorario;
	}

	public void setSituacaoHorario(DominioSituacaoHorario situacaoHorario) {
		this.situacaoHorario = situacaoHorario;
	}

	@Column(name = "TIPO")
	public Short getTipo() {
		return this.tipo;
	}

	public void setTipo(Short tipo) {
		this.tipo = tipo;
	}

	@Column(name = "IND_HR_EXTRA", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getHrExtra() {
		return this.hrExtra;
	}

	public void setHrExtra(Boolean hrExtra) {
		this.hrExtra = hrExtra;
	}

	@Column(name = "GRADE")
	public Short getGrade() {
		return this.grade;
	}

	public void setGrade(Short grade) {
		this.grade = grade;
	}

	@Column(name = "SEQ_GRADE")
	public Integer getSeqGrade() {
		return this.seqGrade;
	}

	public void setSeqGrade(Integer seqGrade) {
		this.seqGrade = seqGrade;
	}

	@Column(name = "GRUPO_EXAME")
	public Integer getGrupoExame() {
		return this.grupoExame;
	}

	public void setGrupoExame(Integer grupoExame) {
		this.grupoExame = grupoExame;
	}

	@Column(name = "SIGLA_EXAME", length = 5)
	@Length(max = 5)
	public String getSiglaExame() {
		return this.siglaExame;
	}

	public void setSiglaExame(String siglaExame) {
		this.siglaExame = siglaExame;
	}

	@Column(name = "MAT_EXAME")
	public Integer getMatExame() {
		return this.matExame;
	}

	public void setMatExame(Integer matExame) {
		this.matExame = matExame;
	}

	@Column(name = "UNF_EXAME")
	public Short getUnfExame() {
		return this.unfExame;
	}

	public void setUnfExame(Short unfExame) {
		this.unfExame = unfExame;
	}

	@Column(name = "TEMPO_OCUP_SALA", length = 7)
	public Date getTempoOcupSala() {
		return this.tempoOcupSala;
	}

	public void setTempoOcupSala(Date tempoOcupSala) {
		this.tempoOcupSala = tempoOcupSala;
	}

	@Column(name = "MATRICULA_SER")
	public Integer getMatriculaSer() {
		return this.matriculaSer;
	}

	public void setMatriculaSer(Integer matriculaSer) {
		this.matriculaSer = matriculaSer;
	}

	@Column(name = "VINCULO_SER")
	public Short getVinculoSer() {
		return this.vinculoSer;
	}

	public void setVinculoSer(Short vinculoSer) {
		this.vinculoSer = vinculoSer;
	}

	@Column(name = "SALA")
	public Short getSala() {
		return this.sala;
	}

	public void setSala(Short sala) {
		this.sala = sala;
	}

	@Column(name = "SALA_SEQ")
	public Short getSalaSeq() {
		return this.salaSeq;
	}

	public void setSalaSeq(Short salaSeq) {
		this.salaSeq = salaSeq;
	}

	@Column(name = "DESCR_GRUPO_EX", length = 60)
	@Length(max = 60)
	public String getDescrGrupoEx() {
		return this.descrGrupoEx;
	}

	public void setDescrGrupoEx(String descrGrupoEx) {
		this.descrGrupoEx = descrGrupoEx;
	}

	@Column(name = "IND_AGENDA_EX_MESMO_HOR", length = 1)
	@Length(max = 1)
	public String getIndAgendaExMesmoHor() {
		return this.indAgendaExMesmoHor;
	}

	public void setIndAgendaExMesmoHor(String indAgendaExMesmoHor) {
		this.indAgendaExMesmoHor = indAgendaExMesmoHor;
	}

	@Column(name = "NUM_SALA", length = 10)
	@Length(max = 10)
	public String getNumSala() {
		return this.numSala;
	}

	public void setNumSala(String numSala) {
		this.numSala = numSala;
	}

	@Column(name = "NOME_FUNC", length = 4000)
	@Length(max = 4000)
	public String getNomeFunc() {
		return this.nomeFunc;
	}

	public void setNomeFunc(String nomeFunc) {
		this.nomeFunc = nomeFunc;
	}

	@Column(name = "IND_EXCLUSIVO_EXECUTOR", length = 1)
	@Length(max = 1)
	public String getIndExclusivoExecutor() {
		return this.indExclusivoExecutor;
	}

	public void setIndExclusivoExecutor(String indExclusivoExecutor) {
		this.indExclusivoExecutor = indExclusivoExecutor;
	}
	
	@Column(name = "DIA_SEMANA", nullable = false, length = 3)
	@Enumerated(EnumType.STRING)
	public DominioDiaSemanaColetaExames getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(DominioDiaSemanaColetaExames diaSemana) {
		this.diaSemana = diaSemana;
	}



	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getGrupoExame());
		umHashCodeBuilder.append(this.getSiglaExame());
		umHashCodeBuilder.append(this.getSala());
		umHashCodeBuilder.append(this.getDiaSemana());
		umHashCodeBuilder.append(this.getSituacaoHorario());
		umHashCodeBuilder.append(this.getTipo());
		umHashCodeBuilder.append(this.getDthrAgenda());
		umHashCodeBuilder.append(this.getTempoOcupSala());
		umHashCodeBuilder.append(this.getGrade());
		umHashCodeBuilder.append(this.getSeqGrade());
		umHashCodeBuilder.append(this.getDtAgenda());
		umHashCodeBuilder.append(this.getHrAgenda());
		umHashCodeBuilder.append(this.getMatriculaSer());
		umHashCodeBuilder.append(this.getVinculoSer());
		umHashCodeBuilder.append(this.getSalaSeq());
		umHashCodeBuilder.append(this.getDescrGrupoEx());
		umHashCodeBuilder.append(this.getNumSala());
		umHashCodeBuilder.append(this.getNomeFunc());
		umHashCodeBuilder.append(this.getIndAgendaExMesmoHor());
		umHashCodeBuilder.append(this.getUnfExame());
		umHashCodeBuilder.append(this.getMatExame());
		umHashCodeBuilder.append(this.getHrExtra());
		umHashCodeBuilder.append(this.getIndExclusivoExecutor());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof VAelHrGradeDispId)) {
			return false;
		}
		VAelHrGradeDispId other = (VAelHrGradeDispId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getGrupoExame(), other.getGrupoExame());
		umEqualsBuilder.append(this.getSiglaExame(), other.getSiglaExame());
		umEqualsBuilder.append(this.getSala(), other.getSala());
		umEqualsBuilder.append(this.getDiaSemana(), other.getDiaSemana());
		umEqualsBuilder.append(this.getSituacaoHorario(), other.getSituacaoHorario());
		umEqualsBuilder.append(this.getTipo(), other.getTipo());
		umEqualsBuilder.append(this.getDthrAgenda(), other.getDthrAgenda());
		umEqualsBuilder.append(this.getTempoOcupSala(), other.getTempoOcupSala());
		umEqualsBuilder.append(this.getGrade(), other.getGrade());
		umEqualsBuilder.append(this.getSeqGrade(), other.getSeqGrade());
		umEqualsBuilder.append(this.getDtAgenda(), other.getDtAgenda());
		umEqualsBuilder.append(this.getHrAgenda(), other.getHrAgenda());
		umEqualsBuilder.append(this.getMatriculaSer(), other.getMatriculaSer());
		umEqualsBuilder.append(this.getVinculoSer(), other.getVinculoSer());
		umEqualsBuilder.append(this.getSalaSeq(), other.getSalaSeq());
		umEqualsBuilder.append(this.getDescrGrupoEx(), other.getDescrGrupoEx());
		umEqualsBuilder.append(this.getNumSala(), other.getNumSala());
		umEqualsBuilder.append(this.getNomeFunc(), other.getNomeFunc());
		umEqualsBuilder.append(this.getIndAgendaExMesmoHor(), other.getIndAgendaExMesmoHor());
		umEqualsBuilder.append(this.getUnfExame(), other.getUnfExame());
		umEqualsBuilder.append(this.getMatExame(), other.getMatExame());
		umEqualsBuilder.append(this.getHrExtra(), other.getHrExtra());
		umEqualsBuilder.append(this.getIndExclusivoExecutor(), other.getIndExclusivoExecutor());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
