package br.gov.mec.aghu.model;

// Generated 12/03/2012 14:38:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * VAelUnfExecutaExames generated by hbm2java
 */
@Entity
@Table(name = "V_AEL_UNF_EXECUTA_EXAMES", schema = "AGH")
@Immutable
public class VAelUnfExecutaExames extends BaseEntityId<VAelUnfExecutaExamesId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2387747776719940024L;
	private VAelUnfExecutaExamesId id;
	private String descricaoExame;
	private String descricaoUsualExame;
	private String descricaoMaterial;
	private String descricaoUnidade;
	private Date tempoOcupSala;
	private String indAgendamPrevioInt;
	private String indAgendamPrevioNaoInt;
	private String indSituacaoUfe;
	private String motivoDesativacao;
	private String ufeIndDesativaTemp;
	private Date ufeDthrReativaTemp;
	private String exaManUnidade;

	public VAelUnfExecutaExames() {
	}

	public VAelUnfExecutaExames(VAelUnfExecutaExamesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sigla", column = @Column(name = "SIGLA", nullable = false, length = 5)),
			@AttributeOverride(name = "manSeq", column = @Column(name = "MAN_SEQ", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "unfSeq", column = @Column(name = "UNF_SEQ", nullable = false, precision = 4, scale = 0))})
	public VAelUnfExecutaExamesId getId() {
		return this.id;
	}

	public void setId(VAelUnfExecutaExamesId id) {
		this.id = id;
	}
	
	
	@Column(name = "DESCRICAO_EXAME", nullable = false, length = 100)
	@Length(max = 100)
	public String getDescricaoExame() {
		return this.descricaoExame;
	}

	public void setDescricaoExame(String descricaoExame) {
		this.descricaoExame = descricaoExame;
	}

	@Column(name = "DESCRICAO_USUAL_EXAME", nullable = false, length = 100)
	@Length(max = 100)
	public String getDescricaoUsualExame() {
		return this.descricaoUsualExame;
	}

	public void setDescricaoUsualExame(String descricaoUsualExame) {
		this.descricaoUsualExame = descricaoUsualExame;
	}

	@Column(name = "DESCRICAO_MATERIAL", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricaoMaterial() {
		return this.descricaoMaterial;
	}

	public void setDescricaoMaterial(String descricaoMaterial) {
		this.descricaoMaterial = descricaoMaterial;
	}

	@Column(name = "DESCRICAO_UNIDADE", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescricaoUnidade() {
		return this.descricaoUnidade;
	}

	public void setDescricaoUnidade(String descricaoUnidade) {
		this.descricaoUnidade = descricaoUnidade;
	}

	@Column(name = "TEMPO_OCUP_SALA", length = 7)
	public Date getTempoOcupSala() {
		return this.tempoOcupSala;
	}

	public void setTempoOcupSala(Date tempoOcupSala) {
		this.tempoOcupSala = tempoOcupSala;
	}

	@Column(name = "IND_AGENDAM_PREVIO_INT", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndAgendamPrevioInt() {
		return this.indAgendamPrevioInt;
	}

	public void setIndAgendamPrevioInt(String indAgendamPrevioInt) {
		this.indAgendamPrevioInt = indAgendamPrevioInt;
	}

	@Column(name = "IND_AGENDAM_PREVIO_NAO_INT", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndAgendamPrevioNaoInt() {
		return this.indAgendamPrevioNaoInt;
	}

	public void setIndAgendamPrevioNaoInt(String indAgendamPrevioNaoInt) {
		this.indAgendamPrevioNaoInt = indAgendamPrevioNaoInt;
	}

	@Column(name = "IND_SITUACAO_UFE", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndSituacaoUfe() {
		return this.indSituacaoUfe;
	}

	public void setIndSituacaoUfe(String indSituacaoUfe) {
		this.indSituacaoUfe = indSituacaoUfe;
	}

	@Column(name = "MOTIVO_DESATIVACAO", length = 60)
	@Length(max = 60)
	public String getMotivoDesativacao() {
		return this.motivoDesativacao;
	}

	public void setMotivoDesativacao(String motivoDesativacao) {
		this.motivoDesativacao = motivoDesativacao;
	}

	@Column(name = "UFE_IND_DESATIVA_TEMP", nullable = false, length = 1)
	@Length(max = 1)
	public String getUfeIndDesativaTemp() {
		return this.ufeIndDesativaTemp;
	}

	public void setUfeIndDesativaTemp(String ufeIndDesativaTemp) {
		this.ufeIndDesativaTemp = ufeIndDesativaTemp;
	}

	@Column(name = "UFE_DTHR_REATIVA_TEMP", length = 7)
	public Date getUfeDthrReativaTemp() {
		return this.ufeDthrReativaTemp;
	}

	public void setUfeDthrReativaTemp(Date ufeDthrReativaTemp) {
		this.ufeDthrReativaTemp = ufeDthrReativaTemp;
	}

	@Column(name = "EXA_MAN_UNIDADE", length = 96)
	@Length(max = 96)
	public String getExaManUnidade() {
		return this.exaManUnidade;
	}

	public void setExaManUnidade(String exaManUnidade) {
		this.exaManUnidade = exaManUnidade;
	}

	public enum Fields {

		SIGLA("id.sigla"), 
		MAN_SEQ("id.manSeq"),
		UNF_SEQ("id.unfSeq"),
		DESCRICAO_EXAME("descricaoExame"),
		DESCRICAO_USUAL_EXAME("descricaoUsualExame"),
		DESCRICAO_MATERIAL("descricaoMaterial"),
		DESCRICAO_UNIDADE("descricaoUnidade"),
		AGENDAM_PREVIO_INT("indAgendamPrevioInt"),
		AGENDAM_PREVIO_NAO_INT("indAgendamPrevioNaoInt"),
		IND_SITUACAO_UFE("indSituacaoUfe");

		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return this.fields;
		}
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
		if (obj == null){
			return false;
		}
		if (getClass() != obj.getClass()){
			return false;
		}
		VAelUnfExecutaExames other = (VAelUnfExecutaExames) obj;
		if (id == null) {
			if (other.id != null){
				return false;
			}
		} else if (!id.equals(other.id)){
			return false;
		}
			
		return true;
	}
	
	

	
	
	
}
