package br.gov.mec.aghu.model;

// Generated 26/05/2010 19:23:59 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * VAinConvenioPlanoId generated by hbm2java
 */

@Embeddable
public class VAinConvenioPlanoId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6241944305616403984L;
	private Short cnvCodigo;
	private Byte plano;
	private String descConv;
	private String descPlan;
	private String convenioPlano;
	private String indPermissaoInternacao;
	private String indVerfEscalaProfInt;
	private String indExigeNumMatr;
	private String indSelAutomProf;
	private String indSituacao;
	private String indRestringeProf;
	private String grupoConvenio;
	private String indTipoPlano;
	private String planoIndSituacao;
	private Short pgdSeq;

	public VAinConvenioPlanoId() {
	}

	public VAinConvenioPlanoId(Short cnvCodigo, Byte plano, String descConv,
			String descPlan, String indPermissaoInternacao,
			String indVerfEscalaProfInt, String indExigeNumMatr,
			String indSelAutomProf, String indSituacao,
			String indRestringeProf, String grupoConvenio) {
		this.cnvCodigo = cnvCodigo;
		this.plano = plano;
		this.descConv = descConv;
		this.descPlan = descPlan;
		this.indPermissaoInternacao = indPermissaoInternacao;
		this.indVerfEscalaProfInt = indVerfEscalaProfInt;
		this.indExigeNumMatr = indExigeNumMatr;
		this.indSelAutomProf = indSelAutomProf;
		this.indSituacao = indSituacao;
		this.indRestringeProf = indRestringeProf;
		this.grupoConvenio = grupoConvenio;
	}

	public VAinConvenioPlanoId(Short cnvCodigo, Byte plano, String descConv,
			String descPlan, String convenioPlano,
			String indPermissaoInternacao, String indVerfEscalaProfInt,
			String indExigeNumMatr, String indSelAutomProf, String indSituacao,
			String indRestringeProf, String grupoConvenio, String indTipoPlano,
			String planoIndSituacao, Short pgdSeq) {
		this.cnvCodigo = cnvCodigo;
		this.plano = plano;
		this.descConv = descConv;
		this.descPlan = descPlan;
		this.convenioPlano = convenioPlano;
		this.indPermissaoInternacao = indPermissaoInternacao;
		this.indVerfEscalaProfInt = indVerfEscalaProfInt;
		this.indExigeNumMatr = indExigeNumMatr;
		this.indSelAutomProf = indSelAutomProf;
		this.indSituacao = indSituacao;
		this.indRestringeProf = indRestringeProf;
		this.grupoConvenio = grupoConvenio;
		this.indTipoPlano = indTipoPlano;
		this.planoIndSituacao = planoIndSituacao;
		this.pgdSeq = pgdSeq;
	}

	@Column(name = "CNV_CODIGO", nullable = false, precision = 3, scale = 0)
	public Short getCnvCodigo() {
		return this.cnvCodigo;
	}

	public void setCnvCodigo(Short cnvCodigo) {
		this.cnvCodigo = cnvCodigo;
	}

	@Column(name = "PLANO", nullable = false, precision = 2, scale = 0)
	public Byte getPlano() {
		return this.plano;
	}

	public void setPlano(Byte plano) {
		this.plano = plano;
	}

	@Column(name = "DESC_CONV", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescConv() {
		return this.descConv;
	}

	public void setDescConv(String descConv) {
		this.descConv = descConv;
	}

	@Column(name = "DESC_PLAN", nullable = false, length = 60)
	@Length(max = 60)
	public String getDescPlan() {
		return this.descPlan;
	}

	public void setDescPlan(String descPlan) {
		this.descPlan = descPlan;
	}

	@Column(name = "CONVENIO_PLANO", length = 60)
	@Length(max = 60)
	public String getConvenioPlano() {
		return this.convenioPlano;
	}

	public void setConvenioPlano(String convenioPlano) {
		this.convenioPlano = convenioPlano;
	}

	@Column(name = "IND_PERMISSAO_INTERNACAO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndPermissaoInternacao() {
		return this.indPermissaoInternacao;
	}

	public void setIndPermissaoInternacao(String indPermissaoInternacao) {
		this.indPermissaoInternacao = indPermissaoInternacao;
	}

	@Column(name = "IND_VERF_ESCALA_PROF_INT", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndVerfEscalaProfInt() {
		return this.indVerfEscalaProfInt;
	}

	public void setIndVerfEscalaProfInt(String indVerfEscalaProfInt) {
		this.indVerfEscalaProfInt = indVerfEscalaProfInt;
	}

	@Column(name = "IND_EXIGE_NUM_MATR", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndExigeNumMatr() {
		return this.indExigeNumMatr;
	}

	public void setIndExigeNumMatr(String indExigeNumMatr) {
		this.indExigeNumMatr = indExigeNumMatr;
	}

	@Column(name = "IND_SEL_AUTOM_PROF", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndSelAutomProf() {
		return this.indSelAutomProf;
	}

	public void setIndSelAutomProf(String indSelAutomProf) {
		this.indSelAutomProf = indSelAutomProf;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(String indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "IND_RESTRINGE_PROF", nullable = false, length = 1)
	@Length(max = 1)
	public String getIndRestringeProf() {
		return this.indRestringeProf;
	}

	public void setIndRestringeProf(String indRestringeProf) {
		this.indRestringeProf = indRestringeProf;
	}

	@Column(name = "GRUPO_CONVENIO", nullable = false, length = 1)
	@Length(max = 1)
	public String getGrupoConvenio() {
		return this.grupoConvenio;
	}

	public void setGrupoConvenio(String grupoConvenio) {
		this.grupoConvenio = grupoConvenio;
	}

	@Column(name = "IND_TIPO_PLANO", length = 1)
	@Length(max = 1)
	public String getIndTipoPlano() {
		return this.indTipoPlano;
	}

	public void setIndTipoPlano(String indTipoPlano) {
		this.indTipoPlano = indTipoPlano;
	}

	@Column(name = "PLANO_IND_SITUACAO", length = 1)
	@Length(max = 1)
	public String getPlanoIndSituacao() {
		return this.planoIndSituacao;
	}

	public void setPlanoIndSituacao(String planoIndSituacao) {
		this.planoIndSituacao = planoIndSituacao;
	}

	@Column(name = "PGD_SEQ", precision = 3, scale = 0)
	public Short getPgdSeq() {
		return this.pgdSeq;
	}

	public void setPgdSeq(Short pgdSeq) {
		this.pgdSeq = pgdSeq;
	}
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getIndSituacao());
		umHashCodeBuilder.append(this.getGrupoConvenio());
		umHashCodeBuilder.append(this.getCnvCodigo());
		umHashCodeBuilder.append(this.getPgdSeq());
		umHashCodeBuilder.append(this.getPlano());
		umHashCodeBuilder.append(this.getDescConv());
		umHashCodeBuilder.append(this.getDescPlan());
		umHashCodeBuilder.append(this.getConvenioPlano());
		umHashCodeBuilder.append(this.getIndPermissaoInternacao());
		umHashCodeBuilder.append(this.getIndVerfEscalaProfInt());
		umHashCodeBuilder.append(this.getIndExigeNumMatr());
		umHashCodeBuilder.append(this.getIndSelAutomProf());
		umHashCodeBuilder.append(this.getIndRestringeProf());
		umHashCodeBuilder.append(this.getIndTipoPlano());
		umHashCodeBuilder.append(this.getPlanoIndSituacao());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof VAinConvenioPlanoId)) {
			return false;
		}
		VAinConvenioPlanoId other = (VAinConvenioPlanoId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getIndSituacao(), other.getIndSituacao());
		umEqualsBuilder.append(this.getGrupoConvenio(), other.getGrupoConvenio());
		umEqualsBuilder.append(this.getCnvCodigo(), other.getCnvCodigo());
		umEqualsBuilder.append(this.getPgdSeq(), other.getPgdSeq());
		umEqualsBuilder.append(this.getPlano(), other.getPlano());
		umEqualsBuilder.append(this.getDescConv(), other.getDescConv());
		umEqualsBuilder.append(this.getDescPlan(), other.getDescPlan());
		umEqualsBuilder.append(this.getConvenioPlano(), other.getConvenioPlano());
		umEqualsBuilder.append(this.getIndPermissaoInternacao(), other.getIndPermissaoInternacao());
		umEqualsBuilder.append(this.getIndVerfEscalaProfInt(), other.getIndVerfEscalaProfInt());
		umEqualsBuilder.append(this.getIndExigeNumMatr(), other.getIndExigeNumMatr());
		umEqualsBuilder.append(this.getIndSelAutomProf(), other.getIndSelAutomProf());
		umEqualsBuilder.append(this.getIndRestringeProf(), other.getIndRestringeProf());
		umEqualsBuilder.append(this.getIndTipoPlano(), other.getIndTipoPlano());
		umEqualsBuilder.append(this.getPlanoIndSituacao(), other.getPlanoIndSituacao());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
