package br.gov.mec.aghu.model;

// Generated 27/04/2010 20:08:15 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;


import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.core.persistence.EntityCompositeId;

/**
 * VFatAssocProcCidsId generated by hbm2java
 */
@Embeddable
public class VFatAssocProcCidsId implements EntityCompositeId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1771407865588713126L;
	private Short cpgCphCspCnvCodigo;
	private Byte cpgCphCspSeq;
	private Short iphPhoSeq;
	private Integer iphSeq;
	private Integer phiSeq;
	private Long codTabela;
	private String iphDescricao;
	private String phiDescricao;
	private String phiIndSituacao;
	private String iphIndSituacao;
	private String cidCodigo;
	private Integer cidSeq;
	private String cidDescricao;
	private String cidValidade;

	public VFatAssocProcCidsId() {
	}

	public VFatAssocProcCidsId(Short cpgCphCspCnvCodigo, Byte cpgCphCspSeq,
			Short iphPhoSeq, Integer iphSeq, Integer phiSeq, Long codTabela,
			String iphDescricao, String phiDescricao, String phiIndSituacao,
			String iphIndSituacao, String cidCodigo, Integer cidSeq,
			String cidDescricao) {
		this.cpgCphCspCnvCodigo = cpgCphCspCnvCodigo;
		this.cpgCphCspSeq = cpgCphCspSeq;
		this.iphPhoSeq = iphPhoSeq;
		this.iphSeq = iphSeq;
		this.phiSeq = phiSeq;
		this.codTabela = codTabela;
		this.iphDescricao = iphDescricao;
		this.phiDescricao = phiDescricao;
		this.phiIndSituacao = phiIndSituacao;
		this.iphIndSituacao = iphIndSituacao;
		this.cidCodigo = cidCodigo;
		this.cidSeq = cidSeq;
		this.cidDescricao = cidDescricao;
	}

	public VFatAssocProcCidsId(Short cpgCphCspCnvCodigo, Byte cpgCphCspSeq,
			Short iphPhoSeq, Integer iphSeq, Integer phiSeq, Long codTabela,
			String iphDescricao, String phiDescricao, String phiIndSituacao,
			String iphIndSituacao, String cidCodigo, Integer cidSeq,
			String cidDescricao, String cidValidade) {
		this.cpgCphCspCnvCodigo = cpgCphCspCnvCodigo;
		this.cpgCphCspSeq = cpgCphCspSeq;
		this.iphPhoSeq = iphPhoSeq;
		this.iphSeq = iphSeq;
		this.phiSeq = phiSeq;
		this.codTabela = codTabela;
		this.iphDescricao = iphDescricao;
		this.phiDescricao = phiDescricao;
		this.phiIndSituacao = phiIndSituacao;
		this.iphIndSituacao = iphIndSituacao;
		this.cidCodigo = cidCodigo;
		this.cidSeq = cidSeq;
		this.cidDescricao = cidDescricao;
		this.cidValidade = cidValidade;
	}

	@Column(name = "CPG_CPH_CSP_CNV_CODIGO", nullable = false, precision = 3, scale = 0)
	public Short getCpgCphCspCnvCodigo() {
		return this.cpgCphCspCnvCodigo;
	}

	public void setCpgCphCspCnvCodigo(Short cpgCphCspCnvCodigo) {
		this.cpgCphCspCnvCodigo = cpgCphCspCnvCodigo;
	}

	@Column(name = "CPG_CPH_CSP_SEQ", nullable = false, precision = 2, scale = 0)
	public Byte getCpgCphCspSeq() {
		return this.cpgCphCspSeq;
	}

	public void setCpgCphCspSeq(Byte cpgCphCspSeq) {
		this.cpgCphCspSeq = cpgCphCspSeq;
	}

	@Column(name = "IPH_PHO_SEQ", nullable = false, precision = 4, scale = 0)
	public Short getIphPhoSeq() {
		return this.iphPhoSeq;
	}

	public void setIphPhoSeq(Short iphPhoSeq) {
		this.iphPhoSeq = iphPhoSeq;
	}

	@Column(name = "IPH_SEQ", nullable = false, precision = 8, scale = 0)
	public Integer getIphSeq() {
		return this.iphSeq;
	}

	public void setIphSeq(Integer iphSeq) {
		this.iphSeq = iphSeq;
	}

	@Column(name = "PHI_SEQ", nullable = false, precision = 6, scale = 0)
	public Integer getPhiSeq() {
		return this.phiSeq;
	}

	public void setPhiSeq(Integer phiSeq) {
		this.phiSeq = phiSeq;
	}

	@Column(name = "COD_TABELA", nullable = false, precision = 10, scale = 0)
	public Long getCodTabela() {
		return this.codTabela;
	}

	public void setCodTabela(Long codTabela) {
		this.codTabela = codTabela;
	}

	@Column(name = "IPH_DESCRICAO", nullable = false, length = 250)
	@Length(max = 250)
	public String getIphDescricao() {
		return this.iphDescricao;
	}

	public void setIphDescricao(String iphDescricao) {
		this.iphDescricao = iphDescricao;
	}

	@Column(name = "PHI_DESCRICAO", nullable = false, length = 200)
	@Length(max = 200)
	public String getPhiDescricao() {
		return this.phiDescricao;
	}

	public void setPhiDescricao(String phiDescricao) {
		this.phiDescricao = phiDescricao;
	}

	@Column(name = "PHI_IND_SITUACAO", nullable = false, length = 1)
	@Length(max = 1)
	public String getPhiIndSituacao() {
		return this.phiIndSituacao;
	}

	public void setPhiIndSituacao(String phiIndSituacao) {
		this.phiIndSituacao = phiIndSituacao;
	}

	@Column(name = "IPH_IND_SITUACAO", nullable = false, length = 1)
	@Length(max = 1)
	public String getIphIndSituacao() {
		return this.iphIndSituacao;
	}

	public void setIphIndSituacao(String iphIndSituacao) {
		this.iphIndSituacao = iphIndSituacao;
	}

	@Column(name = "CID_CODIGO", nullable = false, length = 5)
	@Length(max = 5)
	public String getCidCodigo() {
		return this.cidCodigo;
	}

	public void setCidCodigo(String cidCodigo) {
		this.cidCodigo = cidCodigo;
	}

	@Column(name = "CID_SEQ", nullable = false, precision = 5, scale = 0)
	public Integer getCidSeq() {
		return this.cidSeq;
	}

	public void setCidSeq(Integer cidSeq) {
		this.cidSeq = cidSeq;
	}

	@Column(name = "CID_DESCRICAO", nullable = false, length = 300)
	@Length(max = 300)
	public String getCidDescricao() {
		return this.cidDescricao;
	}

	public void setCidDescricao(String cidDescricao) {
		this.cidDescricao = cidDescricao;
	}

	@Column(name = "CID_VALIDADE", length = 1)
	@Length(max = 1)
	public String getCidValidade() {
		return this.cidValidade;
	}

	public void setCidValidade(String cidValidade) {
		this.cidValidade = cidValidade;
	}
	
	

	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		HashCodeBuilder umHashCodeBuilder = new HashCodeBuilder();
		umHashCodeBuilder.append(this.getCpgCphCspSeq());
		umHashCodeBuilder.append(this.getCpgCphCspCnvCodigo());
		umHashCodeBuilder.append(this.getIphPhoSeq());
		umHashCodeBuilder.append(this.getIphSeq());
		umHashCodeBuilder.append(this.getCidSeq());
		umHashCodeBuilder.append(this.getCidCodigo());
		umHashCodeBuilder.append(this.getPhiSeq());
		umHashCodeBuilder.append(this.getCodTabela());
		umHashCodeBuilder.append(this.getIphDescricao());
		umHashCodeBuilder.append(this.getPhiDescricao());
		umHashCodeBuilder.append(this.getPhiIndSituacao());
		umHashCodeBuilder.append(this.getIphIndSituacao());
		umHashCodeBuilder.append(this.getCidDescricao());
		umHashCodeBuilder.append(this.getCidValidade());
		return umHashCodeBuilder.toHashCode();
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof VFatAssocProcCidsId)) {
			return false;
		}
		VFatAssocProcCidsId other = (VFatAssocProcCidsId) obj;
		EqualsBuilder umEqualsBuilder = new EqualsBuilder();
		umEqualsBuilder.append(this.getCpgCphCspSeq(), other.getCpgCphCspSeq());
		umEqualsBuilder.append(this.getCpgCphCspCnvCodigo(), other.getCpgCphCspCnvCodigo());
		umEqualsBuilder.append(this.getIphPhoSeq(), other.getIphPhoSeq());
		umEqualsBuilder.append(this.getIphSeq(), other.getIphSeq());
		umEqualsBuilder.append(this.getCidSeq(), other.getCidSeq());
		umEqualsBuilder.append(this.getCidCodigo(), other.getCidCodigo());
		umEqualsBuilder.append(this.getPhiSeq(), other.getPhiSeq());
		umEqualsBuilder.append(this.getCodTabela(), other.getCodTabela());
		umEqualsBuilder.append(this.getIphDescricao(), other.getIphDescricao());
		umEqualsBuilder.append(this.getPhiDescricao(), other.getPhiDescricao());
		umEqualsBuilder.append(this.getPhiIndSituacao(), other.getPhiIndSituacao());
		umEqualsBuilder.append(this.getIphIndSituacao(), other.getIphIndSituacao());
		umEqualsBuilder.append(this.getCidDescricao(), other.getCidDescricao());
		umEqualsBuilder.append(this.getCidValidade(), other.getCidValidade());
		return umEqualsBuilder.isEquals();
	}
	// ##### GeradorEqualsHashCodeMain #####
	
}
