package br.gov.mec.aghu.model;

// Generated 29/11/2010 14:49:57 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;
import javax.persistence.Transient;


import org.hibernate.annotations.Immutable;
import org.hibernate.validator.constraints.Length;

import br.gov.mec.aghu.dominio.DominioSituacao;
import br.gov.mec.aghu.dominio.DominioTipoSumarioAlta;
import br.gov.mec.aghu.core.persistence.BaseEntityId;

/**
 * VMpmServRecomAltas generated by hbm2java
 */

@Entity
@Table(name = "V_MPM_SERV_RECOM_ALTAS", schema = "AGH")
@Immutable
public class VMpmServRecomAltas extends BaseEntityId<VMpmServRecomAltasId> implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2388752021756981881L;
	private VMpmServRecomAltasId id;
	private String descricao;
	private DominioSituacao indSituacao;
	private Boolean indRecomendado;
	private DominioTipoSumarioAlta indTipoSumrAlta;

	public VMpmServRecomAltas() {
	}

	public VMpmServRecomAltas(VMpmServRecomAltasId id,
			String descricao, DominioSituacao indSituacao, Boolean indRecomendado, DominioTipoSumarioAlta indTipoSumrAlta) {
		this.id = id;
		this.descricao = descricao;
		this.indSituacao = indSituacao;
		this.indRecomendado = indRecomendado;
		this.indTipoSumrAlta = indTipoSumrAlta;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "serMatricula", column = @Column(name = "SER_MATRICULA", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "serVinCodigo", column = @Column(name = "SER_VIN_CODIGO", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "seqp", column = @Column(name = "SEQP", nullable = false, precision = 5, scale = 0)) })
	public VMpmServRecomAltasId getId() {
		return this.id;
	}

	public void setId(VMpmServRecomAltasId id) {
		this.id = id;
	}
	
	@Column(name = "DESCRICAO", nullable = false, length = 500)
	@Length(max = 500)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "IND_SITUACAO", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioSituacao getIndSituacao() {
		return this.indSituacao;
	}

	public void setIndSituacao(DominioSituacao indSituacao) {
		this.indSituacao = indSituacao;
	}

	@Column(name = "IND_RECOMENDADO", length = 1)
	@org.hibernate.annotations.Type(type = "br.gov.mec.aghu.core.persistence.type.BooleanUserType")
	public Boolean getIndRecomendado() {
		return this.indRecomendado;
	}

	public void setIndRecomendado(Boolean indRecomendado) {
		this.indRecomendado = indRecomendado;
	}

	@Column(name = "IND_TIPO_SUMR_ALTA", nullable = false, length = 1)
	@Enumerated(EnumType.STRING)
	public DominioTipoSumarioAlta getIndTipoSumrAlta() {
		return this.indTipoSumrAlta;
	}

	public void setIndTipoSumrAlta(DominioTipoSumarioAlta indTipoSumrAlta) {
		this.indTipoSumrAlta = indTipoSumrAlta;
	}
	
	@Transient
	public MpmServRecomendacaoAltaId getMpmServRecomendacaoAltaId (){
		RapServidores servidor = new RapServidores();
		RapServidoresId servidorId = new RapServidoresId(this.getId().getSerMatricula(), this.getId().getSerVinCodigo());
		servidor.setId(servidorId);
		
		return new MpmServRecomendacaoAltaId(servidor.getId().getMatricula(), servidor.getId().getVinCodigo(), this.getId().getSeqp());
		
	}
	
	public enum Fields {

		SER_MATRICULA("id.serMatricula"), 
		SER_VIN_CODIGO("id.serVinCodigo"), 
		SEQP("id.seqp"),
		DESCRICAO("descricao"),
		IND_SITUACAO("indSituacao"),
		IND_RECOMENDADO("indRecomendado"),
		IND_TIPO_SUMR_ALTA("indTipoSumrAlta");
		
		private String fields;

		private Fields(String fields) {
			this.fields = fields;
		}

		@Override
		public String toString() {
			return fields;
		}
		
	}


	// ##### GeradorEqualsHashCodeMain #####
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof VMpmServRecomAltas)) {
			return false;
		}
		VMpmServRecomAltas other = (VMpmServRecomAltas) obj;
		if (getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!getId().equals(other.getId())) {
			return false;
		}
		return true;
	}
	// ##### GeradorEqualsHashCodeMain #####

}
